### ISSUE TITLE
Intermittent hang, KSH with backgrounded job

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#111]
@McDutchie points out that this hang pre-dates #103, see last comment in that issue.

```
[10:37 AM][ttys000 +1][~/src/ksh-segfault][master]
[1049] iMac $ arch/darwin.i386-64/bin/ksh
[10:37 AM][ttys000 +2][~/src/ksh-segfault][master]
[1050] iMac $ top &
[1]	72570
[10:37 AM][ttys000 +2][~/src/ksh-segfault][master]
[1051] iMac $ 
[1] + Stopped (SIGTTOU)        top &

[10:37 AM][ttys000 +2][~/src/ksh-segfault][master]
[1051] iMac $ fg
top 
[10:38 AM][ttys000 +2][~/src/ksh-segfault][master]
[1052] iMac $ 
```

And now the shell is unresponsive.

This is related to #89 , right?

I've managed to get it to do that four times now just doing the above, but it's not reliably repeatable.  If it does not display the 'Stopped' line without hitting Return again, it seems to never do it.  Only if it does that on its own, and not always.

I have to kill it from somewhere else or close Terminal.app.

`74575 s000  S+     0:00.02 arch/darwin.i386-64/bin/ksh`

^ from the latest one.

_Originally posted by @posguy99 in https://github.com/ksh93/ksh/issues/103#issuecomment-670658303_

**Comment by McDutchie** [comment]
I was just able to reproduce this bug twice on 93u+ 2012-08-01. So this is not a bug we introduced. Phew ;-)

**Comment by posguy99** [comment]
With that simple reproducer?  I only tried for about a hour but wasn't able to make it heppen.

**Comment by posguy99** [comment]
I tried to make it happen again and succeeded.  I left it sitting there stuck for the last half hour and somewhere in that interval it printed a single '>' on the same line as the prompt, but didn't unstick.  Weird.

**Comment by McDutchie** [comment]
I have not been able to reproduce this for months now. I suspect one of the Red Hat patches fixed it, but since the problem was intermittent, it's difficult to go back and figure out which one.

@posguy99, if you can still reproduce this, please comment and I'll reopen this bug.
