### ISSUE TITLE
LINENO corrupted upon autoloading function

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#116]
This bug is also in 93u+ 2012-08-01, as well as ksh2020.

Reproducer:
```sh
tmp=/tmp/LINENO_bug.$$
trap 'rm -rf "$tmp"' EXIT
mkdir "$tmp" || exit
cd "$tmp" || exit
print $'foobar() {\n: two\n: three\n: four\n} #five' > $tmp/foobar
FPATH=$tmp
saveLINENO=$LINENO
foobar
diff=$((LINENO - saveLINENO))
if      ((diff != 2))
then    echo "bug: diff == $diff"
        exit 1
else    echo "ok"
fi
```
Output:
```
bug: diff == 7
```
It appears that the five lines from the function definition file are wrongly added to the main script's `$LINENO`. So the fix probably involves saving and restoring `$LINENO` upon autoloading a function.

**Comment by posguy99** [comment]
If you source a file, should LINENO increase?

**Comment by McDutchie** [comment]
No, LINENO should always be the number of the line containing the command currently being executed in the current file.
