### ISSUE TITLE
${$} throwing syntax error when use in cat << EOF on ksh93 93u+

### ISSUE THREAD

**Issue by Saikiran-m** [ksh93/ksh#127]
Solaris 11 that ship with ksh93, the following behavior is observed:

Version of ksh93 on system:
~# ksh --version
version sh (AT&T Research) 93u+ 2012-08-01

The issue:
`echo ${$}` working fine but `echo ${$}` throwing syntax error when use in `cat << EOF`.

Recreation steps followed below:
Case 1: with `$$`
```
:# echo $$
1323

:# cat << EOF
    $$
    EOF
    1323
```

Case 2 : with `${$}`
```
:# echo ${$}
1323

:# cat << EOF
    echo ${$}
    EOF
    /usr/bin/ksh: syntax error: `$' unexpected
```

**Comment by McDutchie** [comment]
This reproducer:
```sh
for p in @ \* \# ! \$ - \? 0; do
	(eval ': <<EOF
${'"$p"'}
EOF
') && echo "ok: $p" || echo "error: $p"
done
```
shows that `${$}` and `${!}` have this problem:
```
ok: @
ok: *
ok: #
test4.sh[2]: eval[1]: syntax error at line 7: `!' unexpected
error: !
test4.sh[2]: eval[1]: syntax error at line 7: `$' unexpected
error: $
ok: -
ok: ?
ok: 0
```

**Comment by McDutchie** [comment]
This is the call that throws the error, for both `${!}` and `${$}`: https://github.com/ksh93/ksh/blob/55f0f8ce52ec39a797a745031a60816f998ce01a/src/cmd/ksh93/sh/lex.c#L1066

So the bug needs to be traced back from there somehow.

----

In case anyone is interested (and for my own future reference), I found this out using the following temporary diff. It causes ksh to show the source file and line that sh_syntax() was called from.
```diff
diff --git a/src/cmd/ksh93/include/shlex.h b/src/cmd/ksh93/include/shlex.h
index 1574796..8068ab2 100644
--- a/src/cmd/ksh93/include/shlex.h
+++ b/src/cmd/ksh93/include/shlex.h
@@ -149,7 +149,9 @@ extern int		sh_lex(Lex_t*);
 extern Shnode_t		*sh_dolparen(Lex_t*);
 extern Lex_t		*sh_lexopen(Lex_t*, Shell_t*, int);
 extern void 		sh_lexskip(Lex_t*,int,int,int);
-extern void 		sh_syntax(Lex_t*);
+extern void 		_real_sh_syntax(Lex_t*, char *, unsigned int);
+#define sh_syntax(lp)	_real_sh_syntax(lp, __FILE__, __LINE__)
+
 #if SHOPT_KIA
     extern int                  kiaclose(Lex_t *);
     extern unsigned long        kiaentity(Lex_t*, const char*,int,int,int,int,unsigned long,int,int,const char*);
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index 2aa71a7..0d9fc17 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -2109,7 +2109,7 @@ static char	*fmttoken(Lex_t *lp, register int sym, char *tok)
  * print a bad syntax message
  */
 
-void	sh_syntax(Lex_t *lp)
+void	_real_sh_syntax(Lex_t *lp, char *src_file, unsigned int src_line)
 {
 	register Shell_t *shp = lp->sh;
 	register const char *cp = sh_translate(e_unexpected);
@@ -2117,6 +2117,7 @@ void	sh_syntax(Lex_t *lp)
 	register int tok = lp->token;
 	char tokbuf[3];
 	Sfio_t *sp;
+	errormsg(SH_DICT,ERROR_warn(0),"sh_syntax() called from %s:%u", src_file, src_line);
 	if((tok==EOFSYM) && lp->lasttok)
 	{
 		tok = lp->lasttok;
```

**Comment by McDutchie** [comment]
Adding a debug message before every `goto err` in lex.c showed that this is the `goto err` that leads to the sh_syntax() call on line 1066:
https://github.com/ksh93/ksh/blob/55f0f8ce52ec39a797a745031a60816f998ce01a/src/cmd/ksh93/sh/lex.c#L989-L993

So ksh somehow mistakenly thought we were parsing backtick-style command substitutions.

**Comment by McDutchie** [comment]
The bigger problem is that the character `!` or `$` is associated with the `S_ERR` state in whatever state table is being used: https://github.com/ksh93/ksh/blob/55f0f8ce52ec39a797a745031a60816f998ce01a/src/cmd/ksh93/sh/lex.c#L984-L993

Further debug tracing (outputting the value of `mode` at [lex.c line 386](https://github.com/ksh93/ksh/blob/55f0f8ce52ec39a797a745031a60816f998ce01a/src/cmd/ksh93/sh/lex.c#L386)) showed that the state table being used is table 7, which is "for skipping over ${...} until modifier". So my current working hypothesis is that the bug is in that state table.
https://github.com/ksh93/ksh/blob/55f0f8ce52ec39a797a745031a60816f998ce01a/src/cmd/ksh93/data/lexstates.c#L267-L308
Each state table is 256 bytes long, and maps each ASCII character (identified by position in the table) to a state code.

**Comment by McDutchie** [comment]
`!` has ASCII code 33 and `$` has 36.

Changing the values on position 33 and 36 in state table 7 from `S_ERR` to `0` (no special meaning) fixes the bug for me:
```diff
diff --git a/src/cmd/ksh93/data/lexstates.c b/src/cmd/ksh93/data/lexstates.c
index b06d8ca..4f257a3 100644
--- a/src/cmd/ksh93/data/lexstates.c
+++ b/src/cmd/ksh93/data/lexstates.c
@@ -274,7 +274,7 @@ static const char sh_lexstate7[256] =
 	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,
 	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,	S_ERR,
 
-	S_ERR,	S_ERR,	S_ERR,	S_MOD2,	S_ERR,	S_MOD2,	S_ERR,	S_ERR,
+	S_ERR,	0,	S_ERR,	S_MOD2,	0,	S_MOD2,	S_ERR,	S_ERR,
 	S_ERR,	S_ERR,	S_MOD1,	S_MOD1,	S_ERR,	S_MOD1,	S_DOT,	S_MOD2,
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	S_MOD1,	S_ERR,	S_ERR,	S_MOD1,	S_ERR,	S_MOD1,
```
After that, my [reproducer](https://github.com/ksh93/ksh/issues/127#issuecomment-686678464) runs cleanly:
```
ok: @
ok: *
ok: #
ok: !
ok: $
ok: -
ok: ?
ok: 0
```
And the regression test suite does not show any regressions.

**Comment by McDutchie** [comment]
Thanks for your report @Saikiran-m, please don't hesitate to report further bugs you may come across. I'm now committing the fix.
