### ISSUE TITLE
'=' file created during build

### ISSUE THREAD

**Issue by aweeraman** [ksh93/ksh#13]
There appears to be a spurious '=' file created at the top of the source tree after a standard build of 'bin/package make'.

```
$ bin/package make
...
$ ls
'='   LICENSE.md   NEWS   README.md   TODO   arch   bin   docs	 lib   src
```

**Comment by McDutchie** [comment]
Yes, it's even in `.gitignore`. I haven't been bothered to research why it does that; maybe it's to keep track of a timestamp. It's a bit annoying, and does look buggy.

**Comment by aweeraman** [comment]
Yeah, looks harmless. Triggers my OCD though. Will poke around and see what's causing it at some point.

**Comment by McDutchie** [comment]
Datapoint: it doesn't appear when I build on my Mac.

**Comment by aweeraman** [comment]
FWIW I don't see this anymore on Linux.
