### ISSUE TITLE
Intermittent coprocess hang on Debian/Ubuntu and Solaris

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#132]
On roughly 1 in a 100-ish regression test runs, the following failure occurs:
```
test coprocess begins at 2020-09-11+19:51:40
	coprocess.sh[235]: /bin/cat coprocess 2 hung
test coprocess failed at 2020-09-11+19:51:48 with exit code 1 [ 34 tests 1 error ]
```
The test in question is: https://github.com/ksh93/ksh/blob/9f2066f146ae0d3ea733d9cccf5031273fb28e21/src/cmd/ksh93/tests/coprocess.sh#L227-L237

This has shown up on my Mac just once or twice, but it shows up more often on the Github CI test runners.

**Comment by hyenias** [comment]
FYI: Since I updated my code base to recent from something from July, I now encounter these coprocess hang failures the majority of the time whereas before I did not. Now, that I have a mental note about it I will try to understand its circumstances better.

**Comment by McDutchie** [comment]
err_exit() {
	echo "$@" >&2
	exit 1
}
cat=${ whence -p cat; } || exit
trap '[[ $sleep_pid ]] && kill $sleep_pid; trap - INT; kill -s INT $$' INT
n=0
while((++n))
do	printf '\r#%lu - ' "$n" >&2	# counter
	# --- begin original test ---
	trap 'sleep_pid=; kill $pid; err_exit "$cat coprocess 2 hung"' TERM 
	{ sleep 5; kill $$; } & 
	sleep_pid=$! 
	$cat |& 
	pid=$! 
	print foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed" 
	print foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed" 
	kill $pid 
	wait $pid 2> /dev/null 
	trap - TERM 
	[[ $sleep_pid ]] && kill $sleep_pid 
	# --- end original test ---
done

**Comment by McDutchie** [comment]
Here is a standalone version that runs this test repeatedly until interrupted.

*edit:* It [appears](https://github.com/ksh93/ksh/issues/132#issuecomment-699260700) that this hang is only reproducible on Debian Linux and derivatives, e.g. Ubuntu. Unfortunately that includes the GitHub CI runners.
```sh
err_exit() {
	echo "$@" >&2
	exit 1
}
cat=${ whence -p cat; } || exit
trap '[[ $sleep_pid ]] && kill $sleep_pid; trap - INT; kill -s INT $$' INT
n=0
while((++n))
do	printf '\r#%lu - ' "$n" >&2	# counter
	# --- begin original test ---
	trap 'sleep_pid=; kill $pid; err_exit "$cat coprocess 2 hung"' TERM 
	{ sleep 5; kill $$; } & 
	sleep_pid=$! 
	$cat |& 
	pid=$! 
	print foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed" 
	print foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed" 
	kill $pid 
	wait $pid 2> /dev/null 
	trap - TERM 
	[[ $sleep_pid ]] && kill $sleep_pid 
	# --- end original test ---
done
```

**Comment by McDutchie** [comment]
So, I still can't reproduce it on the Mac at all, but I can reproduce it on Linux just fine with the test script above.

The next step is figuring out whether 93u+m introduced that bug...
```sh
git checkout reboot                   # revert to when we started
git checkout master bin src/cmd/INIT  # no need to forgo build system fixes
git reset
rm -rf arch
bin/package make
arch/*/bin/ksh test_coprocess.sh
```

**Comment by McDutchie** [comment]
And after rebuilding the original 93u+ on Linux:
```
$ arch/*/bin/ksh test_coprocess.ksh 
#8 - /bin/cat coprocess 2 hung
```
…it fails in exactly the same way. When repeating, it fails on 10, 6, 9, 3, 8, 6, ... I can't seem to get it to survive more than 10 iterations.

So, we didn't introduce this. This is actually bad news. If we introduced it, a `git bisect` run would be able to identify the commit that caused it. Now there's no hope of that, and I haven't a clue where to begin looking.

**Comment by hyenias** [comment]
Good find. My primary testing environment is Linux. I was thinking I had something in my environment that may be causing these hangs such as terminal software, startup scripts, what shell I was using to launch the test scripts, networking, permissions, having much older boxes, and just maybe how I was running them via a local or remote terminal.

**Comment by McDutchie** [comment]
The hang is also reproducible (with the test script above) on the stock system /bin/ksh on Debian. But it takes longer to fail: iterations 36, 259, 31, 2, 22, 35, 159, 70, ...

@hyenias: I'm using a stock Debian shell account at xs4all.nl with nothing special done to the environment so I doubt it's got anything to do with that.

**Comment by McDutchie** [comment]
~~Some good news.~~ I recently got me a CentOS 8 virtual machine so I can test Red Hat's /bin/ksh93 with all their patches. And the hang is *not* reproducible there. Iteration 80000 and counting...

~~Now that @kdudka has made sure I have access to the relevant non-public Red Hat bugs,  I can simply continue my work of porting all those Red Hat patches to 93u+m, devising regression tests for them, etc. and by the time that work is complete, this bug should have gone away.~~

**Comment by McDutchie** [comment]
I might have spoken too soon there. True, I could not reproduce this hang on Red Hat's CentOS /bin/ksh93. But I can't reproduce it on 93u+m either when it's running on CentOS. And now I don't think I ever could. I probably just assumed the bug was there in 93u+m on CentOS; my bad. In any case, the bug is still there when running Debian, and it doesn't look like Red Hat patches enter into it. \<sigh>

*fires up Slackware Linux and NixOS Linux VMs, compiles ksh*

…and sure enough, I can't reproduce the bug on Slackware or NixOS either. It appears to be Debian-specific then (Ubuntu is a Debian derivative, so it makes sense the bug would show up there too). And it's not caused by any Debian patches, so it's probably a bug somewhere in their system libraries.

So the good news is that this does not appear to be a bug in ksh. The bad news is that that's irrelevant to Debian and Ubuntu users; they still get hangs.

**Comment by McDutchie** [comment]
In addition to Slackware and NixOS (both Linux) and macOS, I've now confirmed the hang *not* reproducible on FreeBSD 12.1, NetBSD 9.0, OpenBSD 6.7, and HP-UX B.11.11.

However, I *can* reproduce it on NetBSD 8.1 and Solaris 11.4. :(

**Comment by hyenias** [comment]
On my Ubuntu based systems (Intel and ARM), introducing a sleep of .01 between commands allows the coprocess script to complete without error even on my slowest box. I used **head** instead of **cat** in the following code snippet while in an interactive session to validate each test by altering the number of lines given to head and various sleeps. 

**Passing head -n #:**

- **2**: All tests pass and the head coprocess terminates by itself. [good]
- **3**: head coprocess has to be terminated manually as it is still waiting on more input [expected, good] 
- **0 with no sleeps**: head process failed to terminate [bad, head -n 0 still running and not had a chance to exit]
- **0 and only having a sleep before 1st print**: both prints fail [good]
- **1 with only sleep before 1st print**: both prints pass, expected 2nd print to fail [bad]
- **1 with sleeps before each print**: second print fails [good]
- **2 with sleeps before each print**: head process fails to terminate [bad]
- **2 with sleeps before each print and the jobs command**: all pass [good]
```ksh
head -n 2 |&; pid=$!
sleep .01
print foo >&p 2> /dev/null || echo 'first write of foo to head coprocess failed'
sleep .01
print foo >&p 2> /dev/null || echo 'second write of foo to head coprocess failed'
sleep .01
jobs $pid 2> /dev/null && { echo 'head coprocess failed to terminate'; kill $pid ;}
wait $pid 2> /dev/null
```
So, I recommend adding in some sleeps as follows to correct whatever on Debian systems that need more time to deal with the coprocess and/or its pipes. It may even be something related to job control--I just do not know. The 3rd sleep is not needed as the wait command provides a pause for the system to catch up.
```ksh
$cat |&
pid=$!
sleep .01
print foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed"
sleep .01
print foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed"
kill $pid
wait $pid 2> /dev/null
```

**Comment by McDutchie** [comment]
> So, I recommend adding in some sleeps as follows to correct whatever on Debian systems that need more time to deal with the coprocess and/or its pipes.

That would defeat the purpose of the regression test, as it would fail to expose the bug. So we might as well not bother running it at all then.

Given that it's only reproducible on a few specific systems (which unfortunately includes Debian and derivatives, which are popular), I suspect this is a race condition in the respective kernels, not in ksh.

**Comment by hyenias** [comment]
Understood. I was looking at this regression test evaluating one way communications to a coprocess and its ability to terminate that coprocess before other tests start evaluating two way communications to a coprocess.

**Comment by JohnoKing** [comment]
I've tested the bugged regression test and I've only been able to get the hang to occur when the `kill` builtin issues `SIGTERM` to the child process. `SIGKILL` prevents the loop, while issuing `SIGTERM` with the external kill command also works:
```sh
err_exit() {
	echo "$@" >&2
	exit 1
}
cat="$(whence -p cat)" || exit
trap '[[ $sleep_pid ]] && kill $sleep_pid; trap - INT; kill -s INT $$' INT
n=0
while((++n))
do	printf '\r#%lu - ' "$n"	# counter
	# --- begin test ---
	trap 'sleep_pid=; kill $pid; err_exit "$cat coprocess 2 hung"' TERM 
	/bin/sh -c "sleep 5; kill -TERM $$" &
	sleep_pid=$! 
	$cat |&
	pid=$! 
	echo foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed" 
	echo foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed" 

	# Both of these commands work
	command -px kill -TERM $pid
	#kill -KILL $pid

	# This one leads to hangs
	#kill -TERM $pid

	wait $pid 2> /dev/null
	trap - TERM 
	[[ $sleep_pid ]] && kill $sleep_pid 
	# --- end test ---
done
```

**Comment by JohnoKing** [comment]
Alternatively, when I comment out the `trap` commands for `SIGTERM` without changing which `kill` command to use, the hang also goes away:
```sh
err_exit() {
	echo "$@" >&2
	exit 1
}
cat="$(whence -p cat)" || exit
trap '[[ $sleep_pid ]] && kill $sleep_pid; trap - INT; kill -s INT $$' INT
n=0
while((++n))
do	printf '\r#%lu - ' "$n"	# counter
	# --- begin test ---
	#trap 'sleep_pid=; kill $pid; err_exit "$cat coprocess 2 hung"' TERM

	#/bin/sh -c "sleep 5; kill -TERM $$" &
	/bin/sh -c "sleep 5" &
	sleep_pid=$! 
	$cat |&
	pid=$!
	echo foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed"
	echo foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed"

	kill -TERM $pid
	wait $pid 2> /dev/null
	#trap - TERM 

	[[ $sleep_pid ]] && kill $sleep_pid
	# --- end test ---
done
```

**Comment by hyenias** [comment]
I have not encountered the coprocess hang in many months.

**Comment by McDutchie** [comment]
I can still trivially reproduce it on Debian with the [standalone reproducer](https://github.com/ksh93/ksh/issues/132#issuecomment-695800255). Note I disabled the corresponding regression test.

**Comment by hyenias** [comment]
Sorry, I did not run the standalone reproducer. I hangs at the following:
```
#2175 - [2175]	26808
[2176]	26809
/bin/cat coprocess 2 hung
```

**Comment by McDutchie** [comment]
I should re-enable the regression test but make the failure a warning with a link to this issue instead, as it's a known bug.

**Comment by hyenias** [comment]
I would not enable it by default as it would cause the _Github CI test runners_ to fail unless you can disable that particular test or similar tests. Maybe have normal `bin/shtests` not run these types of known troubled tests like what was done for pty on OpenBSD and other tests on Cygwin. If possible, I wonder if a new option could be added to bin/shtests to allow us to run for all tests, e.g. --all. Or maybe a --development/dev option so that I can run these tests now-and-again.

**Comment by McDutchie** [comment]
> I would not enable it by default as it would cause the _Github CI test runners_ to fail

Yes, hence my intention to make the failure a warning, i.e., it will not be counted as a failure, but still show up in the output.

**Comment by McDutchie** [comment]
I have been rethinking this issue. I think @hyenias might have had [the right idea](https://github.com/ksh93/ksh/issues/132#issuecomment-703169678) after all – sorry for dismissing it back then.

I now think the race condition is in the test itself and is not a problem in either ksh or in the systems where the reproducer fails.

Consider these lines from the test:
```sh
 $cat |& 
 pid=$! 
 print foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed" 
 print foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed" 
 kill $pid 
```

The external `cat` is launched in the background, so the shell continues as `cat` initialises. The next three lines, before the `kill`, take a very short time to execute. The writes are buffered and nothing in this test reads from the coprocess, so there's nothing here that requires it to actually function. So, in some cases, the fork/exec of `cat` might not have finished yet, and it may not yet be ready to handle `SIGTERM`. I think that is the race condition.

If we insert a very short sleep, like `sleep .01`, just before the `kill $pid`, the problem goes away, corroborating this hypothesis.

This hypothesis also explains @JohnoKing's [findings](https://github.com/ksh93/ksh/issues/132#issuecomment-817074395). As SIGKILL is unignorable, it will kill a process whether it is ready to handle signals or not. And it also makes sense that using the external `kill` does work with SIGTERM -- it should take about as much time to load and init as the external `cat` does.

But what I think we should really do is make the test read from the co-process and verify that it correctly passes through the text written to it. The first read will wait for `cat` to finish loading, eliminating the race condition.

```diff
diff --git a/src/cmd/ksh93/tests/coprocess.sh b/src/cmd/ksh93/tests/coprocess.sh
index cd06024b3..faae20725 100755
--- a/src/cmd/ksh93/tests/coprocess.sh
+++ b/src/cmd/ksh93/tests/coprocess.sh
@@ -215,15 +215,19 @@ do
 	trap - TERM
 	[[ $sleep_pid ]] && kill $sleep_pid

-# TODO: The /bin/cat iteration of this test is known to hang intermittently on Debian and
-# derived systems (such as Ubuntu). See: https://github.com/ksh93/ksh/issues/132
-	trap 'sleep_pid=; kill $pid; warning "$cat coprocess 2 hung (known issue, help us fix it at <https://github.com/ksh93/ksh/issues/132>)"' TERM
+	trap 'sleep_pid=; kill $pid; err_exit "$cat coprocess 2 hung"' TERM
 	{ sleep 5; kill $$; } &
 	sleep_pid=$!
 	$cat |&
 	pid=$!
-	print foo >&p 2> /dev/null || err_exit "first write of foo to $cat coprocess failed"
-	print foo >&p 2> /dev/null || err_exit "second write of foo to coprocess failed"
+	print foo1 >&p 2> /dev/null || err_exit "first write to $cat coprocess failed"
+	print foo2 >&p 2> /dev/null || err_exit "second write to $cat coprocess failed"
+	# avoid race between '$cat |&' initialising and 'kill $pid': read from the coprocess
+	# before 'kill' so that $cat is known to be fully initialised and ready to catch SIGTERM
+	read <&p
+	[[ $REPLY == foo1 ]] || err_exit "first read from $cat coprocess failed"
+	read <&p
+	[[ $REPLY == foo2 ]] || err_exit "second read from $cat coprocess failed"
 	kill $pid
 	wait $pid 2> /dev/null
 	trap - TERM
```
