### ISSUE TITLE
ksh report 'arithmetic syntax error' when float is used under fr_FR.UTF-8 locale

### ISSUE THREAD

**Issue by Saikiran-m** [ksh93/ksh#145]
When i use  fr_FR.UTF-8 locale then getting synatax error and if set to LC_ALL=C there wont be any error.
Whether the behavior is expected ?

Running version of ksh:
ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01

Small script :
test=2334.2435
print $test
if ((test >= 3600));then
        print "big"
else
        print "small"
fi 

If i set locale to  export LANG=fr_FR.UTF-8:
if ((test >= 3600));then
> print "big"
else
        print "small"
fi
/usr/bin/ksh93: 2334.2435: arithmetic syntax error

In case of LC_ALL=C then every goes fine.

Whether the behavior is expected ?

**Comment by McDutchie** [comment]
Yes, it is expected. The parsing of floating point numbers in ksh93 is locale-dependent. So, in a French (or Dutch, etc.) locale, you have to use `test=2334,2435`.

And that would then be a syntax error again in English-language locales. Not an ideal situation at all. It's not a bug, because the original authors intended it this way, but I don't think this is correct design.

So, I am trying to find out how to change this for ksh 93u+m so it always accepts `.` as a fallback to whatever character the current locale uses. That would eliminate this annoying type of syntax error. 

In the meantime, instead of `LC_ALL=C`, you can set `LC_NUMERIC=C` in your script. This only changes the locale for numbers, while keeping the rest of your locale.

**Comment by McDutchie** [comment]
> So, I am trying to find out how to change this for ksh 93u+m so it always accepts `.` as a fallback to whatever character the current locale uses. That would eliminate this annoying type of syntax error.

Here's a diff that makes this change:

```diff
diff --git a/src/cmd/ksh93/sh/arith.c b/src/cmd/ksh93/sh/arith.c
index cea0624..691476c 100644
--- a/src/cmd/ksh93/sh/arith.c
+++ b/src/cmd/ksh93/sh/arith.c
@@ -388,6 +388,7 @@ static Sfdouble_t arith(const char **ptr, struct lval *lvalue, int type, Sfdoubl
 		else
 		{
 			char	lastbase=0, *val = xp, oerrno = errno;
+			const char	radix = GETDECIMAL(0);
 			lvalue->eflag = 0;
 			errno = 0;
 			if(shp->bltindata.bnode==SYSLET && !sh_isoption(SH_LETOCTAL))
@@ -418,7 +419,9 @@ static Sfdouble_t arith(const char **ptr, struct lval *lvalue, int type, Sfdoubl
 				c='e';
 			else
 				c = *str;
-			if(c==GETDECIMAL(0) || c=='e' || c == 'E' || lastbase == 16 && (c == 'p' || c == 'P'))
+			if(c=='.' && radix!='.')  /* fallback: always accept '.' as radix point */
+				c = *str = radix;
+			if(c==radix || c=='e' || c == 'E' || lastbase == 16 && (c == 'p' || c == 'P'))
 			{
 				lvalue->isfloat=1;
 				r = strtold(val,&str);
```

It fixes cases like:
```
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((1.5 + .3))' 
ksh: 1.5 + .3: arithmetic syntax error
```
which will work after the diff: it will output `1,8`, so the locale radix point is used for output, though both `.` and the locale radix point are accepted on input.

However, it doesn't eliminated locale-related syntax errors completely: ksh supports arithmetic functions that take multiple comma-separated arguments. If the radix point is also a comma, that is a problem. As a workaround, you have to put spaces around the separating commas to distinguish them from radix point commas. It needs a space both before and after the separating comma:
```
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((pow(2,8)))'
ksh: pow(2,8): function has wrong number of arguments
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((pow(2, 8)))' 
ksh: pow(2, 8): arithmetic syntax error
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((pow(2 ,8)))' 
ksh: pow(2 ,8): arithmetic syntax error
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((pow(2 , 8)))'
256
$ LC_NUMERIC=fr_FR.UTF-8 ksh -c 'echo $((pow(2,1 , 8,2)))'
438,730893731381976
```
Of course this has always been the case in ksh93, but the diff above does not solve this issue. The only way to solve it would be to stop accepting locale-based radix points other than `.` on input, but that would break backwards compatibility and would also make it impossible to reuse output as input.

So it's effectively unsolvable. If a script uses arithmetic functions with multiple arguments without using spaces around the separating commas, they are still going to need to set `LC_NUMERIC=C` to be compatible (and make sure `LC_ALL` doesn't override that).

However, it does fix the simpler and much more common use case.

**So, is this worth doing? I'm not sure. What does the community think?**

**Comment by posguy99** [comment]
I think it violates least surprise and should not be done.  The reproducer from the OP **should** fail.

**Comment by hyenias** [comment]
I think you should keep it the way it is and use what the locale indicates to use. However, if not done so, I would default to C if there is no a locale defined.

**Comment by McDutchie** [comment]
Thanks for the feedback, everyone. So, no change in behaviour then. However, to resolve the issue that prompted this report (which is surprising for people in locales that use a comma as the radix point), I'll make ksh print a more informative error message instead of 'arithmetic syntax error'.
