### ISSUE TITLE
Please document/specify the globstar behaviour

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#146]
Ksh's `**` recursive globbing (enabled with `set -o globstar`/`set -G`),
when looking closely behaves significantly differently from other
implementations. And in quite surprising ways. The documentation is very
terse about it:

>  -G  Causes the pattern `**` by itself to match files and zero or more
>      directories and sub-directories when used for file name
>      generation. If followed by a `/` only  directories and
>      sub-directories are matched.

It would be useful for its behaviour to be specified more clearly for
users to know what to expect.

Recursive globbing was introduced in 1990 by zsh, and the `**/` form
specifically in 2.2 in 1992.

ksh93 didn't introduce `**` until over 10 years later, but ksh93
implementation was apparently written independently from zsh's. Up until
2016, David Korn did think he had invented it (see
`news://news.gmane.io/CAPVHe3R-qDpi+yG3OwTvhAPSnhBofboeYqonjckjB6EiOmhTDg@mail.gmail.com`)
suggesting he wasn't aware of zsh's implementation when he wrote his.

Which would explain why it's significantly different. A few other shells
(bash, yash, tcsh, fish) have later added support for `**`, with varying
behaviours though often closer to zsh's than to ksh93's.

In zsh, the operator was `**/`, and `**` alone was not special. `**/` was
short for `(*/)#`, that is matches 0 or more subdirectories (excluding
symlinks to directories, see `***/` for the form that follows symlinks).

In ksh93, `**/`, `/**` and `**` are all special.

Here are a few things I've gathered from ksh93's `**` through
experimentation:

`**` alone is like zsh's `**/*`, that is expands to files of any type in the
current directory or in subdirectories, but not following symlinks when
recursing.

`**/` is like zsh's `**/*/` in that it will also include symlinks to
directories (possibly contradicts the manual above), while zsh's `**/`
excludes symlinks to directories.

`**/file` however is like zsh's `**/file` and will not report "file"s inside
symlinks to directories.

`dir/**` will match files under "dir", but

`di[r]/**` will match files under "dir" **and** "dir" (unless "dir" is a
symlink to a directory in which case it will match **only** "dir"). That is
`/**` can match the empty string if it follows a component that
contains wildcards.

`[f]ile/**` will match on "file" even if "file" is not a directory. In
effect, `**`, `*/**`, `**/*` all expand to the same thing.

When `**` is present in a glob, it affects the way symlinks are processed
in all the glob path components.

For instance, `link/dir*/**` or `**/link/*` will not match anything (but
`link/dir/**`, `link/dir/*`, `*/link/*` will). As long as `**` is present, ksh
won't read the contents of symlinked dir components to match files in
them.

`link/**` won't match (but `lin[k]/**` will match on "link" and "link" only
as seen above).

"." and ".." seem to receive a special treatment in ksh93u+m (not in
ksh2020 nor ksh93u) in that `**/.` or `**/..` (or `**/./file...`) don't match anything (possibly related to https://github.com/ksh93/ksh/issues/58)

Note that I'm not saying ksh93's API is better or worse. It's got its
uses. For instance, the not following of symlinks could be seen as an
improvement even if it makes globbing inconsistent globally; the `/**`
possibly matching the empty string as well (like `/foo*/**` matching the
`/foo*` directories and their contents as opposed to just their contents
in zsh's `/foo*/**/*`, or `/etc/profile*/**` that matches on
`/etc/profile` and `/etc/profile.d` and its contents).

bash's ** has undergone several significant changes since it was introduced
in 4.0 and its documentation has been very terse all along as well (and
very similar to ksh93's suggesting the original intention was to copy
the ksh93 behaviour rather than zsh's, also suggested by the choice of
the "globstar" option name). bash's `**` also exhibits some of the
behaviours of ksh93's (like the `di[r]/**` including "dir", though note
that contrary to ksh93, `fil[e]/**` doesn't expand to "file", and
`dir/**` does include `dir/`).

See also
https://unix.stackexchange.com/questions/62660/the-result-of-ls-ls-and-ls

**Comment by McDutchie** [comment]
> `**` alone is like zsh's `**/*`, that is expands to files of any type in the
> current directory or in subdirectories, but not following symlinks when
> recursing.
> 
> `**/` is like zsh's `**/*/` in that it will also include symlinks to
> directories (possibly contradicts the manual above), while zsh's `**/`
> excludes symlinks to directories.
> 
> `**/file` however is like zsh's `**/file` and will not report "file"s inside
> symlinks to directories.

I think this change should cover all that:

```diff
diff --git a/src/cmd/ksh93/sh.1 b/src/cmd/ksh93/sh.1
index ec0e4897..18ccae47 100644
--- a/src/cmd/ksh93/sh.1
+++ b/src/cmd/ksh93/sh.1
@@ -6944,11 +6944,12 @@ to truncate a file when turned on.
 .B \-G
 Causes the pattern
 .B **
-by itself to match files and zero or more directories and sub-directories
+by itself to match files and zero or more directories and subdirectories
 when used for file name generation.
-If followed by a
-.B /
-only directories and sub-directories are matched.
+If the pattern ends in
+.BR **/ ,
+only directories and subdirectories are matched, including symlinks to these.
+Symlinks are not otherwise followed.
 .TP 8
 .B \-H
 Enable \f3!\fP-style history expansion similar to
```

> `dir/**` will match files under "dir", but
> 
> `di[r]/**` will match files under "dir" **and** "dir" (unless "dir" is a
> symlink to a directory in which case it will match **only** "dir"). That is
> `/**` can match the empty string if it follows a component that
> contains wildcards.
> 
> `[f]ile/**` will match on "file" even if "file" is not a directory.

That all seems quite logical as you're turning the initial pathname component from a regular name into a glob pattern. But I'm not sure how to go about documenting this corner case in the manual without confusing more than informing. Any suggestions?

> In effect, `**`, `*/**`, `**/*` all expand to the same thing.

I found that to be not quite true: `*/**` skips file/directory names in the current directory that start with a `.`. Which just means the initial `*` component is acting as normal.

> When ** is present in a glob, it affects the way symlinks are processed
> in all the glob path components.
> 
> For instance, link/dir*/** or **/link/* will not match anything (but
> link/dir/**, link/dir/*, */link/* will). As long as ** is present, ksh
> won't read the contents of symlinked dir components to match files in
> them.

I think this is also covered by the diff above.

> link/** won't match (but lin[k]/** will match on "link" and "link" only
> as seen above).

Right, it's the same corner case that I'm not sure how to document effectively.

> "." and ".." seem to receive a special treatment in ksh93u+m (not in ksh2020 nor ksh93u) in that **/. or **/.. (or **/./file...) don't match anything (possibly related to #58)

Yes, that's a bug introduced by the fix to #58 (5312a59d5a75b0c8edf9d83de09bc0437b26203d). Thanks for catching that.

A slightly more real-world reproducer: from within this repo's main directory:
```
$ ksh -o globstar -c 'echo **/./glob.c'
```
Actual output:
```
**/./glob.c
```
Expected output:
```
src/lib/libast/misc/./glob.c
```

**Comment by McDutchie** [comment]
> > "." and ".." seem to receive a special treatment in ksh93u+m (not in ksh2020 nor ksh93u) in that **/. or **/.. (or **/./file...) don't match anything (possibly related to #58)
> 
> Yes, that's a bug introduced by the fix to #58 ([5312a59](https://github.com/ksh93/ksh/commit/5312a59d5a75b0c8edf9d83de09bc0437b26203d)). Thanks for catching that.

I think this patch fixes the bug. It makes skipping `.` and `..` conditional upon *not* handling globstar right at the moment (the `matchdir` flag) and reinstates the globstar `.`/`..` special-casing from the commit prior to 5312a59.
```diff
diff --git a/src/lib/libast/misc/glob.c b/src/lib/libast/misc/glob.c
index b9fcea38..feab8f3d 100644
--- a/src/lib/libast/misc/glob.c
+++ b/src/lib/libast/misc/glob.c
@@ -528,13 +528,13 @@ skip:
 				*restore2 = gp->gl_delim;
 			while ((name = (*gp->gl_dirnext)(gp, dirf)) && !*gp->gl_intr)
 			{
-				if (name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
-					continue;  /* do not ever match '.' or '..' */
+				if (!matchdir && name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
+					continue;  /* do not ever match '.' or '..', unless we're doing globstar */
 				if (notdir = (gp->gl_status & GLOB_NOTDIR))
 					gp->gl_status &= ~GLOB_NOTDIR;
 				if (ire && !regexec(ire, name, 0, NiL, 0))
 					continue;
-				if (matchdir && !notdir)
+				if (matchdir && (name[0] != '.' || name[1] && (name[1] != '.' || name[2])) && !notdir)
 					addmatch(gp, prefix, name, matchdir, NiL, anymeta);
 				if (!regexec(pre, name, 0, NiL, 0))
 				{
```

**Comment by McDutchie** [comment]
But, unfortunately that patch does reintroduce the problematic aspect of globbing fixed in #58 if globstar is involved, e.g. `**/.*` will also match `**/.` and `**/..` which is not desirable.

**Comment by McDutchie** [comment]
I think this might be a correct fix, though it's a bit involved.

In preceding code, the `matchdir` pointer gets set to the complete glob pattern if we're doing globstar for the current pathname element, null if not. The `pat` pointer gets set to the elements of the pattern that are still left to be processed; already-done elements are trimmed from it by increasing the pointer.

So, to do the right thing, we need to make sure that `.` and `..` are skipped if, and only if, it is the final element in the pattern (i.e., if `pat` does not contain a slash) and is not specified literally as `.` or `..`, i.e. only if `.` or `..` was actually resolved from a glob pattern.

```diff
diff --git a/src/lib/libast/misc/glob.c b/src/lib/libast/misc/glob.c
index b9fcea38..f2a311c6 100644
--- a/src/lib/libast/misc/glob.c
+++ b/src/lib/libast/misc/glob.c
@@ -528,13 +528,14 @@ skip:
 				*restore2 = gp->gl_delim;
 			while ((name = (*gp->gl_dirnext)(gp, dirf)) && !*gp->gl_intr)
 			{
-				if (name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
-					continue;  /* do not ever match '.' or '..' */
+				if (!(matchdir && (pat[0] == '.' && (!pat[1] || pat[1] == '.' && !pat[2]) || strchr(pat,'/')))
+				&& name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
+					continue;  /* never match '.' or '..' as final element unless specified literally */
 				if (notdir = (gp->gl_status & GLOB_NOTDIR))
 					gp->gl_status &= ~GLOB_NOTDIR;
 				if (ire && !regexec(ire, name, 0, NiL, 0))
 					continue;
-				if (matchdir && !notdir)
+				if (matchdir && (name[0] != '.' || name[1] && (name[1] != '.' || name[2])) && !notdir)
 					addmatch(gp, prefix, name, matchdir, NiL, anymeta);
 				if (!regexec(pre, name, 0, NiL, 0))
 				{
```
After this patch, `**/.*`, `**/../.*`, etc. do the right thing, showing all your hidden files and directories without undesirable `.` and `..` results. That is, `.` and `..` are skipped as final elements, unless you literally specify `**/.`, `**/..`, `**/foo/bar/..`, etc.

**Comment by McDutchie** [comment]
> For instance, the not following of symlinks could be seen as an
> improvement even if it makes globbing inconsistent globally

While it makes sense to not follow symlinks that result from file name generation, I think it's another bug that it refuses to follow symlinks that are explicitly specified pathname components if they immediately precede `/**`. For instance, on my system, `/tmp` is a symlink to `/private/tmp`. It's not empty, but ksh acts as if it is and won't resolve the pattern:
```
$ ksh -o globstar -c 'echo /tmp/**'
/tmp/**
```
Whereas:
```
$ ksh -o globstar -c 'echo /tmp/./**'
/tmp/./MozillaUpdateLock-87440542C605238 /tmp/./com.apple.launchd.B0mfJwD7Cm /tmp/./com.apple.launchd.B0mfJwD7Cm/Listeners /tmp/./com.apple.launchd.Y4CLBewuda /tmp/./com.apple.launchd.Y4CLBewuda/org.xquartz:0 /tmp/./com.apple.launchd.zfWdVWSFm5 /tmp/./com.apple.launchd.zfWdVWSFm5/Render /tmp/./powerlog
```
I think that's bogus. It works fine on bash and zsh.

**Comment by McDutchie** [comment]
It does work if we add an extra slash, although then we get an extra slash in the results too (which is harmless but ugly):
```
$ ksh -o globstar -c 'echo /tmp//**'
/tmp//.vbox-martijn-ipc/ipcd /tmp//.vbox-martijn-ipc/lock /tmp//MozillaUpdateLock-87440542C605238 (etc.)
```

**Comment by McDutchie** [comment]
> While it makes sense to not follow symlinks that result from file name generation, I think it's another bug that it refuses to follow symlinks that are explicitly specified pathname components if they immediately precede `/**`.

I think the following patch (added to [the previous one](https://github.com/ksh93/ksh/issues/146#issuecomment-790991990)) provides a compromise we can live with. I found a flag that we can use: `gp->re_first` -- if I understand it right, it is set as long as no glob pattern has been resolved yet and all pathname components so far are literal. If that flag is set, we should try to `opendir` (via a function pointer) even if the type is `GLOB_DEV` which is the ID for some kind of special file, including symlinks. POSIX specifies that [`opendir`(3)](https://pubs.opengroup.org/onlinepubs/9699919799/functions/opendir.html) shall fail for non-directories, so it should be safe enough. This patch changes `symlink/**` to act as expected, but if the symlink results from a pattern as in `symlin[k]/**`, the behaviour does not change. On bash and zsh, even the second variant resolves, but I think implementing that would involve a more fundamental rewrite of this code.
```diff
--- a/src/lib/libast/misc/glob.c
+++ b/src/lib/libast/misc/glob.c
@@ -479,7 +479,9 @@ skip:
                                break;
                        prefix = streq(dirname, ".") ? (char*)0 : dirname;
                }
-               if ((!starstar && !gp->gl_starstar || (*gp->gl_type)(gp, dirname, GLOB_STARSTAR) == GLOB_DIR) && (dirf = (*gp->gl_d$
+               if ((!starstar && !gp->gl_starstar
+                   || (t1 = (*gp->gl_type)(gp, dirname, GLOB_STARSTAR)) == GLOB_DIR || t1 == GLOB_DEV && gp->re_first)
+               && (dirf = (*gp->gl_diropen)(gp, dirname)))
                {
                        if (!(gp->re_flags & REG_ICASE) && ((*gp->gl_attr)(gp, dirname, 0) & GLOB_ICASE))
                        {
```
New man page text:

              -G      Enables recursive file name generation.  This adds the double-star pattern ** to the file gener-
                      ation  mechanism (see File Name Generation above).  By itself, it matches the recursive contents
                      of the current directory, which is to say, all files and directories in  the  current  directory
                      and  in  all its subdirectories, sub-subdirectories, and so on.  If the pathname pattern ends in
                      **/, only directories and subdirectories are matched, including symbolic  links  that  point  to
                      directories.  A prefixed directory name is not included in the results unless that directory was
                      itself found by a pattern. For example, dir/** matches the recursive contents of dir but not dir
                      itself,  whereas  di[r]/**  matches both dir itself and the recursive contents of dir.  Symbolic
                      links to non-directories are not followed.  Symbolic links to directories are only  followed  if
                      specified  as  a literal pathname component preceding any and all pattern components.  For exam-
                      ple, if lnk is a symbolic link to a directory, then lnk/** matches the recursive contents of the
                      directory pointed to by lnk, each result prefixed by lnk/, whereas l[n]k/** will only match lnk.
                      To force following symbolic links to directories found by a pattern, use a  double  slash,  e.g.
                      lnk*//**.

**Comment by McDutchie** [comment]
It is still inconsistent though. For instance, if `/foo/bar/baz/lnk` is a symlink, then `/foo/*/baz/lnk/**` still won't work, though after `cd /foo/bar`, `baz/lnk/**` will work. At least that is consistent with what I documented in the new man page text above, but I don't like it. But I've no idea how to fix that without breaking everything else.

**Comment by McDutchie** [comment]
I'm pretty sure I found a better way. Instead of `gp->re_first`, we can check if the string pointed to by `pat` is exactly equal to `*`. If so, we are doing regular globbing for that particular pathname element, and it's okay to resolve symlinks. If not (if it's `**`), we're doing globstar and we should not be matching symlinks.

Let's also introduce proper identification of symlinks and not lump them in with other special files.

New patch:
```diff
--- a/src/lib/libast/include/glob.h
+++ b/src/lib/libast/include/glob.h
@@ -121,10 +121,11 @@ struct _glob_
 
 /* gl_type return */
 #define GLOB_NOTFOUND	0		/* does not exist		*/
-#define GLOB_DEV	1		/* exists but not DIR EXE REG	*/
 #define GLOB_DIR	2		/* directory			*/
 #define GLOB_EXE	3		/* executable regular file	*/
 #define GLOB_REG	4		/* regular file			*/
+#define GLOB_SYM	5		/* symbolic link		*/
+#define GLOB_DEV	1		/* exists but none of the above	*/
 
 /* error return values */
 #define GLOB_ABORTED	1
diff --git a/src/lib/libast/misc/glob.c b/src/lib/libast/misc/glob.c
index b9fcea38..267283b2 100644
--- a/src/lib/libast/misc/glob.c
+++ b/src/lib/libast/misc/glob.c
@@ -125,6 +125,8 @@ gl_type(glob_t* gp, const char* path, int flags)
 		type = 0;
 	else if (S_ISDIR(st.st_mode))
 		type = GLOB_DIR;
+	else if (S_ISLNK(st.st_mode))
+		type = GLOB_SYM;
 	else if (!S_ISREG(st.st_mode))
 		type = GLOB_DEV;
 	else if (st.st_mode & (S_IXUSR|S_IXGRP|S_IXOTH))
@@ -479,7 +481,9 @@ skip:
 				break;
 			prefix = streq(dirname, ".") ? (char*)0 : dirname;
 		}
-		if ((!starstar && !gp->gl_starstar || (*gp->gl_type)(gp, dirname, GLOB_STARSTAR) == GLOB_DIR) && (dirf = (*gp->gl_diropen)(gp, dirname)))
+		if ((!starstar && !gp->gl_starstar || (t1 = (*gp->gl_type)(gp, dirname, GLOB_STARSTAR)) == GLOB_DIR
+			|| t1 == GLOB_SYM && pat[0]=='*' && pat[1]=='\0') /* follow symlinks to dirs for non-globstar components */
+		&& (dirf = (*gp->gl_diropen)(gp, dirname)))
 		{
 			if (!(gp->re_flags & REG_ICASE) && ((*gp->gl_attr)(gp, dirname, 0) & GLOB_ICASE))
 			{
@@ -528,13 +532,14 @@ skip:
 				*restore2 = gp->gl_delim;
 			while ((name = (*gp->gl_dirnext)(gp, dirf)) && !*gp->gl_intr)
 			{
-				if (name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
-					continue;  /* do not ever match '.' or '..' */
+				if (!(matchdir && (pat[0] == '.' && (!pat[1] || pat[1] == '.' && !pat[2]) || strchr(pat,'/')))
+				&& name[0] == '.' && (!name[1] || name[1] == '.' && !name[2]))
+					continue;  /* never match '.' or '..' as final element unless specified literally */
 				if (notdir = (gp->gl_status & GLOB_NOTDIR))
 					gp->gl_status &= ~GLOB_NOTDIR;
 				if (ire && !regexec(ire, name, 0, NiL, 0))
 					continue;
-				if (matchdir && !notdir)
+				if (matchdir && (name[0] != '.' || name[1] && (name[1] != '.' || name[2])) && !notdir)
 					addmatch(gp, prefix, name, matchdir, NiL, anymeta);
 				if (!regexec(pre, name, 0, NiL, 0))
 				{
```

**Comment by McDutchie** [comment]
New man page text:

              -G      Enables recursive file name generation.  This adds the double-star pattern ** to the file gener-
                      ation  mechanism (see File Name Generation above).  By itself, it matches the recursive contents
                      of the current directory, which is to say, all files and directories in  the  current  directory
                      and  in  all its subdirectories, sub-subdirectories, and so on.  If the pathname pattern ends in
                      **/, only directories and subdirectories are matched, including symbolic  links  that  point  to
                      directories.  A prefixed directory name is not included in the results unless that directory was
                      itself found by a pattern. For example, dir/** matches the recursive contents of dir but not dir
                      itself,  whereas  di[r]/**  matches both dir itself and the recursive contents of dir.  Symbolic
                      links to non-directories are not followed.  Symbolic links to directories are followed  if  they
                      are  specified  literally or match a pattern as described under File Name Generation, but not if
                      they result from a double-star pattern.
