### ISSUE TITLE
Make ksh +s do something sensible

### ISSUE THREAD

**Issue by hvdijk** [ksh93/ksh#150]
When starting `ksh +s`, it gets stuck in an infinite loop continually trying to parse its own binary as a shell script and rejecting it:

    $ arch/linux.i386-64/bin/ksh +s
    arch/linux.i386-64/bin/ksh: arch/linux.i386-64/bin/ksh: cannot execute [Exec format error]
    arch/linux.i386-64/bin/ksh: arch/linux.i386-64/bin/ksh: cannot execute [Exec format error]
    arch/linux.i386-64/bin/ksh: arch/linux.i386-64/bin/ksh: cannot execute [Exec format error]
    arch/linux.i386-64/bin/ksh: arch/linux.i386-64/bin/ksh: cannot execute [Exec format error]
    arch/linux.i386-64/bin/ksh: arch/linux.i386-64/bin/ksh: cannot execute [Exec format error]
    [...]

`ksh +s` is not valid, but it should do something better than this. Options include, but are not limited to, issuing an error message (seen in bosh), treating it as a synonym for `-s` (seen in bash, busybox ash), treating it as a way to negate an earlier `-s` (seen in dash, mksh, yash, zsh).

**Comment by hyenias** [comment]
Here are my thoughts. I do not agree that `ksh +s` is an invalid option. ksh's embedded man page (`ksh --man`) initially states the following:

> ksh is a command language interpreter that executes commands read from a command line string, the standard input, or a specified file.

Using the `+s` option means to **not** use standard input as a source for commands and since the ksh interpreter was called without the `-c` command line string option; ksh attempts to execute commands read from a specified file (perhaps searching the PATH) which was not provided. As you have pointed out, this results in a loop and is a bug.

To comment on your suggested possible corrective actions:
1. I agree that an error message should be displayed if ksh is called with `+s` option lacking a filename.
2. I believe that `+s` should not be treated as a synonym for `-s` as `+s` is a way to tell ksh to launch only using a filename and thus not using standard input for commands including becoming interactive.

As I am not that familiar with dash, mksh, yash, or zsh; can you please elaborate on how mksh uses `+s` to negate an earlier `-s`? To my knowledge, these `s` options only are applicable when initializing the interpreter to run commands.

**Comment by hvdijk** [comment]
> Here are my thoughts. I do not agree that `ksh +s` is an invalid option.

I am going by the POSIX specification and the ksh man page. Both define `+X` in terms of the `set` command, which specifies that `+X` has the effect of turning off the `-X` option. In POSIX's case, `-s` is not defined for the `set` command at all, only for `sh`, so `+s` is not defined anywhere. In ksh's case, `ksh -s` and `set -s` are defined to do completely different things. The man page suggests that `+s` is valid with the `set` command (where it doesn't work either: `set +s b a` sets the positional arguments to `a b`, not `b a`), but overrides the meaning of `-s` in `ksh -s`, and at no point suggests `+s` works to disable that one. Disabling `-s` would be a perfectly reasonable action to take, but I wouldn't call it valid unless it's intended and documented to work in some specific way.

> To comment on your suggested possible corrective actions:
> 
> 1. I agree that an error message should be displayed if ksh is called with `+s` option lacking a filename.

That is actually not one of the suggestions I made, and something no other shell does that I know of, but also a valid action. When I said bosh displays an error message, I meant it displays an error message unconditionally, regardless of whether any file name is provided.

> 2. I believe that `+s` should not be treated as a synonym for `-s` as `+s` is a way to tell ksh to launch only using a filename and thus not using standard input for commands including becoming interactive.

That is something no other shell does that I know of either. In the case where `-s` would be set implicitly, it gets set implicitly after any explicit `+s` is processed, so `sh +s` still reads commands from standard input in those shells. It only cancels out an earlier explicit `-s`.

> As I am not that familiar with dash, mksh, yash, or zsh; can you please elaborate on how mksh uses `+s` to negate an earlier `-s`? To my knowledge, these `s` options only are applicable when initializing the interpreter to run commands.

    $ echo echo hello | mksh -s /dev/null # read command from stdin, set positional arguments to /dev/null
    hello
    $ echo echo hello | mksh -s +s /dev/null # read command from /dev/null, ignore stdin
    $

**Comment by McDutchie** [comment]
This bug also completely overwrites your `~/.sh_history` file, which is very annoying.

Ideally, I think we should follow the behaviour of the other actively developed ksh variant, mksh.

**Comment by hvdijk** [comment]
You can get the mksh behaviour with
```diff
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -1354,8 +1354,10 @@ Shell_t *sh_init(register int argc,register char *argv[], Shinit_f userinit)
                opt_info.disc = 0;
                shp->st.dolv=argv+(argc-1)-shp->st.dolc;
                shp->st.dolv[0] = argv[0];
-               if(shp->st.dolc < 1)
+               if(shp->st.dolc < 1) {
                        sh_onoption(SH_SFLAG);
+                       off_option(&sh.offoptions,SH_SFLAG);
+               }
                if(!sh_isoption(SH_SFLAG))
                {
                        shp->st.dolc--;
```
but style-wise there is probably a better way of doing this, it doesn't seem like messing with `sh.offoptions` directly is something that `sh_init` should be doing. I haven't checked whether the same problem also applies to any other implicitly-enabled options, or whether the rest of the options are always okay for the user to turn off.

**Comment by hyenias** [comment]
I would like to further bring to your attention the following additional text from `ksh --man` description:

> The -s and -c options are mutually exclusive. If the -c option is specified, the first arg is the command-line string and must be specified. Any remaining args will be used to initialize $0 and positional parameters.
> 
> If the neither -s nor -c is specified, then the first arg will be the pathname of the file containing commands and $0 will be set to this value. If there is no file with this pathname, and this pathname does not contain a /, then the PATH will be searched for an executable with this name. Any remaining args will be used to initialize the positional parameters.
> 
> Any option can use a + instead of a - to disable the corresponding option.

Here are some variations of using the `s` invocation option for ksh with filenames and stdin. As far as supplying multiple `s` options on the same command line, the last enablement or disablement wins.
```ksh
~/test$ cat file.txt
echo I am file
```
Command Line | Option | Result
-----|--------|------
ksh | (none) | interactive shell
ksh file.txt | (none) | file.txt is read for commands
echo 'echo I am stdin' \| ksh | (none) | stdin read for commands
echo 'echo I am stdin' \| ksh file.txt | (none) | file.txt is selected for read of commands and wins out over stdin
ksh -s | -s | interactive shell
ksh -s file.txt | -s | interactive shell with $@ being set to file.txt
echo 'echo I am stdin' \| ksh -s | -s | stdin read for commands
echo 'echo I am stdin' \| ksh -s file.txt | -s | stdin read for commands with $@ being set to file.txt
ksh +s file.txt | +s | file.txt is read for commands
echo 'echo I am stdin' \| ksh +s file.txt | +s | file.txt is read for commands, stdin is ignored
echo 'echo I am stdin' \| ksh +s | +s | Without filename provided results in error message, **ksh: cannot execute [Exec format error]**
ksh +s | +s| Without filename provided nor stdin results in a continuous looping error message,  **ksh: cannot execute [Exec format error]**

@McDutchie 
> Ideally, I think we should follow the behaviour of the other actively developed ksh variant, mksh.

I disagree that ksh should follow what mksh does. In my opinion, it is better to error out when ksh is explicitly/expressly/directly called using the `+s` invocation option if the filename is not provided. If a user wants the fallback behavior of using stdin or a filename for commands then the `s` option should not be utilized.

Imagine that you have a pipeline using ksh in the middle of that command chain. stdin and stdout are being passed along the pipeline as usual. ksh is called with a script file that modifies or acts on the stdio streams and should never directly attempt to execute the contents of that pipeline. To me, failing to error out when `+s` is active and ksh is unable to execute commands from an identified file (or in this case the lack of one) is wrong and less safe. ksh currently exhibits this behavior already within a pipeline; it just needs to be corrected to not loop forever when standalone.

**Comment by hyenias** [comment]
I forgot to mention the following tail end of the `ksh --man` page. Please note EXIT status of 127:

**EXIT STATUS**
If ksh executes command, the exit status will be that of the last command executed. Otherwise, it will be one of the following:
 - **0**:  The script or command line to be executed consists entirely of zero or more blank lines or comments.
 - **\>1-125**:  A noninteractive shell detected a syntax error, a variable assignment error, or an error in a special built-in.
 - **126**:  -c and -s were not specified and the command script was found on PATH but was not executable.
 - **127**:  -c and -s were not specified and the command script corresponding to **arg** could not be found.

**Comment by hvdijk** [comment]
> I would like to further bring to your attention the following additional text from `ksh --man` description:

Huh, indeed, that does say `+s` can be used to disable `-s`. I wonder why `ksh --man` and `man ksh` give out different information, and why `ksh --man` is not documented in `man ksh`: `--man` is only documented in there for built-in commands.

However, looking at `man ksh`:
```
       -s      If the -s option is present or if no arguments remain, then
               commands  are  read from the standard input.  [...]
```
Note that this does not say that `-s` is implicitly enabled (which is how it is implemented), this says standard input is used regardless of whether `-s` is enabled. Combined with your quote from `ksh --man` about how `+s` disables `-s`, this already documents the mksh behaviour.

> Please note EXIT status of 127:

That exit status applies when a "command script corresponding to **arg**" was specified, but it cannot be found. When no such command script is specified, ksh never looks for any command script, so neither succeeds nor fails in finding it.

**Comment by hyenias** [comment]
I am glad you found the `ksh --man` information. Unfortunately, ksh's various forms of documentation are not in 100% alignment and often the `--help` and/or `--man` output convey more information about a particular aspect of ksh than the consolidated manual via `man ksh`.  More often than not, ksh's code base is ahead of its documentation. At this point it takes contributors to align and update all of ksh's docs. @McDutchie actually possesses a copy of Morris I. Bolsky and David G. Korn's book, "The New Kornshell: Command and Programming Language", which may potentially provide further insights into the intended direction for ksh.

> Note that this does not say that -s is implicitly enabled (which is how it is implemented), this says standard input is used regardless of whether -s is enabled. Combined with your quote from ksh --man about how +s disables -s, this already documents the mksh behaviour.

From the context of those snippets from the man pages, I agree that ksh is currently behaving in the manner as evidenced in my earlier Command Line table above when `-s` is used or when option `s` is not present and no arguments remain. I will update my earlier table to include the following as well:

Command Line | Option | Result
-- | -- | --
ksh -s | -s | interactive shell
echo 'echo I am stdin' \| ksh -s | -s | stdin read for commands

However, I do not extend my acceptance of the `-s` described behavior to do away with ksh's current `+s` behavior as seen in my Command Line table above. The `+s` indicates that ksh should **not** utilize standard input to read in commands which also prevents an interactive shell. As stated before, ksh has 3 methods to acquire commands to execute: filename, `-s` aka stdin, and `-c` via args. If ksh is executed without `-c` and with `+s` then the only method to acquire commands is by file. As I have recommended, if no such file is provided on such an invocation attempt then ksh should fail and provide an error message as evidenced with my Command Line table for `echo 'echo I am stdin' | ksh +s` row.

If you do not mind, lets switch gears for the moment and back away from the existing documentation for `-s` as it appears that both of our stances have not changed. I would like to know the benefits of following mksh's way-of-things as seen below as compared to ksh's present behavior.
Command Comparison | Result
-- | --
echo 'echo I am stdin' \| mksh +s | I am stdin
echo 'echo I am stdin' \| ksh +s | ksh: ksh: cannot execute [Exec format error]
echo 'echo I am stdin' \| mksh +s file.txt | I am file
 echo 'echo I am stdin' \| ksh +s file.txt | I am file

**Comment by hvdijk** [comment]
> The +s indicates that ksh should not utilize standard input to read in commands which also prevents an interactive shell.

I would ask that if it is decided that this is how ksh should behave, the documentation also be updated to match, because I hope you can agree that my interpretation of the documentation, while perhaps not the only reasonable interpretation, is at least *a* reasonable interpretation.

> I would like to know the benefits of following mksh's way-of-things as seen below as compared to ksh's present behavior.

The present behaviour is just nonsensical and judging from the code happening accidentally. Presumably you don't want to compare to ksh's present behaviour, but to compare to a hypothetical ksh that issues an error message that explains what is wrong, and does not result in an infinite loop when interactive. This is an important distinction to make, because it clarifies that the cost is non-zero regardless of which approach is taken.

Consistency with other shells would be the only benefit that I can think of. Practically speaking, I would be very much surprised if anybody is ever going to rely on `sh +s` in any shell, which is why I did not express any preference for any of the approaches taken by other shells in my initial message.

**Comment by hyenias** [comment]
I also hope that the documentation would be updated in the future. I will put that on my to-do list and submit some pull requests to update the docs to help align them.

I agree that your interpretation of the documentation is a reasonable one. I went skimming through the docs and the disablement/removal of an option/attribute via `+` is rarely referenced.

Presumably?... Nope, I literally provided a Command Comparison table indicating mksh's and ksh's present behavior for comparison. What does not make sense to me is launching ksh with the directive to not use standard input aka `+s` and then have ksh actually use standard input for commands as what happens with mksh.

The infinite loop is a bug that needs to be corrected. You lost me on the non-zero cost line of thought. Fixing a bug or making any change consumes resources.

I am biased towards ksh. I am not for removing a feature/compatibility/etc. **_just_** to align ksh with other shells. I want to preserve, add, and enhance ksh's feature set--not to limit it. I realize that there is a POSIX shell standard and my hopes is that this community is able to create a POSIX option to limit and/or align ksh's operation as a POSIX sh.

**Comment by hvdijk** [comment]
> Presumably?... Nope, I literally provided a Command Comparison table indicating mksh's and ksh's present behavior for comparison.

Okay, I was presuming because I thought it would not be worth mentioning the fact that "ksh: ksh: cannot execute [Exec format error]" is a very confusing error message, and an infinite loop very user-unfriendly, again, but if you were really specifically asking for advantages of mksh's behaviour over ksh's current behaviour, rather than advantages over the behaviour of ksh that you're saying you'd like to see, they do need to be mentioned again.

> The infinite loop is a bug that needs to be corrected. You lost me on the non-zero cost line of thought. Fixing a bug or making any change consumes resources.

Yes, exactly. If the choices were between ksh's current behaviour and mksh's current behaviour, the cost of keeping the current behaviour would be zero. Asking about the benefits of mksh's behaviour over ksh's current behaviour suggested, I felt, that those were the choices, but as you say they are not, the choices are between changing ksh's behaviour in one way, and changing ksh's behaviour in another way.

> I am biased towards ksh. I am not for removing a feature/compatibility/etc. **_just_** to align ksh with other shells.

Absolutely. Neither the documentation nor the code suggested to me this was ever intended as a feature of ksh, but if it is, then please by all means keep it.

I only reported this because I felt that the current behaviour does not make sense. I really have no preference for any specific behaviour as long as it is one that makes sense, and to me all the behaviours seen in other shells, as well as the behaviour you would like, all make at least some degree of sense.

**Comment by hyenias** [comment]
I do appreciate you for taking the time and reporting this issue and related bug.

I agree that ksh's logic that results in the error message, "ksh: ksh: cannot execute [Exec format error]", from the table needs to be reworked as well as the message itself--maybe even expanded to allow for another EXIT status depending on code complexity and impact.

**Comment by McDutchie** [comment]
This bug is tantamount to a crash: a code path is followed that is not intended, leading to a nonsensical error message that may even loop infinitely, overwriting your entire `~/.sh_history`. This needs fixing. I'm with Harald in that I don't care all that much exactly how it is fixed, as long as it makes some kind of sense; this is basically a corner case triviality.

We have a patch from Harald that fixes it and makes ksh act like mksh, bash, dash, yash, and zsh (those are the ones I checked). I can't figure out how to make it more elegant, so I'm inclined to apply it as is. I'd be interested to know how you figured out that patch, though, @hvdijk -- I don't quite get why it works.

Alternatively, @hyenias, if you can come up with a way to make ksh act like you'd prefer it to, I'd be happy to accept a pull request.

**Comment by hvdijk** [comment]
> I'd be interested to know how you figured out that patch, though, @hvdijk -- I don't quite get why it works.

In `main.c`, there is:

    if(sh_isoption(SH_SFLAG))
        fdin = 0;
     else
         (code to open $0 as a file)

This was entering the `else` block because `sh_isoption(SH_SFLAG)` was returning 0, and `$0` is set to the ksh binary as it is supposed to when no other script is provided. When I looked for why `sh_isoption` was returning 0, I found `main.c`'s

    for(i=0; i<elementsof(shp->offoptions.v); i++)
        shp->options.v[i] &= ~shp->offoptions.v[i];

Before this loop, `shp->onoptions` tracks which options were explicitly enabled by the user on the command line, or implicitly enabled by ksh, while `shp->offoptions` tracks which options were explicitly disabled by the user on the command line. The effect of this loop is to make "explicitly disabled" take precedence over "implicitly enabled". My patch removes the registration of the `+s` option.

**Comment by McDutchie** [comment]
`shp->onoptions` (a.k.a. `sh.onoptions`) doesn't actually exist, but the rest makes sense. Thanks @hvdijk, this is useful for the git log.

**Comment by McDutchie** [comment]
@hyenias wrote:
> @McDutchie actually possesses a copy of Morris I. Bolsky and David G. Korn's book, "The New Kornshell: Command and Programming Language", which may potentially provide further insights into the intended direction for ksh.

OK, so I did a quick check. The book states for `-s`, under *Invocation Line Options*, page 261: "**ksh** reads commands from standard input. **ksh** automatically turns on the **-s** option if you do not specify the **-c** option, *or any arguments to **ksh** other than options*. **ksh** ignores the **-s** option if you specify **-c**."

The part I italicised, "*or any arguments to **ksh** other than options*", suggests that `-s` is unconditionally forced on if there are no non-option arguments, which is also how all other shells behave.

*edit:* Given that the behaviour is actually documented in the book, I now really think that we should just follow that and be done with it.

**Comment by hvdijk** [comment]
> `shp->onoptions` (a.k.a. `sh.onoptions`) doesn't actually exist,

Oops, it's called `shp->options`. Sorry for the confusion.

**Comment by McDutchie** [comment]
> > `shp->onoptions` (a.k.a. `sh.onoptions`) doesn't actually exist,
> 
> Oops, it's called `shp->options`.

That keeps track of the options that are currently on, not the options that were explicitly enabled on the command line. This variable is what's changed by the `sh_onoption` and `sh_offoption` macros and checked by `sh_isoption`.

> Sorry for the confusion.

No worries. This codebase is not exactly the easiest to understand…
