### ISSUE TITLE
CDPATH not ignored by cd ./dir

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#151]
Per [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/cd.html), `cd` should skip the `$CDPATH` processing if the first component of the directory given to `cd` is `.` or `..`.

Yet, with ksh93u+m 2021-01-03 at least, while that's OK with `..`, it's not with `.` with or without the `posix` option:

```
$ CDPATH=/ ./ksh -o posix -c 'cd -P ./etc && pwd'
/etc
/etc
```

It seems to be a regression introduced with ksh93u+ as I can't reproduce it with ksh93u or any version prior to that. I can also reproduce in u+, v- and the ksh2020 from the Ubuntu 20.04 package.

**Comment by McDutchie** [comment]
Fixed by properly checking for an initial `.` or `..` component before doing `$CDPATH` processing. Thanks for the report.
