### ISSUE TITLE
Build dies with current HEAD

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#158]
commit d00b4b39f66e2912797195f2aac9913218826350 (HEAD -> master, origin/master, origin/HEAD)

Here's the tail end of the error.  macOS Catalina 10.15.7.

iffe: test: is sys/types.h a header ... yes
iffe: test: is -liconv a library ... yes
iffe: test: is /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/libast.a a library ... yes
iffe: test: is -lutil a library ... yes
iffe: test: is /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/libcmd.a a library ... yes
iffe: test: is /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/libdll.a a library ... yes
iffe: test: is acct a command ... no
iffe: test: is acct a library data symbol ... no
iffe: test: is acct.h a header ... no
iffe: test: is acct a reserved keyword ... no
iffe: test: is acct a library function ... yes
iffe: test: is acct a math library symbol ... no
iffe: test: is sys/acct.h a header ... yes
iffe: test: is acct a type or typedef ... no
+ cc '-D_AST_git_commit="d00b4b39"' -Os -I. -I/Users/mwilson/src/ksh/src/cmd/ksh93 -Iinclude -I/Users/mwilson/src/ksh/src/cmd/ksh93/include -I/Users/mwilson/src/ksh/arch/darwin.i386-64/include/ast '-D_API_ast=20100309' -D_BLD_shell -DSHOPT_DYNAMIC -DSHOPT_MULTIBYTE -D_PACKAGE_ast -DSHOPT_FIXEDARRAY -DSHOPT_SUID_EXEC -DSHOPT_BRACEPAT -DSHOPT_STATS -DSHOPT_NAMESPACE -DSHOPT_HISTEXPAND '-DERROR_CONTEXT_T=Error_context_t' -DSHOPT_ESH -c /Users/mwilson/src/ksh/src/cmd/ksh93/bltins/cd_pwd.c
/Users/mwilson/src/ksh/src/cmd/ksh93/bltins/cd_pwd.c:101:7: error: implicit declaration of function 'test_inode' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if(!test_inode(nv_getval(pwdnod),e_dot))
                    ^
1 error generated.
mamake [cmd/ksh93]: *** exit code 1 making cd_pwd.o
mamake: *** exit code 1 making cmd/ksh93
mamake: *** exit code 1 making all
package: make done  at Wed Jan 20 11:35:56 PST 2021 in /Users/mwilson/src/ksh/arch/darwin.i386-64

**Comment by posguy99** [comment]
Revert ec0155ee65bd5faa6a59e9043516f5e29dff90d8 and it builds again.

**Comment by McDutchie** [comment]
The cause is probably that I forgot to include test.h which contains the declaration of the test_inode() function.
