### ISSUE TITLE
Current HEAD (8e45daea) fails to build on Catalina 10.15.7

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#164]
iffe: test: is stdlib.h a header ... yes
iffe: test: is sys/socket.h a header ... yes
iffe: test: is struct sf_hdtr a type or typedef ... yes
iffe: test: number of bits in pointer ... yes
iffe: test: open files cannot be removed ... no
iffe: test: voidptr is larger than int ... yes
iffe: test: long is larger than int ... yes
iffe: test: register layout ok for vax string operations ... no
iffe: test: native floating point conversions ok ... yes
iffe: test: Stdio fseek/fflush are X/Open-compliant ... no
+ cc -D_BLD_DLL -fPIC -D_BLD_ast '-D_AST_git_commit="8e45daea"' -Os -I. -I/Users/mwilson/src/ksh/src/lib/libast -Icomp -I/Users/mwilson/src/ksh/src/lib/libast/comp -Iport -I/Users/mwilson/src/ksh/src/lib/libast/port -Isfio -I/Users/mwilson/src/ksh/src/lib/libast/sfio -Iinclude -I/Users/mwilson/src/ksh/src/lib/libast/include -Istd -I/Users/mwilson/src/ksh/src/lib/libast/std -I/Users/mwilson/src/ksh/arch/darwin.i386-64/include -D_PACKAGE_ast -c /Users/mwilson/src/ksh/src/lib/libast/port/mc.c
In file included from /Users/mwilson/src/ksh/src/lib/libast/port/mc.c:31:
In file included from /Users/mwilson/src/ksh/src/lib/libast/sfio/sfhdr.h:302:
./FEATURE/float:150:2: error: Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:151:2: error: Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:152:2: error: Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
3 errors generated.
mamake [lib/libast]: *** exit code 1 making mc.o
mamake: *** exit code 1 making lib/libast
mamake: *** exit code 1 making all
package: make done  at Tue Jan 26 17:33:29 PST 2021 in /Users/mwilson/src/ksh/arch/darwin.i386-64

**Comment by posguy99** [comment]
And I must be stupid because I can't make it make any different output with IFFEFLAGS although IFFEFLAGS appears in the build log.

**Comment by posguy99** [comment]
[ 5:44 PM][ttys000 +1][~/src/ksh][master]
[897] mbp13 $ bin/package make IFFEFLAGS='-d1'
package: make with mamake
package: make output captured in /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/package/gen/make.out
package: make start at Tue Jan 26 17:46:32 PST 2021 in /Users/mwilson/src/ksh/arch/darwin.i386-64
CC=cc
SHELL=/bin/ksh
HOSTTYPE=darwin.i386-64
NPROC=8
PACKAGEROOT=/Users/mwilson/src/ksh
INSTALLROOT=/Users/mwilson/src/ksh/arch/darwin.i386-64
PATH=/Users/mwilson/src/ksh/arch/darwin.i386-64/bin/ok:/Users/mwilson/src/ksh/arch/darwin.i386-64/bin:/Users/mwilson/src/ksh/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/mwilson/bin
+ mamake -r '*/*' install IFFEFLAGS=-d1 KSH_RELFLAGS='-D_AST_git_commit=\"8e45daea\"' KSH_SHOPTFLAGS='-DSHOPT_2DMATCH=1 -DSHOPT_AUDIT=1 -DSHOPT_AUDITFILE=\"/etc/ksh_audit\" -DSHOPT_BGX=1 -DSHOPT_BRACEPAT=1 -DSHOPT_DYNAMIC=1 -DSHOPT_EDPREDICT=1 -DSHOPT_ESH=1 -DSHOPT_FILESCAN=1 -DSHOPT_FIXEDARRAY=1 -DSHOPT_HISTEXPAND=1 -DSHOPT_MULTIBYTE=1 -DSHOPT_NAMESPACE=1 -DSHOPT_OPTIMIZE=1 -DSHOPT_PFSH=0 -DSHOPT_RAWONLY=1 -DSHOPT_STATS=1 -DSHOPT_SUID_EXEC=1 -DSHOPT_TYPEDEF=1 -DSHOPT_VSH=1'
+ mamake -C cmd/INIT IFFEFLAGS=-d1 KSH_RELFLAGS='-D_AST_git_commit=\"8e45daea\"' KSH_SHOPTFLAGS='-DSHOPT_2DMATCH=1 -DSHOPT_AUDIT=1 -DSHOPT_AUDITFILE=\"/etc/ksh_audit\" -DSHOPT_BGX=1 -DSHOPT_BRACEPAT=1 -DSHOPT_DYNAMIC=1 -DSHOPT_EDPREDICT=1 -DSHOPT_ESH=1 -DSHOPT_FILESCAN=1 -DSHOPT_FIXEDARRAY=1 -DSHOPT_HISTEXPAND=1 -DSHOPT_MULTIBYTE=1 -DSHOPT_NAMESPACE=1 -DSHOPT_OPTIMIZE=1 -DSHOPT_PFSH=0 -DSHOPT_RAWONLY=1 -DSHOPT_STATS=1 -DSHOPT_SUID_EXEC=1 -DSHOPT_TYPEDEF=1 -DSHOPT_VSH=1' install
+ test '' '=' execrate
+ /usr/bin/cmp -s execrate /Users/mwilson/src/ksh/bin/execrate
+ 2> /dev/null
+ test '' '=' ignore
+ /usr/bin/cmp -s ignore /Users/mwilson/src/ksh/bin/ignore
+ 2> /dev/null
+ test '' '=' mamprobe
+ /usr/bin/cmp -s mamprobe /Users/mwilson/src/ksh/bin/mamprobe
+ 2> /dev/null
+ test '' '=' package
+ /usr/bin/cmp -s package /Users/mwilson/src/ksh/bin/package
+ 2> /dev/null
+ test '' '=' silent
+ /usr/bin/cmp -s silent /Users/mwilson/src/ksh/bin/silent
+ 2> /dev/null
+ test '' '=' package.mk
+ /usr/bin/cmp -s /Users/mwilson/src/ksh/src/cmd/INIT/package.mk /Users/mwilson/src/ksh/lib/package/package.mk
+ 2> /dev/null
+ test ! -x /Users/mwilson/src/ksh/arch/darwin.i386-64/bin/mkdir -a -x /bin/mkdir
+ mkdir -p
+ 2> /dev/null
+ :
+ test -d ./-p
+ test '' '=' mprobe
+ /usr/bin/cmp -s mprobe /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/probe/C/mam/probe
+ 2> /dev/null
+ test '' '=' probe
+ /usr/bin/cmp -s probe /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/probe/C/make/probe
+ 2> /dev/null
+ test '' '=' dl.req
+ /usr/bin/cmp -s dl.req /Users/mwilson/src/ksh/arch/darwin.i386-64/lib/lib/dl
+ 2> /dev/null
+ mamake -C lib/libast IFFEFLAGS=-d1 KSH_RELFLAGS='-D_AST_git_commit=\"8e45daea\"' KSH_SHOPTFLAGS='-DSHOPT_2DMATCH=1 -DSHOPT_AUDIT=1 -DSHOPT_AUDITFILE=\"/etc/ksh_audit\" -DSHOPT_BGX=1 -DSHOPT_BRACEPAT=1 -DSHOPT_DYNAMIC=1 -DSHOPT_EDPREDICT=1 -DSHOPT_ESH=1 -DSHOPT_FILESCAN=1 -DSHOPT_FIXEDARRAY=1 -DSHOPT_HISTEXPAND=1 -DSHOPT_MULTIBYTE=1 -DSHOPT_NAMESPACE=1 -DSHOPT_OPTIMIZE=1 -DSHOPT_PFSH=0 -DSHOPT_RAWONLY=1 -DSHOPT_STATS=1 -DSHOPT_SUID_EXEC=1 -DSHOPT_TYPEDEF=1 -DSHOPT_VSH=1' install
+ cc -D_BLD_DLL -fPIC -D_BLD_ast '-D_AST_git_commit="8e45daea"' -Os -I. -I/Users/mwilson/src/ksh/src/lib/libast -Icomp -I/Users/mwilson/src/ksh/src/lib/libast/comp -Iport -I/Users/mwilson/src/ksh/src/lib/libast/port -Isfio -I/Users/mwilson/src/ksh/src/lib/libast/sfio -Iinclude -I/Users/mwilson/src/ksh/src/lib/libast/include -Istd -I/Users/mwilson/src/ksh/src/lib/libast/std -I/Users/mwilson/src/ksh/arch/darwin.i386-64/include -D_PACKAGE_ast -c /Users/mwilson/src/ksh/src/lib/libast/port/mc.c
In file included from /Users/mwilson/src/ksh/src/lib/libast/port/mc.c:31:
In file included from /Users/mwilson/src/ksh/src/lib/libast/sfio/sfhdr.h:302:
./FEATURE/float:150:2: error: Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:151:2: error: Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:152:2: error: Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
3 errors generated.
mamake [lib/libast]: *** exit code 1 making mc.o
mamake: *** exit code 1 making lib/libast
mamake: *** exit code 1 making all
package: make done  at Tue Jan 26 17:46:32 PST 2021 in /Users/mwilson/src/ksh/arch/darwin.i386-64

**Comment by posguy99** [comment]
iffe: test: Stdio fseek/fflush are X/Open-compliant ...
In file included from <built-in>:367:
<command line>:3:26: warning: missing terminating '"' character [-Winvalid-pp-token]
#define _AST_git_commit \"206bba4f\"
                         ^
./4907.c:52:11: error: implicit declaration of function 'creat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if((fd = creat(file,0666)) < 0)
                 ^
./4907.c:58:7: error: implicit declaration of function 'write' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (write(fd,buf,sizeof(buf)) != sizeof(buf))
                    ^
./4907.c:58:7: note: did you mean 'fwrite'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:165:9: note: 'fwrite' declared here
size_t   fwrite(const void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream) __DARWIN_ALIAS(fwrite);
         ^
./4907.c:59:11: error: implicit declaration of function 'unlink' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        return Failed(file);
                               ^
./4907.c:39:23: note: expanded from macro 'Failed'
#define Failed(file)    (unlink(file),1)
                         ^
./4907.c:60:2: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        close(fd);
        ^
./4907.c:63:11: error: implicit declaration of function 'dup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
           (fd = dup(fileno(f1))) < 0 ||
                 ^
1 warning and 5 errors generated.
iffe: ... no
sed: FEATURE/sfio: No such file or directory
+ cc -D_BLD_DLL -fPIC -D_BLD_ast '-D_AST_git_commit="206bba4f"' -Os -I. -I/Users/mwilson/src/ksh/src/lib/libast -Icomp -I/Users/mwilson/src/ksh/src/lib/libast/comp -Iport -I/Users/mwilson/src/ksh/src/lib/libast/port -Isfio -I/Users/mwilson/src/ksh/src/lib/libast/sfio -Iinclude -I/Users/mwilson/src/ksh/src/lib/libast/include -Istd -I/Users/mwilson/src/ksh/src/lib/libast/std -I/Users/mwilson/src/ksh/arch/darwin.i386-64/include -D_PACKAGE_ast -c /Users/mwilson/src/ksh/src/lib/libast/port/mc.c
In file included from /Users/mwilson/src/ksh/src/lib/libast/port/mc.c:31:
In file included from /Users/mwilson/src/ksh/src/lib/libast/sfio/sfhdr.h:302:
./FEATURE/float:150:2: error: Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:151:2: error: Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
./FEATURE/float:152:2: error: Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
#error Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS= -d1 to debug.
 ^
3 errors generated.
mamake [lib/libast]: *** exit code 1 making mc.o
mamake: *** exit code 1 making lib/libast
mamake: *** exit code 1 making all
package: make done  at Tue Jan 26 19:19:02 PST 2021 in /Users/mwilson/src/ksh/arch/darwin.i386-64

**Comment by posguy99** [comment]
It doesn't like that iffe isn't including stdio.h now, the build log has errors about things like implicit definition of fprintf.  I reverted that and now iffe doesn't bomb out the tests.

**Comment by posguy99** [comment]
[make.txt](https://github.com/ksh93/ksh/files/5877880/make.txt)
^ the make.out now that I got it to pay attention to IFFEFLAGS

**Comment by McDutchie** [comment]
Very odd, works for me on Mojave, all three BSDs, Linux, and Solaris. And iffe does already include that stdio.h itself, you can see it in the code. So something is going on that I'm not understanding.

If you restore the `#include <stdio.h>` for just the float feature tests, will it build on Catalina, or will it now fail at another point?
```sh
git checkout -f 8e45daea && git log -p -1 src/lib/libast/features/float | patch -Rp1 && bin/package make
```

**Comment by McDutchie** [comment]
@posguy99, please let me know if current HEAD builds now.

**Comment by posguy99** [comment]
Yes, and passes all shtests.

--
Marc Wilson
posguy99@gmail.com
