### ISSUE TITLE
Arithmetic operators like `*=` and `+=` do not work with indexed multi-dimensional arrays

### ISSUE THREAD

**Issue by sdesj** [ksh93/ksh#168]
Operators like `*=` and `+=` in ksh arithmetic evaluation `(( ))` does not work properly when the variable is an indexed multi-dimensionnal array.
For example :
```
typeset -a FOO ; FOO[0]=(3 4)
(( FOO[0][1] *= 2 ))
```
You should expect to have values (3 8) in the ${FOO[0]} array. Instead, the variable is not changed. Worse, if you do the same thing with the index 1, you will obtain values (8 4).
However, I wasn't able to reproduce this issue with associative arrays.
You will find below a very small script I used to test the issue on different system/ksh version, and I confirm the issue on

- SLES 11 and SLES 12 with ksh Version AJM 93u+ 2012-08-01   (I think this ksh version is altered by SuSE)
- ubuntu 18.04.05 LTS with ksh Version AJM 93u+ 2012-08-01
- AIX 7.1 with ksh Version M 93t+ 2009-05-01 but results are not exactly the same
- Solaris 11.4 with ksh Version AJM 93u+ 2012-08-01

Output results of my tests:
```
KSH_VERSION : Version AJM 93u+ 2012-08-01

=== indexed array ===

--- IDX 0 ---
  "FOO*=2" notation : 3 4
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 4
  "FOO++" notation : 3 5
--- IDX 1 ---
  "FOO*=2" notation : 8 4
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 5 4
  "FOO++" notation : 3 5
--- IDX 2 ---
  "FOO*=2" notation : 3 4
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 4
  "FOO++" notation : 3 5
--- IDX 3 ---
  "FOO*=2" notation : 3 4
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 4
  "FOO++" notation : 3 5

=== associative array ===

--- IDX A ---
  "FOO*=2" notation : 3 8
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 5
  "FOO++" notation : 3 5
--- IDX B ---
  "FOO*=2" notation : 3 8
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 5
  "FOO++" notation : 3 5
--- IDX C ---
  "FOO*=2" notation : 3 8
  "FOO=FOO*2" notation : 3 8
  "FOO+=1" notation : 3 5
  "FOO++" notation : 3 5
```

On AIX, nothing works, either the indexed arrays and the associative array and each notation. I wasn't even able to find a workaround:
`FOO[0][1]=$(( FOO[0][1] * 2 ))`
end with (3 0) as a result.

Ugly script used:
```
#/usr/bin/ksh

print "KSH_VERSION : ${KSH_VERSION}"

print '\n=== indexed array ===\n'
for I in {0..3}
do
  print -- "--- IDX $I ---"

   # *=
  unset FOO ; typeset -a FOO ; FOO[${I}]=(3 4)
  (( FOO[${I}][1] *= 2 ))
  print "  \"FOO*=2\" notation : ${FOO[${I}][*]}"

   #  = *2
  unset FOO ; typeset -a FOO ; typeset -a FOO[${I}]=(3 4)
  (( FOO[${I}][1] = FOO[${I}][1] * 2 ))
  print "  \"FOO=FOO*2\" notation : ${FOO[${I}][*]}"

  #  +=1
  unset FOO ; typeset -a FOO ; typeset -a FOO[${I}]=(3 4)
  (( FOO[${I}][1] += 1 ))
  print "  \"FOO+=1\" notation : ${FOO[${I}][*]}"

  #  ++
  unset FOO ; typeset -a FOO ; typeset -a FOO[${I}]=(3 4)
  (( FOO[${I}][1]++ ))
  print "  \"FOO++\" notation : ${FOO[${I}][*]}"

done


print '\n=== associative array ===\n'
for I in A B C
do
  print -- "--- IDX $I ---"

   # *=
  unset FOO ; typeset -A FOO ; FOO[${I}]=(3 4)
  (( FOO[${I}][1] *= 2 ))
  print "  \"FOO*=2\" notation : ${FOO[${I}][*]}"

   #  = *2
  unset FOO ; typeset -A FOO ; FOO[${I}]=(3 4)
  (( FOO[${I}][1] = FOO[${I}][1] * 2 ))
  print "  \"FOO=FOO*2\" notation : ${FOO[${I}][*]}"

  #  +=1
  unset FOO ; typeset -A FOO ; FOO[${I}]=(3 4)
  (( FOO[${I}][1] += 1 ))
  print "  \"FOO+=1\" notation : ${FOO[${I}][*]}"

  #  ++
  unset FOO ; typeset -A FOO ; FOO[${I}]=(3 4)
  (( FOO[${I}][1]++ ))
  print "  \"FOO++\" notation : ${FOO[${I}][*]}"

done


```

**Comment by McDutchie** [comment]
Thanks for the report. I can confirm that 93u+m currently produces results identical to 93u+. So does ksh2020 (the abandoned fork of the abandoned 93v- beta), so there's no fix to backport from there either.

**Comment by hyenias** [comment]
Here are my observations:

Edited: [All works] ~Given a multidimensional indexed string array, appending a string using subscripts other than 0 fail as the **target** of the operation is applied to top level array using the subscript offset.~
```
works:
$ typeset -a arr=((a b c) 1); arr+=(2); typeset -p arr
typeset -a arr=((a b c) 1 2)
$ typeset -a arr=((a b c) 1); arr[0]+=(d); typeset -p arr
typeset -a arr=((a b c d) 1)
$ typeset -a arr=((a b c) 1); arr+=d; typeset -p arr
typeset -a arr=((ad b c) 1)
$ typeset -a arr=((a b c) 1); arr[0]+=d; typeset -p arr
typeset -a arr=((ad b c) 1)
$ typeset -a arr=((a b c) 1); arr[1]+=d; typeset -p arr
typeset -a arr=((a b c) 1d)
$ typeset -a arr=((a b c) 1); arr[2]+=d; typeset -p arr
typeset -a arr=((a b c) 1 d)
$
```
Given a multidimensional indexed integer array, arithmetic operations on subscripts other than 0 fail as the **result** of the operation is applied to top level array using the subscript offset as its destination.
```
works:
$ typeset -a -i arr=((10 11 12) 3 4); (( arr += 2 )); typeset -p arr
typeset -a -i arr=((12 11 12) 3 4)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[0] += 2 )); typeset -p arr
typeset -a -i arr=((12 11 12) 3 4)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[0][0] += 2 )); typeset -p arr
typeset -a -i arr=((12 11 12) 3 4)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[1] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12) 5 4)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[2] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12) 3 6)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[3] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12) 3 4 2)

fails:
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[0][1] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12) 13 4)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[0][2] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12) 3 14)
$ typeset -a -i arr=((10 11 12) 3 4); (( arr[0][3] += 2 )); typeset -p arr
typeset -a -i arr=((10 11 12 0) 3 4 2)
```
 From the reproducer:
```
from index[0] (which is a subarray), fails:
$ unset FOO; typeset -a FOO ; FOO[0]=(3 4); typeset -p FOO; (( FOO[0][1] *= 2 )); typeset -p FOO
typeset -a FOO=((3 4) )
typeset -a FOO=((3 4) 8)
$ unset FOO; typeset -a -i FOO ; FOO[0]=(3 4); typeset -p FOO; (( FOO[0][1] *= 2 )); typeset -p FOO
typeset -a -i FOO=((3 4) )
typeset -a -i FOO=((3 4) 8)

from index[1] (default scalar string), works:
$ unset FOO; typeset -a FOO ; FOO[0]=(3 4); typeset -p FOO; (( FOO[1] *= 2 )); typeset -p FOO
typeset -a FOO=((3 4) )
typeset -a FOO=((3 4) 0)
$ unset FOO; typeset -a -i FOO ; FOO[0]=(3 4); typeset -p FOO; (( FOO[1] *= 2 )); typeset -p FOO
typeset -a -i FOO=((3 4) )
typeset -a -i FOO=((3 4) 0)

When a skipped interval indexed array is used, it appears the operation places the result using the subscript offset:
$ unset FOO ; typeset -a FOO ; FOO[1]=(3 4); typeset -p FOO; (( FOO[1][1] *= 2 )); typeset -p FOO
typeset -a FOO=([1]=(3 4) )
typeset -a FOO=([1]=(8 4) )
$
$ unset FOO ; typeset -a FOO ; FOO[2]=(3 4); typeset -p FOO; (( FOO[2][1] *= 2 )); typeset -p FOO
typeset -a FOO=([2]=(3 4) )
typeset -a FOO=([1]=8 [2]=(3 4) )
$ unset FOO ; typeset -a FOO ; FOO[3]=(3 4); typeset -p FOO; (( FOO[3][2] *= 2 )); typeset -p FOO
typeset -a FOO=([3]=(3 4) )
typeset -a FOO=([2]=0 [3]=(3 4 ) )
$
```

**Comment by hyenias** [comment]
Just wanted to check in and indicate that I have just made some forward progress. For the first time, I can do the following without crashing my build or having some sort of garbled output. :)) Its just been so hard that even this little success feels so good. No idea if it will pan out or not.
```ksh
$ arch/*/bin/ksh -c 'typeset -a -i arr=((10 20 30) 1 2); ((arr[0][1]+=1)); typeset -p arr'
typeset -a -i arr=((10 21 30) 1 2)
```

**Comment by McDutchie** [comment]
Nice, @hyenias. Could you show a patch of what you've got so far?

**Comment by hyenias** [comment]
It be too embarrassing with all the debug print statements and commented out lines with various attempts I have made with editing code. Just wanted to let all know that I have been working on this issue so efforts are not duplicated. When I get my work to a point to share with others, I will.

**Comment by hyenias** [comment]
Checking in again. I have made progress. Currently, everything passes my hand testing and the included bin/shtests but my full testing script shows many errors outstanding. Next up, see what is going on with my testing script then code cleanup.

**Comment by hyenias** [comment]
@sdesj I have created #296 to solve this issue. It does not solve all issues with multidimensional arrays but to my knowledge fixes the assignment operations for indexed arrays. While testing I became aware of other issues, see my [arrmath](https://github.com/hyenias/code/blob/main/ksh/arrmath.ksh) testing script. In particular given `arr=((10 20 30) 1 2)`, attempting to use partial subscripts such as arr and arr[0] was problematic. So, when performing arithmetic assignment operations make sure to use a fully qualified subscript.
