### ISSUE TITLE
Some questions about searching in history

### ISSUE THREAD

**Issue by DesantBucie** [ksh93/ksh#169]
Hi,

This is not an issue report or feature request post. I'm just asking for help.

In ksh emacs mode "search in history" is triggered by `Ctrl+r`. This is a little bit annoying as, you have to first remember to switch to search in history and then type desirable command to fill. 

Now, i'd like to find a way to take user input, and while some combination of keys is pressed, ksh alias/script would take current user input, put it into search in history mode, and printed result.
"ssh => press ctrl+sth => fill() "ssh root@mydoimain...."

Now i've searched for my solution for a couple of minutes, and i didn't find anything, so i thought maybe you will be able to help me. Two more questions:

Is there an accessible env variable that holds current user input?
Is there maybe a built-in solution that i haven't heard of?

**Comment by posguy99** [comment]
I type what I want to search for and hit up-arrow.

From the fine man page...

     M-[A      (Up arrow) If the cursor is at the end of the line, it is equivalent to ^R with string  set
                 to the contents of the current line.  Otherwise, it is equivalent to ^P.


--
Marc Wilson
posguy99@gmail.com

**Comment by DesantBucie** [comment]
Ah yes, i had different alias for the up arrow and I found a problem with that solution.

https://user-images.githubusercontent.com/46130107/107634719-467f1980-6c6a-11eb-8a2a-0112d21be8df.mov

When i will fill something from history and erase my input, and enter new, it still searches old input. It's like:
ssh (up arrow) => ssh root@xxx (backspace) => vim (up arrow) => ssh root@xxx

**Comment by posguy99** [comment]
I can make that happen with ksh93u+, I can't make it happen with ksh93u+m.  Which and who's ksh are you using?

**Comment by DesantBucie** [comment]
I'm using u+m, but i tried u+ from 2012 as well. I probably did mistake while making my own aliases, as i did alias arrows, already being in emacs mode, and now it seems to work.

**Comment by McDutchie** [comment]
Since the question seems to be resolved, I'll close this issue now.
