### ISSUE TITLE
`case' unmatched when the case list is empty

### ISSUE THREAD

**Issue by oguz-ismail** [ksh93/ksh#177]
```
$ ksh -c 'case x in esac'
ksh: syntax error at line 1: `case' unmatched
```
`case x in esac` is syntactically correct, that error is unexpected here.

**Comment by McDutchie** [comment]
Yes. Not that anyone ever does this, which is probably why this bug was never fixed in ksh93. It's in every ksh93 version, but not in ksh88. Thanks for the report.

**Comment by McDutchie** [comment]
Hmm. It accepts an empty `case` list with a newline before the `esac`:

```
$ ksh -c $'case x in\nesac'
```
(no output)

**Comment by McDutchie** [comment]
The syntax error is thrown from line 629 in this function. The value of `tok` is 2048 (`EOFSYM`) when the syntax error is thrown, or a value corresponding to whatever follows the `esac` -- so the parser seems to skip past it for some reason (?). See [include/shlex.h](https://github.com/ksh93/ksh/blob/5be585f45b4ba61aa61cd8951f5e9e5d9a7ba623/src/cmd/ksh93/include/shlex.h#L69-L89) for the token definitions. I've no idea yet how to avoid the syntax error; so far all my attempts have failed. I am not close to understanding how the parser actually works.
https://github.com/ksh93/ksh/blob/5be585f45b4ba61aa61cd8951f5e9e5d9a7ba623/src/cmd/ksh93/sh/parse.c#L604-L648

**Comment by McDutchie** [comment]
We do find an interesting tidbit in the code: ksh93 also supports the undocumented syntax `case foo { bar) stuff ;; }`.

**Comment by McDutchie** [comment]
When compiling with [`-DDBUG`](https://github.com/ksh93/ksh/blob/29b11bba3ac25f468ef8db4829cd64d4d0ca5330/src/cmd/ksh93/sh/lex.c#L290-L314) to get debug output from lex.c, the output is:

```
$ arch/*/bin/ksh -c $'case x in esac'       
41507: line 1: 415: case
41507: line 1: 0: x
41507: line 1: 405: in
41507: line 1: 0: esac
41507: line 1: 4000: end of file
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `case' unmatched
```

The value 0 for `esac` looks wrong -- the octal token value for it is 410 (`ESACSYM`).

This makes the check on line 611-612 in `syncase()` fail; `esym` is set to the end symbol (`ESACSYM` or `RBRACE`) and if the token is 0, it won't match either.

But why is it 0? I've not the foggiest idea. But the bug must be somewhere in lex.c.

If we insert the newline, `esac` gets the expected 410 value:

```
$ arch/*/bin/ksh -c $'case x in\nesac'
41513: line 1: 415: case
41513: line 1: 0: x
41513: line 1: 405: in
41513: line 2: 12: newline
41513: line 2: 410: esac
41513: line 2: 4000: end of file
```

**Comment by McDutchie** [comment]
> But why is it 0?

The token variable `c` is 0 because it is set to 0 on line 1484 below (near the end of `sh_lex()`), and it's never set to the results of `sh_lookup()` on line 1488 because `lp->lex.reservok` is 0/false; reserved words such as `esac` are not recognised.

Why is that? Because of lines 1506-1507. An `in` (`INSYM`) reserved word unconditionally makes subsequent reserved words not recognised as such. This is correct for `for foo in esac` and `select foo in esac`, but for `case x in esac`, that is wrong. My current hypothesis is that this is the bug.

https://github.com/ksh93/ksh/blob/29b11bba3ac25f468ef8db4829cd64d4d0ca5330/src/cmd/ksh93/sh/lex.c#L1484-L1543

**Comment by McDutchie** [comment]
So, it looks like this fixes it:
```diff
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index 31614b4..64487b4 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -1503,7 +1503,7 @@ breakloop:
 			}
 			else
 				lp->lex.skipword = 0;
-			if(c==INSYM)
+			if(c==INSYM && !lp->lex.incase)
 				lp->lex.reservok = 0;
 			else if(c==TIMESYM)
 			{
```

**Comment by McDutchie** [comment]
The fix in that diff has a side effect. The following is now a syntax error:
```
$ arch/*/bin/ksh -c 'case x in esac) ;; esac'
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `)' unexpected
```
I think that's unavoidable. Either we recognise a reserved word after `in`, or we do not.

It is also a syntax error on other shells:
```
$ mksh -c 'case x in esac) ;; esac' 
mksh: syntax error: unexpected ')'
$ bash -c 'case x in esac) ;; esac'
bash: -c: regel 1: syntaxfout nabij onverwacht symbool ')'
bash: -c: regel 1: `case x in esac) ;; esac'
$ zsh -c 'case x in esac) ;; esac' 
zsh:1: parse error near `)'
$ dash -c 'case x in esac) ;; esac'
dash: 1: Syntax error: ")" unexpected
$ yash -c 'case x in esac) ;; esac'
yash -c:1: syntax error: encountered `)' without a matching `('
```
You have to quote the `esac` matching string for this to work. IIRC, POSIX also specifies it this way.

However, do we risk breaking some historic/legacy ksh93 script by applying this fix? It's possible, although hard to imagine.

One possibility would be to fix it for POSIX mode only (the `-o posix` option, or when ksh is invoked as `sh`):

```diff
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index 31614b4..533c52f 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -1503,7 +1503,7 @@ breakloop:
 			}
 			else
 				lp->lex.skipword = 0;
-			if(c==INSYM)
+			if(c==INSYM && !(lp->lex.incase && sh_isoption(SH_POSIX)))
 				lp->lex.reservok = 0;
 			else if(c==TIMESYM)
 			{
```
After this diff:
```
$ arch/*/bin/ksh -c 'case x in esac'
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `case' unmatched
$ arch/*/bin/ksh --posix -c 'case x in esac'
$ arch/*/bin/ksh -c 'case x in esac) foo;; esac'
$ arch/*/bin/ksh --posix -c 'case x in esac) foo;; esac'
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `)' unexpected
```

**Comment by oguz-ismail** [comment]
> The fix in that diff has a side effect. The following is now a syntax error:
> 
> ```
> $ arch/*/bin/ksh -c 'case x in esac) ;; esac'
> arch/darwin.i386-64/bin/ksh: syntax error at line 1: `)' unexpected
> ```

And it should be. The fix you posted above seems to work fine, whether it should be limited to POSIX mode or not is up to you, I'm comfortable as long as there is a way to make it work.

**Comment by McDutchie** [comment]
(following on from [two comments back](https://github.com/ksh93/ksh/issues/177#issuecomment-779605457))

Hmm. On the other hand, an `esac` selector was already a syntax error in ksh93 if it was the second selector or on:
```
$ /bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
$ /bin/ksh -c 'case x in esac) foo;; esac'     
$ /bin/ksh -c 'case x in y) bar ;; esac) foo;; esac'
/bin/ksh: syntax error at line 1: `)' unexpected
```

This tells me that we do *not* need to make this fix conditional upon the posix option -- it was clearly never the intention that this not be a syntax error.

**Comment by McDutchie** [comment]
Also, a newline makes even the first unqoted `esac` pattern a syntax error again:
```
$ /bin/ksh -c $'case x in\nesac) foo;; esac'    
/bin/ksh: syntax error at line 2: `)' unexpected
```
