### ISSUE TITLE
${!FOO*} expansion does not include FOO itself

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#183]
`${!FOO*}` is supposed to be expanded to all variable names beginning with `FOO`. As the manual puts it:
```
       ${!prefix*}
              Expands to the names of the variables whose names begin with prefix.
```

However, on my system:

```
$ set|grep ^LANG
LANG=nl_NL.UTF-8
LANGUAGE=ia:nl:sv:en
$ echo ${!LANG*}
LANGUAGE
```

I believe `${!LANG*}` should also have included `LANG`. By definition, `LANG` begins with `LANG`.

----

*edit:* looks like this bug is fixed in ksh2020. So there is a fix to backport somewhere.

bash also supports this type of expansion and also includes `LANG`.

**Comment by McDutchie** [comment]
Hmm. The 1995 book (on page 189) documents a `${!prefix@}` variant that is supposed to be identical. And it does work identically, including this behaviour which I believe to be a bug.

**Comment by McDutchie** [comment]
To put this another way: I think the user may reasonably expect that
```sh
unset ${!LANG*} ${!LC_*}
```
unsets all the locale-related variables. However, it currently does not unset `LANG`.

**Comment by McDutchie** [comment]
> Hmm. The 1995 book (on page 189) documents a `${!prefix@}` variant that is supposed to be identical. And it does work identically, including this behaviour which I believe to be a bug.

Aha! They're not identical:

```
$ LC_one=1 LC_two=2 LC_3=three
$ printf %s\\n "${!LC_@}"     
LC_3
LC_one
LC_two
$ printf %s\\n "${!LC_*}"
LC_3 LC_one LC_two
$ (IFS=/; printf %s\\n "${!LC_*}")
LC_3/LC_one/LC_two
```

So, `"${!foo@}"` expands to one word per variable in the style of `"$@"`, whereas `"${!foo*}"` expands to one word containing variable names separated by the first character of IFS, in the style of `"$*"`.

None of that is documented in either the book or the manual page, so that's another TODO item.

**Comment by posguy99** [comment]
Silly question...

```
[11:12 AM][ttys001 +1][~]
[595] iMac $ set -o histexpand
[11:12 AM][ttys001 +1][~]
[596] iMac $ echo ${!LANG*}   
-ksh: !LANG: event not found
[11:13 AM][ttys001 +1][~]
[596] iMac $ set +o histexpand
[11:13 AM][ttys001 +1][~]
[597] iMac $ echo ${!LANG*}   

[11:13 AM][ttys001 +1][~]
[598] iMac $ 
```

I understand what ksh thinks the error means, but should the bang be interpreted that way in that construct?

**Comment by McDutchie** [comment]
I am not sure, because I'm prejudiced against history expansion. I hate it a lot because it overrides all other uses of `!`, even those in double quotes. And it does that at such a fundamental level you can't even go back one step in the history and fix your command line. It does that on bash, too. I turn that off and use history search (^R) and the `fc` command instead.

bash does not seem to interpret the `!` for history expansion inside the braces of an expansion, though:
```
$ set -o histexpand
$ printf %s\\n "$BASH_VERSION" ${!LANG@}
5.1.0(30)-rc2
LANG
LANGUAGE
```
So maybe we should call this a bug in ksh. My motivation to work on history expansion is really low, though. :-P

**Comment by posguy99** [comment]
zsh does mostly the same thing ksh does, although zsh is such a mess of twisty little options, I have no idea whether zsh could be told to do what bash does or not...

```
[11:36 AM][ttys000 +1][~]
[1421] mbp13 $ zsh
mwilson@mbp13 ~ % echo ${!LANG@}
zsh: event not found: LANG@
mwilson@mbp13 ~ % 
```

So there's that.

**Comment by McDutchie** [comment]
> Silly question...
> 
> ```
> [11:12 AM][ttys001 +1][~]
> [595] iMac $ set -o histexpand
> [11:12 AM][ttys001 +1][~]
> [596] iMac $ echo ${!LANG*}   
> -ksh: !LANG: event not found
> [11:13 AM][ttys001 +1][~]
> [596] iMac $ set +o histexpand
> [11:13 AM][ttys001 +1][~]
> [597] iMac $ echo ${!LANG*}   
> 
> [11:13 AM][ttys001 +1][~]
> [598] iMac $ 
> ```
> 
> I understand what ksh thinks the error means, but should the bang be interpreted that way in that construct?

I took a look at this again and it's actually not that difficult to fix: just consider `${` to escape a history expansion character, like `\` does. As far as I can tell, that is what bash does as well.

```diff
diff --git a/src/cmd/ksh93/edit/hexpand.c b/src/cmd/ksh93/edit/hexpand.c
index b0118213f..9b9886dc6 100644
--- a/src/cmd/ksh93/edit/hexpand.c
+++ b/src/cmd/ksh93/edit/hexpand.c
@@ -197,7 +197,7 @@ int hist_expand(const char *ln, char **xp)
 		if((*cp != hc[0] && *cp != hc[1] && *cp != hc[2]) 
 		   || (*cp == hc[1] && cp != ln))
 		{
-			if(*cp == '\\')	/* skip escaped designators */
+			if(*cp == '\\' || (cp > ln && cp[-1]=='$' && *cp == '{')) /* skip escaped designators */
 				sfputc(sh.stk,*cp++);
 			else if(*cp == '\'') /* skip quoted designators */
 			{
```
