### ISSUE TITLE
typeset -L/-R: string length breaks on multibyte characters

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#189]
See: https://github.com/ksh93/ksh/issues/142#issuecomment-703337434

Reproducer:
```sh
unset s
s='コーンシェル'
echo ${#s}
typeset -L s
typeset -p s
echo ${#s}
```
Output:
```
6
typeset -L 18 s='コーンシェル      '
12
```
Expected output:
```
6
typeset -L 6 s='コーンシェル'
6
```

**Comment by JohnoKing** [comment]
This is (partly) a regression introduced in ksh93u+ 2012-02-02 in the following diff ([2012-01-01 version for comparison](https://github.com/multishell/ksh93/blob/2345e82cf1f3d150e39f28b5fc3b624b4c31b998/src/cmd/ksh93/sh/name.c#L2829-L2833)):
```diff
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 20b0785f..77793f42 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -2828,7 +2828,7 @@ done:
 		return(cp);
 	}
 #endif
-	if((numeric=nv_size(np)) && up->cp && up->cp[numeric])
+	if(!nv_isattr(np,NV_LJUST|NV_RJUST) && (numeric=nv_size(np)) && up->cp && up->cp[numeric])
 	{
 		char *cp = getbuf(numeric+1);
 		memcpy(cp,up->cp,numeric);

```
When this change is reverted the bug is limited to the second line of output, although it causes a regression test failure:
```
$ ./reproducer.sh
6
typeset -L 18 s=コーンシェル
6

$ bin/shtests -p attributes
#### Regression-testing /home/johno/Documents/GitRepos/Clones/ksh/arch/linux.i386-64/bin/ksh ####
test attributes begins at 2021-02-23+11:12:55
	attributes.sh[488]: width of character '\001' is not zero
test attributes failed at 2021-02-23+11:12:55 with exit code 1 [ 121 tests 1 error ]
Total errors: 1
```

**Comment by hyenias** [comment]
I have been thinking about this issue.

**Comment by McDutchie** [comment]
Three years ago, I [wrote](#issue-812623210):
> Expected output:
> 
> ```
> 6
> typeset -L 6 s='コーンシェル'
> 6
> ```

Nope. This is wrong.

What I failed to understand back then, and finally do now, is that the `-L` and `-R` values do not count either bytes or characters. Their purpose is to justify. They count horizontal terminal positions. Double-width characters, like Japanese, occupy two horizontal terminal positions each, instead of one, and ksh takes this into account. (Also, control characters have no width and do not count at all.)

So the expected output is:

```
6
typeset -L 12 s=コーンシェル
6
```

**Comment by McDutchie** [comment]
The default width is [set in nv_newattr()](https://github.com/ksh93/ksh/blob/9a48c61e1e5cc0881d7126fe818fe32c429b4a0b/src/cmd/ksh93/sh/name.c#L2947-L2948) in name.c, using the results of [a simple strlen call](https://github.com/ksh93/ksh/blob/9a48c61e1e5cc0881d7126fe818fe32c429b4a0b/src/cmd/ksh93/sh/name.c#L2924). This is the bug. The following patch should fix it. See the [ast.h multibyte macros](https://github.com/ksh93/ksh/blob/9a48c61e1e5cc0881d7126fe818fe32c429b4a0b/src/lib/libast/include/ast.h#L199-L242) for reference.

(Note that, in 7577f389a6ed916138414ad8005721db04514fbd, I fixed mbwidth() to work for non-multibyte locales as well; as of that commit it returns no width, i.e. -1, for control characters, 1 for all others. So, mbwidth() should be called even for single-byte locales in the loop below, so the loop is simply always run and not only when mbwide() returns true.)

```diff
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 356203159..2574e6bbe 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -2945,7 +2945,20 @@ void nv_newattr (Namval_t *np, unsigned newatts, int size)
 					ap->nelem |= ARRAY_SCAN;
 			}
 			if(size==0 && !(newatts&NV_INTEGER) && (newatts&NV_HOST)!=NV_HOST && (newatts&(NV_LJUST|NV_RJUST|NV_ZFILL)))
+			{	/*
+				 * Calculate the default terminal width for -L, -R, -Z if no numeric option-argument was given.
+				 * Note: we count terminal positions, not characters (double-width adds 2, control char adds 0)
+				 */
+				char *cq = cp;
+				wchar_t c;
+				int w;
+				n = 0;
+				mbinit();
+				while(c = mbchar(cq))
+					if ((w = mbwidth(c)) > 0)
+						n += w;
 				size = n;
+			}
 		}
 		else if(!trans)
 			_nv_unset(np,NV_EXPORT);
```
