### ISSUE TITLE
Strange error when executing ksh script on AIX 7.x

### ISSUE THREAD

**Issue by HansH111** [ksh93/ksh#194]
We compiled (-maix64) the ksh93u+m version on a different AIX 7.2 system and moved that executable to an AIX 7.1 system  and on some scripts we get strange errors
  + CURWKDY=4
  + DIFFTIME=0
  + MISSEDNO=0
  + date '+%Y%m%d %H:%M:%S'
  scriptname line 4483: write to 1 failed [A file descriptor does not refer to an open file.]
  scriptname line 4483: open file limit exceeded [A file descriptor does not refer to an open file.]
 
Probably  has nothing to do with ksh....  because if we compile the ksh on the AIX 7.1 server, the same script has no problems.
The only difference is what we can see between the 2 binaries is the dependencies of libiconv location
on the AIX 7.2 binary it points to /usr/lib/libiconv.a(shr4_64.o)
on the AIX 7.1  binary it points to /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/8.3.0/../../../libiconv.a(libiconv.so.2)

I have no idea if this makes any difference...
Just wondering if you give me some pointers how to debug this further.

**Comment by McDutchie** [comment]
This seems relevant: https://www.ibm.com/support/pages/member-libiconvso2-not-found-archive

If you unset `LIBPATH` on AIX 7.1 before running the binary compiled on AIX 7.2, does the problem go away?

(Note: I only have access to AIX 7.1, via a [polarhome.com](http://www.polarhome.com/) account.)

**Comment by HansH111** [comment]
I tried it out,  but got same results.  (with set -x)

+ MISSEDNO=0
+ date '+%Y%m%d %H:%M:%S'
scriptname: line 4483: write to 1 failed [A file descriptor does not
refer to an open file.]
scriptname  line 4483: open file limit exceeded [A file descriptor
does not refer to an open file.]

If I run the script repeatedly it sometimes only reports the 1st error

I never heard of polarhome.com ,,, looks great...  I will get an
account on it and use an AIX version from there
You can close the issue.

thx for the support

**Comment by McDutchie** [comment]
Basically, as you've implied, it's not surprising you get unexpected/undefined results when ksh, at startup, is dynamically linked with a libiconv from a completely different vendor/developer (AIX vs GNU) than the one you compiled it with. I can't really explain the results you're getting but I'm not much inclined to dig further. What *is* surprising to me is that ksh didn't plainly refuse to start at all! Does AIX not have library version checking?

**Comment by HansH111** [comment]
Normally I don't experience any problems after I compiled with gcc on AIX
7.2 and distribute those binaries across the different servers with AIX 7.x
I am not sure if that libiconv is really causing that problem,, it is the
only difference I can see.
Other large scripts seems to just work....

But nevermind , I will first try to compile it using the polarhome service
and see if that will solve the problem...

.
