### ISSUE TITLE
vi: tab completion appears to write past input buffer

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#195]
This was discovered while debugging several completion-related editor state bugs as part of #71. Prior discussion:

@McDutchie in <https://github.com/ksh93/ksh/issues/71#issuecomment-656951783>:
> […] an inconsistent state occurs if you cause the menu to appear with two TABs (which also puts you in command mode) but then re-enter insert mode (e.g. with `a`) instead of entering a number. Fun fun fun.
> 
> ```
> $ ksh -o vi
> $ cd /
> $ bin/p            [press TAB twice]
> 1) pax
> 2) ps
> 3) pwd             [now press 'a' to re-enter insert mode, type 'wd' and then return]
> $ bin/pwd
> >                  [the PS2 prompt wrongly appears; pressing return then executes 'pwd']
> /
> $ 
> ```

@hvdijk in <https://github.com/ksh93/ksh/issues/71#issuecomment-785434187>:
> > That leaves the fourth bug in this issue, [the vi one](https://github.com/ksh93/ksh/issues/71#issuecomment-656951783). I've no clue where to look for the cause yet -- it may or may not even be in vi.c. Any ideas anyone? @JohnoKing @hyenias @lkujaw @hvdijk
> 
> What little I can quickly find without trying to understand the code: with the following debug patch:
> 
> ```diff
> --- a/src/cmd/ksh93/sh/lex.c
> +++ b/src/cmd/ksh93/sh/lex.c
> @@ -397,6 +397,7 @@ int sh_lex(Lex_t* lp)
>                                 fcseek(-LEN);
>                                 goto breakloop;
>                         case S_EOF:
> +                               write(2, "S_EOF\n", 6);
>                                 sp = fcfile();
>                                 if((n=lexfill(lp)) > 0)
>                                 {
> ```
> 
> After the Enter after tab completion, the `S_EOF` case is hit again, and the call to `lexfill(lp)` is what causes the prompt for more input (I think).
> 
> After the Enter without tab compltion, the `S_EOF` case is not hit again.
> 
> Hopefully this will speed up a deeper investigation by someone who actually understands the code.

@McDutchie in <https://github.com/ksh93/ksh/issues/71#issuecomment-785454292>:
> Here's another reproducer of the vi bug, suggesting the problem is a write past the end of the screen buffer (which also explains the `S_EOF` case being hit where it shouldn't be):
> 
> ```
> $ set -o vi
> $ cd /
> $ bin/p            [press TAB twice]
> 1) pax
> 2) ps
> 3) pwd             [now press '0' for start of line, then '$' for end of line]
> $ bin/p            [cursor is positioned one too far to the right! should be on the 'p', not next to it]
> ```
> 
> And from there on, if you press `a` and then type `wd`(return) to complete the command, you get unpredictable symptoms because we're now past the screen buffer, accessing presumably uninitialised memory. I've gotten everything from
> 
> ```
> $ bin/p????????wd
> ```
> 
> to
> 
> ```
> $ bin/pd
> ```
> 
> to an outright crash.

@hvdijk in <https://github.com/ksh93/ksh/issues/71#issuecomment-785457166>:
> On the lex side, the reason `S_EOF` is hit is because the newline character is not part of its input buffer. At that point, `_Fcin.fcptr` is `"bin/pwd\n"` when the bad tab completion is not performed, or `"bin/pwd"` if it is. If `"bin/pwd"` has been read without a terminating newline, getting more input is the right thing to do.

@McDutchie in <https://github.com/ksh93/ksh/issues/71#issuecomment-785462208>:
> Yes. That looks like correct behaviour on the lexer side of things. The bug is most likely somewhere in edit/vi.c, possibly in [this block](https://github.com/ksh93/ksh/blob/caf7ab6c71fdc0ed357582b03e93db41c609731e/src/cmd/ksh93/edit/vi.c#L2457-L2500) or a function called by it.

**Comment by hvdijk** [comment]
In `vi.c`'s `textmod` there is

```c
        case '=':               /** list file name expansions **/
...
                ++last_virt;
...
                if(ed_expand(vp->ed,(char*)virtual, &cur_virt, &last_virt, ch, vp->repeat_set?vp->repeat:-1)<0)
                {
...
                        last_virt = i;
...
                }
                else if((c=='=' || (c=='\\'&&virtual[last_virt]=='/')) && !vp->repeat_set)
                {
...
                }
                else
                {
...
                        --last_virt;
...
                }
                break;
```

That middle block does not restore `last_virt`, and everything goes wrong after that. That function used to restore `last_virt` until commit 4cecde1d (#41). The commit message says it was taken from ksh93v- and indeed this bug is also present in that version too. If I restore the `last_virt = i;` that was there originally, like below, then this bug seems to be fixed. I do not know why it was taken out, taking it out does not seem to be necessary to fix the original bug.

```diff
--- a/src/cmd/ksh93/edit/vi.c
+++ b/src/cmd/ksh93/edit/vi.c
@@ -2485,6 +2485,7 @@ addin:
                }
                else if((c=='=' || (c=='\\'&&virtual[last_virt]=='/')) && !vp->repeat_set)
                {
+                       last_virt = i;
                        vi_redraw((void*)vp);
                        return(GOOD);
                }
```

**Comment by McDutchie** [comment]
Thank you very much for that, Harald. I could have sworn I was able to reproduce this bug in 93u+ as well, but I clearly made that up somehow, because I can't now! Maybe it was ksh2020 I was testing -- the bug is in that version, as expected because it's based on 93v-.

Who knows why they removed that line. It may have been a simple editing mistake. It certainly doesn't seem to make sense.
