### ISSUE TITLE
emacs: autocomplete stops numeric input

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#198]
From Arnon Weinberg, 2012-12-23 07:15:19 UTC, at <https://bugzilla.redhat.com/889745>:
```
Description of problem:
Immediately after using autocomplete ([tab] or [esc][esc]) in ksh (emacs
mode), the terminal does not accept additional character input if the next
character pressed is a number - ie, if a file or directory starts with a
number, then it is not possible to type it out immediately after using
autocomplete.  Non-numeric characters work fine.

Version-Release number of selected component (if applicable):
>rpm -q ksh
ksh-20120801-3.fc17.i686

How reproducible:
Always

Steps to Reproduce:
1. mkdir -p test/123abc
2. cd test[tab]123abc
  
Actual results:
cd test/abc

Expected results:
cd test/123abc

Additional info:
This was working on a previous version of ksh: ksh-20100309-5.fc11.i586

Workarounds are to press a non-numeric key followed by backspace, or hit
[tab] again to get a list of options.
```
This bug still exists in 93u+m.

A [Red Hat patch](https://src.fedoraproject.org/rpms/ksh/blob/642af4d6/f/ksh-20120801-tabfix.patch) is available for it, but I didn't apply it because it breaks menu-based filename completion completely after the first slash: all digits are taken as literal characters then so it becomes impossible to select from the menu. A better fix is needed.

For reference and testing/tweaking purposes, here is that patch as a diff against the current code:
```diff
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index ef82360..1861e85 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1025,10 +1025,13 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 					ep->ed->e_tabcount=0;
 				else
 				{
+					int oldi = i;
 					i=ed_getchar(ep->ed,0);
 					ed_ungetchar(ep->ed,i);
-					if(digit(i))
+					if(isdigit(i) && oldi=='=')
 						ed_ungetchar(ep->ed,ESC);
+					else if (isdigit(i) || i=='\t')
+						ep->ed->e_tabcount=0;
 				}
 			}
 			else
```

**Comment by hyenias** [comment]
Disclaimer: I have very limited experience with using the tab completion or its related menu.

With that said, by reading this issue and trying it out. Here are my thoughts:

- A different numbering style might need to be used when the patterns start with a decimal which matches what the tab menu is using for its ordered list selection style.
- If you look at what html css does for list-style-type, perhaps decimal-leading-zero or lower-alpha might help solve the problem. Not sure how big the tab completion menu can be and if 26 letters from the lower-alpha is enough. That then leads to maybe just always using a zero making a new style of leading-zero-decimal list when the pattern match is numeric and does not start with a zero.  [list-style-type](https://www.w3.org/wiki/CSS/Properties/list-style-type%20?iframe=true&width=100%&height=100%)
- Of course the leading-zero-decimal list could use any character instead of zero perhaps minus, i.e. leading-char-decimal

**Comment by hyenias** [comment]
I was just smashing numeric keys trying to get out of the tab completion menu so I could select 123abc. I ended up hitting ESC+ESC and that provided "123abc/" string--not sure if it actually selected the `1) 123abc/` menu item. Never knew about the ESC+ESC completion. Additionally, I was able to escape out of the tab menu by hitting ESC+] so I could then do a TAB to get the remaining "123abc/".

**Comment by hyenias** [comment]
Or perhaps an easy solution as to not match the selection list entry with the initial pattern is to advance the selection by one, e.g. `2) 123abc/`.

**Comment by JohnoKing** [comment]
After testing this issue it looks like ksh93v- (2013-10-10 alpha) has fixed this bug in a different way than Red Hat:
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1009,7 +1009,10 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 			ep->mark = cur;
 			if(cur<1)
 				beep();
-			else if(ed_expand(ep->ed,(char*)out,&cur,&eol,i,count) < 0)
+			ch = i;
+			if(i=='\\' && ep->mark>0 && out[ep->mark-1]=='/')
+				i = '=';
+			if(ed_expand(ep->ed,(char*)out,&cur,&eol,ch,count) < 0)
 			{
 				if(ep->ed->e_tabcount==1)
 				{
@@ -1022,7 +1025,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 			else if(i=='=' || (i=='\\' && out[cur-1]=='/'))
 			{
 				draw(ep,REFRESH);
-				if(count>0)
+				if(count>0 || i=='\\')
 					ep->ed->e_tabcount=0;
 				else
 				{
```
I should note that the latter part of the patch above was originally applied in e8b3274a, then reverted in 16e4824c. I can't reproduce the bug described in the later commit when the full patch is applied, and from what I can tell it works correctly. @McDutchie are you able to break the ksh93v- patch?

**Comment by McDutchie** [comment]
Mostly works for me. Thanks. Would be nice to understand *how* it works, though...

One thing this changes: if `cur<1`, it still beeps but then continues processing, so we're back to getting a huge menu of every command on the system. The 93u+m fix can be kept by adding a `return(-1);` after the `beep();`.

**Comment by McDutchie** [comment]
I think this version of the patch is more understandable/readable. Since `ep->mark` was just set to `cur` we can use `cur` a few lines after that instead of `ep->mark`. Also the check for `ep->mark >0` is redundant in 93u+m since it will return if the cursor is at position zero.

What it seems to do is check if the character before the cursor is a slash, and if so, switch from `\` mode (filename completion) to `=` mode (which is normally for listing all matching file names upon `ESC` `=`).
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1008,8 +1008,14 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 		case '=':	/* escape = - list all matching file names */
 			ep->mark = cur;
 			if(cur<1)
+			{
 				beep();
-			else if(ed_expand(ep->ed,(char*)out,&cur,&eol,i,count) < 0)
+				return(-1);
+			}
+			ch = i;
+			if(i=='\\' && out[cur-1]=='/')
+				i = '=';
+			if(ed_expand(ep->ed,(char*)out,&cur,&eol,ch,count) < 0)
 			{
 				if(ep->ed->e_tabcount==1)
 				{
@@ -1022,7 +1028,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 			else if(i=='=' || (i=='\\' && out[cur-1]=='/'))
 			{
 				draw(ep,REFRESH);
-				if(count>0)
+				if(count>0 || i=='\\')
 					ep->ed->e_tabcount=0;
 				else
 				{
```
