### ISSUE TITLE
Add '-o posix' shell option

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#20]
Recent email correspondence with @kdudka has made me think that maybe, in making POSIX compliance front and centre to development here, I've been giving insufficient consideration to the fact that there is an installed base of set-and-forget ksh93 scripts still running, which may somehow depend on old non-compliant behaviour.

In principle, I'm still thinking that anyone who needs 100% bug compatibility should stick with exactly the version they are running. However, we can restore the documented or otherwise clearly intended non-compliant behaviour as part of an option that can be turned on and off.

Other shells such as bash, mksh and yash can do `set -o posix` to enable POSIX compliance mode. It is worth considering adding a similar option to ksh93. ksh should probably default to POSIX mode when invoked as sh, and to "legacy" otherwise. Having the posix option *off* would restore behaviour such as what has been fixed in 6a4972069fd9c338e53c6cae48be9d732e37dab4 *(edit: nah, that's just pure breakage, and completely undocumented)*, eeee77edd1fbffd350f626504208c6e5b2ec8fa2 *(edit: done in c607c48c84dc29b994d397bc31c8bd6fe6a9201b)*, and maybe 36da314c9e30d485c48abb7ed3c318b6e56dcb8d *(edit: nah, that was just a bug)*.

It would also keep the Bourne shell compatibility hack for a literal `[ -t ]` or `test -t` being interpreted as `[ -t 1 ]`/`test -t 1`. Korn hacked the [parser](https://github.com/ksh93/ksh/blob/764acefaf171f10924b850dd4942665d74419b04/src/cmd/ksh93/sh/parse.c#L1831) so that only a literal `[ -t ]` is changed and not something like `x=-t; [ "$x" ]`. Still, that hack violates POSIX and should be deactivated in any new POSIX mode. *(edit: done in 55f0f8ce52ec39a797a745031a60816f998ce01a)*

Let's think about this for a while before doing anything. We can talk about it in this issue's thread, and figure out a list of things that need to be switched by such an option.

**Comment by McDutchie** [comment]
One other thing that a `posix` option should control is the interpretation of numbers with initial zeros as octal in the `let` builtin, as currently controlled by the `letoctal` option. The `posix` option should enable the behaviour of `letoctal` regardless of the setting of the latter.

It is a little ambiguous because `let` is not actually specified by POSIX. However, shell arithmetic is specified, and `let` processes exactly that: it is a regular shell grammar version of the `((`…`))` arithmetic command. So it's actually quite bizarre that `let` and `((`...`))` behave differently by default.

*(edit: done in b301d41731945fe0a537277abc43f0410bff1e3f)*

**Comment by JohnoKing** [comment]
The Bash compatibility mode has a `posix` option:
https://github.com/ksh93/ksh/blob/8b51d12f4b6eae265112c3cfd67e84dabc08cb31/src/cmd/ksh93/data/options.c#L93
https://github.com/ksh93/ksh/blob/8b51d12f4b6eae265112c3cfd67e84dabc08cb31/src/cmd/ksh93/include/defs.h#L310

It was originally intended by the KSH authors to replicate the quirks present in the `posix` option Bash has, although this could also be used for implementing a backward compatibility mode with `set +o posix`.

**Comment by McDutchie** [comment]
```
$ ksh -c 'readonly foo=bar; unset -v foo; echo $?'
ksh: unset: warning: foo: is read only
1
```

POSIXly, unsetting a readonly variable is an error, not a warning (edit: at least I *think* so; the [spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_29) doesn't seem all that clear on it). So it should cause the special built-in command `unset` to exit, and never get to the `echo` command.

Fixing this unconditionally might cause incompatibilities with old scripts, so this is another one for the POSIX mode.

*(edit: Never mind, this is nontrivial. I don't understand why, but changing the relevant [`ERROR_warning(0)`](https://github.com/ksh93/ksh/blob/3ede73aa33801c7a60a364518e213566ed2e1d6c/src/cmd/ksh93/bltins/typeset.c#L797) into `ERROR_exit(1)` does not cause `unset` to exit the shell on error, even though it's defined as a special builtin. But mksh and bash don't exit either, and this is not important enough to spend more time on.)*

**Comment by JohnoKing** [comment]
POSIX mode should be enabled if `$POSIXLY_CORRECT` is set (like in bash). This would make the following commands equivalent:

```ksh
$ ksh -o posix
$ POSIXLY_CORRECT=1 ksh
```

**Comment by McDutchie** [comment]
I'm not really convinced making `POSIXLY_CORRECT` equivalent to `set -o posix` is a good idea; that variable is part of the GNU ecosystem, and ksh is not. Other systems like AIX and HP-UX have different variables for that, and Solaris has a different strategy altogether (POSIX compliant utilities are stored in /usr/xpg[764]/bin). Why should ksh prefer one over another?

As far as I know, bash is the only shell that honours any such variable, and it does it in a way that causes side effects and [corner case bugs](https://lists.gnu.org/archive/html/bug-bash/2020-01/msg00019.html). The posix option on pdksh/mksh is just that: a shell option. I think that's a better way.

However, the posix option should probably be enabled by default if ksh is invoked as sh.

**Comment by McDutchie** [comment]
ksh closes globally open file descriptors > 2 when executing external commands. That behaviour violates POSIX, which [states](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_12):

> Utilities other than the special built-ins […] shall be invoked in a separate environment that consists of the following. The initial value of these objects shall be the same as that for the parent shell, except as noted below.
> * Open files inherited on invocation of the shell, open files controlled by the exec special built-in plus any modifications, and additions specified by any redirections to the utility
> * […]

Also, no other shell acts like this, ~~not even mksh~~ except mksh, and it disables that behaviour in its POSIX mode. So here's another one to fix for the POSIX mode.

This fix should probably be added to [`sh_redirect()`](https://github.com/ksh93/ksh/blob/be5ea8bbb27cd39c2451e49b9d080ed40ba3f4e5/src/cmd/ksh93/sh/io.c#L1075-L1494); flag==2 should act like flag==1 when in POSIX mode.

*(edit: done in fd977388a265b1c4e3199f0ba7880986fb9d089a)*

**Comment by McDutchie** [comment]
> POSIX mode should be enabled if `$POSIXLY_CORRECT` is set (like in bash).

I'm changing my opinion on this. Turns out that libast already supports this variable. If you use the `getconf` builtin and do `getconf CONFORMANCE`, then the output is normally `ast`, but if `POSIXLY_CORRECT` was set on invoking ksh, the output is `standard`. The bash emulation mode used this to initialise POSIX mode on init, so ksh 93u+m should probably do so as well.

What I'm not going to do is change the option dynamically along with the variable (and vice versa) as bash does; there be dragons.

*(edit: done in 921bbcaeb706729a87bded701f02ea4c07fada08)*

*(edit 2: undone in 6affd23601439e2e00e29fbff5cf4eb627647ecb; see commit message)*
