### ISSUE TITLE
Unable to build 64bit version on AIX 

### ISSUE THREAD

**Issue by HansH111** [ksh93/ksh#200]
32 bit version compilation works, but I am unable to get a 64bit version compiled.
Probably has to do with my lack of knowledge
I use aix7.polarhome.com server for compilation.

-bash-4.2$ bin/package debug make HOSTTYPE="ibm.risc-64"
PACKAGEROOT=/home/h/hansh111/src/ksh-master
export PACKAGEROOT
HOSTTYPE=ibm.risc-64
export HOSTTYPE
INSTALLROOT=/home/h/hansh111/src/ksh-master/arch/ibm.risc-64
export INSTALLROOT
Assembler:
/tmp/cciMCKXq.s: line 9: Only .llong should be used for relocatable expressions.
/tmp/cciMCKXq.s: line 57: Only .llong should be used for relocatable expressions.
package: gcc: failed to compile and link /home/h/hansh111/src/ksh-master/src/cmd/INIT/hello.c -- is it a C compiler?
...

Martijn, can you tell how you compile it on polarhome.com for aix
 
thx

**Comment by McDutchie** [comment]
This works for me:
```sh
export CCFLAGS='-Os -maix64'
bin/package make
```
You gave me the `-maix64` flag yourself in #194. :)

**Comment by HansH111** [comment]
yes, I know..... seems something got stuck in my environment
because I couldn't compile any more with -maix64, i constantly got that
error.

so I logged out and in again, removed the arch directory and now it works..
thx

**Comment by McDutchie** [comment]
Deleting the arch directory is probably what fixed it. By providing a `HOSTTYPE` that didn't correspond with the compiler flags, that `arch` directory would have been populated with incorrect data.

**Comment by McDutchie** [comment]
By the way, the regression tests hang on AIX. I've found the cause and I'm working to fix it.
