### ISSUE TITLE
Unsetting a running function is silently ignored

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#21]
The segfault has been fixed. Now the problem is that *both* types of functions, POSIX and ksh, silently fail to unset themselves. See b7932e87b637b885423aafcd63108d04f0c204c6 and 975117485c9c52a2d94bcf1eb7ae7f44088a3302 and the issues referenced in them for more information.

_____
[Original report] It should not be this easy to make ksh segfault:

```
$ ksh -c 'fn() { unset -f fn; echo end; }; fn'
Segmentation fault: 11
```

**Comment by hyenias** [comment]
Please note that this memory fault (on macOS) does not occur using the KornShell style type of function as compared to the Bourne/POSIX style above. Within the KornShell style function, the unset command does not remove the running function nor causes a fault.
```
$ functions
$ function fn { unset -f fn; echo end; }
$ fn
end
$ functions
function fn { unset -f fn; echo end; }
$
```

**Comment by jghub** [comment]
also, it seems to be fixed in ksh93v-: I don't see the segfault there (on OSX).

**Comment by McDutchie** [comment]
I am not happy with the `function fn` behaviour either:

```sh
$ ksh -c 'function fn { unset -f fn; echo end; }; fn; fn'
end
end
```

Unsetting a function should never be silently ignored. If it refuses to unset, an error message should be printed at the very least.

Much better would be to do what all other shells do: make the name unavailable, but keep running the function, delaying its actual deletion until the run is complete.

*edit:* And that appears to be exactly what ksh2020 does (I can't get 93v- to compile on my machine at all). Looks like the fix is out there to be backported.

**Comment by hyenias** [comment]
To comment on the expectation of what ksh93 should do when unset is unable to perform its operation in some way, EXIT STATUS would be set to >0. 
```
$ unset --man
NAME
  unset - unset values and attributes of variables and functions

SYNOPSIS
  unset [ options ] name...

DESCRIPTION
  For each name specified, unset unsets the variable, or function if -f is specified, from the current shell execution environment.
  Readonly variables cannot be unset.

OPTIONS
  -n              If name refers to variable that is a reference, the variable name will be unset rather than the variable it
                  references. Otherwise, is is equivalent to -v.
  -f              name refers to a function name and the shell will unset the function definition.
  -v              name refers to a variable name and the shell will unset it and remove it from the environment. This is the default
                  behavior.

EXIT STATUS
    0     All names were successfully unset.
    >0    One or more name operands could not be unset or an error occurred.
```
A similar discussion about adding error messages was brought up when someone added error messages to the unalias command. The end result was more work had to be done to deal with the normally unwanted result of the error message(s), e.g. sending stderr/stdout to null.

**Comment by McDutchie** [comment]
I found the cause of the crash that the `unset -f` fix caused, so the fix has now been reapplied plus a fix for that crash, and `unset -f` no longer needs to error out on a function unsetting itself.
