### ISSUE TITLE
Ctrl+C in an exec'd interactive shell is buggy in some contexts

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#210]
This bug is a regression introduced in commit 41ebb55a. From my testing it can be reproduced on Linux but not FreeBSD or Solaris. When Ctrl+C is used in an interactive shell to send `SIGINT`, one of the following can happen:

1) An erroneous 'Interrupt' message is printed after stopping the `read` builtin in a script. Reproducer:
```sh
$ exec arch/*/bin/ksh
$ cat ./reproducer.sh 
#!/bin/sh
read foo

$ ./reproducer.sh 
^C$ <Enter>
[1] + Interrupt                ../reproducer.sh
```

2) Ctrl+C fails to stop `/bin/package make`. Reproducer:
```sh
$ exec arch/*/bin/ksh
$ mv arch arch.old
$ bin/package make
# Press Ctrl+C multiple times
```

**Comment by McDutchie** [comment]
I'm not having any success reproducing this on Linux. I'm testing it on Slackware 14.2 x86_64 on a VirtualBox VM, and Debian 10.8 x86_64 as hosted by xs4all.nl. I follow your exact steps but everything seems to work as it should.

FWIW, it doesn't reproduce for me on macOS, either.

**Comment by McDutchie** [comment]
This is a bit of a barely-educated guess in the dark, but does this partial revert make any difference to the problem on your end?
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index d8603bd6..59fc235b 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1628,7 +1628,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 					shp->bckpid = parent;
 				else if(!(type&(FAMP|FPOU)))
 				{
-					if(!sh_isstate(SH_MONITOR))
+					if(!sh_isoption(SH_MONITOR))
 					{
 						if(!(shp->sigflag[SIGINT]&(SH_SIGFAULT|SH_SIGOFF)))
 							sh_sigtrap(SIGINT);
@@ -1646,7 +1646,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 						sh_iorestore(shp,topfd,0);
 					if(usepipe && tsetio &&  subdup && unpipe)
 						sh_iounpipe(shp);
-					if(!sh_isstate(SH_MONITOR))
+					if(!sh_isoption(SH_MONITOR))
 					{
 						shp->trapnote &= ~SH_SIGIGNORE;
 						if(shp->exitval == (SH_EXITSIG|SIGINT))
```

**Comment by hyenias** [comment]
I am able to confirm the reproducer.sh using an Ubuntu 18.04 box. If I launch the ksh interpreter as a child process to bash then I do not get the error. If I use the exec command to replace my login shell interpreter with ksh only, then the  reproducer.sh works. To be clear, after I issue a CTRL+C when reproducer.sh is running; I hit the ENTER key.
```sh
exec ./ksh
$ ps
  PID TTY          TIME CMD
 2549 pts/0    00:00:00 ksh
 2946 pts/0    00:00:00 ps
$ set --state
set --default --bgnice --braceexpand --emacs --monitor --multiline --viraw
$ ./reproducer.sh
^C$
[1] + Interrupt                ./reproducer.sh
$
$ exec /bin/bash
~/ksh93/bin$ ./ksh
$ ps
  PID TTY          TIME CMD
 2549 pts/0    00:00:00 bash
 2972 pts/0    00:00:00 ksh
 2976 pts/0    00:00:00 ps
$ ./reproducer.sh
^C$
$
```

**Comment by hyenias** [comment]
Just confirmed 2nd reproducer trying to issue Ctrl+C to stop `bin/package make`. Also, when the compile finally finished, I did not get a blinking command prompt back, so I hit ENTER and got the following:
```
+ /bin/cp /home/hyenias/git/hyenias/ksh93/src/cmd/ksh93/fun/pushd /home/hyenias/git/hyenias/ksh93/arch/linux.i386-64/fun/pushd
+ chmod ugo+x /home/hyenias/git/hyenias/ksh93/arch/linux.i386-64/fun/pushd
package: make done  at Sun Mar  7 08:37:44 EST 2021 in /home/hyenias/git/hyenias/ksh93/arch/linux.i386-64

[1] +  Done                    bin/package make
$
```

**Comment by McDutchie** [comment]
Both reproducers confirmed on Slackware now. Thanks for the clarifications, @hyenias.

**Comment by McDutchie** [comment]
Can also report that my wild-guess patch makes no difference to the problem.

**Comment by McDutchie** [comment]
So, my next hunch is that job control is failing to initialise properly under the conditions that trigger the bug.

To verify that, I'm using the following debug patch to [`job_init()`](https://github.com/ksh93/ksh/blob/aad74597f7e7bf5ee3a58d59f964e5880731fb20/src/cmd/ksh93/sh/jobs.c#L490-L638)...

```diff
--- a/src/cmd/ksh93/sh/jobs.c
+++ b/src/cmd/ksh93/sh/jobs.c
@@ -510,13 +510,17 @@ void job_init(Shell_t *shp, int lflag)
 #   else
 		if(ioctl(JOBTTY,TIOCGETD,&job.linedisc) !=0)
 #   endif /* FIOLOOKLD */
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 1\n");
 			return;
+}
 		if(job.linedisc!=NTTYDISC && job.linedisc!=OTTYDISC)
 		{
 			/* no job control when running with MPX */
 #   if SHOPT_VSH
 			sh_onoption(SH_VIRAW);
 #   endif /* SHOPT_VSH */
+sfprintf(sfstderr,"[DEBUG] job_init(): return 2\n");
 			return;
 		}
 		if(job.linedisc==NTTYDISC)
@@ -538,11 +542,17 @@ void job_init(Shell_t *shp, int lflag)
 		if(sh_isoption(SH_INTERACTIVE))
 		{
 			if(job.mypgid<0 || !(ttynam=ttyname(JOBTTY)))
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 3\n");
 				return;
+}
 			while(close(JOBTTY)<0 && errno==EINTR)
 				;
 			if((fd = open(ttynam,O_RDWR)) <0)
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 4\n");
 				return;
+}
 			if(fd!=JOBTTY)
 				sh_iorenumber(shp,fd,JOBTTY);
 #ifdef SIGTSTP
@@ -559,7 +569,10 @@ void job_init(Shell_t *shp, int lflag)
 		while((job.mytgid=tcgetpgrp(JOBTTY)) != job.mypgid)
 		{
 			if(job.mytgid <= 0)
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 5\n");
 				return;
+}
 			/* Stop this shell until continued */
 			signal(SIGTTIN,SIG_DFL);
 			kill(shp->gd->pid,SIGTTIN);
@@ -567,6 +580,7 @@ void job_init(Shell_t *shp, int lflag)
 			if(ntry++ > IOMAXTRY)
 			{
 				errormsg(SH_DICT,0,e_no_start);
+sfprintf(sfstderr,"[DEBUG] job_init(): return 6\n");
 				return;
 			}
 		}
@@ -581,16 +595,25 @@ void job_init(Shell_t *shp, int lflag)
 #   ifdef FIOPUSHLD
 		tty_get(JOBTTY,&my_stty);
 		if (ioctl(JOBTTY, FIOPOPLD, 0) < 0)
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 7\n");
 			return;
+}
 		if (ioctl(JOBTTY, FIOPUSHLD, &linedisc) < 0)
 		{
 			ioctl(JOBTTY, FIOPUSHLD, &job.linedisc);
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 8\n");
 			return;
+}
 		}
 		tty_set(JOBTTY,TCSANOW,&my_stty);
 #   else
 		if(ioctl(JOBTTY,TIOCSETD,&linedisc) !=0)
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 9\n");
 			return;
+}
 #   endif /* FIOPUSHLD */
 		if(lflag==0)
 			errormsg(SH_DICT,0,e_newtty);
@@ -599,14 +622,20 @@ void job_init(Shell_t *shp, int lflag)
 #endif /* NTTYDISC */
 	}
 	if(!possible)
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 10: not possible\n");
 		return;
+}
 
 #ifdef SIGTSTP
 	/* make sure that we are a process group leader */
 	setpgid(0,shp->gd->pid);
 	job.mypid = shp->gd->pid;
 	if(!sh_isoption(SH_INTERACTIVE))
+{
+sfprintf(sfstderr,"[DEBUG] job_init(): return 11: OK, but not interactive\n");
 		return;
+}
 #   if defined(SA_NOCLDSTOP) || defined(SA_NOCLDWAIT)
 #   	if !defined(SA_NOCLDSTOP)
 #	    define SA_NOCLDSTOP	0
@@ -634,6 +663,7 @@ void job_init(Shell_t *shp, int lflag)
 	sh_onoption(SH_MONITOR);
 	job.jobcontrol++;
 #endif /* SIGTSTP */
+sfprintf(sfstderr,"[DEBUG] job_init(): return 12: OK!\n");
 	return;
 }
 
```

A normal ksh launch on Slackware 14.2 outputs:
```
$ arch/*/bin/ksh
[DEBUG] job_init(): return 12: OK!
```
But when I replace my bash login shell by ksh using `exec`, I get:
```
$ exec arch/*/bin/ksh
[DEBUG] job_init(): return 10: not possible
```
So, the `possible` flag is failing to be set for some reason.

**Comment by McDutchie** [comment]
I think I found the bug.

Before 41ebb55a: https://github.com/ksh93/ksh/blob/37a18bab7173427ce045c9a67772cb98eb678cb7/src/cmd/ksh93/sh/jobs.c#L552

As of 41ebb55a: https://github.com/ksh93/ksh/blob/41ebb55a3a9133f58cf3cc1c47e83bb5dc11404e/src/cmd/ksh93/sh/jobs.c#L555-L556

This is wrong, I screwed up there. Before this commit, `possible` was set to 1 (true) if `setpgid()` either succeeded or failed with `EPERM`. After that commit, it is only set to 1 if `setpgid()` succeeds.

Now to fix it and test...

**Comment by McDutchie** [comment]
After fixing my screw-up with the following patch, I can no longer reproduce the problem. @JohnoKing and @hyenias, can you confirm?
```diff
--- a/src/cmd/ksh93/sh/jobs.c
+++ b/src/cmd/ksh93/sh/jobs.c
@@ -552,8 +552,8 @@ void job_init(Shell_t *shp, int lflag)
                 job.mypgid = shp->gd->pid;
         }
 #ifdef SIGTSTP
-	possible = (setpgid(0,job.mypgid) >= 0);
-	if(sh_isoption(SH_INTERACTIVE) && (possible || errno==EPERM))
+	possible = (setpgid(0,job.mypgid) >= 0) || errno==EPERM;
+	if(sh_isoption(SH_INTERACTIVE) && possible)
 	{
 		/* wait until we are in the foreground */
 		while((job.mytgid=tcgetpgrp(JOBTTY)) != job.mypgid)
```

**Comment by JohnoKing** [comment]
I can no longer reproduce the bug after applying that patch.

**Comment by hyenias** [comment]
I have no idea how to successfully copy out the diff contents you keep supplying. After minutes of having a corrupt diff file created by my copy-and-paste method into a text editor, I gave up and just hand edited the file. Testing now.

**Comment by McDutchie** [comment]
Sorry about that @hyenias, copy/paste works for me... but then I just type `patch -p1`, Return, paste, and then press Ctrl+D. Maybe your editor expands the tabs to spaces, which would corrupt it. To tolerate whitespace changes you can try `patch -p1 -l` (or `-p1 --ignore-whitespace`).

**Comment by hyenias** [comment]
Confirmed. All works now.

**Comment by hyenias** [comment]
@McDutchie Thanks for the pointers. I have been using `git apply`. Always learning. So, I am able now to copy/paste comment diffs using `cat > file.patch` then CTRL+D. I will work on how to use the patch command and perhaps some options for the git apply. I give up on my command line text editors altering the input text stream or my web browser.

**Comment by McDutchie** [comment]
Heh, I had no idea `git apply` even existed, but knew `patch` long before I ever heard of git. Learning all the time...

**Comment by posguy99** [comment]
I copy them out of the github thread, then paste them into `mg `and save them.

Then:

`$ patch -p1 < the_patch_file`

From the root of the source tree.

I can't copy them out of my email, they always end up with no line endings.  Yay HTML email clients. :(

**Comment by McDutchie** [comment]
A shortcut is to just type `patch -p1` and paste the patch directly into its standard input (press Ctrl+D, or whatever you set as your `stty eof`, on a new line after pasting). To undo, just `git checkout` those files.

**Comment by posguy99** [comment]
Yeah, I'm with @hyenias ... I've had enough wacky issues with pasting text that tuned out to be enhanced some way or another that I want to see what I'm patching with.

**Comment by McDutchie** [comment]
I could provide downloadable patches instead if people prefer. The disadvantage would be that the patches then won't be part of the comment so things become harder to follow. But it avoids the possibility of copy/paste problems. Thoughts?

**Comment by hyenias** [comment]
I like seeing the colored diffs within the comments. More often than not, I look at the contents on screen than attempt to apply them to my git repo. Now, that I have been trained how to snip the diff contents and create a remote file.patch; I am good-to-go. I like seeing all the colors when I view the .patch file in my text editor. I bet, in time, github.com will enhance the web interface to allow us to download the embedded source text as diff or a file.

**Comment by posguy99** [comment]
My process works fine, no need to change it on my account.  I also like being able to read the diff in the discussion, even if my C is +20 years old and I don't necessarily understand them. :)
