### ISSUE TITLE
Tilde expansion weirdness with .sh.tilde builtin

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#217]
Something odd called `.sh.tilde` showed up in my tab completion list. This is how I found out that using a tilde expansion causes a `.sh.tilde` built-in command to be added:

```
$ ENV=/./dev/null arch/*/bin/ksh
$ type .sh.tilde
arch/darwin.i386-64/bin/ksh: type: .sh.tilde: not found
$ echo ~/foo
/Users/martijn/foo
$ type .sh.tilde
.sh.tilde is a shell builtin
```

***Warning:*** Running that built-in without any arguments will instantly crash your shell. This is easy to fix by adding a rudimentary arguments check to `sh_btilde()`. The fact that they didn't do this suggests this functionality is completely untested.

Running it with one argument performs tilde expansion and writes the result to standard output. Any further arguments are ignored.
```
$ .sh.tilde ~/foo
/Users/martijn/foo
```

The built-in itself is defined here. It simply calls `sh_tilde()` and writes the result to standard output. https://github.com/ksh93/ksh/blob/d2c1700f63597e1e1f2399a470446452b1fb12c4/src/cmd/ksh93/sh/macro.c#L2622-L2634

The built-in is added in this function, upon doing the first tilde expansion. Standard output is temporarily redirected to a stack so that the built-in can write the tilde expansion to standard output. https://github.com/ksh93/ksh/blob/d2c1700f63597e1e1f2399a470446452b1fb12c4/src/cmd/ksh93/sh/macro.c#L2636-L2680

The comment says `sh_btilde()` is the default discipline function for tilde expansion. That suggests it should be possible to override it. And indeed it is. However, it doesn't seem to work: standard output is not intercepted as expected, so the function does nothing.

```
$ ENV=/./dev/null arch/*/bin/ksh
$ function .sh.tilde { echo test; }
$ v=~/foo
test
$ echo $v
~
```

Digging through the multishell repo history shows this thing was added in the 2004-02-29 version. It has never been documented. I can't seem to make it work, or make sense. It seems like another failed experiment, one that they tried back in 2004 and then forgot about. Unless someone can find a way to make this make sense, I think it should be removed.

Thoughts? @JohnoKing @hyenias (and anyone else)

**Comment by McDutchie** [comment]
FWIW, the fix for the crash is:
```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index f62d5a19..6c337965 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -2625,8 +2625,10 @@ static int	charlen(const char *string,int len)
 static int sh_btilde(int argc, char *argv[], Shbltin_t *context)
 {
 	Shell_t *shp = context->shp;
-	char *cp = sh_tilde(shp,argv[1]);
-	NOT_USED(argc);
+	char *cp;
+	if(argc != 2)
+		return(1);
+	cp = sh_tilde(shp,argv[1]);
 	if(!cp)
 		cp = argv[1];
 	sfputr(sfstdout, cp, '\n');
```

**Comment by posguy99** [comment]
This is in ksh93u+ [release notes](https://github.com/att/ast/blob/master/src/cmd/ksh93/RELEASE):

	`12-06-14  builtin without argument no longer lists .sh.tilde as a built-in.`

So someone knew it was there then.

Clark Wang's comment [here](https://www.mail-archive.com/ast-users@research.att.com/msg01887.html) and Glenn Fowler's subsequent comment would add evidence that someone forgot it was there before that time. ^_^

Given the date of the supposed change and the ast-users thread, you'd almost think that the source code change was prompted by Glenn's comment.

Why would tilde expansion need a dicipline function anyway?

**Comment by McDutchie** [comment]
> So someone knew it was there then.

But only because someone noticed it show up in the output of `builtin`. That's no evidence that they knew what it was, or what it was for.

> Given the date of the supposed change and the ast-users thread, you'd almost think that the source code change was prompted by Glenn's comment.

That Glenn Fowler thought it was suspicious is kind of hilarious, and very telling. Nice find.

The change in question would be here: https://github.com/ksh93/ksh/blob/d2c1700f63597e1e1f2399a470446452b1fb12c4/src/cmd/ksh93/bltins/typeset.c#L1362-L1363
…which means "print all the builtins except `.sh.tilde`". What a hack. :-/

*edit:* That was done in the 2012-06-20 version, just 15 days after those comments. So that adds up.

> Why would tilde expansion need a dicipline function anyway?

Good question. I've no idea.

Unless I'm missing something, defining a discipline function never even worked for any purpose, so it's not as if it was missed.

**Comment by JohnoKing** [comment]
If the `.sh.tilde` builtin is deleted `echo ~` will crash the shell, even with [the patch](https://github.com/ksh93/ksh/issues/217#issuecomment-797816762) in this thread:
```sh
$ builtin -d .sh.tilde
$ echo ~
Memory fault
```
`builtin` should at least error out when trying to remove `.sh.tilde` to prevent this from happening.

**Comment by hyenias** [comment]
Why hide .sh.tilde builtin? Does it not do tilde substitution? My book has 2 pages of text on the subject.

I would make it a special shell builtin and make it visible. Also, add in a man/help page for the builtin. Not sure how this would impact restricted shells. Perhaps, being able to remove it or redefine it has something to do with restricting shell behavior.

Or maybe, someone could rewrite tilde behavior to do something more complex than what it does now. For instance `~user` returns the home directory of **user.** What if the tilde builtin allowed for more in-place expansion of commonly used places? maybe ~java, ~git, or etc. This is, of course, duplication of some stuff that people have implemented in cd functionality. But can this cd functionality integrate so tightly inlined as what could be done with this overlooked and presently hidden builtin?

I would not delete the code altogether. I would like to learn how to create a ksh loadable builtin. Perhaps, this code code be used to provide a training template or example on how to make your own ksh loadable builtin.

These are my thoughts.

**Comment by posguy99** [comment]
> Why hide .sh.tilde builtin? Does it not do tilde substitution? My book has 2 pages of text on the subject.

What book?  The Bolsky?  That has multiple pages about tilde expansion, but doesn't discuss being able to override it.  The O'Reilly doesn't even mention dicipline functions.

I think the question is more why is there a builtin for it, or a dicipline function for it.

Note: Tilde expansion is handled in the `sh_tilde()` function below that.

https://github.com/ksh93/ksh/blob/d2c1700f63597e1e1f2399a470446452b1fb12c4/src/cmd/ksh93/sh/macro.c#L2683-L2691

**Comment by McDutchie** [comment]
@hyenias, trust me when I say that this trivial bit of built-in code is not a useful place to learn how to write a custom built-in.

There's a [good article](https://blog.fpmurphy.com/2008/11/korn-shell-secrets-11.html) about that on the web, but it's from 2008 and rather outdated; ksh 93u+ also expects a `plugin_version()` function that returns a date in the form of a `long` value. Custom built-ins also should use libast and not the system default stdio as it's not compatible (libast has stdio-compatible wrappers).

But I emailed the author, Finnbarr P. Murphy, and he gave permission for me to use it in ksh 93u+m. So at some point we'll have updated documentation.

What I should also do is write a little script in shell that makes it easy to compile custom built-ins. With nmake gone and not coming back, that is going to be necessary. Such a script should not be difficult to write.

> I would make it a special shell builtin and make it visible.

Making it a special built-in would make it impossible to override it with a shell function, which defeats what I believe is the intended purpose (not that it actually works, as standard output is not successfully captured).

> Or maybe, someone could rewrite tilde behavior to do something more complex than what it does now. For instance ~user returns the home directory of user. What if the tilde builtin allowed for more in-place expansion of commonly used places? maybe ~java, ~git, or etc.

Yes, that would be a possible reason to fix and document this.

I think no built-in should be added by default. Regular tilde expansion doesn't need it, and it only serves to confuse and annoy. However, the code could still detect if a function or custom built-in exists, and use it instead of the regular tilde expansion mechanism. A way for that function or custom built-in to fall back to the regular mechanism should be added, too.

I think it is a significant project to fix this functionality so it works as apparently intended. It may have to wait until after the 1.0 release. I will remove the current broken mess before any release, because fixing it will amount to rewriting it anyway.

**Comment by hyenias** [comment]
@McDutchie Thanks for the explanations. I thought by classifying a built-in as special kept it from being deleted via `-d ` option as the --man from `builtin` indicates _"Deletes each of the specified built-ins. Special built-ins cannot be deleted."_ I did not know that it also keeps one from overriding it. **By providing an updated howto for making custom built-ins along with helper script(s) would be out of this world fantastic!**

As all have pointed out, this identified code is problematic and overall have indicated the code should be removed. I am in agreement and am pleased with everyone taking the time to research the history and implications of removing this code. This is a welcomed refreshing way of validating code removal than what had happened previously in the past code base when code was just indiscriminately deleted.

**Comment by McDutchie** [comment]
> However, the code could still detect if a function or custom built-in exists, and use it instead of the regular tilde expansion mechanism. A way for that function or custom built-in to fall back to the regular mechanism should be added, too.

This was not as complicated as I expected. See: https://github.com/ksh93/ksh/pull/225
Please play with it and report results.
