### ISSUE TITLE
What should be done about the SHOPT_TEST_L, _c99_in_the_wild and 'future' ifdefs?

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#219]
Ksh currently has quite a few unused ifdefs. One if these is `SHOPT_TEST_L` (_edit:_ this one [is actually used](https://github.com/ksh93/ksh/issues/219#issuecomment-798778520)), which adds a `test -l` option (equivalent to `test -L`). This compile time option currently isn't listed in [src/cmd/ksh93/SHOPT.sh](https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/cmd/ksh93/SHOPT.sh):
https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/cmd/ksh93/bltins/test.c#L393-L397

Then there are the `_c99_in_the_wild` ifdefs in `sfcvt` that enable the usage of `fpclassify`:
https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/lib/libast/sfio/sfcvt.c#L163-L191

After that are the `future` and `xxx` ifdefs that enable various unused sections of code:
https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/cmd/ksh93/sh/deparse.c#L479-L487
https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/cmd/ksh93/edit/history.c#L249-L260

Is anything going to be done with these ifdefs? Most of the code hidden behind the ifdefs shown above was removed in ksh2020 (aside from `_c99_in_the_wild`, see https://github.com/att/ast/issues/1351).

**Comment by McDutchie** [comment]
> Ksh currently has quite a few unused ifdefs. One if these is `SHOPT_TEST_L`, which adds a `test -l` option (equivalent to `test -L`). This compile time option currently isn't listed in [src/cmd/ksh93/SHOPT.sh](https://github.com/ksh93/ksh/blob/6d63b57dd3bc0b9b6439a15aecbe00dc8375350c/src/cmd/ksh93/SHOPT.sh):

It's detected here: https://github.com/ksh93/ksh/blob/844e6b241045060651f2ae00dca7493cc0fc51ac/src/cmd/ksh93/features/options#L37-L38
So that is turned on if the operating system's external `/bin/test` supports the non-standard lowercase `-l` variant, presumably to make ksh compatible with local scripts. I don't know of any such current system, though. `test` doesn't always live in `/bin`, either.

**Comment by JohnoKing** [comment]
`test -l` is noted as an addition in the ksh93l change log:
```
01-03-10 +ksh93 accepts -l as a synonym for -L in test on systems for
          which /bin/test -l tests for symbolic links.
```

**Comment by McDutchie** [comment]
> Then there are the _c99_in_the_wild ifdefs in sfcvt that enable the usage of fpclassify:

I'll try replacing those with [`#if __STDC_VERSION__ >= 199901L`](https://en.wikipedia.org/wiki/C99#Version_detection). Let's see what happens.

> After that are the `future` and `xxx` ifdefs that enable various unused sections of code:
[...]
> Is anything going to be done with these ifdefs?

I seriously doubt it. I'll just remove them.

Note that deparse.c is entirely unused (only [`run_subshell()`](https://github.com/ksh93/ksh/blob/3abbb0dcb5a527fa22f40d31d0ed5737d4dda101/src/cmd/ksh93/sh/xec.c#L3462-L3538) still calls it, which is a subshell mechanism for systems without `fork(2)`, and that'll be removed soon as well -- man, that stuff looks very dodgy, I wonder if it ever worked at all). `typeset -fp` uses the function's literal input text including comments, so does not deparse like it did in ksh88 and still does on mksh, bash, yash and zsh. However, I'm reluctant to get rid of the deparser altogether. There might be a new use for it someday.
