### ISSUE TITLE
Reverse-search bug in Emacs line editor

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#220]
<s>This isn't a bug, or I don't think it's really a bug.  But is it proper behavior?  It's certainly not expected.
(aside: u+m needs fora)</s>

This is a bug in reverse-search...

```
$ history
1	PS1='$ '
2	CLEAR
3	history
```

Ok, now you can search backwards:

`$ hist↑`

Which is replaced on the command line by:

`$ history`

All good.

But now, do something that isn't found in a reverse-search:

`$ hist2↑`

You get a bell, because there's no match.  All good.

Backspace, remove the '2'. reverse-search again:

`$ hist↑`

And you get a bell.  Why?  There's a match, it was just demonstrated.  You have to remove the entire typed string before reverse-search finds `history` again.

it's not backspacing that does this, it's the failed search that makes it happen.  You can reverse-search successfully, backspace over part of the result, and search again, and the reverse-search succeeds.

It's actually broken differently on `ksh2020`, if reverse-search fails there, backspacing and searching again doesn't work until there's been an intervening `<CR>`.

**Comment by posguy99** [comment]
Ok, Bolsky p108 says what ksh93u+ is doing, is broken.

`Searches the history file for the first occurrence of a commmand line containing _string_`

No mention of it being a fuzzy search.

**Comment by JohnoKing** [comment]
The issue with ksh93u+ is that it refuses to do a reverse search based on the current string (i.e., it's not doing a fuzzy search). That bug was fixed in commit b5e52703.

**Comment by posguy99** [comment]
You're going to have to explain that for the stupid people in the audience, because it seems that u+m *today* has this problem.  Otherwise backspacing to remove the null search result would then return the correct result.

**Comment by posguy99** [comment]
I cleaned up my original issue report.  This is a bug.

**Comment by McDutchie** [comment]
> And you get a bell. Why? There's a match, it was just demonstrated. You have to remove the entire typed string before reverse-search finds `history` again.

Testing this right now. I don't actually have to retype the entire string. Just deleting and re-typing the last character of it is enough. Still a bug, of course.

**Comment by McDutchie** [comment]
@posguy99, can you test this patch? The issue was that the up-arrow search was only activated if the previous operation appended a character to the command line. The patch also activates it if the `killing` flag is set, i.e., if the previous operation erased a character.
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1097,7 +1097,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				if(cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
 #endif /* SHOPT_EDPREDICT */
 				{
-					if(ep->lastdraw==APPEND)
+					if(ep->lastdraw==APPEND || killing)
 					{
 						out[cur] = 0;
 						gencpy((genchar*)lstring+1,out);
```

**Comment by posguy99** [comment]
No, no change in the behavior for the reproducer I gave.  Backspace one character, or four, after the failed search makes no difference.

**Comment by McDutchie** [comment]
Strange. It really does work for me. @JohnoKing, @hyenias, could you try this and see what happens on your end?

**Comment by hyenias** [comment]
I followed @posguy99 instructions and it still happens as he describes. Once, I get the bell and try an up arrow it always bells until I start over with a new line or erase the entire line. I will note that the behavior @McDutchie describes starts happening when I have another occurrence of 'history' in my history log.
```ksh
$ arch/*/bin/ksh
$ set --state
set --default --bgnice --braceexpand --emacs --monitor --multiline --viraw
$ history
510	ls
511	cd git
512	set --state
513	history
$ # perform instructions and get a bell no matter what I do
$ history
510	ls
511	cd git
512	set --state
513	history
514	history
$ # perform instructions and now able to just backspace to a character and get a match with hist and up arrow.
```

**Comment by posguy99** [comment]
This is going to be a stream-of-consciousness thing, it's not like I can point to something in the Bolsky that says this is how it works,  But @hyenias made me really think about it.

Take my original example.

It finds `history` when you search.  Great.  **But where does that leave you in the history list?**  What would make it reset to the bottom of the list?  **I** thought doing any edit on the input line (the backspace) would reset the search to start at the bottom of the list again.  But what if it doesn't?

In @hyenias example, `history` was there twice.  So another reverse search finds the one higher up on the stack, correct.  But in my example, there isn't a second one to find.
 
Is this how reverse-search **actually** works and the pointer *doesn't* reset unless you clear the line or start a new line?

**Comment by JohnoKing** [comment]
@McDutchie I think it's only "working" on your end because of duplicate entries in your history file. To reproduce the bug I have to put new command entries in the history file on each run. Hopefully this is a more clarified reproducer:

```sh
# The following two commands are _always_ run for each attempt at reproducing the bug.
$ alias foo=bar
$ alias foo=other

$ alias foo<Up Arrow>  # This give you 'alias foo=other'. Press the backspace key five times, then up arrow
$ alias foo=bar  # It completes to 'alias foo=bar', because it didn't reset it's entry in the history file
```

Additionally, I've found a bug related to tab completion.  Reverse search doesn't activate after tab completion:
```sh
# Like the above, always run the following three commands for each attempt
$ true /bin/foo
$ true /bin/bar
$ false

$ true /bin<Tab> <Up Arrow>  # The result is 'false' rather than 'true /bin/bar'
```

**Comment by posguy99** [comment]
@JohnoKing But is it **supposed** to reset if you edit the input line?  I mean, I can make an argument for both yes and no, and can't find anything in the Bolsky that comes out and says.

Re tab completion... is that a bug, if it doesn't reverse search while you have the selection menu on the screen after hitting tab?  Should it use what you typed or one of the menu choices?  What does it do if you make a menu choice and **then** try to search?

**Comment by McDutchie** [comment]
I don't think reverse search is supposed to be activated after tab completion.

I think the main problem is that this feature is simply not well-designed. I like mksh's approach much better; the up and down arrow keys always go one step back and forth in the history, and PageUp and PageDown are used for search -- in both directions, so you can go back in the search if you search one step too far. However, possibly changing the design is for a future release.

Meanwhile I have been able to reproduce the problem with my previous patch now, thanks to @hyenias and @JohnoKing for the reproducers. I found code that resets the search state and that was deactivated with an `#ifdef ESH_NFIRST`. Following patch re-enables it, which hopefully makes it work properly after backspacing. Please try.

A side effect of resetting the search state after a beep is that you now won't get another beep when trying again; instead, the search restarts. I don't think this is actually a problem.

```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1097,7 +1097,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				if(cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
 #endif /* SHOPT_EDPREDICT */
 				{
-					if(ep->lastdraw==APPEND)
+					if(ep->lastdraw==APPEND || killing)
 					{
 						out[cur] = 0;
 						gencpy((genchar*)lstring+1,out);
@@ -1385,10 +1385,9 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 #ifdef ESH_NFIRST
 		location.hist_command = hline;
 		location.hist_line = hloff;
-#else
+#endif /* ESH_NFIRST */
 		hloff = 0;
 		hline = histlines;
-#endif /* ESH_NFIRST */
 	}
 restore:
 	genncpy(string,str_buff,sizeof(str_buff)/sizeof(*str_buff));
```

**Comment by hyenias** [comment]
It now works for me.

**Comment by posguy99** [comment]
With the patch in https://github.com/ksh93/ksh/issues/220#issuecomment-833163523 ...

```
$ alias foo=bar
$ alias foo=other

$ alias foo<Up Arrow>  # This give you 'alias foo=other'. then I backspaced and up arrow again
$ alias foo=bar  # I get 'alias foo=bar'... with the patch, shouldn't I have got 'alias foo=other' ?
```

I am not getting the reset of state when I would expect to.  With my original reproducer, any amount of backspacing, even to a search string that would lead to a valid search result, gets me a bell.  Then I hit the up arrow again, and I get the proper search result.

I think that's worse than before.  The bell indicates there's no valid search result, although I'm looking right at one on the screen, and then I do the same thing a second time and get a different result?

The search should (IMO) reset to the bottom of the stack if the line is edited.  That is not happening with this patch, using @JohnoKing reproducer and my own.

**Comment by posguy99** [comment]
Unrelated... for myself, the `mksh` behavior would not be desirable.  The `ksh` behavior makes much more sense and is one of the reasons I use it, reverse-search-isms currently being discussed notwithstanding.

**Comment by McDutchie** [comment]
> With the patch in [#220 (comment)](https://github.com/ksh93/ksh/issues/220#issuecomment-833163523) ...
> 
> ```
> $ alias foo=bar
> $ alias foo=other
> 
> $ alias foo<Up Arrow>  # This give you 'alias foo=other'. then I backspaced and up arrow again
> $ alias foo=bar  # I get 'alias foo=bar'... with the patch, shouldn't I have got 'alias foo=other' ?
> ```

No. The previous search was valid, so its position is remembered as the starting point for the next search. This behaviour is also in 93u+ and the patch does nothing to change that. It only resets the search state for the current command line if nothing is found.

> The search should (IMO) reset to the bottom of the stack if the line is edited.

Can you explain why you think it should do that?

**Comment by posguy99** [comment]
I think it violates least surprise if the current search pointer is somewhere in the middle of the history stack, and the input line is altered such that it now matches a line below the pointer but does not match any lines above the pointer.  In that scenario, a reverse search will now fail, but the patch will reset the search pointer, and a second search with the same term will now find a result.

Obviously an argument is that of course a reverse search should fail in that situation.

Since there is no visual indication on the screen of the current pointer location, how would the user to know where they currently are in the history stack without using `^x^h` ?  And of course that **removes** the current input line from the screen (without actually removing it from the input buffer), the next input character brings the current line back.

Not sure there is a **correct** answer to this.  Both approaches are valid.

Aside... `bash` has an interesting twist on this, if you use reverse search there (not the incremental search, which is highly annoying and easy to crash), it will pull the next match into the input line, but leave the cursor after the search term, rather than at the end of the line.  I like that. :)

Another aside... in other annoying things about `mksh`, I just noticed that `fc -l` there lists the history with the lowest number at the top. (shrug)

**Comment by McDutchie** [comment]
Please try this. I think it makes it act like you prefer, i.e., the search is reset whenever the line is edited.
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1097,7 +1097,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				if(cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
 #endif /* SHOPT_EDPREDICT */
 				{
-					if(ep->lastdraw==APPEND)
+					if(ep->lastdraw==APPEND || killing)
 					{
 						out[cur] = 0;
 						gencpy((genchar*)lstring+1,out);
@@ -1422,7 +1422,14 @@ static void draw(register Emacs_t *ep,Draw_t option)
 	logcursor = sptr + cur;
 	longline = NORMAL;
 	ep->lastdraw = option;
-	
+
+	if (option == APPEND || killing)
+	{
+		/* Reset arrow-up history search state */
+		hloff = 0;
+		hline = histlines;
+	}
+
 	if (option == FIRST || option == REFRESH)
 	{
 		ep->overflow = NORMAL;
```

**Comment by McDutchie** [comment]
Just waiting to confirm that the lastest patch in #220 is good to commit, and then I think we're ready. I'm preparing an announcement, here is a draft. Let me know ASAP if anything is wrong or missing.
```
Announcing: KornShell 93u+m 1.0.0-beta.1

In May 2020, when every KornShell (ksh-93) development project was abandoned,
development was rebooted in a new fork based on the last stable AT&T version:
ksh 93u+. Now, one year and hundreds of bugfixes later, the first beta version
is ready, and KornShell lives again. The new fork is called ksh 93u+m as a
permanent nod to its origin; a standard semantic version number is added
starting at 1.0.0-beta.1. Please test the beta and report any bugs you find.

Main developers: Martijn Dekker, Johnothan King, hyenias

Contributors: Andy Fiddaman, Anuradha Weeraman, Chase, Gordon Woodhull,
Govind Kamat, Harald van Dijk, Lev Kujawski, Marc Wilson, Sterling Jensen

HOW TO GET IT

Please download the source code release from our GitHub page:

	https://github.com/ksh93/ksh

To build, follow the instructions in README.md or src/cmd/ksh93/README.
Hopefully, OS packagers will make packages available soon.
If you want a binary for your OS from us, ask and we'll upload it.

HOW TO REPORT BUGS

It's preferred to open an issue at our GitHub page (see above).
Alternatively, email me at martijn@inlv.org with your report.

MAIN CHANGES SINCE KSH 93U+ 2012-08-01

Hundreds of bugs have been fixed, including many serious/critical bugs. This
includes upstreamed patches from OpenSUSE, Red Hat, and Solaris, as well as
many fixes from the community. See the NEWS file for more information, and the
git commit log for complete documentation of every fix. Incompatible changes
have been minimised, but not at the expense of fixing bugs. For a list of
potentially incompatible changes, see src/cmd/ksh93/COMPATIBILITY.

New command line editor features:

- The forward-delete and End keys are now handled as expected in the emacs and
  vi built-in line editors.

- In the vi and emacs line editors, repeat count parameters can now also be
  used for the arrow keys and the forward-delete key. E.g., in emacs mode,
  <ESC> 7 <left-arrow> will now move the cursor seven positions to the left.
  In vi control mode, this would be entered as: 7 <left-arrow>.

New shell language features:

- The &>file redirection shorthand (for >file 2>&1) is now available for all
  scripts and interactive sessions (unless the new --posix shell option is on).

- File name generation (a.k.a. pathname expansion, a.k.a. globbing) now never
  matches the special navigational names '.' (current directory) and '..'
  (parent directory). This change makes a pattern like .* useful; it now
  matches all hidden files (dotfiles) in the current directory, without the
  harmful inclusion of '.' and '..'.

- Tilde expansion can now be extended or modified by defining a .sh.tilde.get
  or .sh.tilde.set discipline function. This replaces a 2004 undocumented
  attempt to add this functionality via a .sh.tilde command, which never
  worked and crashed the shell. See the manual for details on the new method.

New features in built-in commands:

- Path-bound built-ins (such as /opt/ast/bin/cat) can now be executed by
  invoking the canonical path, so the following will now work as expected:
	$ /opt/ast/bin/cat --version
	  version         cat (AT&T Research) 2012-05-31

- 'command -x' now looks for external commands only, skipping built-ins.
  In addition, its xargs-like functionality no longer freezes the shell on
  Linux and macOS, making it effectively a new feature on these systems.

- 'redirect' now checks if all arguments are valid redirections before
  performing them. If an error occurs, it issues an error message instead
  of terminating the shell.

- 'suspend' now refuses to suspend a login shell, as there is probably no
  parent shell to return to and the login session would freeze.

- 'times' now gives high precision output in a POSIX compliant format.

- 'typeset' now gives an informative error message if an incompatible
  combination of options is given.

- 'whence -v/-a' now reports the location of autoloadable functions.

New features in shell options:

- A new --globcasedetect shell option is added to ksh on OSs where we can
  check for a case-insensitive file system (currently macOS, Windows/Cygwin,
  Linux and QNX 7.0+). When this option is turned on, file name generation
  (globbing), as well as file name tab completion on interactive shells,
  automatically become case-insensitive on file systems where the difference
  between upper- and lowercase is ignored for file names. This is
  transparently determined for each directory, so a path pattern that spans
  multiple file systems can be part case-sensitive and part case-insensitive.

- A new --nobackslashctrl shell option disables the special escaping
  behaviour of the backslash character in the emacs and vi built-in editors.
  Particularly in the emacs editor, this makes it much easier to go back,
  insert a forgotten backslash into a command, and then continue editing
  without having your next cursor key replace your backslash with garbage.
  Note that Ctrl+V (or whatever other character was set using 'stty lnext')
  always escapes all control characters in either editing mode.

- New --posix shell option for enhanced compatibility with other POSIX
  standard shells. See the manual for details. On by default if ksh is
  invoked as sh.

- Enhancement to -G/--globstar: symbolic links to directories are now
  followed if they match a normal (non-**) glob pattern. For example, if
  '/lnk' is a symlink to a directory, '/lnk/**' and '/l?k/**' now work as
  you would expect.
```

**Comment by hyenias** [comment]
I am not savvy at command line editing. But for my novice self after trying both out, I prefer [option 2](https://github.com/ksh93/ksh/issues/220#issuecomment-834755801) as it makes more sense to me because I may have not heard the bell. I will explain my preference.
```ksh
$ rm ~/.sh_history
./kshtest
$ alias foo=bar
$ alias foo=other
$ history
1	alias foo=bar
2	alias foo=other
3	history
$
```
If I perform the above steps then proceed with the following, **option 2** is clearly a better choice for me than [option 1](https://github.com/ksh93/ksh/issues/220#issuecomment-833163523).

Steps for Option 2:
1. type `alias foo` then \<up arrow\> yields `alias foo=other`. All good.
2. \<backspace\> the `r` away from "other" then perform another \<up arrow\> which yields `alias foo=other`. All good.

Steps for Option 1:
1. type `alias foo` then \<up arrow\> yields `alias foo=other`. All good.
2. \<backspace\> the `r` away from "other" then perform another \<up arrow\> which yields a _**bell**_. Perform another \<up arrow\> which yields `alias foo=other`. Say what? Is my arrow key working? Then it does??? Maybe I did not press the \<up arrow\> firmly enough? Now I start to double tap stuff. (I may not have heard the bell as it maybe turned off on the terminal client, earbuds off, and etc.)

**Comment by posguy99** [comment]
The patch in https://github.com/ksh93/ksh/issues/220#issuecomment-834755801 breaks `^N` as described on Bolsky p108.

I'm trying to work up a guaranteed reproducer.

**Comment by McDutchie** [comment]
OK, thanks for testing. Unfortunately, this means that this bug is not going to be fixed in the beta. It seems like a simple fix is not doable without side effects, so this looks likely to be one for the long haul.

**Comment by posguy99** [comment]
Ok, going back to my reproducer, what's going on is that after the first search, the pointer is sitting on line 3.  Editing the line to `hist2` and searching of course fails.

The pointer is left on line 3 after the failed search because there has been no other correct search.  This can be verified with `^X^H` .

I'm becoming more convinced **that** is the correct behavior, especially after reading and re-reading pp108-109.  Why should it return again the line you're sitting on **unless** you completely erase the search term?  Not that it appears to even do that.

More examples (current HEAD, no patches)...

```
10	echo test
11	history
12	echo bleck
13	echo blec
14	history
$ Current command 15; Previous command 12  # after ^X^H on a blank line
```

Now just add a command to the stack...

```
8	ls
9	ls
10	echo test
11	history
12	echo bleck
13	echo blec
14	history
$ echo test                              
test
$ Current command 16; Previous command 12  # it's still remembering the previous command as 12
```

Now search for `echo test'

```
10	echo test
11	history
12	echo bleck
13	echo blec
14	history
15	echo test
16	echo testhistory
17	history
$ Current command 18; Previous command 10  # it found the one on line 10 this time
```

Why didn't it find the one in position 15 (the last one I typed)?  Because the **search** pointer is still at position 12, and the next instance of that search string is at position 10.

So the patch in https://github.com/ksh93/ksh/issues/220#issuecomment-832403555 at least I think may be correct, in that reverse search isn't possible after a backspace, and it should be.  But the only way currently to get `ksh` to reset the pointer to the current line once you've had a successful search seems to be to have a failed search first.  **That** is a problem, since without asking with `^X^H` , you can't tell where you are.

And "successful" is as simple as using `up-arrow` a couple times.  You can verify that by using `up-arrow` a couple times, submitting the command returned, and then hitting the `down-arrow`.  You don't get a bell.  You get the command following the one you just chose from the stack.

What a mess.

I wish `ksh` had something you could include in a prompt that would tell you the stack position, like `!` tells you the history line.

**Comment by posguy99** [comment]
I think this should be closed with "working as designed", at this point.  It's not a bug, whatever else I may think about how it works.  What does everyone else think?

**Comment by posguy99** [comment]
Augh.  In which file does `ksh` expand `'!'` ?

Found it myself.  In src/cmd/ksh93/sh/io.c

```
                        for(;c= *cp;cp++)
                        {
                                if(c==HIST_CHAR)
                                {
                                        /* look at next character */
                                        c = *++cp;
                                        /* print out line number if not !! */
                                        if(c!= HIST_CHAR)
                                        {
                                                sfprintf(sfstderr,"%d", shp->gd->hist_ptr?(int)shp->gd->hist_ptr->histind:++cmdno);
                                        }
                                        if(c==0)
                                                goto done;
                                }
                                sfputc(sfstderr,c);
                        }
```
My head hurts.  It doesn't insert the history number into the prompt and then print the prompt, it just outputs the history number in the middle of printing the prompt character by character after expanding everything **else**.

Ok, `ksh`... now where do you keep the current search pointer... I will find you.

**Comment by McDutchie** [comment]
> The patch in [#220 (comment)](https://github.com/ksh93/ksh/issues/220#issuecomment-834755801) breaks `^N` as described on Bolsky p108.

Right, that makes sense to me now. The variable that is used for the search position (`ep_>e_hline`) is the same one that is also used for keeping track of the current ^P/^N position.

> I wish `ksh` had something you could include in a prompt that would tell you the stack position, like `!` tells you the history line.

That would be possible in theory. However, it would be pointless, as the stack position gets reset before printing every prompt.

> I think this should be closed with "working as designed", at this point. It's not a bug, whatever else I may think about how it works. What does everyone else think?

It does seem that way. OK, closing.
