### ISSUE TITLE
`unset -f` fails in forked subshells if a function is defined before forking

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#228]
This seems to be another variant of https://github.com/att/ast/issues/73. `unset -f` will fail in a forked subshell if a function was defined in the subshell before it was forked. Reproducer:
```sh
$ cat ./reproducer.sh
fail() {
	echo Failure
}
(
	foo() { true; }
	ulimit -t unlimited	# Fork the subshell
	printf "Parent PID: $$\nSubshell PID: ${.sh.pid}\n\n"
	unset -f fail
	fail 2> /dev/null || echo 'Success'
)
$ arch/*/bin/ksh ./reproducer.sh
Parent PID: 4032
Subshell PID: 4033

Failure
```

When the dummy `foo` function is moved out of the subshell or after `ulimit -t unlimited`, the bug vanishes. Additionally, the bug doesn't occur in `-c` scripts unless an extra `true` is added to the reproducer:
```sh
$ ksh -c "$(cat ./reproducer.sh)"
Parent PID: 4348
Subshell PID: 4348

Success
$ echo true >> ./reproducer.sh
$ ksh -c "$(cat ./reproducer.sh)"
Parent PID: 4476
Subshell PID: 4477

Failure
```

**Comment by McDutchie** [comment]
I believe I have this fixed now as I've implemented `unset -f` for virtual subshells without forking. Commit coming up, please test.

**Comment by JohnoKing** [comment]
I've tested the patch and it's working on my system without any problems. If I do end up encountering a bug, then it'll be filed in a new bug report.

**Comment by JohnoKing** [comment]
I have found one bug in the new commit, although the fix for it is a simple one. I'll be submitting the bugfix in a pull request (**edit:** now submitted as https://github.com/ksh93/ksh/pull/287).
