### ISSUE TITLE
Fix high priority bugs before releasing 1.0.0 beta 1

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#252]
We've been at this since May last year. Various downstream packagers have been waiting a long time. We need to release something soon or we're going to lose credibility.

I think the following issues currently have the highest priority:
* ~~I really want the [rest of #87](https://github.com/ksh93/ksh/issues/87#issuecomment-771194255) fixed before releasing. It's just embarrassing. I keep hitting a brick wall trying to trace it, though, so could really use some eyes on this.~~ **Done!** Thanks to @JohnoKing for putting in a lot of work tracing the fixes to backport from 93v-.
* ~~I also really want #165 fixed before releasing.~~ ~~Either that or we should remove or deprecate shcomp.~~ **Done!**
* ~~Fixing #138 would also be great as this bug breaks common shell idioms that execute commands using their pathnames.~~ **Done!**
* ~~#268 as it causes crashes while doing tab completion, a common editing operation.~~ **Done!**
* ~~#290, a serious regression introduced by 93u+m.~~ **Done!**
* Getting the following ones done would be nice, but I don't think they're show stoppers:
  * #123 
  * #161 
  * ~~#168~~ **Done,** with many thanks to @hyenias :) 

IMHO the rest can wait, but if you have any opinions about that, please do speak up.

**Comment by hyenias** [comment]
Since you asked, here are my thoughts:

As for #165, I do not understand your comment, "shcomp is basically not usable before this is fixed, unless you know the script does not contain any process substitutions." Doesn't the shtests run using shcomp? Isn't it not a MAJOR feature of ksh93 to be able to run compiled scripts via shcomp? I am sure folks/companies are actively using the feature. Fine, it lacks process substitutions at the moment--something to hopefully fix down the line but not to remove shcomp altogether. Until recently, I did not even know about process substitutions.

I do not understand the relative impact of #138 to the average user. Can an alias take care of the some of the common use cases?

 #123 is a new feature so push it down the road. As I perceive bugs that cause faults or ksh93 to crash as a higher priority.

As for #161, it would seem that non-forking subshells have too many issues perhaps a new set option could be made to turn the behavior on/off so a user can still execute non-forking subshells for performance with caveats not just compile time disable. This might help users from having to add in all the `ulimit -t unlimited;` statements. Remember associative arrays have memory leaks in shared subshells.

#168 is work-in-progress for me. As I have been working with arrays lately. I have a better understanding of what is going on.

**Comment by ormaaj** [comment]
Remind me again what shcomp is... it's just a lame UPX style "executable packer" right? Or is it actually something more sophisticated? If it's just a packer I'd say almost nobody runs shell scripts that way. Pointless noise. I'd split it out and let somebody that actually cares about it maintain the thing.

**Comment by McDutchie** [comment]
No, it's not a packer, "comp" stands for compile and not compress. shcomp "compiles" shell scripts, as in, it parses a script and dumps the word code to a file, so ksh can run that without parsing it first. Parsing is fast, so the speed gain is negligible. The real use case is distributing a shell script without allowing access to the source, which seems quite evil to me. But it's the sort of thing that makes pointy-haired bosses happy, so it might have helped some people keep their jobs. I don't know how widely used it is. Solaris, Debian and Red Hat ship it, at least. macOS does not.

**Comment by ormaaj** [comment]
Oh it's a bytecode interpreter. Interesting. With all the macro expansion going on that's a pretty reasonable design. Only problem is the script evaluation scheme with most of the code expansion happening line-at-a-time during execution.  Maybe the gains could be huge if the script is written to avoid runtime expansions with an execution mode that precompiles entire files with alias expansion disabled.

As an obfuscation method... meh. I can't imagine commercial interest in diabolical proprietary shell scripts. Maybe back in the 80s / early 90s it was a "huge feature".

There are packers that call themselves "compilers", which sometimes have a crude code encryption scheme. Autoit is an example. I figured it could be something like that.

**Comment by JohnoKing** [comment]
> I also really want #165 fixed before releasing. Either that or we should remove or deprecate shcomp.

Fixing that bug is probably doable, but I'm having a hard time seeing it as a release blocker. I've only been able to get this bug to occur when using process substitutions with redirections, and it only applies to `shcomp`. That's not a very common use case IMO.

> Getting the following ones done would be nice, but I don't think they're show stoppers:
#123

I've been working on this on-off and while my current implementation does work in ksh functions, I've hit a brick wall as far as POSIX functions are concerned. My current patch can be found here (**edit:** updated on 04-22-2021):
https://github.com/JohnoKing/ksh/commit/ccfe8a65de9796dcacb234b73042616933807bf5

**Comment by McDutchie** [comment]
> Fixing that bug is probably doable, but I'm having a hard time seeing it as a release blocker. I've only been able to get this bug to occur when using process substitutions with redirections, and it only applies to `shcomp`. That's not a very common use case IMO.

Process substitutions combined with redirections are common in bash scripts as you find these in examples in tutorials all over the web. I think the only reason they aren't common in ksh scripts is that this was always broken in ksh itself until you fixed it in 0aa9e03f55f7846c47530d466a7a65d35684cb48. If shcomp is of any importance, then it's of equal importance to fix it in there as well. I'll admit that it's not worth blocking the beta release over, though.

**Comment by hyenias** [comment]
I am working on back porting ksh93v- math.tab changes which include a real int function instead of it being an alias to floor() as I want my integers to round towards zero instead of negative infinity. Hopefully, these math lib changes can be accepted in time for the beta.

**Comment by McDutchie** [comment]
Just waiting to confirm that the lastest patch in #220 is good to commit, and then I think we're ready. I'm preparing an announcement, here is a draft. Let me know ASAP if anything is wrong or missing.
```
Announcing: KornShell 93u+m 1.0.0-beta.1

In May 2020, when every KornShell (ksh-93) development project was abandoned,
development was rebooted in a new fork based on the last stable AT&T version:
ksh 93u+. Now, one year and hundreds of bugfixes later, the first beta version
is ready, and KornShell lives again. The new fork is called ksh 93u+m as a
permanent nod to its origin; a standard semantic version number is added
starting at 1.0.0-beta.1. Please test the beta and report any bugs you find.

Main developers: Martijn Dekker, Johnothan King, hyenias

Contributors: Andy Fiddaman, Anuradha Weeraman, Chase, Gordon Woodhull,
Govind Kamat, Harald van Dijk, Lev Kujawski, Marc Wilson, Sterling Jensen

HOW TO GET IT

Please download the source code release from our GitHub page:

	https://github.com/ksh93/ksh

To build, follow the instructions in README.md or src/cmd/ksh93/README.
Hopefully, OS packagers will make packages available soon.
If you want a binary for your OS from us, ask and we'll upload it.

HOW TO REPORT BUGS

It's preferred to open an issue at our GitHub page (see above).
Alternatively, email me at martijn@inlv.org with your report.

MAIN CHANGES SINCE KSH 93U+ 2012-08-01

Hundreds of bugs have been fixed, including many serious/critical bugs. This
includes upstreamed patches from OpenSUSE, Red Hat, and Solaris, as well as
many fixes from the community. See the NEWS file for more information, and the
git commit log for complete documentation of every fix. Incompatible changes
have been minimised, but not at the expense of fixing bugs. For a list of
potentially incompatible changes, see src/cmd/ksh93/COMPATIBILITY.

New command line editor features:

- The forward-delete and End keys are now handled as expected in the emacs and
  vi built-in line editors.

- In the vi and emacs line editors, repeat count parameters can now also be
  used for the arrow keys and the forward-delete key. E.g., in emacs mode,
  <ESC> 7 <left-arrow> will now move the cursor seven positions to the left.
  In vi control mode, this would be entered as: 7 <left-arrow>.

New shell language features:

- The &>file redirection shorthand (for >file 2>&1) is now available for all
  scripts and interactive sessions (unless the new --posix shell option is on).

- File name generation (a.k.a. pathname expansion, a.k.a. globbing) now never
  matches the special navigational names '.' (current directory) and '..'
  (parent directory). This change makes a pattern like .* useful; it now
  matches all hidden files (dotfiles) in the current directory, without the
  harmful inclusion of '.' and '..'.

- Tilde expansion can now be extended or modified by defining a .sh.tilde.get
  or .sh.tilde.set discipline function. This replaces a 2004 undocumented
  attempt to add this functionality via a .sh.tilde command, which never
  worked and crashed the shell. See the manual for details on the new method.

New features in built-in commands:

- Path-bound built-ins (such as /opt/ast/bin/cat) can now be executed by
  invoking the canonical path, so the following will now work as expected:
	$ /opt/ast/bin/cat --version
	  version         cat (AT&T Research) 2012-05-31

- 'command -x' now looks for external commands only, skipping built-ins.
  In addition, its xargs-like functionality no longer freezes the shell on
  Linux and macOS, making it effectively a new feature on these systems.

- 'redirect' now checks if all arguments are valid redirections before
  performing them. If an error occurs, it issues an error message instead
  of terminating the shell.

- 'suspend' now refuses to suspend a login shell, as there is probably no
  parent shell to return to and the login session would freeze.

- 'times' now gives high precision output in a POSIX compliant format.

- 'typeset' now gives an informative error message if an incompatible
  combination of options is given.

- 'whence -v/-a' now reports the location of autoloadable functions.

New features in shell options:

- A new --globcasedetect shell option is added to ksh on OSs where we can
  check for a case-insensitive file system (currently macOS, Windows/Cygwin,
  Linux and QNX 7.0+). When this option is turned on, file name generation
  (globbing), as well as file name tab completion on interactive shells,
  automatically become case-insensitive on file systems where the difference
  between upper- and lowercase is ignored for file names. This is
  transparently determined for each directory, so a path pattern that spans
  multiple file systems can be part case-sensitive and part case-insensitive.

- A new --nobackslashctrl shell option disables the special escaping
  behaviour of the backslash character in the emacs and vi built-in editors.
  Particularly in the emacs editor, this makes it much easier to go back,
  insert a forgotten backslash into a command, and then continue editing
  without having your next cursor key replace your backslash with garbage.
  Note that Ctrl+V (or whatever other character was set using 'stty lnext')
  always escapes all control characters in either editing mode.

- New --posix shell option for enhanced compatibility with other POSIX
  standard shells. See the manual for details. On by default if ksh is
  invoked as sh.

- Enhancement to -G/--globstar: symbolic links to directories are now
  followed if they match a normal (non-**) glob pattern. For example, if
  '/lnk' is a symlink to a directory, '/lnk/**' and '/l?k/**' now work as
  you would expect.
```

**Comment by JohnoKing** [comment]
The `${.sh.pid}` variable should be listed with the other additions:

```
- Added the '${.sh.pid}' variable as an alternative to Bash's '$BASHPID'.
  This variable is set to the current shell's PID, unlike '$$' (which is
  set to the main shell's PID). In virtual subshells '${.sh.pid}' is not
  changed from its previous value, while in forked subshells '${.sh.pid}'
  is set to the subshell's process ID.
```

**Comment by hyenias** [comment]
Is 'bugfixes' one word?

The new fork is called ksh 93u+m... ==> **_This_** new fork...

You could update the platform testing to include the other ARM boxes and OSes you successfully tested against in https://github.com/ksh93/ksh/blob/master/src/cmd/ksh93/README. 

This includes upstreamed patches from OpenSUSE, Red Hat, and Solaris, ... Did you not pull in bug fixes and/or patches from Debian, Ubuntu, Apple, and maybe others?

automatically become case-insensitive on file systems where the difference between upper- and lowercase ==> delete extra hypen after upper

Particularly in the emacs editor, this makes it much easier to go back, insert a forgotten backslash into a command, and then continue editing without having your next cursor key replace your backslash with garbage. ==>
Particularly in the emacs editor; this makes it much easier to go backward, insert a forgotten backslash into a command, and continue editing without having your next cursor key replace the backslash with garbage.

**Comment by posguy99** [comment]
> Particularly in the emacs editor, this makes it much easier to go back, insert a forgotten backslash into a command, and then continue editing without having your next cursor key replace your backslash with garbage. ==>
> Particularly in the emacs editor; this makes it much easier to go backward, insert a forgotten backslash into a command, and continue editing without having your next cursor key replace the backslash with garbage.

Semantics, really.  @McDutchie is describing editing a failed command line, @hyenias is describing editing the command line that hasn't failed yet.  They're both a problem.

**Comment by hyenias** [comment]
@McDutchie asked for proof reading. So, I did as I see it. My edit to his sentence was just that. Perhaps it should read for the new --nobackslashctrl behavior, "Particularly in the emacs editor; this makes it much easier to go backward on the command line, insert a forgotten backslash into a command, and continue editing without having your next cursor key replace the backslash with garbage."

**Comment by McDutchie** [comment]
> This includes upstreamed patches from OpenSUSE, Red Hat, and Solaris, ... Did you not pull in bug fixes and/or patches from Debian, Ubuntu, Apple, and maybe others?

No, it's pretty much just those three. Debian/Ubuntu and Apple patch quite little, and what they do patch is either covered by the other patches or only of interest to those OSs.

**Comment by hyenias** [comment]
All tests pass on my machines and can be added to src/cmd/ksh93/README for additional platforms:
- macOS 10.13.6 (High Sierra) on x86_64
- GNU/Linux: Ubuntu 18.04 on x86_64
- GNU/Linux: Ubuntu 18.04 on armv7l (32bit)
- GNU/Linux: Ubuntu 20.04 on aarch64
