### ISSUE TITLE
Unsetting an array element removes all remaining elements if after subscript expansion

### ISSUE THREAD

**Issue by hyenias** [ksh93/ksh#254]
If performing a removal of an array element after a certain type of subscript expansion all remaining array elements are removed. In the following larger listing, a 4 element indexed array is created. Then, true is executed to perform an array subscript expansion followed by an attempt to just remove the 3rd element 'c' from the array.

Short example:
```ksh
$ unset arr; set -A arr a b c d; echo ${arr[0..0]}; unset arr[2]; echo ${arr[@]}
a
a b
```
Larger listing (just uncomment out a particular subscript expansion for ${arr}:
```ksh
{
unset arr
set -A arr a b c d
#true ${arr[0..3]} # works
#true ${arr[1..3]} # works
#true ${arr[0..2]} # fails
#true ${arr[0..1]} # fails
#true ${arr[1..2]} # fails
#true ${arr[2..3]} # works
#true ${arr[0..-1]} # works because includes end of arr
#true ${arr[0..-2]} # fails because not inclusive of end of arr
#true ${arr[..]} # fails
#true ${arr[0..]} # fails
#true ${arr[1..]} # fails
#true ${arr[2..]} # fails
#true ${arr[3..]} # works
#true ${arr[..0]} # fails
#true ${arr[..1]} # fails
#true ${arr[..2]} # fails
#true ${arr[..3]} # works
#true ${arr[-4..]} # fails
#true ${arr[-3..]} # fails
#true ${arr[-2..]} # fails
#true ${arr[-1..]} # works
#true ${arr[..-4]} # fails
#true ${arr[..-3]} # fails
#true ${arr[..-2]} # fails
#true ${arr[..-1]} # works
#true ${arr[-4..-1]} # works
#true ${arr[-3..-1]} # works
#true ${arr[-2..-1]} # works
#true ${arr[-1..-1]} # works
unset arr[2] # remove 3rd element 'c'
echo ${arr[@]}
}
```
As a workaround, performing a variable substitution via `$arr`/`${arr}` just before the unset allows the elemental unset to work properly. I can only guess that some sort of variable(s) need to be initialized within `unset` as it appears to be inheriting values.
```ksh
unset arr; set -A arr a b c d; true ${arr[2..-2]}; true $arr; unset arr[2]; echo ${arr[@]} # workaround
a b d
```

**Comment by McDutchie** [comment]
Interesting, I didn't even know indexed array subscripts can be expressed as ranges like that. Is this documented anywhere? I can't find that in the man page. 

Note that the command `unset arr[2]` is unsafe unless `-f`/`noglob` is on. `arr[2]` is a glob pattern, so if the file `arr2` exists, `arr[2]` expands to `arr2`. So that should be quoted, e.g. `unset 'arr[2]'`.

**Comment by McDutchie** [comment]
Trying older ksh versions, it looks like this bug was introduced sometime between 2009-05-01 and 2010-10-10. That will probably make it easier to find the cause in the changes between those two versions.
```
$ /usr/local/bin/ksh_2009-05-01  -c 'unset arr; set -A arr a b c d e f g h i j; echo ${arr[3..6]}; unset arr\[4]; echo ${arr[@]}'
d e f g
a b c d f g h i j
$ /usr/local/bin/ksh_2010-10-10 -c 'unset arr; set -A arr a b c d e f g h i j; echo ${arr[3..6]}; unset arr\[4]; echo ${arr[@]}' 
d e f g
a b c d
```

**Comment by McDutchie** [comment]
I found the code that introduces the regression by looking at the differences between those two old ksh versions. When we delete the following lines, the bug disappears. The regression tests show no failures. However, I don't know what this was meant to accomplish and what other bug we might introduce by deleting this.
```diff
diff --git a/src/cmd/ksh93/sh/array.c b/src/cmd/ksh93/sh/array.c
index b0c00a85..dd7f7f4d 100644
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -1532,7 +1532,6 @@ char *nv_endsubscript(Namval_t *np, register char *cp, int mode)
 		}
 
 		Namarr_t *ap = nv_arrayptr(np);
-		int scan = 0;
 #if SHOPT_FIXEDARRAY
 		if((mode&NV_FARRAY) && !nv_isarray(np))
 		{
@@ -1543,8 +1542,6 @@ char *nv_endsubscript(Namval_t *np, register char *cp, int mode)
 			}
 		}
 #endif /* SHOPT_FIXEDARRAY */
-		if(ap)
-			scan = ap->nelem&ARRAY_SCAN;
 		if((mode&NV_ASSIGN) && (cp[1]=='=' || cp[1]=='+'))
 			mode |= NV_ADD;
 		else if(ap && cp[1]=='.' && (mode&NV_FARRAY))
@@ -1555,8 +1552,6 @@ char *nv_endsubscript(Namval_t *np, register char *cp, int mode)
 		else
 #endif /* SHOPT_FIXEDARRAY */
 		nv_putsub(np, sp, ((mode&NV_ADD)?ARRAY_ADD:0)|(cp[1]&&(mode&NV_ADD)?ARRAY_FILL:mode&ARRAY_FILL));
-		if(scan)
-			ap->nelem |= scan;
 	}
 	if(quoted)
 		stakseek(count);
```

**Comment by McDutchie** [comment]
Reading the code, it is starting to make sense to me why this change causes this bug. Setting the `ARRAY_SCAN` attribute causes array expansions to yield multiple elements, e.g. as in ${array[@]} and apparently this is also used for subscript ranges like ${array[x..y]}. I've not yet determined how all that works exactly, but you can see how restoring the `ARRAY_SCAN` attribute and leaving it on might spuriously affect the next command.

Meanwhile, as luck would have it, the other day @ormaaj sent me a tarball with a complete archive of the historic ast-open repository as formerly hosted at research.att.com. He'd collected and archived it all in case it would disappear, which it did. It contains many more versions than the [multishell repo](https://github.com/multishell/ksh93/) and also includes the complete AST repo, not just ksh93 and dependencies. I've now put it online read-only at <https://github.com/ksh93/ast-open-history>. You can clone it and use git to execute fine-grained searches on it.

This means we can now identify more exactly the version that introduced this regression. It's 2009-07-31: <https://github.com/ksh93/ast-open-history/commit/c47896b4dde17511ff5e171ada2b05825d6b5f7c/src/cmd/ksh93/sh/array.c>.

However, no corresponding regression test was added. I also cannot find a corresponding message in the changelog (either in the commit message or in the src/cmd/ksh93/RELEASE file). In fact none of the (few) ksh93 changes in that commit are logged. So this looks to be one of those mystery changes that we'll never know the reason for.

Since we've got proof that this change causes breakage and no evidence that it fixes anything, I think I'll just go ahead and revert it (and add a regression test, of course). If that causes another regression, hopefully someone will find it at some point.

**Comment by McDutchie** [comment]
Meanwhile I found the documentation for those range subscripts in sh.1:
```
       ${!vname[subscript]}
              Expands  to  name  of  the subscript unless subscript is *, @.  or of the form sub1 ..  sub2.  When sub-
              script is *, the list of array subscripts for vname is generated.  For a variable that is not an  array,
              the  value  is  0  if  the  variable is set.  Otherwise it is null.  When subscript is @, same as above,
              except that when used in double quotes, each array subscript yields a separate argument.  When subscript
              is  of the form sub1 ..  sub2 it expands to the list of subscripts between sub1 and sub2 inclusive using
              the same quoting rules as @.
```

**Comment by hyenias** [comment]
Very nice! I can see how ARRAY_SCAN which indicates the presence of ${array[@]} is inferred when using these array expansions as that is what I like about them over trying to use ${arr[@]:offset:length}. The following is so much easier to work with as I do not need to calculate the length from offset by calling ${#arr[@]} inside some an arithmetic operation to pull out a subset of the array when its length is unknown--not to mention, it is faster.

Example: Return the subset of array excluding its 1st and last element.
```ksh
$ unset arr
$ set -A arr a b c d
$ echo ${arr[@]:1:$((${#arr[@]}-2))} # the hard way
b c
$ echo ${arr[1..-2]} # the easy way
b c
```
I agree the added code, propagated ARRAY_SCAN to the next array element so the "@" activity was not lost. Not sure the impact of not passing along  ARRAY_SCAN down the line. I agree with your decision by removing the code as all tests work and it resolves this issue.

In case the ARRAY_SCAN code needs to be restored, here are my thoughts without testing. It seems that "@" aka ARRAY_SCAN was not cleared when the end of array was not reached. When array expansion was inclusive of the last array element, the unset operation worked. It is possible that another potential fix could be to find out if the exit code for array expansion is not clearing ARRAY_SCAN before returning and perhaps that code is only happening when the end of array is reached. Of course it could be a bounds limit that is clearing the variable or ...

Another fix. Since unset does not operate on a range of elements or all elements aka arr[x..y] or arr[@]; adjust unset to reset or ignore that ARRAY_SCAN.

**Comment by hyenias** [comment]
Question: Did you mean to create a 6 element foo array? As the range checks do not directly test 5, 6, -5, and -6 combos. I would think foo being 'a b c d' with exp being 'a b d' would work.
https://github.com/ksh93/ksh/blob/db2b1affdfb01e7d447fd2062872c72a9f8fa693/src/cmd/ksh93/tests/arrays.sh#L715-L728

**Comment by McDutchie** [comment]
> Question: Did you mean to create a 6 element foo array? As the range checks do not directly test 5, 6, -5, and -6 combos. I would think foo being 'a b c d' with exp being 'a b d' would work.

Yes, I did not think that through did I? I'll fix it.

**Comment by McDutchie** [comment]
> > Question: Did you mean to create a 6 element foo array? As the range checks do not directly test 5, 6, -5, and -6 combos. I would think foo being 'a b c d' with exp being 'a b d' would work.
> 
> Yes, I did not think that through did I? I'll fix it.

Actually, 93u+ 2012-08-01 fails more with a b c d e f than it does with a b c d.

With a b c d e f, 22 fails:
```
	arrays.sh[724]: Expanding indexed array range ${foo[0..3]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[1..3]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..2]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..1]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[1..2]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[2..3]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..-2]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[1..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[2..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[3..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..0]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..1]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..2]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..3]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-4..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-3..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-2..]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-4]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-3]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-2]} breaks 'unset foo[2]' (expected 'a b d e f', got 'a b')
```
With a b c d, 17 fails:
```
	arrays.sh[724]: Expanding indexed array range ${foo[0..2]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..1]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[1..2]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..-2]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[0..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[1..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[2..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..0]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..1]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..2]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-4..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-3..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[-2..]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-4]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-3]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
	arrays.sh[724]: Expanding indexed array range ${foo[..-2]} breaks 'unset foo[2]' (expected 'a b d', got 'a b')
```
