### ISSUE TITLE
Recent readonly variable bugfixes break `export`

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#258]
The recent bugfixes for readonly variables (in #239) are causing the [BUG_NOEXPRO modernish regression test](https://github.com/modernish/modernish/blob/master/lib/modernish/cap/BUG_NOEXPRO.t) to fail. Readonly variables cannot be exported:
```sh
$ readonly foo=bar
$ export foo
arch/linux.i386-64/bin/ksh: export: foo: is read only
```

I've tried fixing this with the patch below, but it causes `typeset -xi foo` to change readonly variables:
```diff
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -732,7 +732,7 @@ static int     setall(char **argv,register int flag,Dt_t *troot,struct tdata *tp
 			np = nv_open(name,troot,nvflags|((nvflags&NV_ASSIGN)?0:NV_ARRAY)|((iarray|(nvflags&(NV_REF|NV_NOADD)==NV_REF))?NV_FARRAY:0));
 			if(!np)
 				continue;
-			if(np->nvflag&NV_RDONLY && !tp->pflag && (flag & ~NV_NOFREE) != NV_RDONLY)
+			if(np->nvflag&NV_RDONLY && !tp->pflag && (flag & ~NV_NOFREE) != NV_RDONLY && (flag & NV_EXPORT|NV_IDENT) != (NV_EXPORT|NV_IDENT))
 			{
 				errormsg(SH_DICT,ERROR_exit(1),e_readonly,nv_name(np));
 				UNREACHABLE();
```
```sh
$ readonly foo=bar
$ typeset -xi foo
$ typeset -p foo
typeset -x -r -i foo=0
```

**Comment by McDutchie** [comment]
Thanks for the catch.

Yup. That zsh <= 5.7.1 bug is supported by modernish so when we introduced it in ksh, it coped without a hitch. :)

Adding a debug warning shows that the value of `flag` is 0x2200 when running `export` or `typeset -x` on a variable, so that is the value to whitelist. That is `NV_EXPORT` (0x2000) or'ed with `NV_NOFREE` (0x200). I've previously determined that `NV_NOFREE` is not set on second and subsequent variable arguments.

So the proper fix should be:

```diff
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -732,7 +732,9 @@ static int     setall(char **argv,register int flag,Dt_t *troot,struct tdata *tp
 			np = nv_open(name,troot,nvflags|((nvflags&NV_ASSIGN)?0:NV_ARRAY)|((iarray|(nvflags&(NV_REF|NV_NOADD)==NV_REF))?NV_FARRAY:0));
 			if(!np)
 				continue;
-			if(np->nvflag&NV_RDONLY && !tp->pflag && (flag & ~NV_NOFREE) != NV_RDONLY)
+			if(np->nvflag&NV_RDONLY && !tp->pflag
+			&& (flag & ~NV_NOFREE) != NV_RDONLY	/* allow readonly on readonly vars */
+			&& (flag & ~NV_NOFREE) != NV_EXPORT)	/* allow export on readonly vars */
 			{
 				errormsg(SH_DICT,ERROR_exit(1),e_readonly,nv_name(np));
 				UNREACHABLE();
```

**Comment by McDutchie** [comment]
Hmm. The fix above allows, for a readonly variable: `export var`, `readonly var`, `typeset -x var` and `typeset -r var`, but not `typeset -rx var`. That's a bit inconsistent.

**Comment by McDutchie** [comment]
Better fix, that also allows `typeset -rx var` on a readonly var:
```diff
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -732,7 +732,8 @@ static int     setall(char **argv,register int flag,Dt_t *troot,struct tdata *tp
 			np = nv_open(name,troot,nvflags|((nvflags&NV_ASSIGN)?0:NV_ARRAY)|((iarray|(nvflags&(NV_REF|NV_NOADD)==NV_REF))?NV_FARRAY:0));
 			if(!np)
 				continue;
-			if(np->nvflag&NV_RDONLY && !tp->pflag && (flag & ~NV_NOFREE) != NV_RDONLY)
+			if(np->nvflag&NV_RDONLY && !tp->pflag
+			&& (!(flag & ~NV_NOFREE & (NV_RDONLY|NV_EXPORT))))  /* allow readonly and export on readonly vars */
 			{
 				errormsg(SH_DICT,ERROR_exit(1),e_readonly,nv_name(np));
 				UNREACHABLE();
```

**Comment by McDutchie** [comment]
Nonsense deleted, sorry. Trying again...

**Comment by McDutchie** [comment]
OK, this should do it.

I've also now discovered that `NV_ASSIGN` has the same bitmask as `NV_NOFREE`, and the former is what is meant in this function. The logic of that is yet to be worked out. `NV_ASSIGN` is set for the first variable argument (even if it is not an assignment argument) but not for subsequent ones. Perhaps this is not logical at all, but that is for later.

So, the below allows the operation if any of `NV_ASSIGN`, `NV_EXPORT` or `NV_RDONLY` are the only bits that are set (in other words, if no bits are left after removing those three).

```diff
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -732,7 +732,8 @@ static int     setall(char **argv,register int flag,Dt_t *troot,struct tdata *tp
 			np = nv_open(name,troot,nvflags|((nvflags&NV_ASSIGN)?0:NV_ARRAY)|((iarray|(nvflags&(NV_REF|NV_NOADD)==NV_REF))?NV_FARRAY:0));
 			if(!np)
 				continue;
-			if(np->nvflag&NV_RDONLY && !tp->pflag && (flag & ~NV_NOFREE) != NV_RDONLY)
+			if(np->nvflag&NV_RDONLY && !tp->pflag
+			&& (flag & ~(NV_ASSIGN|NV_RDONLY|NV_EXPORT)))	/* allow readonly/exoprt on readonly vars */
 			{
 				errormsg(SH_DICT,ERROR_exit(1),e_readonly,nv_name(np));
 				UNREACHABLE();
```

**Comment by JohnoKing** [comment]
The patch works for me. On a side note the reason I noticed this bug is because I was testing a bugfix for BUG_CSUBSTDO (which I backported from ksh93v- 2012-08-24). If all goes well you can expect to see that in a pull request very soon.
