### ISSUE TITLE
Spurious 'undefined function' msg in 'whence -a' output after loading builtin

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#26]
```
$ ksh -c 'builtin cat; whence -a cat'
cat is a shell builtin
cat is /bin/cat
cat is an undefined function
```

The third line should not appear.

This bug was found by @JohnoKing while working on #25.

**Comment by JohnoKing** [comment]
It looks like this is because `whence` depends on the command being present in the hash table. In the following example, `nohup` is added to the hash table as a result of running whence:
```
$ hash -r
$ whence nohup
/usr/bin/nohup
$ hash
nohup=/usr/bin/nohup
```

**Comment by McDutchie** [comment]
I just realised what this "undefined function" thing actually means: it's a function that doesn't exist yet but is marked for autoloading with `autoload` a.k.a. `typeset -fu`. Internally, it's a null node: it exists but doesn't have a value.

This is normally handled here (note `is_ufunction` is `" is an undefined function"`):
https://github.com/ksh93/ksh/blob/fbc6cd42866db7c6dcc46247c99e79076c5172ec/src/cmd/ksh93/bltins/whence.c#L195-L196
But the bug is triggered on lines 256-257, here:
https://github.com/ksh93/ksh/blob/fbc6cd42866db7c6dcc46247c99e79076c5172ec/src/cmd/ksh93/bltins/whence.c#L247-L259
Line 256 causes `is_ufunction` to be output if the `nv_search` on line 251 didn't find any node and returned a null pointer. That is wrong; an "undefined function" is a node that exists, but is null. So changing line 256 to the following makes the bug go away:
```c
			else if(np && nv_isnull(np))
```
But I haven't figured out yet if the `sfprintf` is ever reached in that case. After all, reporting an undefined function is normally handled on lines 195-196. So the fix is either this change, or deleting lines 256-257.

**Comment by McDutchie** [comment]
I'm now pretty sure the second `is_ufunction` message is never reached after the test fix, so those two lines (256 and 257) should simply be removed.
