### ISSUE TITLE
shcomp test option issue with invalid variable name

### ISSUE THREAD

**Issue by hyenias** [ksh93/ksh#274]
I am getting an `invalid variable name` when the shcomp option test runs when followed by the other -p and UTF-8 ones on my Ubuntu 20.04 arm64 box.
```
$ bin/shtests options
#### Regression-testing /dev/shm/ksh/arch/linux.aarch64-64/bin/ksh ####
test options begins at 2021-04-13+09:19:51
test options passed at 2021-04-13+09:19:55 [ 171 tests 0 errors ]
test options(C.UTF-8) begins at 2021-04-13+09:19:55
test options(C.UTF-8) passed at 2021-04-13+09:19:59 [ 171 tests 0 errors ]
test options(shcomp) begins at 2021-04-13+09:19:59
/tmp/ksh93.shtests.471842.12105/shcomp-options.ksh[575]: �2b�: invalid variable name
test options(shcomp) passed at 2021-04-13+09:20:04 [ 171 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.020s    0m00.010s
tests:     0m00.800s    0m00.350s
$ bin/shtests -c options
#### Regression-testing /dev/shm/ksh/arch/linux.aarch64-64/bin/ksh ####
test options(shcomp) begins at 2021-04-13+09:20:10
test options(shcomp) passed at 2021-04-13+09:20:15 [ 171 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.010s    0m00.010s
tests:     0m00.320s    0m00.210s
```
I rebooted and tried the `bin/shtests options` again. I was successful for 3 iterations. Then, the _invalid variable name_ showed up again but still passed with `bin/shtests -c options`.
```
...
test options(shcomp) begins at 2021-04-13+09:29:17
/tmp/ksh93.shtests.3976.27553/shcomp-options.ksh[575]: ��R�: invalid variable name
```
Note, _invalid variable name_ does not show up when attempted on my Ubuntu 18.04 arm7 box.

**Comment by hyenias** [comment]
I did a `bin/shtests -xk` test and cross referenced line 575 from shcomp-options.ksh back to:
https://github.com/ksh93/ksh/blob/d6ddd89053299a564c683154cdc0d75874162ea0/src/cmd/ksh93/tests/options.sh#L540

**Comment by hyenias** [comment]
Confirmed. If I comment out either one of these lines, the _invalid variable name_ error does not occur after several attempts.
https://github.com/ksh93/ksh/blob/d6ddd89053299a564c683154cdc0d75874162ea0/src/cmd/ksh93/tests/options.sh#L540-L541

**Comment by McDutchie** [comment]
This occasionally shows up in the GitHub CI run output as well. I think this is a manifestation of bug #165.
