### ISSUE TITLE
On Linux `getconf -n` matches variables names that shouldn't match

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#279]
This bug was reported at https://github.com/att/ast/issues/1172. The `getconf` builtin doesn't match variable names when passed the `-n` flag, contradicting the documentation for `getconf -n`:
```
  -n, --name=RE   Display variables with name that match RE.
```
Reproducer:
```sh
$ builtin getconf
$ getconf -n=GETCONF
_POSIX_THREAD_ROBUST_PRIO_INHERIT=
_POSIX_THREAD_ROBUST_PRIO_PROTECT=
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
POSIX_V6_ILP32_OFF32_CFLAGS=
# ...
# The long list of variables doesn't include GETCONF 
LEVEL3_CACHE_ASSOC=16
LEVEL3_CACHE_LINESIZE=64
LEVEL4_CACHE_SIZE=
LEVEL4_CACHE_ASSOC=
LEVEL4_CACHE_LINESIZE=
```
This bug can be worked around by using `grep` instead of `getconf -n`, e.g.:
```sh
$ builtin getconf
$ getconf | grep GETCONF=
GETCONF=/usr/bin/getconf
```

**Comment by McDutchie** [comment]
> Reproducer:
> 
> ```shell
> $ builtin getconf
> $ getconf -n=GETCONF
> ```

Your option syntax is incorrect. Short options don't use `=`. It's either `-n GETCONF` (with or without space; short options can be stacked) or `--name=GETCONF`.

```
$ arch/*/bin/ksh -c '/opt/ast/bin/getconf -n GETCONF'
GETCONF=/usr/bin/getconf
$ arch/*/bin/ksh -c '/opt/ast/bin/getconf -nGETCONF'
GETCONF=/usr/bin/getconf
$ arch/*/bin/ksh -c '/opt/ast/bin/getconf --name=GETCONF'
GETCONF=/usr/bin/getconf
```

(note that the above invocation type will only work as of 519bb082651390239040005cffbcbed5075d1e4f)

So `-n=GETCONF` really means that you're looking for a configuration variable called `=GETCONF`. On my system, this yields nothing, as I would expect. If you get different results, that may be a bug.

**Comment by JohnoKing** [comment]
> Your option syntax is incorrect. Short options don't use `=`. It's either `-n GETCONF` (with or without space; short options can be stacked) or `--name=GETCONF`.

I overlooked that when running the reproducer from https://github.com/att/ast/issues/1172. Despite that, although it does show the value of `GETCONF` when using the correct syntax, it also prints extra variables (tested on Ubuntu 20.04, 20.10 and Artix):
```sh
$ arch/*/bin/ksh -c 'PATH=/opt/ast/bin getconf --name=GETCONF'
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
_POSIX_C_LANG_SUPPORT=
_POSIX_C_LANG_SUPPORT_R=
GETCONF=/usr/bin/getconf

# When specifying a non-existent variable
$ arch/*/bin/ksh -c 'PATH=/opt/ast/bin getconf -n NOTAVAR'    
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
_POSIX_C_LANG_SUPPORT=
_POSIX_C_LANG_SUPPORT_R=
```

**Comment by McDutchie** [comment]
All that the built-in does is pass the flag bit `ASTCONF_matchname` to `astconflist()` so the bug must be somewhere in that function. https://github.com/ksh93/ksh/blob/61e0f90460ed4518837434d5901319766ff5df3c/src/lib/libast/port/astconf.c#L1555-L1704

**Comment by JohnoKing** [comment]
The bug is occurring in the `_pth_getconf_a` code block below. When that code is disabled with `#if 0`, the bug stops occurring:
https://github.com/ksh93/ksh/blob/61e0f90460ed4518837434d5901319766ff5df3c/src/lib/libast/port/astconf.c#L1628-L1656

**Comment by McDutchie** [comment]
That explains why the bug doesn't happen on my Mac -- its native `getconf` doesn't support `-a`, so the `_pth_getconf_a` feature is not detected. Looks like that code block is simply lacking the code needed to handle `ASTCONF_matchname`.

**Comment by McDutchie** [comment]
Can you confirm that this fixes the bug? If so, feel free to add it to your PR.
```diff
--- a/src/lib/libast/port/astconf.c
+++ b/src/lib/libast/port/astconf.c
@@ -1634,7 +1634,7 @@ astconflist(Sfio_t* sp, const char* path, int flags, const char* pattern)
 				for (s = f; *s && *s != '=' && *s != ':' && !isspace(*s); s++);
 				if (*s)
 					for (*s++ = 0; isspace(*s); s++);
-				if (!lookup(&look, f, flags))
+				if ((!(flags & ASTCONF_matchname) || !regexec(&re, f, 0, NiL, 0)) && !lookup(&look, f, flags))
 				{
 					if (flags & ASTCONF_table)
 					{
```

**Comment by JohnoKing** [comment]
Your patch does fix the issue with `-n`, but I've recently discovered the bug also affects the `-c` and `-s` flags (which your patch doesn't fix):
```sh
$ arch/*/bin/ksh -c 'PATH=/opt/ast/bin getconf -c unknown'
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
_POSIX_C_LANG_SUPPORT=
_POSIX_C_LANG_SUPPORT_R=
$ arch/*/bin/ksh -c 'PATH=/opt/ast/bin getconf -s unknown'
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
_POSIX_C_LANG_SUPPORT=
_POSIX_C_LANG_SUPPORT_R=
```

I've pushed a new commit to my pull request that should fix the `-c` and `-s` flags as well, in addition to fixing `-n`.
