### ISSUE TITLE
Alt+D and Alt+H with repeat parameters delete extra characters (Emacs mode)

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#292]
In emacs mode, using Alt+D or Alt+H with a repeat parameter results in the deletion of extra characters. Reproducer:
```sh
$ set -o emacs
$ foo bar delete add   # <Ctrl+A> <ESC+3+Alt+D>
$ d  # Should be ' add'

$ foo bar delete add   # <ESC+3+Alt+H>
$ f  # Should be 'foo '
```

The cause of this bug was introduced in 13c3fb21e (which was later modified in #178, resulting in the current behavior).

**Comment by McDutchie** [comment]
I think this fixes it, can you test for side effects? The approach is: if the `escape` function (which handles both ESC repeat counts and commands like ESC d and ESC h) returns a repeat count, do not use the saved repeat count for v220 sequences.
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -623,6 +623,8 @@ update:
 			vt220_save_repeat = oadjust;
 		do_escape:
 			adjust = escape(ep,out,oadjust);
+			if(adjust > -1)
+				vt220_save_repeat = 0;
 			continue;
 		case cntl('R') :
 			search(ep,out,count);
```

**Comment by JohnoKing** [comment]
> I think this fixes it, can you test for side effects?

The patch you posted does fix the issue for Alt+D and Alt+H, but recently I've discovered this bug also affects the Delete and Arrow keys (which this patch has no effect on). Reproducer:

```sh
$ test_string <Ctrl+A> <ESC+3+Delete>  # This will delete all of 'test', which is four characters
$ test_string <Ctrl+A> <ESC+4+Right Arrow>  # This should move the cursor to '_', not 's'
```

**Comment by JohnoKing** [comment]
@McDutchie the patch below should fix the issue with the Delete and Arrow keys:
```diff
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -324,7 +324,7 @@ int ed_emacsread(void *context, int fd,char *buff,int scend, int reedit)
 			count = 1;
 		if(vt220_save_repeat>0)
 		{
-			count += vt220_save_repeat;
+			count = vt220_save_repeat;
 			vt220_save_repeat = 0;
 		}
 		adjust = -1;
@@ -623,6 +623,8 @@ update:
 			vt220_save_repeat = oadjust;
 		do_escape:
 			adjust = escape(ep,out,oadjust);
+			if(adjust > -1)
+				vt220_save_repeat = 0;
 			continue;
 		case cntl('R') :
 			search(ep,out,count);
```

This version of the patch reverts part of #178, as it seems your patch also fixes the bug that pull request fixed.

**Comment by McDutchie** [comment]
Yes, that makes sense. Your version of the patch works for me for all the reproducers.
