### ISSUE TITLE
Random seed test failures across all ARM boxes running Ubuntu or FreeBSD

### ISSUE THREAD

**Issue by hyenias** [ksh93/ksh#298]
While testing some new code across my platforms, I came across multiple failures of the new RANDOM seed functionality and a pty test failure. All of my ARM boxes (32 or 64bit) are failing tests in someway. On the FreeBSD aarch64 box, I had to use bash as my interactive shell in order to issue the bin/package make otherwise when using the defaulted csh it complained about ()'s and would not run.

I will provide more info after some rest if necessary.

**Comment by McDutchie** [comment]
If you'd like me to take a look at it on your test machines, please email me with the current login data (e.g. IP address). Thanks.

**Comment by hyenias** [comment]
Please check your email.

**Comment by McDutchie** [comment]
Fixed in 6b3805724dc80fa34c6ab4bb9c822386f866ca63.
