### ISSUE TITLE
`sleep -s` regression on Void Linux (musl) on tty console

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#301]
Following regression occurs on an up-to-date Void Linux with musl libc on x86_64:
```
[martijn@microleegte ksh]$ echo $CCFLAGS
-Os -D_AST_ksh_release
[martijn@microleegte ksh]$ arch/linux.i386-64/bin/ksh -c 'echo ${.sh.version}'
Version AJM 93u+m/1.0.0-alpha 2021-05-07
[martijn@microleegte ksh]$ bin/shtests -p builtins
#### Regression-testing /home/martijn/src/ksh/arch/linux.i386-64/bin/ksh ####
test builtins begins at 2021-05-08+22:05:24
	builtins.sh[1030]: 'sleep -s' doesn't work with intervals of more than 30 seconds
test builtins failed at 2021-05-08+22:05:32 with exit code 1 [ 237 tests 1 error ]
Total errors: 1
CPU time       user:      system:
main:      0m00.005s    0m00.002s
tests:     0m00.203s    0m00.193s
```
The failing test is: https://github.com/ksh93/ksh/blob/92f7ca54237aca31647ff446607099cdeab5b8a7/src/cmd/ksh93/tests/builtins.sh#L1016-L1030 Looks like the `exit 1` on line 1025 is triggered. I've tried increasing the `sleep .1` delays; no effect.

(ping @JohnoKing, @lkujaw)

**Comment by JohnoKing** [comment]
I can't reproduce this bug on Void Linux with musl libc. All of the regression tests pass on my end. Additionally, running the regression test from the terminal works without issues:
```sh
$ sleep -s 100 &
[1]	10608
$ kill -CONT 10608
[1] +  Done                    sleep -s 100 &
$ kill -0 10608
kill: 10608: no such process
```

**Comment by McDutchie** [comment]
That's odd. I'll try reinstalling the VM from scratch and seeing what happens.

FWIW, I'm running it on VirtualBox (macOS), are you running it on a VM and if so, using what?

**Comment by JohnoKing** [comment]
I'm running the latest version of Void Linux in VirtualBox (VirtualBox is running on top of Artix Linux).

**Comment by McDutchie** [comment]
I reformatted and reinstalled the VirtualBox VM from the latest ISO (void-live-x86_64-musl-20210218.iso), installed gcc and git using xbps-install, recompiled ksh, and the failure still happens, reliably. :-/

**Comment by McDutchie** [comment]
Tried recompiling with tcc, in case the problem is gcc. The test fails identically.

**Comment by JohnoKing** [comment]
Update: I have managed to reproduce the bug, but only on a tty console. I couldn't reproduce the bug using the XFCE terminal, but on tty1 the regression test fails consistently.

**Comment by McDutchie** [comment]
Right, at least that much is consistent then... I haven't been using a GUI at all.

It's still strange though. On Alpine Linux 3.12 with musl libc, the test passes (on tty1; I didn't install a GUI on that either).

**Comment by JohnoKing** [comment]
Update 2: I have done some more testing and I've found that the bug only occurs with `SIGCONT`. Other signals marked with `SH_SIGIGNORE` (such as `SIGWINCH` and `SIGURG`) work correctly when used with `sleep -s` on Void Linux.
```sh
# SIGWINCH
$ sleep -s 100 &
[1]	127644
$ kill -WINCH $!
[1] +  Done                    sleep -s 100 &
$ kill -0 $!
kill: 127644: no such process

# SIGURG
$ sleep -s 100 &
[1]	127646
$ kill -URG $!
[1] +  Done                    sleep -s 100 &
$ kill -0 $!  
kill: 127646: no such process

# SIGCONT
$ sleep -s 100 &
[1]	127648
$ kill -CONT $!
$ kill -0 $!
$ echo $?
0   # Wrong result
```
https://github.com/ksh93/ksh/blob/1dc183461a76fe585e8e230731bebf7b03af9376/src/cmd/ksh93/data/signals.c#L78
https://github.com/ksh93/ksh/blob/1dc183461a76fe585e8e230731bebf7b03af9376/src/cmd/ksh93/data/signals.c#L222
https://github.com/ksh93/ksh/blob/1dc183461a76fe585e8e230731bebf7b03af9376/src/cmd/ksh93/data/signals.c#L240

**Comment by McDutchie** [comment]
Ha, there we have it, well spotted. This is not a bug in ksh. For some reason, `SIGCONT` is ignored on the Void Linux console, and that is a Void Linux problem. The "bug" can be replicated on any other system like this:
```
$ (trap '' CONT; bin/shtests -p builtins)
#### Regression-testing /usr/local/src/ksh93/ksh/arch/darwin.i386-64/bin/ksh ####
test builtins begins at 2021-11-22+16:25:51
	builtins.sh[1030]: 'sleep -s' doesn't work with intervals of more than 30 seconds
test builtins failed at 2021-11-22+16:25:59 with exit code 1 [ 239 tests 1 error ]
```

We should not change ksh for this. Signals that are ignored in the parent process should stay ignored, that is how it's supposed to work.

However, there's nothing wrong with a workaround in shtests:
```diff
--- a/src/cmd/ksh93/tests/shtests
+++ b/src/cmd/ksh93/tests/shtests
@@ -172,6 +172,7 @@ command set +o posix 2>/dev/null
 unset DISPLAY FIGNORE HISTFILE POSIXLY_CORRECT _AST_FEATURES
 export ENV=/./dev/null SHTESTS_COMMON=$PWD/_common
 trap + PIPE # unadvertized -- set SIGPIPE to SIG_DFL #
+trap + CONT # Void Linux ignores SIGCONT on the console :/
 
 integer compile=-1 posix=-1 utf8=-1
 integer debug=0 keep=0 locale=0 time=1
```

**Comment by leahneukirchen** [comment]
For what it's worth, we have traced back this behavior to runit and are investigating whether it has any purpose.

**Comment by McDutchie** [comment]
> For what it's worth, we have traced back this behavior to runit and are investigating whether it has any purpose.

Thanks, I was having trouble figuring out where to report that bug but it looks like I don't need to now.
