### ISSUE TITLE
version not updated with beta

### ISSUE THREAD

**Issue by HansH111** [ksh93/ksh#304]
I just build the ksh93u+m
but it shows: ./ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha 2021-05-10

I was expecting a beta version...

**Comment by posguy99** [comment]
Did you download the beta, or clone the repository?

**Comment by HansH111** [comment]
clone the repository.....  so that was my mistake....

Hans

**Comment by McDutchie** [comment]
After cloning the repository, use `git checkout 1.0` to switch to the 1.0 branch and compile the current beta code.

Note that at the moment, it doesn't matter yet, because the master and 1.0 branches are identical except for the version number. However, at some point they will start to diverge.
