### ISSUE TITLE
Error in redirection of function call causes shell to exit

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#310]
This regression was introduced in commit 23f2e23385aca41ba03427f241434096195d4e54. It also exists on ksh 93v- and ksh2020, from which it was backported.

Reproducer:

```
$ (fn() { true; }; fn >/dev/null/nonexistent; true) 2>/dev/null; echo $?
1
```

Expected output: `0` (as on ksh 93u+).

FreeBSD sh and NetBSD sh are the only other known shells that share this behaviour. POSIX [currently allows](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_08_01) both behaviours, but may require the ksh 93u+ behaviour in future. In any case, this causes an incompatibility with established ksh behaviour that could easily break existing ksh scripts.

**Comment by McDutchie** [comment]
I think I found a fix. Commit 23f2e23385aca41ba03427f241434096195d4e54 introduced a check for `jmpval > SH_JMPIO`. All those longjmp exit value macros are defined here: https://github.com/ksh93/ksh/blob/1fc28dc2bb3edc967daaa99890529aad2cb032f6/src/cmd/ksh93/include/fault.h#L77-L87 When a function call pushes context for a redirection, this is done with the jmpval exit value of `SH_JMPCMD`. If we change that to `SH_JMPIO`, it seems like no regressions are introduced, and this bug is fixed without reintroducing the other bug. Which makes sense as a special builtin like `shift` will still fail with `SH_JMPCMD`. @JohnoKing, can you confirm?

```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1550,7 +1550,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 					if(io)
 					{
 						indx = shp->topfd;
-						sh_pushcontext(shp,buffp,SH_JMPCMD);
+						sh_pushcontext(shp,buffp,SH_JMPIO);
 						jmpval = sigsetjmp(buffp->buff,0);
 					}
 					if(jmpval == 0)
diff --git a/src/cmd/ksh93/tests/functions.sh b/src/cmd/ksh93/tests/functions.sh
index 731c1a6e..bc11b27f 100755
--- a/src/cmd/ksh93/tests/functions.sh
+++ b/src/cmd/ksh93/tests/functions.sh
@@ -1291,6 +1291,10 @@ $SHELL <<- \EOF
 EOF
 [[ $? == 2 ]] && err_exit 'Over-shifting in a POSIX function does not terminate the script if the function call has a redirection'
 
+# An error in a redirection attached to a function call should not cause the shell to exit
+(fun() { true; }; fun >/dev/null/nonexistent; true) 2>/dev/null \
+|| err_exit 'Error in redirection of function call causes shell to exit'
+
 # ======
 # https://bugzilla.redhat.com/1116508
 expect=$'13/37/1/1'
```

**Comment by JohnoKing** [comment]
I can confirm the patch fixes the regression. I haven't been able to break it on my end.
