### ISSUE TITLE
head -c k and m suffixes are 1000-based instead of 1024-based.

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#319]
For the `head` builtin of ksh93, `head -c1k` is `head -c1000` and `head -c1048576`.

Those suffixes are obviously inspired from the GNU implementation. The man page (output of `head --man`) has almost exactly the same text as in early versions of GNU head man page.

GNU `head` from textutils 1.19 (1996):
```
    b      512-byte blocks.
    k      1-kilobyte blocks.
    m      1-megabyte blocks.
```

ksh93 head:
```
    b     512 bytes.
    k     1-killobyte.
    m     1-megabyte.
```

(note the kil**l**obyte typo though).

The confusion may be coming from the fact that nowadays, kilobyte does refer to 1000 bytes, and 1024 is kibibyte, though it wasn't the case when those suffixes were added to GNU head decades ago.

For GNU head, k and m suffixes have always (from as far back as 1992 at least AFAICT) meant 1024 and 1048576 AFAIK (it even used to support `-k` and `-m` options).

Later (2007), `KB` and `MB` support were added and even later KiB and MiB.

Now GNU head manual has:

```
          ‘b’  =>            512 ("blocks")
          ‘KB’ =>           1000 (KiloBytes)
          ‘K’  =>           1024 (KibiBytes)
          ‘MB’ =>      1000*1000 (MegaBytes)
          ‘M’  =>      1024*1024 (MebiBytes)
          ‘GB’ => 1000*1000*1000 (GigaBytes)
          ‘G’  => 1024*1024*1024 (GibiBytes)
     and so on for ‘T’, ‘P’, ‘E’, ‘Z’, and ‘Y’.  Binary prefixes can be
     used, too: ‘KiB’=‘K’, ‘MiB’=‘M’, and so on.
```

ksh93's `head` builtin should align to avoid confusion.

**Comment by McDutchie** [comment]
FYI, the `killobyte` typo was fixed in 814b5c6890b897d0e7b2625a16a6513aa5d2789b.

**Comment by stephane-chazelas** [comment]
Thanks. My bad for checking the wrong version. I also notice that `Mi`, `MiB` are supported (and are 1048576 like in GNU head) as well as MB (1000000 like in GNU head), though not documented.

I was also surprised to see other options being processed after that:

```
$ ksh -c 'builtin head; head -c1Mo' < /dev/zero | wc -c
head: -o: unknown option
Usage: head [-qv] [-n lines] [-c chars] [-s skip] [ file ... ]
0
```

**Comment by stephane-chazelas** [comment]
There is a potential consistency  implication with `printf`'s `%#i` vs `%#d` where `M` means 1000000 and `Mi` means 1048576:

```
$ ksh -c 'printf "%1\$#d %1\$#i\n" "2**30"'
1.1G 1.0Gi
```

**Comment by McDutchie** [comment]
A quick look at the very short [`head` code](https://github.com/ksh93/ksh/blob/42becab63cae760addae6e88008665be352bdbbd/src/lib/libcmd/head.c#L71-L154) shows that it does not know or care about numeric multiplier suffixes at all – it leaves that to [libast `optget()`](https://github.com/ksh93/ksh/blob/42becab63cae760addae6e88008665be352bdbbd/src/lib/libast/misc/optget.c#L4104-L4127) which in turn calls [`strtoll()`](https://github.com/ksh93/ksh/blob/master/src/lib/libast/comp/strtoll.c) which is implemented in [strtoi.h](https://github.com/ksh93/ksh/blob/42becab63cae760addae6e88008665be352bdbbd/src/lib/libast/string/strtoi.h#L471-L586) where the multiplier suffixes are handled. Changing how that central code works would change the behaviour of many commands and scripts. So I'm afraid this is just going to have to stay the way it is, except for fixing the documentation.

**Comment by stephane-chazelas** [comment]
FWIW, the `tail` builtin (in libcmd but not included in ksh93 by default) is documented with `k -> 1KiB`, `m -> 1MiB` though it doesn't reflect reality as in my tests 1k is also 1000. Still, suggesting that `1k` might have been 1024 in the past.

Why not have `head`/`tail`, `strtoll()` etc behave the current way in the "ast" universe, and the GNU way in the  GNU universe (and maybe other universes, as I've yet to see Unix-like systems /tools where 1k means 1000)

**Comment by stephane-chazelas** [comment]
Yes, `head -c 1M` and `head -c 1MB` was 1048576 in ksh93s+ and didn't support MiB, so it did change already in the past.

`src/lib/libast/RELEASE` has: 

```
10-04-11 string/strtoi.h: k (1000) and ki (1024) now differentiated
```

So that's only since ksh93u that `head -c1m` gets you 1000000 bytes. ast `head` used to behave like GNU `head` in that regard

**Comment by stephane-chazelas** [comment]
(I'll have to admit though that `head -n 1k` giving you 1000 lines feels more natural than 1024 lines).

**Comment by McDutchie** [comment]
> `src/lib/libast/RELEASE` has:
> 
> ```
> 10-04-11 string/strtoi.h: k (1000) and ki (1024) now differentiated
> ```

That change was made about a decade ago, so changing it back now would surely do more harm than good in terms of backwards compatibility with ksh/ast scripts – particularly as the code in question is used wherever AST optget(3) parses a numeric argument.

Using the full suffixes `kB`, `KiB`, etc. will provide consistent results between AST and GNU versions.
