### ISSUE TITLE
'v' key in vi mode not linking with 'vi' on linux

### ISSUE THREAD

**Issue by Maselko** [ksh93/ksh#328]
I do not know weather this is a bug or not but the 'v' key in the vi mode does not open vi. As did vi did not come with distribution, I had to install it later. Could it cause the issue?
I have ksh version 93u+m/1.1.0-alpha+3f177bfd 2021-09-13 (linux.i386-64) and running Arch Linux on WSL.

**Comment by posguy99** [comment]
The 'v' command tries to execute:

`hist -e ${VISUAL:-${EDITOR:-vi}} count`

So yes, if you don't set $EDITOR, and you don't set $VISUAL, it's going to try to launch `vi`.  This is documented in the `ksh` man page.

**Comment by Maselko** [comment]
Yupp, my bad. I should've digged deeper into man page. Thank you again for your help!
