### ISSUE TITLE
[ "$a" -a "$b" ] invokes unary operator if $a is ! (same for -o)

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#330]
Reported by `@Gilles` at https://unix.stackexchange.com/questions/676608/bash-negation-of-a-file-exists-does-not-change-result-whereas-for-e-chang/676612#676612

binary -a and -o should not be used and are deprecated by POSIX, but still, POSIX does require `[ "$a" -a "$b" ]` to return true iff both $a and $b are non-empty. And `[ "$a" -o "$b" ]` iff any of `$a` and `$b` is non-empty.

Still:

```
$ a='!' b='' ksh93u+m -o posix -c '[ "$a" -a "$b" ]'; echo "$?"
0
```
```
$ a='!' b='trackall' ksh93u+m -o posix -c '[ "$a" -o "$b" ]'; echo "$?"
1
```

If it's important that ksh93 keeps invoking the unary -a here, the same could be done as for `[ -t ]` vs `string=-t; [ "$string" ]` (where `[ -t ]`, where `t` is literal is the same as `[ -t 0 ]` for historical compatibility) and check whether `!` is literal or not here.

**Comment by McDutchie** [comment]
>  (where `[ -t ]`, where `t` is literal is the same as `[ -t 0 ]` for historical compatibility)

Note that that particular hack is disabled in POSIX mode as of 55f0f8ce52ec39a797a745031a60816f998ce01a.

**Comment by McDutchie** [comment]
FWIW, some relevant results from other shells (using [`testshells.sh` from modernish](https://github.com/modernish/modernish/blob/master/share/doc/modernish/utils/testshells.sh)):

```
$ a='!' b='' testshells -P -c '[ "$a" -a "$b" ]'    
> /usr/local/bin/bash-5.1 -o posix
[exit 1]
> '/private/tmp/POSIXMODE_Pdi56HoaG:/|usr|local|bin|dash-0.5.11.5/sh'
/private/tmp/POSIXMODE_Pdi56HoaG:/|usr|local|bin|dash-0.5.11.5/sh: 1: [: -a: unexpected operator
[exit 2]
> '/private/tmp/POSIXMODE_Pdi56HoaG:/|usr|local|bin|gwsh/sh'
/private/tmp/POSIXMODE_Pdi56HoaG:/|usr|local|bin|gwsh/sh: 1: [: -a: unexpected operator
[exit 2]
> /usr/local/bin/yash-2.51 -o posix
[exit 1]
> '/private/tmp/POSIXMODE_Pdi56HoaG:/|bin|ksh/sh'
[exit 0]
> '/private/tmp/POSIXMODE_Pdi56HoaG:/|usr|local|bin|ksh-2020.0.0/sh'
[exit 0]
> /usr/local/src/mksh/old/mksh-R52c -o posix
[exit 0]
> /usr/local/bin/lksh-R59c -o posix
[exit 1]
> /usr/local/bin/mksh-R59c -o posix
[exit 1]
> /usr/local/bin/zsh-5.7.1 --emulate sh -o POSIX_ARGZERO
[exit 1]
```

I think we might be in POSIX 'unspecified' territory here. So I'm not sure this is a bug exactly. Still, it wouldn't be bad to make ksh93 act like bash, mksh, zsh and yash, if it can be done without causing side effects.

**Comment by stephane-chazelas** [comment]
POSIX (+XSI for -a/-o) does define the algorithm unambiguously here:

>  In the following list, $1, $2, $3, and $4 represent the arguments presented to test:
> [...]
>  3 arguments:
>      • If $2 is a binary primary, perform the binary test of $1 and $3.
>      • If $1 is '!', negate the two-argument test of $2 and $3.

And `-a`/`-o` are clearly listed as binary (XSI) operators, though obsoleted.

So I don't think that there's any question that ksh93 is non-compliant in this case.

Note that GNU coreutils `test` has similar problems.

**Comment by stephane-chazelas** [comment]
BTW, it would be great if the documentation could be updated to make it clear that -a/-o binary and -a unary are obsolete and should not be used (along with `(` and `)`).

Unary `-o` is a problem as it's useful, but would be broken if we fixed `[ ! -o option ]` POSIX compliance. When used with `[[ ... ]]`, there's no problem.

**Comment by stephane-chazelas** [comment]
I'm now thinking fixing `[ "$a" -a "$b" ]`, `[ "$a" -o "$b" ]` in `posix` mode only (as there's no unary `-a`/`-o` in POSIX sh syntax so no reason why anyone would use it there), and formerly deprecating binary `-a`/`-o` (in both posix and non-posix mode) would probably be the best approach.

**Comment by McDutchie** [comment]
The reproducers at the top can be simplified as follows:
```
$ ksh -c 'test ! -a ""'; echo "$?"
0   (expected: 1)
$ ksh -c 'test ! -o trackall'; echo "$?"
1   (expected: 0)
```

**Comment by McDutchie** [comment]
I agree that fixing it in POSIX mode only is probably needed to avoid breaking backwards compatibility. The unary `-a` operator is an obsolete synonym of of `-e`, so some old ksh scripts may use `test ! -a filename` to check that a file does not exist. Similarly, some ksh scripts may rely on `test ! -o optionname` to check that an option is off.

**Comment by McDutchie** [comment]
@stephane-chazelas et al, please test this patch:
```diff
diff --git a/src/cmd/ksh93/bltins/test.c b/src/cmd/ksh93/bltins/test.c
index df4ebdce..db1d8979 100644
--- a/src/cmd/ksh93/bltins/test.c
+++ b/src/cmd/ksh93/bltins/test.c
@@ -308,7 +308,8 @@ static int e3(struct test *tp)
 	register int op;
 	char *binop;
 	arg=nxtarg(tp,0);
-	if(arg && c_eq(arg, '!'))
+	if(arg && c_eq(arg, '!')
+	&& !(sh_isoption(SH_POSIX) && (c2_eq(tp->av[tp->ap], '-', 'a') || c2_eq(tp->av[tp->ap], '-', 'o'))))
 		return(!e3(tp));
 	if(c_eq(arg, '('))
 	{
```
If I've got this right, it causes `!` to not be interpreted as a negator (making it a string argument like any other) if the argument following it is `-a` and `-o` and the `posix` option is on.

**Comment by McDutchie** [comment]
Another problem, I don't know if it's related:
```
$ test \( x -a y \)
-ksh: test: argument expected
$ test \( x -o y \)
-ksh: test: argument expected
```
Those parentheses should be accepted.

**Comment by stephane-chazelas** [comment]
> Another problem, I don't know if it's related:
> 
> ```
> $ test \( x -a y \)
> -ksh: test: argument expected
> $ test \( x -o y \)
> -ksh: test: argument expected
> ```
> 
> Those parentheses should be accepted.

Here, you have 5 arguments, so the results are unspecified per POSIX. Can still be seen as a bug, but not a POSIX compliance one.

```
$ ksh -c 'test \( -a \)'
ksh: test: argument expected
```

is a POSIX compliance issue though (and one that can be fixed without breaking backward compatibility)

**Comment by stephane-chazelas** [comment]
> @stephane-chazelas et al, please test this patch:
[...]

That may not be sufficient as there appears to still be a problem with:

```
$ ./arch/linux.i386-64/bin/ksh -o posix -c '[ ! -a ! ]'
./arch/linux.i386-64/bin/ksh: [: argument expected
```

**Comment by McDutchie** [comment]
Thanks @stephane-chazelas. Please try this instead:
```diff
diff --git a/src/cmd/ksh93/bltins/test.c b/src/cmd/ksh93/bltins/test.c
index df4ebdce..fb2e2279 100644
--- a/src/cmd/ksh93/bltins/test.c
+++ b/src/cmd/ksh93/bltins/test.c
@@ -308,7 +308,18 @@ static int e3(struct test *tp)
 	register int op;
 	char *binop;
 	arg=nxtarg(tp,0);
-	if(arg && c_eq(arg, '!'))
+	if(sh_isoption(SH_POSIX) && tp->ap + 1 < tp->ac && ((op=sh_lookup(tp->av[tp->ap],shtab_testops)) & TEST_BINOP))
+	{	/*
+		 * In POSIX mode, makes sure standard binary -a/-o takes precedence
+		 * over nonstandard unary -a/-o if first argument is "!"
+		 */
+		tp->ap++;
+		if(op==TEST_AND)
+			return(*arg && expr(tp,2));
+		else /* TEST_OR */
+			return(*arg || expr(tp,3));
+	}
+	if(arg && c_eq(arg, '!') && tp->ap < tp->ac)
 		return(!e3(tp));
 	if(c_eq(arg, '('))
 	{
```

**Comment by McDutchie** [comment]
> > Those parentheses should be accepted.
> 
> Here, you have 5 arguments, so the results are unspecified per POSIX. Can still be seen as a bug, but not a POSIX compliance one.

Oh good, I don't have to care then. The `test`/`[` disaster should have been deprecated decades ago.

**Comment by McDutchie** [comment]
> ```
> $ ksh -c 'test \( -a \)'
> ksh: test: argument expected
> ```

This also seems to be fixed in POSIX mode by the patch above. So the comment should say: …if the first argument is "!" or "("
