### ISSUE TITLE
Build: FreeBSD 13 regression test path.sh errors

### ISSUE THREAD

**Issue by hyenias** [ksh93/ksh#331]
I upgraded my development FreeBSD aarch64 box from FreeBSD 12.2 to FreeBSD 13 and found the following regression path.sh test failures. All tests pass on the older FreeBSD.
```
$ arch/*/bin/ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+40201330 2021-11-07
$ bin/shtests
#### Regression-testing /tmp/ksh/arch/freebsd13.arm64-64/bin/ksh ####
...
test path begins at 2021-11-10+09:29:08
	path.sh[886]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	path.sh[902]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
test path failed at 2021-11-10+09:29:25 with exit code 2 [ 138 tests 2 errors ]
test path(C.UTF-8) begins at 2021-11-10+09:29:25
	path.sh[886]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	path.sh[902]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
test path(C.UTF-8) failed at 2021-11-10+09:29:43 with exit code 2 [ 138 tests 2 errors ]
test path(shcomp) begins at 2021-11-10+09:29:43
	shcomp-path.ksh[926]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	shcomp-path.ksh[942]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
```

**Comment by McDutchie** [comment]
Please email me with current access details so I can trace the problem. Thanks.

**Comment by JohnoKing** [comment]
These regression test failures are happening because a change in FreeBSD 13 now causes extremely long command names to error out with errno `E2BIG` (argument list too long). The regression tests in question are meant to check the exit status after a command fails with `ENAMETOOLONG` (file name too long). As of commit 2c38fb93 `ENOENT` and `ENAMETOOLONG` use exit status 127, while other errors (such as `E2BIG`) use exit status 126:
https://github.com/ksh93/ksh/blob/402013309f5ecb44465b234d01ca596148bc986d/src/cmd/ksh93/sh/path.c#L1070-L1086

Shortening the long command name to about double the length of `NAME_MAX` seems to fix the issue on my end. Patch:
```diff
--- a/src/cmd/ksh93/tests/path.sh
+++ b/src/cmd/ksh93/tests/path.sh
@@ -879,7 +879,8 @@ got=$?
 	"(expected $exp, got $got)"
 
 # Tests for attempting to use a command name that's too long.
-long_cmd=$(awk -v ORS= 'BEGIN { for(i=0;i<500;i++) print "xxxxxxxxxx"; }')
+name_max=$(getconf NAME_MAX $PWD)
+long_cmd="$(awk -v ORS= 'BEGIN { for(i=0;i<'$name_max';i++) print "xx"; }')x/a"
 exp=127
 PATH=$PWD $SHELL -c "$long_cmd" > /dev/null 2>&1
 got=$?
```

**Comment by hyenias** [comment]
Yes, the above patch stops the path.sh errors. I checked on my various systems and `getconf NAME_MAX $PWD` all return 255. The original awk command produced a 5000 length string of x's for long_cmd. Now, the long_cmd's length is 513 which includes 511 x's and an ending `/a`. @JohnoKing, why did you end the long_cmd string with `/a`? Just curious.

**Comment by JohnoKing** [comment]
> why did you end the long_cmd string with `/a?` Just curious.

That addition was a leftover from testing the `ENAMETOOLONG` exit status with paths exceeding the length of `PATH_MAX`. It isn't necessary and has been removed from the latest version of the patch (#333).
