### ISSUE TITLE
arithmetic: Fix the leading octal 0 mess

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#334]
It's a horrible mess and if anything, fixing #326 made it slightly worse. Sorry @hyenias, but I don't find [your arguments](https://github.com/ksh93/ksh/issues/326#issuecomment-918598086) convincing here.

Reference: https://github.com/ksh93/ksh/issues/326#issuecomment-918663411 and onwards

I'm with @stephane-chazelas who said "Having arithmetic expressions evaluated differently depending on where they're found is less than ideal." Quite. I'd go so far as to say it's unacceptable.  Arithmetic expressions behaving differently within and outside `((`…`))` is bad enough, but having `$((x))` and `$(($x))` mean different things is just bizarre.

More so because this confusing behaviour does not appear to be documented anywhere. The man page only mentions the leading octal zero for the `let` builtin in the description of the `letoctal` option. Otherwise, it ~~documents~~ implies 10 to be the default base.

In the Bolsky & Korn book, I can find no mention at all of the fact that a leading 0 denotes an octal number. Only the *base*`#`*number* format is documented there, unless I'm missing it. See pages 64 and 136.

It might be best if ksh consistently recognises a leading zero as introducing an octal number only in POSIX mode, in all arithmetic contexts (`let` and `printf` included). This is what mksh and zsh already do.

This would make the `letoctal` option redundant. We could repurpose it to switch on and off the leading octal `0` for all arithmetic contexts (in which case we may or may not want to rename it to `arithoctal`), or we could get rid of it completely and let it depend on `posix` directly.

Opinions?

Ping @hyenias, @JohnoKing, @stephane-chazelas, @hvdijk, @lkujaw

**Comment by hvdijk** [comment]
> having `$((x))` and `$(($x))` mean different things is just bizarre.

And rather directly contradicts POSIX, which says

> If the shell variable *x* contains a value that forms a valid integer constant, then the arithmetic expansions `"$((x))"` and `"$(($x))"` shall return the same value.

What you do outside of POSIX mode is up to you, if you see octal as strictly a POSIX conformance thing that nobody really wants, you could make it only for POSIX mode, that would seem reasonable to me. If you think some reasonable scripts rely on octal constants and you'd like to keep them working in non-POSIX mode, you could keep the `letoctal` option but make it work everywhere, enable that option automatically in POSIX mode, but additionally allow it to be set in non-POSIX mode as well.

**Comment by hyenias** [comment]
I see octal as a strictly POSIX conformance thing.

Personally, I am not a fan of expanding octal support by using a leading zero to denote an octal value. I prefer having everything in base 10 and if you want something else then one needs to use _base#number_ format.

I am cautious so I lean towards keeping the things working then depreciate later if that is the route. If POSIX requires octals then just fix POSIX mode and also keep the letoctal in tact as-is without expanding on it in any way in non-POSIX mode.

**Comment by McDutchie** [comment]
> but having `$((x))` and `$(($x))` mean different things is just bizarre.

Yet, this was introduced deliberately in version 2010-12-12.
```
    ksh93: 10-11-29  When a variable is used directly in an arithmetic expression,
    ksh93:    leading zeros no longer cause the value to be treated as an
    ksh93:    octal constant.  This was true in previous versions for justified
    ksh93:    variables.
```
("Used directly" is apparently their language for `$((x))` as opposed to `$(($x))`. Not obvious.)

This is the code that introduced these changes: https://github.com/ksh93/ksh/blob/07b474c6fe0132d7d82159f2e7fcc2f4a777e8b3/src/cmd/ksh93/sh/name.c#L2958-L2962 (and the same code is repeated in nvdisc.c). It survives unchanged up to 93u+, 93v-, and ksh2020.

It's plain to see that it's broken. The check for the justify attribute (which the changelog entry implies should have been removed) is harmful as it disables the check for 'x'/'X' as in hexadecimal numbers. So, taking '0x15', it removes the '0', leaving 'x15' which is invalid:
```
$ typeset -Z x=0x15; echo $((x))                        
-ksh: x15: parameter not set
```

**Comment by McDutchie** [comment]
The fact that they introduced this insanity deliberately is no reason to keep it, in my opinion. Even in non-POSIX mode, it blatantly violates the principle of least astonishment. I am strongly leaning towards going with the solution proposed by @hvdijk and @hyenias. I've got that working now, I just need to tie up some loose ends and then I'll submit a pull request for testing.
