### ISSUE TITLE
Reconsider default built-ins list

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#349]
I'd like to do this before releasing 1.0. Distributions can make their own decisions but we should ship a sane default list of built-in libcmd commands. I don't think the current selection makes much sense:

```
$ builtin | grep ^/
/opt/ast/bin/basename
/opt/ast/bin/cat
/opt/ast/bin/chmod
/opt/ast/bin/cmp
/opt/ast/bin/cut
/opt/ast/bin/dirname
/opt/ast/bin/getconf
/opt/ast/bin/head
/opt/ast/bin/logname
/opt/ast/bin/mkdir
/opt/ast/bin/sync
/opt/ast/bin/uname
/opt/ast/bin/wc
```

IMO, good choices are: `basename`, `cat`, `cut`, `dirname`. Those are often used in performance-sensitive code paths like loops, and/or in command substitutions. Having these as built-ins on $PATH can greatly increase performance.

We may want to keep `getconf` as well since it can report on some of the internal libast state, which an external `getconf` clearly cannot. Although we might want to consider if it should be in release builds by default or perhaps only in development builds. The AST userland universe is dead except for ksh, so it doesn't seem likely many people still run scripts that depend on its AST-specific functionality.

I'm not so sure about having these as defaults, I'd be inclined to remove them unless someone can give me a reason why they should stay:
* `chmod`. Some scripts do change the permission of lots of files, but if they care about performance then `xargs chmod`… is typically used which, being external, will not invoke any built-ins.
* `cmp`. I think it's relatively rarely used. People use `diff` a lot more, but it's external.
* `head`. Why have this, but not `tail`? Also, neither of these are typically performance-sensitive. Some process that produces a lot of output gets piped into `head` or `tail` and that generally only needs to be done once.
* `uname`. This is fairly frequently used in system scripts but if the script is any good, it'll store the value in a variable before using it in any performance-sensitive manner.
* `wc`. This is for counting lines/words in files. I don't think this is commonly used in a loop either, though I could be wrong.

I think the following are almost certainly unnecessary defaults, and I would need a pretty solid reason to keep them:
* `logname`. Getting your login name only needs to be done once.
* `sync`. This generally only needs to be done at shutdown time by system scripts, which will not be using any ksh built-ins. Even if you do occasionally want to sync your disk during regular usage, the external command should do just fine for that.

Ones that aren't in the defaults list, but I think would be nice to have:
* `cp`, `ln`, `mv`. Having these as built-ins can be a good performance optimisation. This is done in loops all the time, often with one file at a time.
* `fds` and `pids`. Lists open file descriptors and process IDs, respectively. These could not possibly work unless built-in. Also, they're very small.
* `mktemp`. Not for performance reasons (clearly), but because external `mktemp` implementations are so different and incompatible on various systems that it would be good for ksh to come with a known interface to this important functionality.

Thoughts/opinions? @hyenias @JohnoKing

**Comment by McDutchie** [comment]
I also [asked the mailing list](https://groups.google.com/g/korn-shell/c/2u1AxSwsRAs).

**Comment by hyenias** [comment]
I need to think about the listing and all the available [libcmd](https://github.com/ksh93/ksh/tree/master/src/lib/libcmd)s. Please note, using a particular ksh libcmd version over the particular OS version has the advantage of not just being faster but providing some consistency across platforms. I wish there was a way to build them all for dynamic loading so that the main ksh executable can be kept smaller.

**Comment by McDutchie** [comment]
Me too, and at some point I will succeed at hacking that into the existing build system, but not soon.

**Comment by avih** [comment]
I don't see `printf` at the list, and IMHO it's one of the most important utilities to have as a builtin for performance reasons.

I also don't see `getopts` and `read` at the list, but I'm pretty sure these are already builtins.

All the others shouldn't generally be used in a hot loop IMO, and therefore defaulting to an external system/posix up to date utilities should be preferred IMO, but maybe I haven't seen enough real-world scripts, and I guess they could help unoptimized scripts.

**Comment by McDutchie** [comment]
Thanks, avih. `printf`, `getopts` and `read` are a regular built-ins in ksh93, without a path. So those aren't part of this discussion. Nothing is going to change there.

**Comment by posguy99** [comment]
I agree with addinbg these to the built-ins list.

> * `cp`, `ln`, `mv`. Having these as built-ins can be a good performance optimisation. This is done in loops all the time, often with one file at a time.

> * `mktemp`. Not for performance reasons (clearly), but because external `mktemp` implementations are so different and incompatible on various systems that it would be good for ksh to come with a known interface to this important functionality.

**Comment by hyenias** [comment]
I would recommend reducing the quantity of libcmd builtins being statically compiled into the default ksh program. Keep in mind restricted ksh shells--watch those file operation commands. If someone in particular would benefit more from these static libcmds then that someone/entity should compile them in. I look forward to being able to dynamically import them but as you say that comes down the road. As such, I would not alter the ecosystem with more libcmds by default but limit them in favor of the future dynamic loading scheme. I want to do something similar to the default math functions (most people are not going to use all of those statically linked math functions either and I have no idea how much space that will save but with the libcmds the default platform programs exist).

static default libcmds | vote | comment
----------------------- | ---- | ---------
/opt/ast/bin/basename | keep | commonly used
/opt/ast/bin/cat | keep | commonly used
/opt/ast/bin/chmod | remove | deals with files
/opt/ast/bin/cmp | remove | rarely used
/opt/ast/bin/cut | keep | commonly used
/opt/ast/bin/dirname | keep | commonly used
/opt/ast/bin/getconf | limit | not commonly used but helpful for development builds just like vmstate
/opt/ast/bin/head | remove | commonly used but it is missing some features as compared to the platform
/opt/ast/bin/logname | remove | commonly used but agree people miss use it in their prompts and such
/opt/ast/bin/mkdir | remove | deals with files
/opt/ast/bin/sync | remove | very rarely needed and when it is need the platform's sync is fine.
/opt/ast/bin/uname | remove | somewhat used but performance is not needed rather have the smaller ksh size
/opt/ast/bin/wc | keep | commonly used like cut/head for validation/insights with iteration over files

I do not agree with adding in additional default libcmds such as cp, ln, and mv as they are file operations. In my viewpoint, if these are added into the base compiled ksh then all the other related file operations libcmds should be added in as well for the same reasons. As for adding the fds, pids, and mktemp; once again, I recommend against this as making them part of the base becomes an issue later down the road when they are not there by default.

**Comment by McDutchie** [comment]
Your argument against including built-ins that do file arguments seems to be that it interferes with the restrictions of restricted shells. However, restricted shells aren't really relevant here at all. Either `/opt/ast/bin` is in the `$PATH` so those built-ins are found, or it isn't, and a restricted shell user cannot change `$PATH`. Nor can they invoke commands using any path containing a slash. So having these as path-bound built-ins does not change anything about the ability of a system administrator to restrict their users from using them. For example:
```
$ ENV= PATH=/bin:/usr/bin /usr/local/bin/ksh --restricted   
$ echo ${.sh.version}
Version AJM 93u+m/1.0.0-beta.2 2021-11-18
$ /opt/ast/bin/basename --version
/usr/local/bin/ksh: /opt/ast/bin/basename: restricted
$ PATH=/opt/ast/bin:$PATH basename --version
/usr/local/bin/ksh: PATH: restricted
$ PATH=/opt/ast/bin:$PATH
/usr/local/bin/ksh: PATH: restricted
$ basename --version
basename: illegal option -- -
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
```
As you can see, it is not possible to get a restricted shell to use the /opt/ast/bin/basename built-in (unless, of course, it is on the `$PATH` that was set at invocation). If any way to circumvent this is found, that's a bug and should be fixed (as we fixed several such bugs before). But it's not an argument against file operation commands as default path-bound built-ins.

**Comment by McDutchie** [comment]
Perhaps there is an argument to be made that a system administrator might want to give access to some default built-ins that do not do file operations (e.g. `head`, `cut`) while blocking access to built-ins that do file operations.

That could be solved by having different paths for these builtins, e.g. `/opt/ast/files/bin` for commands that do file operations, the old `/opt/ast/bin` for the rest. The system administrator could then have more fine-grained control via `$PATH`.

But honestly, I don't think we should go there. Not by default. I could be wrong but I really believe that **nobody uses restricted shells** as sysadmins stopped taking this seriously as a security measure decades ago. And given how massively broken ksh's restricted mode was before we fixed it, it had better be that no one was using it.

So, I have a hard time caring about the restricted mode. I would not be opposed to removing the feature altogether, but we do seem to have fixed it, so it might as well stay for the time being. But I don't think we should let restricted mode considerations influence what we do about built-ins. Sysadmins that want fine-grained control can compile their own ksh and edit their own built-ins configuration using all the different paths they like.

**Comment by hyenias** [comment]
I understand your viewpoint on having sysadmins compile their own for a restricted shell and/or other improvements/features so I concede my viewpoint on the restricted mode consideration.

**Comment by hyenias** [comment]
I compiled each libcmd one at a time. See below for some data behind the impact of including each libcmd.
```
while read libcmd size
do
	printf '%8s %s %6i %.4f\n' $libcmd $size $((size-1270744)) $((size/1270744.0))
done << EOF
basename 1274960
cat 1279048
chmod 1279536
cmp 1279184
cut 1279096
dirname 1274920
getconf 1279064
head 1274968
logname 1275104
mkdir 1274968
sync 1274960
uname 1279344
wc 1279152
vmstate 1283664
chgrp 1279616
chown 1279680
cksum 1311560
comm 1274920
cp 1288848
date 1283336
expr 1279432
fds 1275656
fmt 1279072
fold 1274928
id 1275208
join 1283528
ln 1288904
md5sum 1311624
mkfifo 1274976
mktemp 1274968
mv 1288904
paste 1274928
pathchk 1275000
pids 1279472
rev 1274992
rm 1279744
rmdir 1274968
stty 1295832
sum 1311616
sync 1274960
tail 1283336
tee 1274984
tty 1274920
uniq 1274968
none 1270744
all 1512488
EOF
```
ouput:
```
basename 1274960   4216 1.0033
     cat 1279048   8304 1.0065
   chmod 1279536   8792 1.0069
     cmp 1279184   8440 1.0066
     cut 1279096   8352 1.0066
 dirname 1274920   4176 1.0033
 getconf 1279064   8320 1.0065
    head 1274968   4224 1.0033
 logname 1275104   4360 1.0034
   mkdir 1274968   4224 1.0033
    sync 1274960   4216 1.0033
   uname 1279344   8600 1.0068
      wc 1279152   8408 1.0066
 vmstate 1283664  12920 1.0102
   chgrp 1279616   8872 1.0070
   chown 1279680   8936 1.0070
   cksum 1311560  40816 1.0321
    comm 1274920   4176 1.0033
      cp 1288848  18104 1.0142
    date 1283336  12592 1.0099
    expr 1279432   8688 1.0068
     fds 1275656   4912 1.0039
     fmt 1279072   8328 1.0066
    fold 1274928   4184 1.0033
      id 1275208   4464 1.0035
    join 1283528  12784 1.0101
      ln 1288904  18160 1.0143
  md5sum 1311624  40880 1.0322
  mkfifo 1274976   4232 1.0033
  mktemp 1274968   4224 1.0033
      mv 1288904  18160 1.0143
   paste 1274928   4184 1.0033
 pathchk 1275000   4256 1.0033
    pids 1279472   8728 1.0069
     rev 1274992   4248 1.0033
      rm 1279744   9000 1.0071
   rmdir 1274968   4224 1.0033
    stty 1295832  25088 1.0197
     sum 1311616  40872 1.0322
    sync 1274960   4216 1.0033
    tail 1283336  12592 1.0099
     tee 1274984   4240 1.0033
     tty 1274920   4176 1.0033
    uniq 1274968   4224 1.0033
    none 1270744      0 1.0000
     all 1512488 241744 1.1902
```
