### ISSUE TITLE
Can't pass regression tests with vmalloc disabled

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#363]
Since vmalloc causes so many bugs (see also https://github.com/ksh93/ksh/issues/95), I have made an experimental branch that removes all traces of vmalloc: https://github.com/JohnoKing/ksh/commit/1d14de67791a9b41156db1dbf21b8348bd551310. Without vmalloc present in any capacity ksh seems to work fine, although there are regress test failures ~(which I suspect indicate memory leaks when using `-D_std_malloc` on the normal repo)~ which occur because of the removal of `vmclose` (which frees regions of memory):
```
test leaks begins at 2021-12-05+08:11:54
	leaks.sh[157]: memory leak on PATH reset before PATH search (leaked approx 4022272 bytes after 4096 iterations)
	leaks.sh[363]: set PATH value in main shell (leaked approx 4022272 bytes after 4096 iterations)
test leaks failed at 2021-12-05+08:11:56 with exit code 2 [ 41 tests 2 errors ]
test leaks(C.UTF-8) begins at 2021-12-05+08:11:56
	leaks.sh[157]: memory leak on PATH reset before PATH search (leaked approx 4018176 bytes after 4096 iterations)
	leaks.sh[256]: associative array in function (leaked approx 77824 bytes after 4096 iterations)
	leaks.sh[363]: set PATH value in main shell (leaked approx 4018176 bytes after 4096 iterations)
test leaks(C.UTF-8) failed at 2021-12-05+08:11:59 with exit code 3 [ 41 tests 3 errors ]
test leaks(shcomp) begins at 2021-12-05+08:11:59
	shcomp-leaks.ksh[197]: memory leak on PATH reset before PATH search (leaked approx 4022272 bytes after 4096 iterations)
	shcomp-leaks.ksh[403]: set PATH value in main shell (leaked approx 4018176 bytes after 4096 iterations)
test leaks(shcomp) failed at 2021-12-05+08:12:02 with exit code 2 [ 41 tests 2 errors ]
```

_Originally posted by @JohnoKing in https://github.com/ksh93/ksh/issues/360#issuecomment-986259798_

**Comment by posguy99** [comment]
I am unable to pass all regression tests when building @f919df6 on both macOS 10.15.7 and macOS 11.6.1 with vmalloc disabled.

I get the failure @JohnoKing describes that comes and goes on 11.6.1.

(The below errors are repeatable on every test run)

I also get this one on 10.15.7:

```
test leaks begins at 2021-12-05+19:18:56
	leaks.sh[137]: memory leak with read -C when using <<< (leaked approx 188 KiB after 16384 iterations)
test leaks failed at 2021-12-05+19:19:26 with exit code 1 [ 41 tests 1 error ]
test leaks(C.UTF-8) begins at 2021-12-05+19:19:26
	leaks.sh[137]: memory leak with read -C when using <<< (leaked approx 132 KiB after 16384 iterations)
	leaks.sh[156]: unset of associative array causes memory leak (leaked approx 136 KiB after 16384 iterations)
test leaks(C.UTF-8) failed at 2021-12-05+19:19:56 with exit code 2 [ 41 tests 2 errors ]
test leaks(shcomp) begins at 2021-12-05+19:19:56
	shcomp-leaks.ksh[177]: memory leak with read -C when using <<< (leaked approx 156 KiB after 16384 iterations)
test leaks(shcomp) failed at 2021-12-05+19:20:26 with exit code 1 [ 41 tests 1 error ]
```

And this one on 11.6.1:

```
test leaks begins at 2021-12-05+19:17:06
test leaks passed at 2021-12-05+19:17:42 [ 41 tests 0 errors ]
test leaks(C.UTF-8) begins at 2021-12-05+19:17:42
	leaks.sh[156]: unset of associative array causes memory leak (leaked approx 132 KiB after 16384 iterations)
test leaks(C.UTF-8) failed at 2021-12-05+19:18:18 with exit code 1 [ 41 tests 1 error ]
test leaks(shcomp) begins at 2021-12-05+19:18:18
	shcomp-leaks.ksh[196]: unset of associative array causes memory leak (leaked approx 136 KiB after 16384 iterations)
test leaks(shcomp) failed at 2021-12-05+19:18:53 with exit code 1 [ 41 tests 1 error ]
```

This one comes and goes on 10.15.7:

```
test coprocess begins at 2021-12-05+19:16:30
test coprocess passed at 2021-12-05+19:16:33 [ 34 tests 0 errors ]
test coprocess(C.UTF-8) begins at 2021-12-05+19:16:33
/Users/mwilson/src/ksh/src/cmd/ksh93/tests/coprocess.sh: line 135: process already exists
	coprocess.sh[136]: cat coprocess cleanup not working correctly
test coprocess(C.UTF-8) failed at 2021-12-05+19:16:36 with exit code 1 [ 34 tests 1 error ]
test coprocess(shcomp) begins at 2021-12-05+19:16:36
test coprocess(shcomp) passed at 2021-12-05+19:16:40 [ 34 tests 0 errors ]
```

All regression tests pass on both machines if I pass `-D_AST_vmalloc`.

**Comment by posguy99** [comment]
I can build @f919df6 on Linux Mint with no regression errors using std_malloc.

**Comment by JohnoKing** [comment]
I might as well add on that I've been getting the following test failure on Arch Linux when compiling the master branch with std_malloc:
```
test leaks(shcomp) begins at 2021-12-05+22:25:54
	shcomp-leaks.ksh[177]: memory leak with read -C when using <<< (leaked approx 65536 bytes after 4096 iterations)
test leaks(shcomp) failed at 2021-12-05+22:25:57 with exit code 1 [ 41 tests 1 error ]
```
This is consistently 65536 bytes and happens 100% of the time with the leaks test run under shcomp.

**Comment by McDutchie** [comment]
This is all quite frustrating. I'm not getting any leaks on macOS 10.14 (Mojave).

Note that these reported memory leaks are all quite small:
* 65536 bytes after 4096 iterations is 16 bytes per iteration.
* 188 KiB after 16384 iterations is 11 bytes per iteration.

Those are not very plausible for real memory leaks. I can't think of anything that would malloc the size of 11 or 16 bytes. Even something like `getcwd` will usually yield a larger string.

So I'll probably just increase the tolerance in the tests again. <sigh>

Why is there not *any* tool that can accurately and consistently measure how much memory a process uses? It's maddening.

**Comment by posguy99** [comment]
Just commenting, I can now build @a874f8c on both machines with std_malloc and get no regression test failures so far.

**Comment by McDutchie** [comment]
Thanks for confirming that.
