### ISSUE TITLE
Line continuation breakage within $(comsub)

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#367]
Reproducer:
```sh
echo $(
echo one two\
three
)
```
Actual output (ksh93, all versions):
```
one two\ three
```
Expected output (every other shell, [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_01)):
```
one twothree
```

**Comment by atheik** [comment]
Here's a patch that I think fixes the issue:
```diff
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index c9971851..3f129264 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -313,6 +313,13 @@ int sh_lex(Lex_t* lp)
 		/* skip over characters in the current state */
 		state = sh_lexstates[mode];
 		while((n=STATE(state,c))==0);
+		/*
+		sfprintf(sfstderr,"sh_lex:        mode: %d\n",mode);        sfsync(sfstderr);
+		sfprintf(sfstderr,"sh_lex: oldmode(lp): %d\n",oldmode(lp)); sfsync(sfstderr);
+		sfprintf(sfstderr,"sh_lex:           c: %d\n",c);           sfsync(sfstderr);
+		sfprintf(sfstderr,"sh_lex:           n: %d\n",n);           sfsync(sfstderr);
+		sfprintf(sfstderr,"======\n");                              sfsync(sfstderr);
+		*/
 		switch(n)
 		{
 			case S_BREAK:
@@ -571,6 +578,10 @@ int sh_lex(Lex_t* lp)
 				/* check for \<new-line> */
 				fcgetc(n);
 				c=2;
+				/*
+				sfprintf(sfstderr,"sh_lex: case S_ESC: n: %d\n",n); sfsync(sfstderr);
+				sfprintf(sfstderr,"^^^^^^\n");                      sfsync(sfstderr);
+				*/
 #if SHOPT_CRNL
 				if(n=='\r')
 				{
@@ -670,9 +681,13 @@ int sh_lex(Lex_t* lp)
 			case S_REG:
 				if(mode==ST_BEGIN)
 				{
+					/*
+					sfprintf(sfstderr,"sh_lex: case S_REG: mode==ST_BEGIN: lp->lexd.dolparen: %d\n",lp->lexd.dolparen); sfsync(sfstderr);
+					sfprintf(sfstderr,"^^^^^^\n");                                                                      sfsync(sfstderr);
+					*/
 				do_reg:
-					/* skip new-line joining */
-					if(c=='\\' && fcpeek(0)=='\n')
+					/* skip new-line joining if not called from comsub() */
+					if(c=='\\' && fcpeek(0)=='\n' && !lp->lexd.dolparen)
 					{
 						sh.inlineno++;
 						fcseek(1);
@@ -798,7 +813,15 @@ int sh_lex(Lex_t* lp)
 				poplevel(lp);
 				fcseek(-LEN);
 				n = lp->digits;
+				/*
+				sfprintf(sfstderr,"sh_lex: case S_PAR: comsub(lp,c): begin\n"); sfsync(sfstderr);
+				sfprintf(sfstderr,"^^^^^^\n");                                  sfsync(sfstderr);
+				*/
 				wordflags |= comsub(lp,c);
+				/*
+				sfprintf(sfstderr,"sh_lex: case S_PAR: comsub(lp,c): end\n"); sfsync(sfstderr);
+				sfprintf(sfstderr,"^^^^^^\n");                                sfsync(sfstderr);
+				*/
 				lp->digits = n;
 				continue;
 			case S_RBRA:
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index b1ade153..9b831740 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -2267,6 +2267,10 @@ static void comsubst(Mac_t *mp,register Shnode_t* t, int type)
 			lastc = str[c];
 			str[c] = 0;
 		}
+		/*
+		sfprintf(sfstderr,"comsubst: str: %s\n",str); sfsync(sfstderr);
+		sfprintf(sfstderr,"^^^^^^\n");                sfsync(sfstderr);
+		*/
 		mac_copy(mp,str,c);
 	}
 	if(was_interactive)

```

If you comment out the fix and uncomment the debug prints, then I hope you'll see what I was going after in this fix:
```sh
arch/linux.i386-64/bin/ksh <<'EOF'
# works
echo $(
printf %s, A\ B
)

# mac_copy() called from comsubst() ends up with wrong input
echo $(
printf %s, A\
B
)
EOF
```

**Comment by hyenias** [comment]
I wonder why the legacy Bourne shell syntax (old command substitution) using backquotes as in \`...\` work whereas the new command substitution syntax as in $(...) aka comsubs do not. Also note, that ${ ...; } do not work as well.

Reproducer using old style backquotes:
```
$ echo `
> echo one two\
> three
> `
one twothree
```
Reproducer using new style shared comsubs:
```
$ echo ${
> echo one two\
> three
> }
one two\ three
```

**Comment by atheik** [comment]
@hyenias Maybe you're looking for a more exhaustive answer but if you'll apply my patch, comment out the fix, and uncomment the debug prints, you'll see how the codepaths differ in `sh_lex()` for your two reproducers. The patch does fix both the `$(...)` and `${ ...; }` cases.

**Comment by hyenias** [comment]
I was just bringing to your attention that perhaps another area in the source code has resulted in this problem.

I tried out your additional condition check against `lp->lexd.dolparen` as follows and could not break it by hand. Seems to work just do not know why.
```diff
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index c9971851..25369faf 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -672,7 +672,7 @@ int sh_lex(Lex_t* lp)
                                {
                                do_reg:
                                        /* skip new-line joining */
-                                       if(c=='\\' && fcpeek(0)=='\n')
+                                       if(c=='\\' && fcpeek(0)=='\n' && !lp->lexd.dolparen)
                                        {
                                                sh.inlineno++;
                                                fcseek(1);
```
Do you have an idea of what `lp->lexd.dolparen` means and/or does? Not sure how it relates to a comsub when `lp->comsub` exists.

**Comment by atheik** [comment]
@hyenias 
The snippet you extracted from the patch does not have the change made to the comment. It said `skip new-line joining if not called from comsub()`. Please take a look at the definition of `comsub()` which is below the definition of `sh_lex()`.

`comsub()` is called from `sh_lex()` when `S_PAR` is the current state. In `src/cmd/ksh93/data/lexstates.c`, we see that `S_PAR` is reached in the `ST_DOL` state table at index 40. Decimal 40 is `(` in ASCII. So, the previous skipping of characters was done according to the `ST_DOL` state table, and the character that stopped it was `(`. This means we have `$(`.

Alternatively, `comsub()` may be called from `sh_lex()` by jumping to the `do_comsub` label. In brief, that is the case when we have `${`.

Regardless of which it is from the two, `comsub()` is now called from `sh_lex()`. In `comsub()`, `lp->lexd.dolparen` is incremented at the beginning and decremented at the end. Between them, we see that `sh_lex()` is called. So, `lp->lexd.dolparen` in `sh_lex()` indicates the depth of nesting `$(` or `${` statements we're in. Thus, it is also the number of `comsub()` invocations seen in a backtrace taken in `sh_lex()`.

The codepath for ``` `...` ``` is different which you'll see if you enable the debug prints.

I hope this helps.

**Comment by hyenias** [comment]
@atheik Thanks for the explanation. It has helped me. I tried the following and it was not effective as checking against `lp->lexd.dolparen`.
```
if(c=='\\' && fcpeek(0)=='\n' && !lp->comsub)
```
