### ISSUE TITLE
.. completion

### ISSUE THREAD

**Issue by fbrau** [ksh93/ksh#372]
I'm not getting .. [TAB] completion. I've tried to bisect but there is a big gap of commits which dont compile on my computer.
2020 commits do implement the ".." completion but on the second half of that year the functionality dissapears and I cant track
when this changed.

I was using the att shell, and just noticed this because slackware switched to this repository to build its ksh. 

In the att ksh I type "..[TAB]" and the shell immediatly completes with "../". 
This worked on any part of a path, for example, "cd /usr/share/doc/..[TAB]" and the shell completes with "/"...
That has been the usual for years I've using ksh93. 

Is this a bug or an indented decision?

**Comment by McDutchie** [comment]
It's not intended; it's a side effect of commit 5312a59d that caused `.` and `..` to be skipped in the pathname expansion (globbing) of `.*`. The completion code internally uses that mechanism, so changed along with it. In general, I stand behind this change in pathname expansion (see the two links in the commit message for the rationale), but I'll have to figure out a good way to restore the expected completion behaviour. Thanks for the report.

**Comment by fbrau** [comment]
it works for me. Brilliant
