### ISSUE TITLE
Build failure on macOS with memccpy: error: expected parameter declarator

### ISSUE THREAD

**Issue by ryandesign** [ksh93/ksh#373]
I'm trying to add a port for this ksh93u+m fork to MacPorts, but neither 1.0.0-beta.1 nor the latest commit as of now (dfb699b5caeac31494886de5fe0151bd7456446a) builds for me on macOS Catalina 10.15.7. The error is:

```
.../src/lib/libast/comp/memccpy.c:40:1: error: expected parameter declarator
memccpy(void* as1, const void* as2, register int c, size_t n)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:47: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:38:63: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                              ^
.../src/lib/libast/comp/memccpy.c:40:1: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:47: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:38:63: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                              ^
.../src/lib/libast/comp/memccpy.c:40:1: note: to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:47: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:38:54: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                                                     ^
.../src/lib/libast/comp/memccpy.c:40:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
memccpy(void* as1, const void* as2, register int c, size_t n)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:47: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:38:32: note: expanded from macro '__darwin_obsz0'
#define __darwin_obsz0(object) __builtin_object_size (object, 0)
                               ^
.../src/lib/libast/comp/memccpy.c:40:1: error: conflicting types for '__builtin___memccpy_chk'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:3: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
.../src/lib/libast/comp/memccpy.c:40:1: note: '__builtin___memccpy_chk' is a builtin with type 'void *(void *, const void *, int, unsigned long, unsigned long)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:3: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
.../src/lib/libast/comp/memccpy.c:40:1: error: definition of builtin function '__builtin___memccpy_chk'
memccpy(void* as1, const void* as2, register int c, size_t n)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:55:3: note: expanded from macro 'memccpy'
                __builtin___memccpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                ^
1 warning and 4 errors generated.
mamake [lib/libast]: *** exit code 1 making memccpy.o
mamake: *** exit code 1 making lib/libast
mamake: *** exit code 1 making all
```

It's the same error that has been preventing the MacPorts ksh93 port (ksh93u+ 2012-08-01) from building on OS X 10.9 or later for the past 8 years: https://trac.macports.org/ticket/43392

The reporter of that ticket sent the problem on to the ast-users mailing list but I did not see any response: https://www.mail-archive.com/ast-users@lists.research.att.com/msg00850.html

**Comment by ryandesign** [comment]
If I add `-D_lib_memccpy` to the `CCFLAGS` I'm passing to `bin/package make`, then it builds, which is strange because as of e856094ca28a54bc02ab8860d02d6214f7043550 I thought you were already using that flag.

**Comment by posguy99** [comment]
@McDutchie , here is [make.out](https://www.dropbox.com/s/h05r4l80q5gebj8/make_out_dfb699b_10_15_7.txt.gz?dl=0) from a successful build on my Catalina system.  No special options (although I do need to remove `CCFLAGS=-USHOPT_EDPREDICT` from my Makefile these days. 🙂

**Comment by ryandesign** [comment]
You are probably allowing the default compiler to be used. If I do that, then I see that arch/darwin.i386/bin/cc is the shell script beginning with `: unix wrapper for macOS cc : 2020-07-17 :` that specifies `-D_lib_memccpy` and other stuff.

I'm not allowing the default compiler to be used. In MacPorts, we always want to tell a build what compiler to use. It was my understanding that the way to do this was to set the environment variable or argument `CC` to the path to the compiler that I want, as in more mainstream build systems. When I do e.g. `CC=/usr/bin/clang` then for one thing the wrapper has moved to arch/darwin.i386-64/bin/cc and it only contains:
```
: /usr/bin/clang :
/usr/bin/clang "$@"
```
I guess if the wrapper script is necessary, then a user setting `CC` should not cause the wrapper script not to be used. Instead, I guess the path to the compiler should be inserted into the wrapper script where it currently reads `CC=/usr/bin/cc`?

**Comment by McDutchie** [comment]
> I guess if the wrapper script is necessary, then a user setting CC should not cause the wrapper script not to be used. 

That is not feasible; wrapper scripts are used to set highly compiler-specific flags. However, this particular flag is not compiler-specific, so should really be applied elsewhere instead. (Why didn't I do that to begin with? Because I backported Apple's build fix a year and a half ago, when I still knew very little about how how this code base works.)

The root problem is that the [`lib_memccpy` feature test](https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/lib#L448-L573) produces a false negative on macOS. Adding the `-D_lib_memccpy` flag forces an override of that negative test result.

Preferably, we should fix that test so that the feature detection produces a positive result on macOS, because the functionality is in fact supported. But I don't know how to do that, and figuring it out would simply take more time than I have available for the foreseeable future.

If anyone else would like to have a go at properly fixing the feature test, please, be my guest. (To see the compiler messages when compiling feature tests, pass `IFFEFLAGS=-d1` in the environment. To see iffe documentation, `arch/*/bin/ksh arch/*/bin/iffe --man`.)

However, as long as we don't have a proper fix, forcing a positive result for macOS should be done in that feature test itself, and not in the compiler flags.

**Comment by McDutchie** [comment]
Hrm. There is another flag from Apple's build fix that is passed in the compiler wrapper script: `-D_ast_int8_t=int64_t`

I wonder what that does, and if we actually need it.

**Comment by ryandesign** [comment]
> The root problem is that the [`lib_memccpy` feature test](https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/lib#L448-L573) produces a false negative on macOS.

I noticed that but didn't know where the feature test was or how to see its results, so thanks for pointing it out!

**Comment by ryandesign** [comment]
> wrapper scripts are used to set highly compiler-specific flags

I don't think the darwin wrapper script is. For one thing, it's set to use `/usr/bin/cc`, which is not a specific compiler. Since Xcode 5, it has been various versions of Apple clang, but prior to that it could have been llvm-gcc or various versions of Apple gcc. So the flags in the darwin wrapper have to be general to any compiler Apple shipped with any Xcode, at least, and I would assume they would work fine with any macOS compatible compiler, including open source versions of clang and gcc.

Since the build succeeds for me when specifying a compiler and `-D_lib_memccpy`, without the wrapper having been used, that makes me wonder if the wrapper does anything useful at all for darwin. (I know nearly zero about ksh or its build system so there could be a purpose I'm not aware of.)

**Comment by McDutchie** [comment]
> > wrapper scripts are used to set highly compiler-specific flags
> 
> I don't think the darwin wrapper script is.

Agreed. I think I'll end up getting rid of it as part of fixing this issue.

But I want to figure out what that `-D_ast_int8_t=int64_t` redefinition is for, first. On my macOS 10.14.6 x86_64, ksh builds just fine without out, and all the regression tests pass.

It overrides the result of [this test](https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/common#L182-L312). It is run up to 8 times, defining N to 1 through 8. It stops when one of the runs succeeds.

By adding #warning directives after `#if N==1`, `#if N==2`, etc., and passing `IFFEFLAGS=-d1`, I've determined that the fist run, `N==1`, passes on macOS. So that means that `_ast_int8_t` is defined as `long` on macOS.

A `long` is a 32-bit value (even on 64-bit systems). So the flag passed turns `_ast_int8_t` into a 64-bit type instead.

I will note an inconsistency in that test. `N==1` sets it to `long`, a 32-bit type. `N==2` sets it to `long long`, a 64-bit type. And all further tries, `N==3` through `N==8`, also set 64-bit types. That seems like an obvious inconsistency. Even if it doesn't seem to have any effect that is currently detected by the regression tests, there might be something we haven't encountered yet.

The name of the type `_ast_int8_t` seems to suggest that it should be (at least) 8 bytes, a.k.a. 64 bits, long. And `long` isn't.

So perhaps the proper fix is to simply delete the first iteration `N==1`, so that `long long` is the first one tried, and this test will always result in a type being defined that is at least 64 bits long.

**Comment by McDutchie** [comment]
In fact, perhaps we should not only delete `long` from the possibilities in that test, but also make `long long` the *last* type tried, instead of the first, because all the others specify a length of exactly 64 bits and this test does seem to be about figuring out a type that is 64 bits long.

**Comment by McDutchie** [comment]
Hmm. I'm now actually reading the code of that test. It does seem to explicitly allow for a 32-bit (4-byte) integer type: https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/common#L270-L271

Maybe this test is about figuring out the *largest possible* integer type supported.

`long long` is 64 bits, or possibly larger.
All the \*int64\* types are 64 bits.
`long` is 32 bits.

So what we should do is try `long long` first, then try the \*int64\* types, then try `long` *last*.

**Comment by McDutchie** [comment]
Actually, never mind – I'm wrong about the size of `long`.

`long` is generally 32 bits long on 32-bit systems, and 64 bits long on 64-bit systems.

On my macOS x86_64, the test results are:
```
$ grep _ast_int._t arch/darwin.i386-64/include/ast/ast_common.h
#define _ast_int1_t		char
#define _ast_int2_t		short
#define _ast_int4_t		int
#define _ast_int8_t		long
#define _ast_intmax_t		_ast_int8_t
```

On linux i386 (32 bit), the results are:
```
$ grep _ast_int._t arch/linux.i386/include/ast/ast_common.h 
#define _ast_int1_t             char
#define _ast_int2_t             short
#define _ast_int4_t             int
#define _ast_int8_t             long long
#define _ast_intmax_t           _ast_int8_t
```

So it's working fine as it is. To me, this confirms that Apple's `-D_ast_int8_t=int64_t` addition is unnecessary, because on 64 bit macOS, `long` and `int64_t` should be equivalent.

If anyone more expert in C integer data types has any thoughts, please post.

**Comment by McDutchie** [comment]
@ryandesign, please let me know if the following patch fixes the problem at your end.
```diff
diff --git a/src/cmd/INIT/cc.darwin b/src/cmd/INIT/cc.darwin
deleted file mode 100755
index e9e188c6..00000000
--- a/src/cmd/INIT/cc.darwin
+++ /dev/null
@@ -1,52 +0,0 @@
-: unix wrapper for macOS cc : 2020-07-17 :
-
-HOSTTYPE=darwin.generic
-
-case " $* " in
-*" -dumpmachine "*) echo $HOSTTYPE; exit ;;
-esac
-
-CC=/usr/bin/cc
-op=init
-for arg
-do	case $op in
-	init)	op=ld
-		set ''
-		;;
-	esac
-	case $arg in
-	-c)	op=cc
-		;;
-	-E)	op=cpp
-		continue
-		;;
-	-G)	op=dll
-		continue
-		;;
-	-lc)	continue
-		;;
-	-lm)	continue
-		;;
-	esac
-	set "$@" "$arg"
-done
-case $# in
-0)	;;
-*)	shift ;;
-esac
-case $* in
--v)	$CC "$@"; exit ;;
-esac
-case $op in
-init)	echo "cc: arguments expected" >&2
-	exit 1
-	;;
-cpp)	$CC -E "$@"
-	;;
-cc)	$CC -D_ast_int8_t=int64_t -D_lib_memccpy "$@"
-	;;
-dll)	$CC -Wl,-flat_namespace -dynamiclib -undefined dynamic_lookup "$@"
-	;;
-ld)	$CC -Wl,-search_paths_first "$@"
-	;;
-esac
diff --git a/src/lib/libast/features/lib b/src/lib/libast/features/lib
index 39410ad9..c90e1c30 100644
--- a/src/lib/libast/features/lib
+++ b/src/lib/libast/features/lib
@@ -446,6 +446,9 @@ tst	lib_memcmp string.h note{ standard memcmp interface that works }end execute{
 }end
 
 tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat.h sys/mman.h fcntl.h note{ standard memccpy interface that works }end execute{
+	#if __APPLE__
+	int main() { return 0; }	/* TODO: fix false negative on macOS; for now, force a positive */
+	#else
 	#if _STD_
 	static void gotcha(int sig)
 	#else
@@ -570,6 +573,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 	#endif
 		return 0;
 	}
+	#endif /* __APPLE__ */
 }end
 
 tst	lib_utime_now note{ utime works with 0 time vector }end execute{
```

**Comment by McDutchie** [comment]
> To me, this confirms that Apple's `-D_ast_int8_t=int64_t` addition is unnecessary, because on 64 bit macOS, `long` and `int64_t` should be equivalent.

I've also confirmed that it works fine as is on my ancient Power Mac Pro G5 running a 32-bit Mac OS X 10.3 operating system:
```
$ grep _ast_int._t arch/darwin07.ppc/include/ast/ast_common.h                                                                      
#define _ast_int1_t             char
#define _ast_int2_t             short
#define _ast_int4_t             int
#define _ast_int8_t             long long
#define _ast_intmax_t           _ast_int8_t
```
So really I don't know what Apple were on about there.

**Comment by ryandesign** [comment]
> the [`lib_memccpy` feature test](https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/lib#L448-L573) produces a false negative on macOS

I copied the feature test to a standalone source file. It is crashing here:

```
$ lldb ./lib_memccpy
(lldb) target create "./lib_memccpy"
Current executable set to '/tmp/lib_memccpy' (x86_64).
(lldb) run
Process 71105 launched: '/tmp/lib_memccpy' (x86_64)
Process 71105 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffffffffffff)
    frame #0: 0x00000001000038f1 lib_memccpy`main at lib_memccpy.c:116:14
   113 			if (!mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0))
   114 				return 0;
   115 			for (i = 0; i < siz; i++)
-> 116 				srcbuf[i] = 'x';
    				          ^
   117 			srcbuf[siz - 1] = 0;
   118 			alarm(10);
   119 			signal(SIGSEGV, gotcha);
Target 0: (lib_memccpy) stopped.
(lldb) p srcbuf
(char *) $0 = 0xffffffffffffffff
(lldb) ^D
```

`srcbuf` has not been allocated. Its value is -1, or `MAP_FAILED`, as the `mmap` manpage on macOS says it will when it fails. Seems like the feature test should not check that the returned pointer is nonzero; it should check that it is not `MAP_FAILED`.

When `mmap` returns `MAP_FAILED` it sets `errno`. Checking that, I see it returns 19 which means:
```
$ errno 19
ENODEV 19 Operation not supported by device
```

```diff
--- src/lib/libast/features/lib.orig	2021-05-10 11:42:42.000000000 -0500
+++ src/lib/libast/features/lib	2021-12-11 12:03:24.000000000 -0600
@@ -544,7 +544,7 @@
 			return 0;
 		if ((fd = open("/dev/zero", O_RDWR)) < 0)
 			return 0;
-		if (!(srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)))
+		if ((srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)) == MAP_FAILED)
 			return 0;
 		if (!mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0))
 			return 0;
```

With this change the test passes, though of course the full functionality of `memccpy` is not being exercised by the test in this case.

**Comment by ryandesign** [comment]
I guess all three invocations of `mmap` should be fixed:
```diff
--- src/lib/libast/features/lib.orig	2021-05-10 11:42:42.000000000 -0500
+++ src/lib/libast/features/lib	2021-12-11 12:18:59.000000000 -0600
@@ -490,7 +490,7 @@
 			return 1;
 		}
 		m = n * (sizeof(x)-1);
-		if (!(b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)))
+		if ((b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)) == MAP_FAILED)
 		{
 			close(d);
 			return 1;
@@ -544,9 +544,9 @@
 			return 0;
 		if ((fd = open("/dev/zero", O_RDWR)) < 0)
 			return 0;
-		if (!(srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)))
+		if ((srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)) == MAP_FAILED)
 			return 0;
-		if (!mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0))
+		if (mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0) == MAP_FAILED)
 			return 0;
 		for (i = 0; i < siz; i++)
 			srcbuf[i] = 'x';
```

**Comment by ryandesign** [comment]
Some other code, e.g. in src/lib/libast/features/mmap, checks if the result is either 0 or -1 to indicate failure.
```c
		mm = mmap((caddr_t)0, sizeof(buf), (PROT_READ|PROT_WRITE),
			  (MAP_PRIVATE|MAP_VARIABLE), fd, 0);
		if(mm == (caddr_t)0 || mm == (caddr_t)(-1))
			return Failed(file);
```
That could be done in the `memccpy` test too if desired.

**Comment by McDutchie** [comment]
Thank you very much for that, @ryandesign.

The macro `MAP_FAILED` is not used anywhere else in this code base. Indeed, it seems to be a [new addition to POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/mmap.html#tag_16_332_08):
> Existing implementations of *mmap()* return the value -1 when unsuccessful. Since the casting of this value to type **void \*** cannot be guaranteed by the ISO C standard to be distinct from a successful value, this volume of POSIX.1-2017 defines the symbol MAP_FAILED, which a conforming implementation does not return as the result of a successful call.

So, for backwards compatibility, we should get the `mmap` feature test to check if `MAP_FAILED` is defined, and if not, output a directive that defines it as `(void*)-1` which does work on most/all systems in practice. Then we should update the rest of the code base to use `MAP_FAILED`.

**Comment by McDutchie** [comment]
The '[mmap is worth using](https://github.com/ksh93/ksh/blob/dfb699b5caeac31494886de5fe0151bd7456446a/src/lib/libast/features/mmap#L222-L324)' test returns negative on macOS for some reason – at least macOS 10.14.6 x86_64. (sigh)

@ryandesign: any ideas?

In the meantime, for now I'll just fix the `lib_memccpy` test and make it build properly, as this is getting too big for this issue.

**Comment by McDutchie** [comment]
New patch against master, @ryandesign could you please test this?
```diff
diff --git a/src/cmd/INIT/cc.darwin b/src/cmd/INIT/cc.darwin
deleted file mode 100755
index e9e188c6..00000000
--- a/src/cmd/INIT/cc.darwin
+++ /dev/null
@@ -1,52 +0,0 @@
-: unix wrapper for macOS cc : 2020-07-17 :
-
-HOSTTYPE=darwin.generic
-
-case " $* " in
-*" -dumpmachine "*) echo $HOSTTYPE; exit ;;
-esac
-
-CC=/usr/bin/cc
-op=init
-for arg
-do	case $op in
-	init)	op=ld
-		set ''
-		;;
-	esac
-	case $arg in
-	-c)	op=cc
-		;;
-	-E)	op=cpp
-		continue
-		;;
-	-G)	op=dll
-		continue
-		;;
-	-lc)	continue
-		;;
-	-lm)	continue
-		;;
-	esac
-	set "$@" "$arg"
-done
-case $# in
-0)	;;
-*)	shift ;;
-esac
-case $* in
--v)	$CC "$@"; exit ;;
-esac
-case $op in
-init)	echo "cc: arguments expected" >&2
-	exit 1
-	;;
-cpp)	$CC -E "$@"
-	;;
-cc)	$CC -D_ast_int8_t=int64_t -D_lib_memccpy "$@"
-	;;
-dll)	$CC -Wl,-flat_namespace -dynamiclib -undefined dynamic_lookup "$@"
-	;;
-ld)	$CC -Wl,-search_paths_first "$@"
-	;;
-esac
diff --git a/src/lib/libast/features/lib b/src/lib/libast/features/lib
index 39410ad9..70dfe5be 100644
--- a/src/lib/libast/features/lib
+++ b/src/lib/libast/features/lib
@@ -446,6 +446,9 @@ tst	lib_memcmp string.h note{ standard memcmp interface that works }end execute{
 }end
 
 tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat.h sys/mman.h fcntl.h note{ standard memccpy interface that works }end execute{
+	#ifndef MAP_FAILED
+	#define MAP_FAILED ((void*)-1)	/* introduced in POSIX-1.2017 */
+	#endif
 	#if _STD_
 	static void gotcha(int sig)
 	#else
@@ -490,7 +493,7 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 			return 1;
 		}
 		m = n * (sizeof(x)-1);
-		if (!(b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)))
+		if ((b = mmap((void*)0, m, PROT_READ|PROT_WRITE, MAP_PRIVATE, d, (off_t)0)) == MAP_FAILED)
 		{
 			close(d);
 			return 1;
@@ -544,9 +547,9 @@ tst	lib_memccpy string.h unistd.h stdlib.h fcntl.h signal.h sys/types.h sys/stat
 			return 0;
 		if ((fd = open("/dev/zero", O_RDWR)) < 0)
 			return 0;
-		if (!(srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)))
+		if ((srcbuf = (char*)mmap(NULL, siz, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0)) == MAP_FAILED)
 			return 0;
-		if (!mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0))
+		if (mmap(srcbuf + siz, siz, PROT_NONE, MAP_PRIVATE, fd, 0) == MAP_FAILED)
 			return 0;
 		for (i = 0; i < siz; i++)
 			srcbuf[i] = 'x';
```

**Comment by ryandesign** [comment]
I can test it tomorrow.

I assume that by deleting the wrapper the compiler will be called directly?

I'm just wary about deleting the wrapper without really knowing why it's there. I mean, those various flags were added for a reason. `-search_paths_first` was added because Apple is using it in their ksh builds, and the comment in their Makefile explaining why says it is to "find ksh overrides before libSystem". Are there still "ksh overrides"? The `-dynamiclib` flag is needed to make a shared library. `-flat_namespace -undefined dynamic_lookup` is one of the two ways (granted, it's the obsolete for-Mac-OS-X-10.2-and-older way) to indicate that you want to allow undefined symbols in your library; without it, undefined symbols will cause a build failure. Is it that this wrapper was made generically and the shared library commands were never used? Did there used to be a shared library and it was removed and there will never be any shared libraries in ksh again? I'm worried that although I could build successfully bypassing the wrapper, maybe there are optionally buildable ksh features that might require it.

**Comment by McDutchie** [comment]
This distribution is not currently capable of building dynamic libraries because that requires AST nmake, which we got rid of right from the get go, as it didn't work on the Mac at all. I later experimented with restoring it. I got things to build but there was a mysterious regression test failure; building also took about twice as long, and it's slow already. So I gave up in frustration. I acknowledge that nmake had desirable qualities, but no one has time to maintain a complicated make system that is not used anywhere else and is very probably just as buggy as ksh was before we started on it.

I'm working to restore the ability to build dynamic libraries in a new, simple and cleanly separated way, see #357 to track my progress on that. Those system-specific dynamic library building flags will be added to a new generic compiler wrapper script instead – roughly comparable to GNU libtool, but specific to this code base and much simpler.

Now that we've determined that Apple's `-D_ast_int8_t=int64_t` addition is a no-op (on 32-bit systems, `_ast_int8_t` is defined as `long long` and on 64-bit systems it's defined as `long`, either way it's equivalent) and removed the need to pass `-D_lib_memccpy`, the rest is irrelevant and will remain so in this distribution. So the darwin compiler wrappers can safely go away.

In the longer term I hope to get rid of all compiler wrappers, as I think it's a very flawed way to make a build work. As you've observed, simply passing the `CC` env var breaks it, and that's just rubbish.

**Comment by McDutchie** [comment]
Regarding this flag:

> `-search_paths_first` was added because Apple is using it in their ksh builds, and the comment in their Makefile explaining why says it is to "find ksh overrides before libSystem". Are there still "ksh overrides"?

My `man ld` says for that flag: "This is now the default (in Xcode4 tools)". Which is from 2010, and we're currently at Xcode 13. So I'm not worried about that one either. :)

**Comment by ryandesign** [comment]
Good to know. MacPorts still works back to Mac OS X 10.4 which maxes out at Xcode 2.5 (and you mentioned your Power Mac running Mac OS X 10.3 which would use Xcode 1.5) so if I notice any build failures on old OS versions I'll keep it in mind to try re-adding this flag.

**Comment by McDutchie** [comment]
It's building just fine for me on my museum-grade Power Mac G5 with Mac OS X 10.3, with this fix and without any wrapper, and without introducing any new regression test failures.
