### ISSUE TITLE
AIX build error with ar on ibm.risc-64

### ISSUE THREAD

**Issue by HansH111** [ksh93/ksh#385]
I get an error when building a 64bit version on AIX

ar: 0707-100 -lsum does not exist.

And it goes back to the first:

**Comment by HansH111** [comment]
I get an error when building a 64bit version on AIX
ar: 0707-100 -lsum does not exist.

And it goes back to the first ar:
ar: 0707-126 state.o is not valid with the current object file mode.
        Use the -X option to specify the desired object mode.

seems it is missing a -X64 flag.

But if I try to define it with AR="ar -X64"   the bin/package make does not work
because it check if it can be found in the path

So I defined a  export  ARFLAGS="-X64"
and I adapted the bin/package  as
```diff
nlxsapan11:sapmgr> diff -u package.old package
---     1944-07-08 23:41:20.000000000 +0000
+++     1944-07-08 23:41:20.000000000 +0000
@@ -2964,6 +2964,7 @@
                        ;;
                esac
        done
+         [ -n "$ARFLAGS" ] && AR="$AR $ARFLAGS"

        # verify the top view
```
After that it builds correctly.

no idea if there is a different way to solve this.

**Comment by McDutchie** [comment]
Unfortunately, polarhome.com is now officially dead, so it looks very unlikely that I'll ever have access to an AIX test system again. And no, I'm not going to pay significant money to get one; I'm already donating huge amounts of my time, that should be enough. If I am to test and fix AIX problems, someone needs to donate me access to an AIX test system.

**Comment by McDutchie** [comment]
Having said that… It may be possible to fix this problem by adding an ar wrapper script to the src/cmd/INIT directory.

There is currently an example in src/cmd/INIT/ar.ibm.risc

Copy that to a new file name, where you change the `ibm.risc` part of the file name to your host type, i.e., the output of `bin/package host type` or the name of your `arch` subdirectory. Then edit it to use the ar flags you need.

If you figure out a correct ar wrapper script to use, please post it here so I can commit it. Thanks.

**Comment by JohnoKing** [comment]
I just made a pull request that adds an `ar` wrapper for ibm.risc-64: https://github.com/ksh93/ksh/pull/428. @HansH111 you'll need to confirm if it fixes the AIX build error, as I don't have an AIX system to test it on.

**Comment by HansH111** [comment]
compilation now works with that src/cmd/INIT/ar.ibm.risc-64 wrapper.

thx
