### ISSUE TITLE
Converting indexed array to associative fails in non-forked comsub

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#409]
I am experimenting with a shell option that causes subshells to always fork. Activating it exposes some bugs. This is one of them.

Reproducer:
```
$ unset a
$ typeset -a a=(1 2 3)
$ x=$(typeset -A a; typeset -p a); echo "$x"
typeset -A a=()                              <=== BAD; conversion failed
$ x=$(ulimit -t unlimited; typeset -A a; typeset -p a); echo "$x"
typeset -A a=([0]=1 [1]=2 [2]=3)             <=== ok; forking works around it
$ (typeset -A a; typeset -p a)
typeset -A a=([0]=1 [1]=2 [2]=3)             <=== ok; non-comsub subshell works
$ typeset -p a
typeset -a a=(1 2 3)                         <=== ok; didn't affect main shell
$ typeset -A a; typeset -p a
typeset -A a=([0]=1 [1]=2 [2]=3)             <=== ok; works in main shell
```

The fact that [these regression tests](https://github.com/ksh93/ksh/blob/5422af4e333e7c37c6beb46e7173c3653e8a0eaa/src/cmd/ksh93/tests/arith.sh#L805-L849) pass is a bug, because prior to them, [`a` was already typeset as an indexed array](https://github.com/ksh93/ksh/blob/5422af4e333e7c37c6beb46e7173c3653e8a0eaa/src/cmd/ksh93/tests/arith.sh#L561). Since `a` is not unset before repurposing it, the following regression test failures should have occurred: <details><summary>Test failures</summary>
```
	arith.sh[809]: FAIL: Array subscript quoting test 2A: expected $'typeset -A a=([\'1$(echo INJECTION >&2)\']=1)', got $'typeset -A -l -i a=([0]=2 [1]=495 [\'1$(echo INJECTION >&2)\']=1)'
	arith.sh[811]: FAIL: Array subscript quoting test 2B: expected $'typeset -A a=([\'1$(echo INJECTION >&2)\']=1)', got $'typeset -A -l -i a=([0]=2 [1]=495 [\'1$(echo INJECTION >&2)\']=1)'
	arith.sh[815]: FAIL: Array subscript quoting test 3A: expected $'typeset -A a=([\'$0`echo INJECTION >&2`\']=1)', got $'typeset -A -l -i a=([\'$0`echo INJECTION >&2`\']=1 [0]=2 [1]=495)'
	arith.sh[817]: FAIL: Array subscript quoting test 3B: expected $'typeset -A a=([\'$0`echo INJECTION >&2`\']=1)', got $'typeset -A -l -i a=([\'$0`echo INJECTION >&2`\']=1 [0]=2 [1]=495)'
	arith.sh[821]: FAIL: Array subscript quoting test 4A: expected $'typeset -A a=([\'x\\]+b\\[$(echo INJECTION >&2)\']=1)', got $'typeset -A -l -i a=([0]=2 [1]=495 [\'x\\]+b\\[$(echo INJECTION >&2)\']=1)'
	arith.sh[823]: FAIL: Array subscript quoting test 4B: expected $'typeset -A a=([\'x\\]+b\\[$(echo INJECTION >&2)\']=1)', got $'typeset -A -l -i a=([0]=2 [1]=495 [\'x\\]+b\\[$(echo INJECTION >&2)\']=1)'
	arith.sh[827]: FAIL: Array subscript quoting test 5A: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[829]: FAIL: Array subscript quoting test 5B: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[831]: FAIL: Array subscript quoting test 5C: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[833]: FAIL: Array subscript quoting test 5D: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[835]: FAIL: Array subscript quoting test 5E: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[837]: FAIL: Array subscript quoting test 5F: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[839]: FAIL: Array subscript quoting test 5G: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[841]: FAIL: Array subscript quoting test 5H: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[843]: FAIL: Array subscript quoting test 5I: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[845]: FAIL: Array subscript quoting test 5J: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[847]: FAIL: Array subscript quoting test 5K: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[849]: FAIL: Array subscript quoting test 5L: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
	arith.sh[851]: FAIL: Array subscript quoting test 5M: expected $'typeset -A a=([\'$var\']=1)', got $'typeset -A -l -i a=([\'$var\']=1 [0]=2 [1]=495)'
```
</details>

#94 is a related bug.

**Comment by McDutchie** [comment]
So, yet again, forking is an effective workaround, and we've got the umpteenth bug with non-forking subshells. (See also my rant in 4491bc6a991759b61c5f7d49dd0477a2f2bfb1a1.)

To work around this one, we need to fork in bltins/typeset.c, unlike #94 which requires [a fork in sh/xec.c](https://github.com/ksh93/ksh/issues/94#issuecomment-1002397084) – because in this bug we are not passing any assignment-argument so all processing is done in typeset.c.

```diff
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -270,6 +270,8 @@ int    b_typeset(int argc,register char *argv[],Shbltin_t *context)
 				tdata.tname = opt_info.arg;
 				break;
 			case 'A':
+				if(sh.subshell && !sh.subshare)
+					sh_subfork();
 				flag |= NV_ARRAY;
 				break;
 			case 'C':
```

**Comment by JohnoKing** [comment]
This is about as far I got debugging this so far. The bug may have something to do with this codeblock:
https://github.com/ksh93/ksh/blob/00300f976fc5e049c3f4d9dfab8900fd6e7ce567/src/cmd/ksh93/bltins/typeset.c#L1363-L1373
When `sh_assignok` creates a local scope for a variable, it will remove the array's discipline function because it's moved, not copied:
https://github.com/ksh93/ksh/blob/00300f976fc5e049c3f4d9dfab8900fd6e7ce567/src/cmd/ksh93/sh/nvdisc.c#L988-L991
The `sh_assignok` code removed the discipline function from the array, which causes `nv_arrayptr` to return a null pointer (it calls `nv_hasdisc`, which will not find the array discipline function). `nv_setarray` only converts arrays that have a discipline function:
https://github.com/ksh93/ksh/blob/00300f976fc5e049c3f4d9dfab8900fd6e7ce567/src/cmd/ksh93/sh/array.c#L927-L932
https://github.com/ksh93/ksh/blob/00300f976fc5e049c3f4d9dfab8900fd6e7ce567/src/cmd/ksh93/sh/array.c#L990-L999
https://github.com/ksh93/ksh/blob/00300f976fc5e049c3f4d9dfab8900fd6e7ce567/src/cmd/ksh93/bltins/typeset.c#L831-L845

**Comment by McDutchie** [comment]
I've been trying various ways of fixing it using the information @JohnoKing found above, but I've got nothing but crashes or data corruption so far.

In the meantime, here is a better and more specific forking workaround. We're forking from setall() which is called by b_typeset(). Only fork if we're actually converting a variable to an associative array, i.e.: the NV_ARRAY (-A, associative array) attribute was passed, there are no assignments (sh.envlist is NULL), and the variable is not unset and is not already an associative array.

This effectively makes it work correctly, and the use case of doing this in a subshell is rare enough that I've no performance concerns.

```diff
diff --git a/src/cmd/ksh93/bltins/typeset.c b/src/cmd/ksh93/bltins/typeset.c
index f85a72eb2..56adae37b 100644
--- a/src/cmd/ksh93/bltins/typeset.c
+++ b/src/cmd/ksh93/bltins/typeset.c
@@ -823,13 +823,15 @@ static int     setall(char **argv,register int flag,Dt_t *troot,struct tdata *tp
 			}
 			if(troot==sh.var_tree)
 			{
-				if(sh.subshell)
+				if(sh.subshell && !sh.subshare)
 				{
 					/*
 					 * Create local scope for virtual subshell. Variables with discipline functions
 					 * (LC_*, LINENO, etc.) need to be cloned, as moving them will remove the discipline.
 					 */
-					if(!nv_isattr(np,NV_NODISC|NV_ARRAY) && !nv_isvtree(np))
+					if((flag&NV_ARRAY) && !sh.envlist && !nv_isnull(np))
+						sh_subfork();	/* work around https://github.com/ksh93/ksh/issues/409 */
+					else if(!nv_isattr(np,NV_NODISC|NV_ARRAY) && !nv_isvtree(np))
 						np=sh_assignok(np,2);
 					else
 						np=sh_assignok(np,0);
```

**Comment by McDutchie** [comment]
My original reproducer includes:
> ```
> $ (typeset -A a; typeset -p a)
> typeset -A a=([0]=1 [1]=2 [2]=3)             <=== ok; non-comsub subshell works
> ```

In fact, this only works on interactive shells because that subshell is forked as of d11d4c7acd44ae478fd182a4fa5db9e45f989a04. In scripts, regular subshells fail the same way as command substitutions.
