### ISSUE TITLE
Extra zero element added to array after unsetting all subscripts in array

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#420]
This bug was originally reported in https://github.com/att/ast/issues/69#issuecomment-325551035. Unsetting all array subscripts without unsetting the array itself will cause a '0' element to be added to the array:
```sh
$ cat /tmp/bar
#!/bin/ksh
typeset -a X_ARR=(aa bb cc)
typeset -p X_ARR
unset X_ARR[2]
unset X_ARR[1]
unset X_ARR[0]
typeset -p X_ARR

# Bad results from ksh93u+m, ksh93u+ and ksh93v- 2012-08-24
$ ksh /tmp/bar
typeset -a X_ARR=(aa bb cc)
typeset -a X_ARR=([0]=)

# Correct results in ksh93v- 2012-10-04 and ksh2020
$ ksh93v /tmp/bar
typeset -a X_ARR=(aa bb cc)
typeset -a X_ARR=()
```

I identified ksh93v- 2012-10-04 as having fixed the bug, but I haven't made any progress in backporting the fix.

**Comment by JohnoKing** [comment]
Also of note is that giving an empty indexed array a `.unset` discipline function will add a zero element as well (see https://github.com/att/ast/issues/69#issuecomment-325435618):
```sh
$ cat /tmp/arrayunsetfunc
typeset -a Y_ARR
typeset -p Y_ARR
function Y_ARR.unset {
	:
}
typeset -p Y_ARR

# ksh93u+m, ksh93u+ and ksh93v- 2012-08-24
$ ksh /tmp/arrayunsetfunc
typeset -a Y_ARR
typeset -a Y_ARR=([0]=)

# ksh93v- 2012-10-04 and ksh2020
$ ksh93v /tmp/arrayunsetfunc
typeset -a Y_ARR
typeset -a Y_ARR=()
```

**Comment by hyenias** [comment]
Not sure if I would call the `[0]=` an extra zero element being added to the array after unsetting all the individual elements. From issue #148, it would seem to me that ksh93 is expressing a 0 size/length array as such. And as @JohnoKing pointed out this fix exists in ksh93v-.
```
{
unset arr
typeset -a arr=(aa bb cc)
print -n len=${#arr[@]}': '; typeset -p arr
unset arr[2] arr[1] arr[0]
print -n len=${#arr[@]}': '; typeset -p arr
}
```
produces:
```
len=3: typeset -a arr=(aa bb cc)
len=0: typeset -a arr=([0]=)
```
