### ISSUE TITLE
`printf -v` cannot handle associative array members with `[` in name

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#421]
`printf -v` cannot assign a value to associative array members containing a quoted bracket in their name, although it works fine when avoiding `printf`. The following script should print 'line1' followed by 'line2', but `printf` complains that the variable name is invalid:
```sh
$ cat /tmp/arraysub 
typeset -A foo
# This doesn't work
printf -v foo\['['\] line1
echo ${foo['[']}
# This does work
foo['[']=line2
echo ${foo['[']}

$ ksh /tmp/arraysub 
/tmp/arraysub[3]: printf: foo[[]: invalid variable name

line2
```
Note that some scripts rely on being able to use quoted brackets in the name of an array member, such as [this keyboard trap (scroll to bottom of page)](http://www.bolthole.com/solaris/ksh-oddthings.html). Any such script can't be converted to use `printf -v` because of this bug.

**Comment by McDutchie** [comment]
> ```shell
> # This doesn't work
> printf -v foo\['['\] line1
> ```

It is logical that this doesn't work; it cannot. `printf` is a regular command so all forms of shell quoting are parsed and removed before `printf` can ever see them.

However, backslashes are also parsed by array subscripts themselves (apart from the shell grammar), and you can use that if you also quote the argument:

```shell
# This works
printf -v 'foo[\[]' line1
```

> ```
> # This does work
> foo['[']=line2
> ```

A shell assignment is part of the shell grammar, so can take shell quoting into account. IIRC, internally, this gets converted to backslashes of the kind that is used explicitly in the `printf` argument above.

**Comment by JohnoKing** [comment]
My bad, I didn't realize that escaping the bracket with a backslash would work in that manner. I'll close this issue.
