### ISSUE TITLE
"Killed: 9" Failure on MacOS M1 after 3023d53b3a061825f8649201cfeb1a9d36383f5a

### ISSUE THREAD

**Issue by dwierenga** [ksh93/ksh#429]
Compiling the dev branch at 3023d53b3a061825f8649201cfeb1a9d36383f5a results in a usable binary.  Advancing to the next commit builds just fine, but when I execute the binary it just says "Killed: 9".

This on Macbook Pro M1 running MacOS Monterey.

Logfile from shtests attached.

[shtests.log](https://github.com/ksh93/ksh/files/7873931/shtests.log)

**Comment by McDutchie** [comment]
So it's commit f0e54607e760ddf7540cd340ca1c2ebd2f899dca that causes the problem? I can't imagine how that is possible.

Unfortunately I don't have M1 hardware yet, but that might change in the next few months.

**Comment by dwierenga** [comment]
If you can tell me how to make the binary yield more information, like a stack trace, I’m happy to provide.

**Comment by McDutchie** [comment]
Unless that changed in macOS versions more recent than I have (10.14.6), stack traces are automatically done whenever a crash occurs and saved in ~/Library//Logs/DiagnosticReports.

**Comment by McDutchie** [comment]
@ryandesign, do you have access to M1 hardware to confirm this bug?

**Comment by ryandesign** [comment]
On a Mac mini with an Apple Silicon M1 processor, I tried building the latest commit as of now (011fc1122af8203984a24e72397da84821843c90) on both macOS 11.6.3 and macOS 12.2 and it worked fine on both.

**Comment by McDutchie** [comment]
Thanks @ryandesign, that's encouraging to hear.

@dwierenga, can you still reproduce the problem if you delete everything and rebuild from scratch, first making sure that the `CC` and `CCFLAGS` variables are unset so they use default values?

**Comment by McDutchie** [comment]
OK, given the lack of response so far I'm going to assume that @dwierenga's problem was some sort of fluke because something went wrong in the build process. Without further information, and with confirmation it's working fine on macOS 11.6.3 and 12.2 on M1, there's nothing else to do here. If it's still broken, just reply here with more info and I'll reopen the issue.

**Comment by dwierenga** [comment]
Apologies, I somehow missed the previous comments.

I deleted my repo tree and re-cloned.  The build process works just fine now, sorry for the false alarm.  Thanks for your efforts on this!

**Comment by McDutchie** [comment]
Glad to hear, thanks for letting us know.
