### ISSUE TITLE
FreeBSD: pty.sh fail: POSIX sh 101(C)

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#44]
On this system:

```
$ uname -vm
FreeBSD 12.1-RELEASE-p6 GENERIC  amd64
```

The following regression test failure occurs:
```
        pty.sh[291]: POSIX sh 101(C): line 323: expected "^backslash-erase=:\r?\n$", got EOF
```

The test in question:
https://github.com/ksh93/ksh/blob/f8114823504b4888a3308f078504c3fbf32b5d87/src/cmd/ksh93/tests/pty.sh#L291-L333

**Comment by JohnoKing** [comment]
The test always fails in vi mode or when there isn't an editing mode enabled, but it will pass in emacs mode. Placing the following line at the start of the regression test allows it to pass:
```
w set -o emacs
```

Replacing `set -o emacs` with `set -o vi` or `set +o vi; set +o emacs` causes the test failure to occur on Linux as well.

**Comment by JohnoKing** [comment]
The regression test that fails is testing the escaping backslash feature (see https://github.com/ksh-community/ksh/issues/8#issuecomment-605461221 for what it does). If escaping backslashes are disabled with a patch (like the one appended below) the test will always fail on Linux.

[ksh93-escbackslash.patch.txt](https://github.com/ksh93/ksh/files/4904742/ksh93-escbackslash.patch.txt)

**Comment by McDutchie** [comment]
Thanks, @JohnoKing, for figuring out what that test does exactly.

Just found this. After doing
```
stty erase ^H kill ^X
```
on the real terminal from which you're running the regression tests, this regression test failure (and another one that was introduced in a0dcdeea) goes away on FreeBSD. The regression test itself already issues that command, but apparently, FreeBSD's stty does not work correctly on a pty pseudoterminal…
