### ISSUE TITLE
The backported ksh93v- regex stack causes a performance regression in extglob.ksh

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#440]
The separate regex stack backported from ksh93v- in commit ffe84ee7 (which was reverted in b936c94fb, then reapplied in e311f1e65) is causing the shbench [extglob benchmark](https://github.com/ksh-community/shbench/blob/master/bench/extglob.ksh) benchmark to run a bit slower than it used to. Below are results from benchmarking (200 iterations for each shell):

```sh
# CCFLAGS was set to '-Os' for every build of ksh (run on Arch Linux, results could differ on other platforms).
#
# ksh-b9171968 and ksh-87ad17e6-oldstack aren't using the 93v- regex stack.
# ksh-ffe84ee7 and ksh-87ad17e6 are both using the separate regex stack.
#
$ ./shbench -b 'bench/extglob.ksh' -l 200 ./ksh-b9171968 ./ksh-ffe84ee7 ./ksh-87ad17e6 ./ksh-87ad17e6-oldstack

benchmarking ./ksh-b9171968, ./ksh-ffe84ee7, ./ksh-87ad17e6, ./ksh-87ad17e6-oldstack ...
*** extglob.ksh ***
# ./ksh-b9171968
# ./ksh-ffe84ee7
# ./ksh-87ad17e6
# ./ksh-87ad17e6-oldstack

---------------------------------------------------------------------------------------------------
name         ./ksh-b9171968       ./ksh-ffe84ee7       ./ksh-87ad17e6       ./ksh-87ad17e6-oldstack
---------------------------------------------------------------------------------------------------
extglob.ksh  0.399 [0.349-0.462]  0.494 [0.463-0.570]  0.516 [0.483-0.556]  0.384 [0.352-0.444]
---------------------------------------------------------------------------------------------------
```

**Comment by McDutchie** [comment]
My results with my usual `-O0 -g` debug build, both at commit 87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7, `ksh.old` with the regex stack change reverted and `ksh` without changes:
```
$ ./shbench -b bench/extglob.ksh -l 200 ../ksh/arch/darwin.i386-64/bin/ksh.old ../ksh/arch/darwin.i386-64/bin/ksh

benchmarking ../ksh/arch/darwin.i386-64/bin/ksh.old, ../ksh/arch/darwin.i386-64/bin/ksh ...
*** extglob.ksh ***
# ../ksh/arch/darwin.i386-64/bin/ksh.old
# ../ksh/arch/darwin.i386-64/bin/ksh

---------------------------------------------------------------------------------------
name         ../ksh/arch/darwin.i386-64/bin/ksh.old  ../ksh/arch/darwin.i386-64/bin/ksh
---------------------------------------------------------------------------------------
extglob.ksh  0.821 [0.783-0.953]                     1.196 [1.157-1.271]
---------------------------------------------------------------------------------------
```
So yeah, that's a significant difference.

**Comment by McDutchie** [comment]
This seems to fix it for me:

```diff
--- a/src/lib/libast/regex/regcomp.c
+++ b/src/lib/libast/regex/regcomp.c
@@ -3278,7 +3278,7 @@ regcomp(regex_t* p, const char* pattern, regflags_t flags)
 	if (!(p->env = (Env_t*)alloc(disc, 0, sizeof(Env_t))))
 		return fatal(disc, REG_ESPACE, pattern);
 	memset(p->env, 0, sizeof(*p->env));
-	if (!(p->env->mst = stkopen(STK_SMALL|STK_NULL)))
+	if (!(p->env->mst = stkopen(STK_NULL)))
 		return fatal(disc, REG_ESPACE, pattern);
 	memset(&env, 0, sizeof(env));
 	env.regex = p;
```

After this change (still with `-O0 -g` on my system):

```
$ ./shbench -b bench/extglob.ksh -l 200 ../ksh/arch/darwin.i386-64/bin/ksh

benchmarking ../ksh/arch/darwin.i386-64/bin/ksh ...
*** extglob.ksh ***
# ../ksh/arch/darwin.i386-64/bin/ksh

-----------------------------------------------
name         ../ksh/arch/darwin.i386-64/bin/ksh
-----------------------------------------------
extglob.ksh  0.789 [0.753-0.873]
-----------------------------------------------
```

Can you confirm this fixes the performance regression on your end?

I haven't looked in detail at what the `STK_SMALL` flag does, but I'm guessing it enables an optimisation that makes it use less memory at the expense of performance.

**Comment by JohnoKing** [comment]
That patch does fix the performance regression on my end. Result with `-Os`:
```
$ ./shbench -b 'bench/extglob.ksh' -l 200 ../ksh/arch/linux.i386-64/bin/ksh

benchmarking ../ksh/arch/linux.i386-64/bin/ksh ...
*** extglob.ksh ***
# ../ksh/arch/linux.i386-64/bin/ksh

----------------------------------------------
name         ../ksh/arch/linux.i386-64/bin/ksh
----------------------------------------------
extglob.ksh  0.375 [0.364-0.442]
----------------------------------------------
```

As for what `STK_SMALL` does, it's described in the [`stk(3)`](https://github.com/ksh93/ksh/blob/87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7/src/lib/libast/man/stk.3#L58-L60) man page as follows:
> A flags argument of `STK_SMALL` indicates that unused space on the stack should be freed whenever this stack ceases to be the active stack.

**Comment by McDutchie** [comment]
> As for what `STK_SMALL` does, it's described in the [`stk(3)`](https://github.com/ksh93/ksh/blob/87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7/src/lib/libast/man/stk.3#L58-L60) man page as follows:
> 
> > A flags argument of `STK_SMALL` indicates that unused space on the stack should be freed whenever this stack ceases to be the active stack.

Ah yes. That wasn't in my `grep -rwn STK_SMALL src` results. I should grep without the w flag more often. :)

However, it also seems to slash the block size that the stack uses by a factor of 16: https://github.com/ksh93/ksh/blob/87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7/src/lib/libast/misc/stk.c#L232-L237 https://github.com/ksh93/ksh/blob/87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7/src/lib/libast/misc/stk.c#L511-L516

Note that `USE_REALLOC` is never defined, it seems to be the start of another unfinished experiment – something for the next accumulated cleanups commit. https://github.com/ksh93/ksh/blob/87ad17e64f02f78ae2f17ce007a9c2a5e257cbf7/src/lib/libast/misc/stk.c#L282-L284

In fact, I can't find any other spots in the code where that `STK_SMALL` flag is checked for, so I wonder if the man page is even correct. Also, it does not document `STK_NULL`.

**Comment by JohnoKing** [comment]
This is somewhat unrelated, but while I was browsing around the ksh93v- source code I found this addition in the [2012-08-24 release](https://github.com/ksh93/ast-open-archive/blob/2012-08-24/src/cmd/ksh93/sh/macro.c#L2259-L2265):
```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index ef529f52..8df9d61d 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -2309,6 +2309,13 @@ static void mac_copy(register Mac_t *mp,register const char *str, register int s
 	Stk_t			*stkp=sh.stk;
 	int			oldpat = mp->pattern;
 	nopat = (mp->quote||(mp->assign==1)||mp->arith);
+	if(size>512)
+	{
+		/* pre-allocate to improve performance */
+		c = stktell(stkp);
+		stkseek(stkp,c+size+(size>>4));
+		stkseek(stkp,c);
+	}
 	if(mp->sp)
 		sfwrite(mp->sp,str,size);
 	else if(mp->pattern>=2 || (mp->pattern && nopat) || mp->assign==3)
```
I'm not sure what this is optimizing since it makes no difference in shbench on my system. The 2012-08-24 changelog mentions that the `.sh.match` rewrite improved performance, so maybe it's related to that?

**Comment by McDutchie** [comment]
I've no idea. If it makes no discernable difference we can just leave it out.
