### ISSUE TITLE
Leaks regression test fails, Debian Linux 11/64, dev@ea830096

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#443]
I removed the DEBUG leaks regression test messages

On the first Linode Debian 11:

```
debian-linode $ bin/shtests leaks
#### Regression-testing /home/mwilson/src/ksh/arch/linux.i386-64/bin/ksh ####
test leaks begins at 2022-01-31+02:14:36
	leaks.sh[167]: FAIL: unset of associative array: leaked approx 432 KiB after 16384 iterations
...
test leaks failed at 2022-01-31+02:14:39 with exit code 1 [ 35 tests 1 error ]
test leaks(C.UTF-8) begins at 2022-01-31+02:14:39
	leaks.sh[167]: FAIL: unset of associative array: leaked approx 756 KiB after 16384 iterations
...
test leaks(shcomp) begins at 2022-01-31+02:14:42
	shcomp-leaks.ksh[167]: FAIL: unset of associative array: leaked approx 540 KiB after 16384 iterations
...
test leaks(shcomp) failed at 2022-01-31+02:14:44 with exit code 1 [ 35 tests 1 error ]
Total errors: 3
CPU time       user:      system:
main:      0m00.000s    0m00.007s
tests:     0m05.957s    0m01.822s
```

On the second Linode Debian 11 (different leak):

```
bouncer $ bin/shtests leaks
#### Regression-testing /home/mwilson/src/ksh/arch/linux.i386-64/bin/ksh ####
...
test leaks(shcomp) begins at 2022-01-30+18:19:58
...
	shcomp-leaks.ksh[329]: FAIL: function call via autoload in command substitution: leaked approx 612 KiB after 16384 iterations
...
test leaks(shcomp) failed at 2022-01-30+18:20:02 with exit code 1 [ 35 tests 1 error ]
Total errors: 1
CPU time       user:      system:
main:      0m00.000s    0m00.012s
tests:     0m09.094s    0m03.609s
```

These are repeatable across successive compiles.

Does NOT happen on macOS 10.15.7, or 11.6.2, does not happen on my Ubuntu 20.04/64 VM or Mint 20.2/64 VM.  Which is weird because you'd think if it happens on actual Debian it'd happen on the derivatives.

**Comment by McDutchie** [comment]
What happens if you double the `max_iter` value here to 32768 and try the tests again on the linode machines? https://github.com/ksh93/ksh/blob/ea830096194ee3d704e6f104516d043635ccfafc/src/cmd/ksh93/tests/leaks.sh#L72

**Comment by posguy99** [comment]
> What happens if you double the `max_iter` value here to 32768 and try the tests again on the linode machines?

The first two double in size, and the third one seems to have disappeared.

```
debian-linode $ bin/shtests leaks
test leaks begins at 2022-01-31+02:55:44
	leaks.sh[167]: FAIL: unset of associative array: leaked approx 972 KiB after 32768 iterations
...
test leaks(C.UTF-8) begins at 2022-01-31+02:55:47
	leaks.sh[167]: FAIL: unset of associative array: leaked approx 1080 KiB after 32768 iterations

```

**Comment by McDutchie** [comment]
So, at least one of them is not a real leak – real leaks don't disappear if you increase the amount of test iterations. And I don't know if the other one is or not. What happens if you quadruple the value (65535) or octuple it (131072)?

Honestly, I'm about ready to give up on fixing the leak tests. Modern OS memory management is some kind of dark voodoo, you can't rely on it being consistent or predictable in any way. I don't understand it at all.

**Comment by posguy99** [comment]
I rebooted both Linode machines, the leak went away.  So I assume that means it's spurious.
