### ISSUE TITLE
confusing behaviour of backreferences with alternation

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#447]
```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|b)/<\1+\2>}"'
<a+a><b+\2>
```

I expected:

```
<a+a><b+>
```

These are OK:

```
$ var='a1b2' ksh -c 'print -r -- "${var//@(@(a)|b)@(?)/[1:<\1> 2:<\2> 3:<\3>]}"'
[1:<a> 2:<a> 3:<1>][1:<b> 2:<> 3:<2>]
```
```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|@(b))/<\1+\2>}"'
<a+a><b+>
````

Though in that latter one, we have the same problem with `\3`:

```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|@(b))/<\1+\2+\3>}"'
<a+a+\3><b++b>
```

**Comment by McDutchie** [comment]
> ```
> $ var='ab' ksh -c 'print -r -- "${var//@(@(a)|b)/<\1+\2>}"'
> <a+a><b+\2>
> ```
> 
> I expected:
> 
> ```
> <a+a><b+>
> ```

Why? Please explain.

The man page says:
```
              @(pattern-list)
                     Matches exactly one of the given patterns.
```

So, it seems to me that this says that, in `@(@(a)|b)`, if `@(a)` is matched, `b` is not. Why are you expecting a corresponding back reference?

Please note I'm not saying you're wrong and my request for an explanation is not rhetorical. I still don't fully grok ksh extended glob patterns.

Also the src/lib/libast/regex code is incomprehensible to mere mortals like me, and largely uncommented and undocumented. I think the chances of bugs in regex behaviour being fixed this century are low, unless someone is willing to pay for a bounty and get some exceptionally competent hackers on the case. See also #207.

**Comment by stephane-chazelas** [comment]
There are too `x(...)` in the `@(@(a)|b)` pattern. `\1` should expand to what is matched by the first, `\2` with what is matched by the second. That's how `s/.../.../` works in `sed` / `perl`, etc.

Even if you argue that since the second `@(...)` doesn't match, there is nothing `\2` can expand to, then it's still inconsistent with:

```
$ var='bc' ksh -c 'print -r -- "${var//@(@(a)|b)@(c)/<\2,\3>}"'
<,c>
```

Where the second `@(...)` didn't match either but `\2` expanded to nothing, not `\2` literally.

**Comment by stephane-chazelas** [comment]
For the record, I came across that whilst coming up with https://unix.stackexchange.com/questions/689003/how-to-get-all-escaped-literal-symbols-in-a-string-using-bash-substitution/689030#689030

That:

```
s/(pattern)|./\1/g
```

is a common idiom to remove all but all the occurrences of a pattern.

**Comment by stephane-chazelas** [comment]
FWIW, it looks like `fish` had a similar issue fixed recently.

With 3.1.0:

```
> string replace -ar '(a)|b' '<$1>' ab
string replace: Regular expression substitute error: requested value is not set
```

With 3.3.1:

```
> string replace -ar '(a)|b' '<$1>' ab
<a><>
````

**Comment by stephane-chazelas** [comment]
> FWIW, it looks like `fish` had a similar issue fixed recently.
[...]

That was https://github.com/fish-shell/fish-shell/issues/7343
