### ISSUE TITLE
Intermittent regression due to faulty exec optimisation

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#449]
Continuing from: https://github.com/ksh93/ksh/issues/344#issuecomment-1018054675

The following regression test failure occurs intermittently:
```
test signal(C.UTF-8) begins at 2022-01-20+22:37:34
	signal.sh[65]: FAIL: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got PIPED)
test signal(C.UTF-8) failed at 2022-01-20+22:37:44 with exit code 1 [ 51 tests 1 error ]
```

Standalone reproducer:
```sh
trap 'rm -f out2' EXIT
typeset -li i=0
while :
do
printf '\r%d: ' "$((i++))"
(
	: disabling xtrace for this test
	set +x -o pipefail
	{
		$SHELL 2> out2 <<- \EOF
			g=false
			trap 'print -u2 PIPED; $g && exit 0;g=true' PIPE
			while :
			do 	print hello
			done
		EOF
	} | head > /dev/null
) &
cop=$!
{ sleep .4; kill $cop; } 2>/dev/null &
spy=$!
if	wait $cop 2>/dev/null
then	kill $spy 2>/dev/null
else	# 'wait $cop' will have passed on the nonzero exit status from the background job into $?
	e=$?
	echo "pipe with --pipefail PIPE trap hangs or produced an error" \
		"(got status $e$( ((e>128)) && print -n /SIG && kill -l "$e"))"
fi
wait
exp=$'PIPED\nPIPED'
got=$(<out2)
[[ $got == "$exp" ]] || echo 'SIGPIPE output on standard error is not correct' \
	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
done
```
Run like:
```
$ SHELL=$PWD/arch/darwin.i386-64/bin/ksh arch/darwin.i386-64/bin/ksh reproducer.sh
```
Sample output on my system (macOS 10.14.16 x86_64):
```
1209: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got PIPED)
2749: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got '')
5524: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got PIPED)
5721: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got PIPED)
7522: SIGPIPE output on standard error is not correct (expected $'PIPED\nPIPED', got PIPED)
11593: ^C$ ▂
```

Failures seem to occur more frequently when system load is high.

The cause is that the background job (the `(`…`) &` block) finishes before the inner `$SHELL 2> out2 <<- \EOF` command is finished writing output. It is piped into `head` and that combined pipe is the last command in that subshell, so my hypothesis is that this is a faulty `no_fork` exec optimization in xec.c; that subshell has no business finishing before the pipe job within it is entirely finished.

This bug is reproducible also on ksh 93u+ 2012-08-01 and ksh2020.

**Comment by McDutchie** [comment]
The following patch seems to fix it reliably, confirming my hypothesis:
```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1589,7 +1589,8 @@ int sh_exec(register const Shnode_t *t, int flags)
 			&& !sh.st.trapcom[0]
 			&& !sh.st.trap[SH_ERRTRAP]
 			&& ((struct checkpt*)sh.jmplist)->mode!=SH_JMPEVAL
-			&& (execflg2 || (execflg && sh.fn_depth==0 && !(pipejob && sh_isoption(SH_PIPEFAIL))));
+			&& !pipejob
+			&& (execflg2 || (execflg && sh.fn_depth==0));
 			if(no_fork)
 				job.parent=parent=0;
 			else
```
Commands in a pipe (except for the last element) run asynchronously, so this optimisation risks terminating the parent process before the pipe is fully finished. This should never happen, so this optimisation should always be disabled when a pipe is running.

**Comment by McDutchie** [comment]
However, when we remove the `set -o pipefail` from the reproducer, the race condition is back, even with the above patch.

To fix that, we need the following as well. The `else` clause is executed when `pipefail` (`SH_PIPEFAIL`) is not active. When running a pipe construct (that is not a background job) we always need to wait until all elements of the pipe are finished before continuing to the next command. Doing anything else is simply incorrect, and is asking for race conditions.

```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1989,7 +1990,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 				memset(exitval,0,job.waitall*sizeof(int));
 			}
 			else
-				job.waitall |= (!pipejob && sh_isstate(SH_MONITOR));
+				job.waitall |= !pipejob;
 			job_lock();
 			nlock++;
 			do
```

**Comment by McDutchie** [comment]
Unfortunately that latter change introduces a few regressions:
```
	builtins.sh[601]: FAIL: read -t in pipe taking 10.003 secs - 1.00000000000000002 minimum - too long
	io.sh[352]: FAIL: read -n3 from fifo failed -- expected 'a', got 'abc'
	io.sh[355]: FAIL: read -n1 from fifo failed -- expected 'b', got 'd'
```

**Comment by McDutchie** [comment]
Well, this seems to fix it without any regressions, though I cannot explain exactly why yet. I've been unable to break this patch so far.
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 5b581cc03..c73c5781a 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1523,7 +1523,8 @@ int sh_exec(register const Shnode_t *t, int flags)
 			&& !sh.st.trapcom[0]
 			&& !sh.st.trap[SH_ERRTRAP]
 			&& ((struct checkpt*)sh.jmplist)->mode!=SH_JMPEVAL
-			&& (execflg2 || (execflg && sh.fn_depth==0 && !(pipejob && sh_isoption(SH_PIPEFAIL))));
+			&& !pipejob
+			&& (execflg2 || (execflg && sh.fn_depth==0));
 			if(no_fork)
 				job.parent=parent=0;
 			else
@@ -1938,7 +1939,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 				memset(exitval,0,job.waitall*sizeof(int));
 			}
 			else
-				job.waitall |= (!pipejob && sh_isstate(SH_MONITOR));
+				job.waitall |= (!pipejob && sh_isstate(SH_INTERACTIVE));
 			job_lock();
 			nlock++;
 			do
```

**Comment by McDutchie** [comment]
I wrote:
> When running a pipe construct (that is not a background job) we always need to wait until all elements of the pipe are finished before continuing to the next command. Doing anything else is simply incorrect, and is asking for race conditions.

Actually, that's wrong. POSIX [allows it](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_02):
> If the pipeline is not in the background (see [Asynchronous Lists](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_03_02)), the shell shall wait for the last command specified in the pipeline to complete, **and may also wait for all commands to complete**.

**Comment by posguy99** [comment]
Can someone explain that statement from POSIX to me with very small words?

You were saying that if the line was 

`A | B | C | D`

the shell should wait untill all of A/B/C/D have ended.

POSIX says you only have to wait for D to end?  Ok, fine, but how can D end if the other three haven't?  What, D accepts some output from C, and then explicitly terminates, but C is still producing output?  Where does that make sense?

Maybe I just don't have enough coffee.

**Comment by McDutchie** [comment]
This applies if the last command stops reading data from the pipe and exits before the others are finished, so the pipe breaks. Consider this useless, but illustrative example:
```
sleep 3 | true
```

The `true` command does nothing with the pipe as it does not read any data (nor does `sleep` write any, but that's irrelevant here). `true` does nothing and terminates immediately, breaking the pipe. If you execute this as a script, it terminates immediately, not in 3 seconds. `sleep 3` happily sleeps in the background for three seconds.

So, when the last command in the pipeline exits, ksh continues with the next pipeline without caring whether the other commands in the pipeline are finished yet.

But if you enter this on the interactive command line, that pipeline does take three seconds to terminate! What gives?

From reading the source code I've now found that there are three circumstances where the shell *does* wait for all the commands in the pipeline to finish:
1. if the `-m`/`monitor` shell option is on (default on interactive shells and its subshells);
2. if the `pipefail` option is on;
3. if the pipeline is preceded by the `time` keyword.

All of this makes sense because these three things only work correctly if they get information about the entire pipeline run, so they have to make the shell wait for the entire pipeline to finish, whether the pipe is broken or not.

The ksh(1) man page only states (under "Commands"):
> A  *pipeline*  is a sequence of one or more commands separated by `|`.  The standard output of each command but the last is connected by a *pipe*(2) to the standard input of the next command.  Each command,  except  possibly  the last,  is  run  as a separate process; the shell waits for the last command to terminate.

I think that needs amending.
