### ISSUE TITLE
sh_match tests failure with @4b445059

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#459]
This is on macOS 12.2.1

```
$ bin/shtests sh_match
#### Regression-testing /Users/mwilson/src/ksh/arch/darwin.i386-64/bin/ksh ####
test sh_match begins at 2022-02-12+06:26:13
	sh_match.sh[502]: FAIL: test_xmlfragment1/0/testfile1.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
	sh_match.sh[502]: FAIL: test_xmlfragment1/1/testfile2.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
test sh_match failed at 2022-02-12+06:26:14 with exit code 2 [ 129 tests 2 errors ]
test sh_match(C.UTF-8) begins at 2022-02-12+06:26:14
	sh_match.sh[502]: FAIL: test_xmlfragment1/0/testfile1.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
	sh_match.sh[502]: FAIL: test_xmlfragment1/1/testfile2.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
test sh_match(C.UTF-8) failed at 2022-02-12+06:26:14 with exit code 2 [ 129 tests 2 errors ]
test sh_match(shcomp) begins at 2022-02-12+06:26:14
	shcomp-sh_match.ksh[502]: FAIL: test_xmlfragment1/0/testfile1.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
	shcomp-sh_match.ksh[502]: FAIL: test_xmlfragment1/1/testfile2.xml: Expected empty stderr, got $'test1_script.sh[2]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[3]: ulimit: 1048576: limit exceeded [Invalid argument]\ntest1_script.sh[4]: ulimit: 1048576: limit exceeded [Invalid argument]'
test sh_match(shcomp) failed at 2022-02-12+06:26:15 with exit code 2 [ 129 tests 2 errors ]
Total errors: 6
CPU time       user:      system:
main:      0m00.011s    0m00.018s
tests:     0m00.665s    0m00.550s
```

**Comment by McDutchie** [comment]
I cannot reproduce this.

This is the command that produces the ulimit error: https://github.com/ksh93/ksh/blob/4b445059788aeeadd8ff9940263140d6235a0e56/src/cmd/ksh93/tests/sh_match.sh#L133

Maybe you're running the tests from a shell in which a  lower memory use limit was already set. That would be inherited by the tests then. What do you get when you type `ulimit -M`?

**Comment by posguy99** [comment]
The test failure does not occur on macOS 10.15.7.

On the 12.2.1 machine:

```
$ ulimit -M
unlimited
```

**Comment by posguy99** [comment]
On macOS 12.2.1:

```
$ ulimit -M $(( 1024 * 1024 )) 
-ksh: ulimit: 1048576: limit exceeded [Invalid argument]
```


On macOS 10.15.7:

```
$ ulimit -M $(( 1024 * 1024 )) 
$ ulimit -M
1048576
```

**Comment by McDutchie** [comment]
Huh. So macOS 12.2.1 doesn't like the user setting a memory usage ulimit for some reason. The "Invalid argument" addition seems to suggest the OS has simply removed or disabled support for that, but I could be wrong.

Does setting that ulimit work in other shells on macOS 12.2.1? And does it work on ksh before commit 4b445059?

**Comment by McDutchie** [comment]
Hmm. ksh93 seems to be the only shell that supports `ulimit -M` so of course it's not going to work on other shells.

I suspect this is an OS issue and we can just ignore it, particularly if you can confirm that `ulimit -M` doesn't work on older ksh93 versions either on macOS 12.2.1.

**Comment by posguy99** [comment]
I get the same error with 20120801 on macOS 12.2.1


```
$ /bin/ksh
ksh: Version AJM 93u+ 2012-08-01
$ type ulimit
ulimit is a shell builtin
$ ulimit -M 8192
/bin/ksh: ulimit: 8192: limit exceeded [Invalid argument]

```

**Comment by McDutchie** [comment]
Thanks. Not our problem then. I've added a `2>/dev/null` to fix the regression test failure. 

Apparently this has never worked on macOS: https://stackoverflow.com/questions/3274385/how-to-limit-memory-of-a-os-x-program-ulimit-v-neither-m-are-working

macOS 12 reports the failure, which is actually an improvement over silently ignoring it.

**Comment by posguy99** [comment]
Funny bit... this is in the man page for setrlimit:

> COMPATIBILITY
>      setrlimit() now returns with errno set to EINVAL in places that historically succeeded.  It no longer
>      accepts "rlim_cur = RLIM_INFINITY" for RLIM_NOFILE.  Use "rlim_cur = min(OPEN_MAX, rlim_max)".

But it's in the man page on 10.15 too. 🤷‍♂️
