### ISSUE TITLE
ksh93 doesn't turn off non-blocking mode for stdin if a program it runs leaves it on

### ISSUE THREAD

**Issue by atheik** [ksh93/ksh#469]
Edit:

The non-cumbersome way to reproduce this in Debian Live would be the following:
```
ksh
# the rest is run in ksh

perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) | O_NONBLOCK)'

chfn
# broken

perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK)'

chfn
# works
```

Most shells seem to implicitly turn off non-blocking mode if a program they run leaves it on.
Some of them, like dash, give a useful message while most won't bother.
Maybe there is a reason why ksh93 doesn't turn off non-blocking mode and my googling fails me.

---

Original title: Many interactive programs break in Linux console when ran from ksh93 after "mlterm-fb -e /bin/true"
Original comment:

Programs that break include passwd, chfn, chsh, and many more.
I think this is a bug in ksh93 and not mlterm-fb because I have not been able to reproduce this with other shells.

Commit 2940b3f was the oldest version of ksh93 I tried.

If you would like, you can reproduce this in Debian Live under x86_64 QEMU:
```
curl -LO https://cdimage.debian.org/cdimage/release/11.2.0-live/amd64/iso-hybrid/debian-live-11.2.0-amd64-standard.iso
qemu-system-x86_64 -cpu host -accel kvm -m 1024 -drive file=debian-live-11.2.0-amd64-standard.iso,media=cdrom
```

Run the following in Debian Live:
```
sudo -i

curl -LO https://downloads.sourceforge.net/mlterm/mlterm-3.9.2.tar.gz
tar xf mlterm-3.9.2.tar.gz
cd mlterm-3.9.2
./configure --with-gui=fb
make
make install

curl -L https://codeload.github.com/ksh93/ksh/tar.gz/a833053 -o ksh-a833053.tar.gz
tar xf ksh-a833053.tar.gz
cd ksh-a833053
bin/package make
install -vm 755 arch/linux.i386-64/bin/ksh /usr/local/bin

ksh
# the rest is run in ksh

mlterm-fb -e /bin/true

passwd
# broken

chfn
# broken

chsh
# broken
```

If you try to reproduce this issue using the dash shell, it outputs the following message after mlterm-fb exits:
```
sh: turning off NDELAY mode
```

I think the problem is that mlterm-fb leaves stdin in non-blocking mode and ksh93 is oblivious to it.
Many shells and interactive programs seem to recognize this scenario and do turn off non-blocking mode.
The programs do work again when I turn off non-blocking mode:
```
perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK)'
```

I would be happy to test any suggested patches.

**Comment by atheik** [comment]
I wonder what does this break, bin/shtests passed:
```diff
diff --git a/src/cmd/ksh93/sh/io.c b/src/cmd/ksh93/sh/io.c
index 20215585..522e25fd 100644
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1944,7 +1944,7 @@ static ssize_t piperead(Sfio_t *iop,void *buff,register size_t size,Sfdisc_t *ha
 static ssize_t slowread(Sfio_t *iop,void *buff,register size_t size,Sfdisc_t *handle)
 {
 	int	(*readf)(void*, int, char*, int, int);
-	int	reedit=0, rsize;
+	int	reedit=0, rsize, n, fno;
 #if SHOPT_HISTEXPAND
 	char    *xp=0;
 #endif /* SHOPT_HISTEXPAND */
@@ -1969,6 +1969,14 @@ static ssize_t slowread(Sfio_t *iop,void *buff,register size_t size,Sfdisc_t *ha
 		errno = EINTR;
 		return(-1);
 	}
+	fno = sffileno(iop);
+#ifdef O_NONBLOCK
+	if((n=fcntl(fno,F_GETFL,0))&O_NONBLOCK)
+	{
+		n &= ~O_NONBLOCK;
+		fcntl(fno, F_SETFL, n);
+	}
+#endif /* O_NONBLOCK */
 	while(1)
 	{
 		if(io_prompt(iop,sh.nextprompt)<0 && errno==EIO)

```
Is there ever a case where fno is not 0 here?

**Comment by McDutchie** [comment]
Reproduced on Slackware 14.2 on VirtualBox with the `chsh` program.

If other shells turn off O_NONBLOCK I see no reason why ksh shouldn't. I think your patch has the correct approach. Yes, I'm pretty sure the file descriptor is always zero there – the shell always reads from standard input, as any redirections will have been processed at this stage. So you can get rid of the fno variable.

If you could do a pull request I'd be happy to merge it.

**Comment by McDutchie** [comment]
We also need to check for an error return value (-1, all bits set) before checking for the O_NONBLOCK bit.
