### ISSUE TITLE
typeset -L/-R/-Z output issues with input having spaces

### ISSUE THREAD

**Issue by lijog** [ksh93/ksh#476]
The typeset output for -L/-R/-Z seems to be wrong when the input has leading/trailing spaces. This started occurring after the dynamic buffer size changes introduced in name.c as part of the fix for 
https://github.com/ksh93/ksh/issues/142

The issue was observed on a Solaris11 test system, but I think it's a general issue. I also built the latest git source and verified that the issue is still present. Here's an illustration

BEFORE FIX #142 
*************************************************************************
$ typeset -L8 -x s_date1=" 22/02/09 08:25:01"
$ echo $s_date1
22/02/09
$ typeset -R10 -x s_date1="22/02/09 08:25:01  ";echo $s_date1       
9 08:25:01
$ typeset -R10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1                                                                                                     
9 08:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1
9 08:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01         ";echo $s_date1
9 08:25:01

AFTER FIX #142
****************************************************************************
$ typeset -L8 -x s_date1=" 22/02/09 08:25:01"
$ echo $s_date1
22/02/0
$ typeset -R10 -x s_date1="22/02/09 08:25:01   ";echo $s_date1                                                                                                      
8:25:01
$ typeset -R10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1                                                                                                     
:25:01
$
$ typeset -Z10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1
:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01         ";echo $s_date1
0000000001

The issue seems to be triggered as the field gets truncated as the size calculation doesn't account for the leading/trailing spaces, ie
code  at
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L3006-L3023

If we strip the leading space in the LJUST case, the -L option output is corrected, but I think that's not really needed as the this is done later in the code  at
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L1848-L1851

Similarly for RJUST, we might be able to compute the actual size after removing the trailing spaces and then fit the buffer accordingly but that will be redoing the work done by the rightjust function at
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L1987-L1991

Attached patch replaces the earlier dynamic buffer size calculation in nv_newattr with just the greater of the strlen and size.
+                    cp = (char*)malloc((n >= (unsigned)size ? n : (unsigned)size) + 1);
( which was proposed as a solution in https://github.com/ksh93/ksh/issues/142, but I guess it was incomplete at that time as the "dot" related changes were not included.)

This addresses the reported issues and I wasn't able to recreate the crash which I'd reported in the original issue
https://github.com/ksh93/ksh/issues/181

Just incase I've attached a dbx trace log with and without the fix to illustrate the issue, guess it's not really needed as the issue is readily reproducible.

**Comment by lijog** [comment]
[ksh-typeset.zip](https://github.com/ksh93/ksh/files/8362539/ksh-typeset.zip)

**Comment by hyenias** [comment]
@lijog I checked out the first set of suspect code you pointed out via some print statements, see below diff. Seems that lines 3006-3023 work for the datetime strings when applying the L/R/Z string justification against them.

> The issue seems to be triggered as the field gets truncated as the size calculation doesn't account for the leading/trailing spaces, ie
code at
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L3006-L3023

```diff
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index b0c085d5..536e04b7 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -2991,6 +2991,7 @@ void nv_newattr (register Namval_t *np, unsigned newatts, int size)
                                if(!*sp) sp--;          /* if number was 0, leave one zero */
                        }
                        n = strlen(sp);
+                       sfprintf(sfstderr,"size: %i, n: %i\n",size,n);
                        if(size==0 || (newatts&(NV_INTEGER|NV_BINARY)))
                        {
                                /* allocate to match existing value for numerics and auto length assignment for -L/R/Z */
@@ -3020,6 +3021,7 @@ void nv_newattr (register Namval_t *np, unsigned newatts, int size)
                                        strncpy(cp, sp, size);
                                }
                                cp[size] = '\0';
+                               sfprintf(sfstderr,"cp: '%s'\n",cp);
                        }
                        if(sp && (mp=nv_opensub(np)))
                        {
```
```
# First reproducer using L
$ arch/*/bin/ksh -c 'typeset -L8 dt=" 22/02/09 08:25:01"; typeset -p dt; echo ${#dt}'
size: 8, n: 18
cp: ' 22/02/0'
typeset -L 8 dt='22/02/0 '
8
$
# Second reproducer using R
$ arch/*/bin/ksh -c 'typeset -R10 dt="22/02/09 08:25:01 "; typeset -p dt; echo ${#dt}'
size: 10, n: 18
cp: ' 08:25:01 '
typeset -R 10 dt='  08:25:01'
10
$
# Third reproducer using Z
$ arch/*/bin/ksh -c 'typeset -Z10 dt="22/02/09 08:25:01 "; typeset -p dt; echo ${#dt}'
size: 10, n: 18
cp: ' 08:25:01 '
typeset -Z 10 -R 10 dt=0008:25:01
10
$
```

**Comment by lijog** [comment]
@hyenias 
Sorry I think I didn't copy paste the datetime string input properly or the formatting stripped the spaces not sure.
The input had some trailing space characters and is not of length 18.  Can you try with the string with more spaces at the end
```
BEFORE
-----------------------------------------
$ typeset -L8 -x s_date1=" 22/02/09 08:25:01"
$ echo $s_date1
22/02/09
$ typeset -L8 -x s_date1=" 22/02/09 08:25:01"
$ echo $s_date1
22/02/09
$ typeset -R10 -x s_date1="22/02/09 08:25:01  ";echo $s_date1       
9 08:25:01
$ typeset -R10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1                                                                                                     
9 08:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1
9 08:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01         ";echo $s_date1
9 08:25:01


AFTER
----------------------------------------------
$ typeset -L8 -x s_date1=" 22/02/09 08:25:01"
$ echo $s_date1
22/02/0
$ typeset -R10 -x s_date1="22/02/09 08:25:01   ";echo $s_date1                                                                                                      
8:25:01
$ typeset -R10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1                                                                                                     
:25:01
$
$ typeset -Z10 -x s_date1="22/02/09 08:25:01    ";echo $s_date1
:25:01
$ typeset -Z10 -x s_date1="22/02/09 08:25:01         ";echo $s_date1
0000000001
```

In the last example,  
```
s_date1="22/02/09 08:25:01         ", 
```
i.e the length of the field is 26, i.e 9 trailing spaces. 

So after the following block, 
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L3006-3012
```
			else
			{
				/* shrinking string */
				cp = (char*)sh_malloc((size_t)size + 1);
				if(newatts&NV_RJUST)
					strncpy(cp, n - size + sp, size);`
```
cp will be  
```
"1         ",  
```
which is passed later to the "rightjust" function at
https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/sh/name.c#L1987-1988
```
			if(nv_isattr(np, NV_RJUST) && nv_isattr(np, NV_ZFILL))
				rightjust(cp,size,'0');
```
leading to the  "0000000001" output

**Comment by hyenias** [comment]
Thanks that helped clear things up for me. I was not aware that leading/trailing spaces should be removed from the value before justification. So, I went searching documentation to validate that process for -L/R/Z strings. Here are my results:

In "The KornShell Command and Programming Language" by Morris Bolsky and David Korn on pages 54-55, there is no direct mention of leading or trailing spaces being removed before value assignment of any of the justification types. However, on page 54 on a cautionary note about parameter expansion when outside of double quotes; it indicates that leading and trailing spaces are removed when used as a command argument. I do not think that note applies to the typeset attribute description that follows that particular text.

Next, "The Korn Shell 3rd edition" by Anatole Olczak page 48 about variable attributes, it states that the attribute has precedence over the value. So, the attribute may change the value.

From `typeset --man`, it has no mention of leading/trailing space removal.
```
  -L[n]           Left justify. If n is given it represents the field width. If the -Z attribute is also specified, then leading zeros
                  are stripped. The option value may be omitted.
  -R[n]           Right justify. If n is given it represents the field width. If the -Z attribute is also specified, then zeros will be
                  used as the fill character. Otherwise, spaces are used. The option value may be omitted.
  -Z[n]           Zero fill. If n is given it represents the field width. The option value may be omitted.
```
However the `man src/cmd/ksh93/sh.1` under typeset has the following about discarding leading blanks from value when using left justification strings.
```
 -L     Left  justify and remove leading blanks from value.  If n is non-zero, it defines the width of the
        field, otherwise it is determined by the width of the value of first assignment.  When  the  vari‐
        able is assigned to, it is filled on the right with blanks or truncated, if necessary, to fit into
        the field.  The -R option is turned off.
 -R     Right  justify and fill with leading blanks.  If n is non-zero, it defines the width of the field,
        otherwise it is determined by the width of the value of  first  assignment.   The  field  is  left
        filled  with  blanks  or  truncated  from the end if the variable is reassigned.  The -L option is
        turned off.
 -Z     Right justify and fill with leading zeros if the first non-blank character is a digit and  the  -L
        option has not been set.  Remove leading zeros if the -L option is also set.  If n is non-zero, it
        defines the width of the field, otherwise it is determined by the width of the value of first  as‐
        signment.
```
It also appears from the code base that not just spaces are being removed but tabs as well.

As I compared how other shells behaved with leading and trailing spaces using justification strings, they all varied.

How exactly should ksh93u+m deal with leading and/or trailing spaces in values before attempting to justify them for each of the attributes: -L, -R, and -Z? Currently, we only have one documentation source that I am aware of directing removal of only leading blanks when processing left justification values.

**Comment by hyenias** [comment]
After investing ksh's source code and related man page descriptions for context around the usage of the term **blanks** and **spaces**; it appears the authors wanted to skip blanks consisting of spaces and tabs which matches POSIX character class **blank**.

@lijog, I am currently testing out the code fixes that address the removal of leading and trailing blanks (spaces and tabs) from value before justification. Left justified strings get their leading blanks removed. Right justified strings get their trailing blanks removed. It all appears to work with my limited testing but I have come across another inconsistency which shows up as follows with auto length/width assignments:
```
$ arch/*/bin/ksh -c 'typeset -L s=" 04/02/22 "; typeset -p s; echo ${#s}:"$s":'
typeset -L 10 s='04/02/22  '
10:04/02/22  :
$ arch/*/bin/ksh -c 'typeset -L s; s=" 04/02/22 "; typeset -p s; echo ${#s}:"$s":'
typeset -L 9 s='04/02/22 '
9:04/02/22 :
``` 
The outcomes of auto length/width assignments via typeset value assignment or successive value assignment should not differ. I am now working on that fix.

**Comment by lijog** [comment]
@hyenias, thanks for the update. 
Infact the original issue which was reported by a customer was related to leading spaces for the left justified option only, but I came across the other issues(-R/-Z) during my testing. I had also done some searching in the documentation for the expected behaviour for blank characters and could find explicit  references only for the -L option. But from the testing results for previous versions of ksh93 and even ksh88, it looks like spaces/tabs were always skipped. 
Thanks again for taking this up, I'll wait for the fix and testing results.

**Comment by hyenias** [comment]
I have found and fixed the auto width assignments. During my code cleanup, I found a couple of other issues that I am investigating at the moment.

**Comment by lijog** [comment]
@hyenias
Just checking if it would be possible to merge the fix for this specific issue now and the other issues as a separate commit if they require more time for investigation/testing.

**Comment by hyenias** [comment]
@lijog I am still developing my code and it is not ready at the moment to share out with all as a potential fix. Currently my developmental code might have fixed the justification strings but it has broken other aspects. It is a very slow learning process for me to understand the code base and correctly adjust it.

**Comment by McDutchie** [comment]
> [ksh-typeset.zip](https://github.com/ksh93/ksh/files/8362539/ksh-typeset.zip)

I just tested @lijog's patch from the zip file (sorry for the delay). It reintroduces [this bug](https://github.com/ksh93/ksh/issues/142#issuecomment-782013674):
```
test attributes begins at 2022-05-25+22:18:20
	attributes.sh[677]: FAIL: failed to zero-fill zero (expected $'00000\n000\n0000000', got 00000)
test attributes failed at 2022-05-25+22:18:20 with exit code 1 [ 156 tests 1 error ]
```
The test is: https://github.com/ksh93/ksh/blob/e5e19cdf27ac31ce49f2afe851697f9366bdf347/src/cmd/ksh93/tests/attributes.sh#L673-L678

The zipped patch undoes the simple one-line fix for that bug, which is: https://github.com/ksh93/ksh/blob/e5e19cdf27ac31ce49f2afe851697f9366bdf347/src/cmd/ksh93/sh/name.c#L2991

The remedy is keeping that fix and applying the rest of the patch, as below. On my end, this fixes the reproducer for this bug without introducing any regression test failures.

```diff
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index b0c085d56..2125cec41 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -2991,36 +2991,8 @@ void nv_newattr (register Namval_t *np, unsigned newatts, int size)
 				if(!*sp) sp--;		/* if number was 0, leave one zero */
 			}
 			n = strlen(sp);
-			if(size==0 || (newatts&(NV_INTEGER|NV_BINARY)))
-			{
-				/* allocate to match existing value for numerics and auto length assignment for -L/R/Z */
-				cp = (char*)sh_malloc((size_t)n + 1);
-				strcpy(cp, sp);
-			}
-			else if(size>=n)
-			{
-				/* growing string */
-				cp = (char*)sh_malloc((size_t)size + 1);
-				strcpy(cp, sp);
-			}
-			else
-			{
-				/* shrinking string */
-				cp = (char*)sh_malloc((size_t)size + 1);
-				if(newatts&NV_RJUST)
-					strncpy(cp, n - size + sp, size);
-				else
-				{
-					/* NV_LJUST and the rest */
-					if(newatts&NV_ZFILL)
-					{
-						while(*sp=='0') sp++;	/* skip initial zeros */
-						if(!*sp) sp--;		/* if number was 0, leave one zero */
-					}
-					strncpy(cp, sp, size);
-				}
-				cp[size] = '\0';
-			}
+			cp = (char*)malloc((n >= (unsigned)size ? n : (unsigned)size) + 1);
+			strcpy(cp, sp);
 			if(sp && (mp=nv_opensub(np)))
 			{
 				if(trans)
```

**Comment by McDutchie** [comment]
After testing it on macOS, Solaris and OpenBSD, it looks to me like @lijog's fix as amended above works correctly, so I'm going to apply it now and close this bug.

@hyenias, that is in no way meant to discourage you from continuing your investigations and perhaps improving on it further! :)

**Comment by McDutchie** [comment]
We should of course also be using sh_malloc instead of malloc directly, or we lose our out of memory checks.

**Comment by hyenias** [comment]
Understood. I am glad that my altered 1 line malloc code from #142 has helped resolve this outstanding issue. Good team effort!

I will continue with my efforts that improve on this fix.

**Comment by McDutchie** [comment]
Sorry about that @hyenias, I totally missed that I should have credited you for that as well.
