### ISSUE TITLE
What to do about typeset -L/-R combined with -i/-F/-E types?

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#48]
This is not currently supported. See #47.

After applying #47, `typeset -R10 -i foo=1; echo "[$foo]"` gives a usage error and something like `typeset -R10 -E3 foo=12345; echo "[$foo]"` or `typeset -R20 -F foo=12345; echo "[$foo]"` simply ignores the `-R` flag.

Which precedent should we follow? Maybe they should all error out? I think giving a usage error is more logical since this combination of flags is not actually possible. But it should be preceded by an informative error message such as "incompatible options combination".

Or maybe we should just fix it so they *can* be combined? I see no real reason why this should be impossible. On mksh (which only supports integer arithmetic) the following works fine:

```
$ mksh -c 'typeset -R10 -i foo=123 bar=4567; printf "%s\n" "[$foo]" "[$bar]"'
[       123]
[      4567]
```

The other ksh-inspired shell that supports floating point arithmetic is zsh, and it has no problem combining any of these:

```
$ zsh -c 'typeset -R20 -F foo=12345; echo "[$foo]"'
[    12345.0000000000]
$ zsh -c 'typeset -R20 -E3 foo=12345; echo "[$foo]"'
[            1.23e+04]
$ zsh -c 'typeset -R20 -i foo=12345; echo "[$foo]"'
[               12345]
```

Community opinions invited. Should this be supported, or should it be an error, or should the `-L`/`-R` be ignored for these?

**Comment by McDutchie** [comment]
To respond to @hyenias's [comment](https://github.com/ksh93/ksh/pull/47#issuecomment-650831081):
> I think having typeset being able to recreate a variable completely in one line is the correct thing to do. I should be able to do a `typeset -p` on a variable and then utilize that output to recreate it. I would differently like to have all the options supported consistently for the numeric types if appropriate. But that is out-of-scope for this particular bugfix. I do like the usage error being given if that could be done consistently.

Thanks for the feedback. Yes, of course `typeset -p` output should be fixed as well if we make it possible to combine these, thanks for pointing that out. For instance, on zsh:

```
$ zsh -c 'typeset -R20 -F foo=12345; typeset -p foo'
typeset -FR20 foo=12345.0000000000
```

**Comment by hyenias** [comment]
I think having typeset being able to recreate a variable completely in one line is the correct thing to do. I should be able to do a `typeset -p` on a variable and then utilize that output to recreate it. I would definitely like to have all the options supported consistently for the numeric types if appropriate. I do like the usage error being given if that could be done consistently.

**Comment by McDutchie** [comment]
Yes, of course `typeset -p` output should be fixed as well if we make it possible to combine these, thanks for pointing that out. For instance, on zsh:

```
$ zsh -c 'typeset -R20 -F foo=12345; typeset -p foo'
typeset -FR20 foo=12345.0000000000
```

**Comment by hyenias** [comment]
It appears when you apply a -L/R/Z to a previously defined numeric type variable (-i/F/E) the variable is changed to a text variable. Not sure if this behavior is documented.

**Comment by JohnoKing** [comment]
If -R/Z are to be combined with -i/F, the bitmask values for `NV_SHORT` and `NV_DOUBLE` will need to be changed. `NV_SHORT` uses the same bit as `NV_RJUST` (right justify), while `NV_DOUBLE` is `NV_INTEGER | NV_ZFILL` (which conflicts with -Z):
https://github.com/ksh93/ksh/blob/1b5bc1802a97010a0225bd7dba55001475334966/src/cmd/ksh93/include/nval.h#L167-L171
https://github.com/ksh93/ksh/blob/1b5bc1802a97010a0225bd7dba55001475334966/src/cmd/ksh93/bltins/typeset.c#L289-L295

**Comment by hyenias** [comment]
I have been working on typeset.c to correct precision of 0 issue and I can now say that attempting to alter NV_INTEGER related combo flags in any way will be met with enormous difficulty. So much logic has been tightly woven into the code base that altering them would not be worth it.

I suggest that the future potential solution try to find some unused bits for new flags. I have tried and failed at finding a new flag that doesn't mess other stuff up.

**Comment by McDutchie** [comment]
Right, so my conclusion is we're going to change very little here. There would be a good argument for making it work like zsh, but that doesn't seem to be realistically doable. I also don't think it has a very high priority. If someone else can manage this (e.g. by finding unused bits to allow new flag combinations) then I'd be very happy to accept a patch or pull request, but I'm not going to try this myself.

I do think we should issue an informative error message if -L/-R is combined with -i/-F/-E in the same typeset command, because that used to crash, or (in the case of -i) print an uninformative usage error.

However, if a typeset -L/-R was followed by separate typeset -i/-F/-E or vice versa, that always used to "work" in the sense that the second would cancel the effect of the first. It's conceivable that there are scripts that rely on thas behaviour. If we make it error out, they stop working. So I think we have to put up with this, and document it in the manual page.
