### ISSUE TITLE
/dev/null: cannot create [Bad file descriptor]

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#483]
Now here's an interesting one:
```
test coprocess begins at 2022-02-08+23:41:52
/usr/local/src/ksh93/ksh/src/cmd/ksh93/tests/coprocess.sh[116]: /dev/null: cannot create [Bad file descriptor]
	coprocess.sh[118]: FAIL: /bin/cat coprocess hung after 'exec 5<&p 6>&p; exec 5<&- 6>&-'
test coprocess failed at 2022-02-08+23:41:56 with exit code 1 [ 33 tests 1 error ]
```
Relevant lines: https://github.com/ksh93/ksh/blob/0af81992ed81cb00af98d8df15d5c3cf76f6833a/src/cmd/ksh93/tests/coprocess.sh#L116-L119 The coprocess didn't hang; the `2>/dev/null` redirection on line 116 somehow failed.

I've never seen this happen before. It's sort of disturbing. My system load was fairly high at the time but nothing too extreme. This test was run with the latest `${.sh.match}` code from #455. I doubt either factor is related but you can never be sure... In any case I'm running those tests in a loop now and I can't manage to reproduce the failure.

----

*(edit)* It just showed up again on my system, without any high system load:
```
test coprocess begins at 2022-04-08+20:30:12
/usr/local/src/ksh93/ksh/src/cmd/ksh93/tests/coprocess.sh[116]: /dev/null: cannot create [Bad file descriptor]
	coprocess.sh[118]: FAIL: /bin/cat coprocess hung after 'exec 5<&p 6>&p; exec 5<&- 6>&-'
test coprocess failed at 2022-04-08+20:30:16 with exit code 1 [ 33 tests 1 error ]
```

----

*(edit)*
````
test coprocess begins at 2022-06-19+22:56:30
/usr/local/src/ksh93/ksh/src/cmd/ksh93/tests/coprocess.sh[116]: /dev/null: cannot create [Bad file descriptor]
	coprocess.sh[118]: FAIL: /bin/cat coprocess hung after 'exec 5<&p 6>&p; exec 5<&- 6>&-'
test coprocess failed at 2022-06-19+22:56:34 with exit code 1 [ 32 tests 1 error ]
````

_Originally posted by @McDutchie in https://github.com/ksh93/ksh/issues/344#issuecomment-1033176367_

**Comment by McDutchie** [comment]
Running the regression test in a loop 10000 times is a fairly reliable way of reproducing the failure on my system. This has allowed me to find the commit that introduced it. It is: ec6639f5

Odd. That commit merely sets `errno` to `EBADF` if `sh_close()` is called with a file descriptor < 0.

**Comment by McDutchie** [comment]
I don't understand how this causes a race condition. But calling `abort()` in the location of the ec6639f5efb38a0029152b6161aa77c7dbf810b9 patch did allow me to trace all the `sh_close()` calls with a negative file descriptor. Those shouldn't be happening in any case. All those `sh_close()` calls were related to co-processes, which this regression test also tests. A co-process pipe that is not in use is set to -1 so we need to avoid calling `sh_close()` if that happened. The following patch does that (as well as making some consistency tweaks) and it makes the race condition go away. Apparently, avoiding setting `errno` to `EBADF` is sufficient for that.
<details>
<summary>Patch</summary>

```diff
diff --git a/src/cmd/ksh93/sh/io.c b/src/cmd/ksh93/sh/io.c
index 5db81ba3e..fc88cb0bc 100644
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1045,9 +1045,9 @@ static Sfoff_t	file_offset(int fn, char *fname)
  */
 void sh_pclose(register int pv[])
 {
-	if(pv[0]>=2)
+	if(pv[0] > -1)
 		sh_close(pv[0]);
-	if(pv[1]>=2)
+	if(pv[1] > -1)
 		sh_close(pv[1]);
 	pv[0] = pv[1] = -1;
 }
diff --git a/src/cmd/ksh93/sh/jobs.c b/src/cmd/ksh93/sh/jobs.c
index 27abc493b..0d55fe9b4 100644
--- a/src/cmd/ksh93/sh/jobs.c
+++ b/src/cmd/ksh93/sh/jobs.c
@@ -396,10 +396,11 @@ int job_reap(register int sig)
 			/* check for coprocess completion */
 			if(pid==sh.cpid)
 			{
-				sh_close(sh.coutpipe);
-				sh_close(sh.cpipe[1]);
-				sh.cpipe[1] = -1;
-				sh.coutpipe = -1;
+				if(sh.coutpipe > -1)
+					sh_close(sh.coutpipe);
+				if(sh.cpipe[1] > -1)
+					sh_close(sh.cpipe[1]);
+				sh.coutpipe = sh.cpipe[1] = -1;
 			}
 			else if(sh.subshell)
 				sh_subjobcheck(pid);
diff --git a/src/cmd/ksh93/sh/path.c b/src/cmd/ksh93/sh/path.c
index e3bda4046..363a1debf 100644
--- a/src/cmd/ksh93/sh/path.c
+++ b/src/cmd/ksh93/sh/path.c
@@ -1275,10 +1275,13 @@ static noreturn void exscript(register char *path,register char *argv[],char **e
 	sh.bckpid = 0;
 	sh.st.ioset=0;
 	/* clean up any cooperating processes */
-	if(sh.cpipe[0]>0)
+	if(sh.cpipe[0] > -1)
 		sh_pclose(sh.cpipe);
-	if(sh.cpid && sh.outpipe)
+	if(sh.cpid && sh.outpipe && *sh.outpipe > -1)
+	{
 		sh_close(*sh.outpipe);
+		*sh.outpipe = -1;
+	}
 	sh.cpid = 0;
 	if(sp=fcfile())
 		while(sfstack(sp,SF_POPSTACK));
diff --git a/src/cmd/ksh93/sh/subshell.c b/src/cmd/ksh93/sh/subshell.c
index 05dbdf2cd..92b2a78a7 100644
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -455,8 +455,10 @@ void sh_subjobcheck(pid_t pid)
 	{
 		if(sp->cpid==pid)
 		{
-			sh_close(sp->coutpipe);
-			sh_close(sp->cpipe);
+			if(sp->coutpipe > -1)
+				sh_close(sp->coutpipe);
+			if(sp->cpipe > -1)
+				sh_close(sp->cpipe);
 			sp->coutpipe = sp->cpipe = -1;
 			return;
 		}
```
</details>

**Comment by posguy99** [comment]
I added a comment to the commit, but I'll also put it here.  I get the same six errors the CI runner does after applying this patch.  macOS 12.4.

**Comment by McDutchie** [comment]
Thanks and sorry for not noticing that before pushing it. That regression was caused by this change in the broken commit:
```diff
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1045,9 +1045,9 @@ static Sfoff_t	file_offset(int fn, char *fname)
  */
 void sh_pclose(register int pv[])
 {
-	if(pv[0]>=2)
+	if(pv[0] > -1)
 		sh_close(pv[0]);
-	if(pv[1]>=2)
+	if(pv[1] > -1)
 		sh_close(pv[1]);
 	pv[0] = pv[1] = -1;
 }
```

I changed that because the original code did not make sense to me (why `=>2`? why close stderr but not stdout or stdin?) but clearly I missed something. In any case, this change is not central to the fix and it'll work without.

**Comment by McDutchie** [comment]
Reproducer for the race condition, reduced as much as I could manage:
```sh
typeset -i i
cat=${ command -pv cat; }
for((i=0;i<20000;i++))
do	printf '\r%d ' "$i"
	ksh |&
	cop=$!
	print -p $'print hello | '$cat$'\nprint '$exp
	read -t 1 -p
	read -t 1 -p
	redirect 5<&p 6>&p 5<&- 6>&-
	{ sleep .4; kill $cop; } &
	spy=$!
	if	wait $cop 2>/dev/null	# "/dev/null: cannot create"?
	then	kill $spy
	else	kill $spy; exit 	# boom
	fi
	wait
done
```
Result on my system. The time it takes to fail varies a lot:
```
$ arch/*/bin/ksh foo
717 foo[13]: /dev/null: cannot create [Bad file descriptor]
$
```

**Comment by McDutchie** [comment]
I think I found the cause of the problem.

errno may get a value during SIGCHLD processing. This may cause the functions called by the signal interrupt to call sh_close() with a negative file descriptor, giving errno the EBADF value as this loop in sh_open() is interrupted: https://github.com/ksh93/ksh/blob/94fc9837b1ada45bbb14b9e2d9a709b80400fc7b/src/cmd/ksh93/sh/io.c#L851-L853

If SIGCHLD is handled between `open()` being interrupted and the check for `errno!=EINTR`, sh_open() will return -1 instead of retrying, causing sh_redirect() to issue the "cannot create" error message.

SIGCHLD is issued whenever a process (such as the coprocess in the reproducer) terminates. job_reap() gets called to handle this. I read the job_reap() code and noticed it does not always save and restore errno. A patch that makes it always save and restore errno seems to fix this issue without regressions.
```diff
diff --git a/src/cmd/ksh93/sh/jobs.c b/src/cmd/ksh93/sh/jobs.c
index 27abc493b..32a6edccb 100644
--- a/src/cmd/ksh93/sh/jobs.c
+++ b/src/cmd/ksh93/sh/jobs.c
@@ -291,7 +291,7 @@ int job_reap(register int sig)
 	struct process *px;
 	register int flags;
 	struct jobsave *jp;
-	int nochild=0, oerrno, wstat;
+	int nochild = 0, oerrno = errno, wstat;
 	Waitevent_f waitevent = sh.waitevent;
 	static int wcontinued = WCONTINUED;
 	int was_ttywait_on;
@@ -312,7 +312,6 @@ int job_reap(register int sig)
 	else
 		flags = WUNTRACED|wcontinued;
 	sh.waitevent = 0;
-	oerrno = errno;
 	was_ttywait_on = sh_isstate(SH_TTYWAIT); /* save tty wait state */
 	while(1)
 	{
@@ -478,7 +477,6 @@ int job_reap(register int sig)
 	}
 	if(errno==ECHILD)
 	{
-		errno = oerrno;
 #if SHOPT_BGX
 		job.numbjob = 0;
 #endif /* SHOPT_BGX */
@@ -494,6 +492,7 @@ int job_reap(register int sig)
 	}
 	if(sig)
 		signal(sig, job_waitsafe);
+	errno = oerrno;
 	return(nochild);
 }

```
