### ISSUE TITLE
Tab completion can cause vi mode to switch to "control"

### ISSUE THREAD

**Issue by pghvlaans** [ksh93/ksh#485]
This might be a corner case, but it's a little strange. Attempting to tab-complete the only member of a directory while in vi mode switches to "control" under the following conditions:

1. `pwd` is outside of the directory
2. No part of the basename has been typed in (e.g., starting with `vim TEST/t` will autocomplete to `vim TEST/test`, but starting with `vim TEST/` will not).

Also, trying to type with "input" or "replace" fails afterwards until a new line has been generated (either with `ctrl + c` or the `j/k` keys in control mode). That makes me wonder whether it might be a termios-related issue, but emacs mode works fine for some reason.

OS: Slackware64-15.0
ksh: Commit [cc16898](https://github.com/ksh93/ksh/commit/cc1689849eaba2abf721c742a1be26ff79f54b50) (1.0 branch)

EDIT
The behavior seems to be the same on `xterm`, `urxvt`, `konsole` and `xfce4-terminal`.

**Comment by McDutchie** [comment]
Yes, this is a bug in the vi line editor. I can reproduce it on macOS as well, so it seems to be a portable bug.

**Comment by McDutchie** [comment]
This bug was introduced somewhere between 93u+ 2012-02-29 and 93u+ 2012-05-17. So hopefully we can identify the change in the ksh93-history repo that introduced the bug.
