### ISSUE TITLE
OPTIND not initialised correctly on Solaris/SPARC when compiled with gcc

### ISSUE THREAD

**Issue by tapas118** [ksh93/ksh#515]
While running the default test on Solaris machine, I am getting the following error.

-bash-5.1$ bin/package test
package: test output captured in /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/lib/package/gen/test.out
package: test start at Mon Aug 15 23:47:14 PDT 2022 in /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64
+ mamake -r '*/*' test
+ mamake -C cmd/INIT test
+ exec /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/regress /builds2/tapapate/ksh1_0_2/ksh-1.0.2/src/cmd/INIT/iffe.tst iffe
/builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/regress[1375]: shift: 0-1: bad number
mamake [cmd/INIT]: *** exit code 1 making test.iffe
mamake: *** exit code 1 making cmd/INIT
mamake: *** exit code 1 making all
package: test failed at Mon Aug 15 23:47:14 PDT 2022 in /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64
-bash-5.1$

**Comment by McDutchie** [comment]
I cannot reproduce this. It works normally on my end on Solaris 11.4 (i386-64).

I am going to need more information to figure out what is triggering this bug.

Somehow, on line 1375 in bin/regress, OPTIND has value 0. That should not be happening, it should be at least 1. So we need to figure out why that is.

It looks like you're running Solaris on a SPARC machine. Unfortunately I do not have access to one, so I cannot do any testing and I currently have no clue where to begin looking for the cause of this problem.

What compiler are you using to build ksh? What is the value of your CC and CCFLAGS variables while building ksh?

**Comment by McDutchie** [comment]
Also, does running `bin/shtests -p` work? If so, do you get any regression test failures from it?

**Comment by tapas118** [comment]
As mentioned in the Readme.md file for solaris studio, I have executed the following commands

export CCFLAGS="-m64 -O" LDFLAGS="-m64"
bin/package make

And the CC  is cc and CCFLAGS is "-m64 -O".

Compiler version:-
bash-5.1$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/gcc/11/lib/gcc/sparcv9-sun-solaris2.11/11.3.0/lto-wrapper
Target: sparcv9-sun-solaris2.11
Configured with: /builds/ulhg/mrcarson-trunk_127/components/gcc11/gcc-11.3.0/configure --prefix=/usr/gcc/11 --mandir=/usr/gcc/11/share/man --bindir=/usr/gcc/11/bin --sbindir=/usr/gcc/11/sbin --libdir=/usr/gcc/11/lib --infodir=/usr/gcc/11/share/info --libexecdir=/usr/gcc/11/lib --enable-languages=ada,c,c++,fortran,go,objc --enable-shared --enable-initfini-array --disable-rpath --with-system-zlib --with-build-config=no --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/usr/gnu/bin/as --disable-bootstrap ‘BOOT_CFLAGS=-g -O2’ sparcv9-sun-solaris2.11
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.3.0 (GCC)
-bash-5.1$

bin/shtests -p also failing with the following logs.

-bash-5.1$ bin/shtests -p
#### Regression-testing /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh ####
shtests[215]: shift: 0-1: bad number
-bash-5.1$

**Comment by McDutchie** [comment]
Just to confirm what seems to be going on, could you post the output of these commands on your system? In both cases the output should be `1` -- OPTIND should be initialised to 1 regardless of its value in the environment. If it's not, then an unusable ksh binary is built on your system.
```sh
/builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh -c 'print $OPTIND'
OPTIND=0 /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh -c 'print $OPTIND'
```

**Comment by tapas118** [comment]
In both cases it's printing 0.

-bash-5.1$ /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh -c 'print $OPTIND'
0
-bash-5.1$ OPTIND=0 /builds2/tapapate/ksh1_0_2/ksh-1.0.2/arch/sol11.sun4-64/bin/ksh -c 'print $OPTIND'
0
-bash-5.1$

**Comment by McDutchie** [comment]
Thanks.

This is a fatal bug. Apparently we cannot currently build a functioning ksh on SPARC hardware.

Unfortunately, without access to SPARC hardware (or a shell account on same) I have no way of figuring out what the problem is. Do you have any idea where I could get a shell account on a SPARC machine running Solaris?

I'll also write to the Solaris ksh maintainers to ask if one of them might be able to help.

**Comment by tapas118** [comment]
On X86 architecture OPTIND value is correctly set to 1. So it looks like endianness issue.

**Comment by McDutchie** [comment]
That thought had crossed my mind, but it works fine on PowerPC-based Macs, which is also a big-endian architecture.

**Comment by tapas118** [comment]
After changing the compiler to Oracle Studio, OPTIND value is initialised to 1.

-bash-5.1$ arch/sol11.sun4-64/bin/ksh 'print $OPTIND'
1
-bash-5.1$

**Comment by McDutchie** [comment]
> After changing the compiler to Oracle Studio, OPTIND value is initialised to 1.

That's encouraging. What are the results when you attempt to run the regression tests on a ksh compiled with Oracle Studio? (using both `bin/shtests -p` and `bin/package test`)

**Comment by tapas118** [comment]
Please find the regression test reports at below.

bin/package test report:-

Total errors: 0
CPU time       user:      system:
main:      0m00.239s    0m00.231s
tests:     2m32.764s    3m15.304s
package: test done at Fri Aug 26 02:31:26 PDT 2022 in /builds2/tapapate/ksh3/ksh-1.0.2/arch/sol11.sun4-64

bin/shtests -p report:-

Total errors: 0
CPU time       user:      system:
main:      0m00.091s    0m00.086s
tests:     0m49.610s    1m04.101s
-bash-5.1$

**Comment by oliwer** [comment]
Could this be a GCC optimization issue? You could try compiling ksh again using `-O0` to see if it changes anything.

**Comment by tapas118** [comment]
I have prepared the binary with GCC compiler using -O0 and the result is same as earlier.

-bash-5.1$ arch/sol11.sun4-64/bin/ksh 'print $OPTIND'
0
-bash-5.1$

**Comment by McDutchie** [comment]
Since there is no one who is willing to give me access to a solaris/sparc test machine with gcc, there's nothing I can do about it. Since it works fine with Oracle Studio cc on that system and also works fine with gcc on every other system, I can only assume that gcc is broken on that system. This is up to Oracle employees to figure out and fix.
