### ISSUE TITLE
ksh hangs forever if `HISTSIZE` has a large value

### ISSUE THREAD

**Issue by GabrielRavier** [ksh93/ksh#522]
When `int` is the same as `int32_t`, starting ksh with `HISTSIZE=2000000000` in the environment (or any number between `1073741824` and `2147483647`) results in an infinite loop, because of this code:
```cpp
        if(cp=nv_getval(HISTSIZE))
                maxlines = (unsigned)strtol(cp, (char**)0, 10);
        else
                maxlines = HIST_DFLT;
        for(histmask=16;histmask <= maxlines; histmask <<=1 );
```

which gets stuck infinitely because `histmask <= maxlines` will always be true (after 26 iterations, `histmask == 1073741824`, after 27 iterations, `histmask == -2147483648` and after more than 28 iterations it's stuck at `0`).

Note that this is not a purely hypothetical situation and that this actually happened to me as my `~/.bashrc` contains this:
```bash
export HISTFILESIZE=2000000000
export HISTSIZE=2000000000
export HISTFILE=~/.bash_infinite_history
shopt -s histappend
```
(which also happened to get ksh to erase my history file, at least now I know not to `export` these...)

(PS: I should also note that setting `HISTSIZE` to a smaller number that does end the loop (e.g. `200000000`) instead results in ksh eating a monstrous amount of memory (which almost forced me to restart my system...), while bash manages to work without any problems with my larger history size...)

**Comment by McDutchie** [comment]
Thanks for the report! Clearly there is a missing bounds check there. Considering this comment:

https://github.com/ksh93/ksh/blob/76babdbb0c6816f41582125883955c64ed3bac69/src/cmd/ksh93/edit/history.c#L194

…the theoretical maximum number of lines (i.e.: each line being empty, consisting only of a terminating 0 byte) is also `HIST_MAX`. This is 16384 on a system where sizeof(int)==4: https://github.com/ksh93/ksh/blob/76babdbb0c6816f41582125883955c64ed3bac69/src/cmd/ksh93/edit/history.c#L41 https://github.com/ksh93/ksh/blob/76babdbb0c6816f41582125883955c64ed3bac69/src/cmd/ksh93/edit/history.c#L48

So the following patch is probably the best we can easily do (i..e., without redesigning the history mechanism).

```diff
diff --git a/src/cmd/ksh93/edit/history.c b/src/cmd/ksh93/edit/history.c
index 574034a84..89c9e5d80 100644
--- a/src/cmd/ksh93/edit/history.c
+++ b/src/cmd/ksh93/edit/history.c
@@ -257,7 +257,14 @@ retry:
 	/* set the file to close-on-exec */
 	fcntl(fd,F_SETFD,FD_CLOEXEC);
 	if(cp=nv_getval(HISTSIZE))
-		maxlines = (unsigned)strtol(cp, (char**)0, 10);
+	{
+		intmax_t m = strtoll(cp, (char**)0, 10);
+		if(m>HIST_MAX)
+			m = HIST_MAX;
+		else if(m<0)
+			m = HIST_DFLT;
+		maxlines = (int)m;
+	}
 	else
 		maxlines = HIST_DFLT;
 	for(histmask=16;histmask <= maxlines; histmask <<=1 );
```
