### ISSUE TITLE
sysctl: cannot stat /proc/sys/kern/consdev: No such file or directory

### ISSUE THREAD

**Issue by Piscium** [ksh93/ksh#539]
First of all a word of thanks to the ksh93u+m developers as well as all the contributors of patches and such.

I am on Arch. I downloaded the 1.0.3 tar file and ran:
bin/package make

ksh was built without errors and without any special configuration. However when I call ksh I get:
sysctl: cannot stat /proc/sys/kern/consdev: No such file or directory

ksh still works though. Any idea how I can get rid of that warning, and if it is relevant?

below is the strace output, in case it helps. I did not install ksh, instead I ran it as myself (not root). I created a one line shell script called 'k' that calls ksh.

gcc --version
gcc (GCC) 12.2.0

glibc Version: 2.36-4

P. S. Markdown is doing funny things to the trace below but apparently there is no way to disable it.

-----------

strace k
execve("/home/myself/bin/k", ["k"], 0x7ffc965e7580 /* 66 vars /) = 0
brk(NULL) = 0x5611a5e38000
arch_prctl(0x3001 / ARCH_??? /, 0x7ffd555526f0) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=227831, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 227831, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9389026000
close(3) = 0
openat(AT_FDCWD, "/usr/lib/libedit.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \220\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=223144, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9389024000
mmap(NULL, 240792, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f9388fe9000
mprotect(0x7f9388ff2000, 180224, PROT_NONE) = 0
mmap(0x7f9388ff2000, 118784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7f9388ff2000
mmap(0x7f938900f000, 57344, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f938900f000
mmap(0x7f938901e000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x34000) = 0x7f938901e000
mmap(0x7f9389021000, 11416, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f9389021000
close(3) = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P4\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1953472, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1994384, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f9388e02000
mmap(0x7f9388e24000, 1421312, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f9388e24000
mmap(0x7f9388f7f000, 356352, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17d000) = 0x7f9388f7f000
mmap(0x7f9388fd6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d4000) = 0x7f9388fd6000
mmap(0x7f9388fdc000, 52880, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f9388fdc000
close(3) = 0
openat(AT_FDCWD, "/usr/lib/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=470232, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 474344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f9388d8e000
mprotect(0x7f9388da4000, 364544, PROT_NONE) = 0
mmap(0x7f9388da4000, 266240, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7f9388da4000
mmap(0x7f9388de5000, 94208, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x57000) = 0x7f9388de5000
mmap(0x7f9388dfd000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6e000) = 0x7f9388dfd000
close(3) = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9388d8b000
arch_prctl(ARCH_SET_FS, 0x7f9388d8b740) = 0
set_tid_address(0x7f9388d8ba10) = 456455
set_robust_list(0x7f9388d8ba20, 24) = 0
rseq(0x7f9388d8c060, 0x20, 0, 0x53053053) = 0
mprotect(0x7f9388fd6000, 16384, PROT_READ) = 0
mprotect(0x7f9388dfd000, 16384, PROT_READ) = 0
mprotect(0x7f938901e000, 8192, PROT_READ) = 0
mprotect(0x5611a53c1000, 8192, PROT_READ) = 0
mprotect(0x7f938908f000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=81921024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f9389026000, 227831) = 0
getpid() = 456455
rt_sigaction(SIGCHLD, {sa_handler=0x5611a53b5400, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f9388e3aa00}, NULL, 8) = 0
geteuid() = 1000
getrandom("\xf4\xa4\xea\xd6\xcd\x6c\xc4\xf1", 8, GRND_NONBLOCK) = 8
brk(NULL) = 0x5611a5e38000
brk(0x5611a5e59000) = 0x5611a5e59000
getppid() = 456452
newfstatat(AT_FDCWD, "/home/myself/develt/ksh-1.0.3", {st_mode=S_IFDIR|0775, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0775, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/home/myself/bin/k", O_RDONLY) = 3
fcntl(3, F_DUPFD, 10) = 10
close(3) = 0
fcntl(10, F_SETFD, FD_CLOEXEC) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x5611a53b5400, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f9388e3aa00}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f9388e3aa00}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f9388e3aa00}, NULL, 8) = 0
read(10, "#!/bin/sh\n/home/myself/develt/ksh"..., 8192) = 66
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], NULL, 8) = 0
vfork() = 456456
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
wait4(-1, sysctl: cannot stat /proc/sys/kern/consdev: No such file or directory
myself:/home/myself/develt/ksh-1.0.3:30$

**Comment by JohnoKing** [comment]
I cannot reproduce this problem on Arch Linux using a bare-bones install and my usual installation. Ksh does not directly use anything under /proc/sys during runtime, so my only guess is something probably **is** wrong with your configuration, likely in /etc/profile or in one of the scripts under /etc/profile.d (or kshrc). Does the problem still occur when using `ENV=/dev/null`, i.e.:
```sh
#!/bin/sh
ENV=/dev/null /home/myself/develt/ksh
```

**Comment by McDutchie** [comment]
Also, invoking ksh as `ksh -x` may help you see what gets executed by the startup scripts.

**Comment by Piscium** [comment]
> I cannot reproduce this problem on Arch Linux using a bare-bones install and my usual installation. Ksh does not directly use anything under /proc/sys during runtime, so my only guess is something probably **is** wrong with your configuration, likely in /etc/profile or in one of the scripts under /etc/profile.d (or kshrc). Does the problem still occur when using `ENV=/dev/null`, i.e.:

Thanks a lot. Problem solved.

Setting ENV had no effect, however your other suggestion of looking at kshrc helped. For some context, I am looking at ksh in general so I have several versions of ksh installed, to compare. It turns out that oksh (from the AUR) installs...

/etc/ksh.kshrc

which includes...

console=$(sysctl kern.consdev)  
console=${console#*=}

That was the cause of the warning. Funny enough, of the several ksh implementations I have installed, only ks93u+m issued the warning.

Going a bit off-topic, do you have a PKGBUILD you could share? I might create one myself someday but not yet.

**Comment by Piscium** [comment]
> Also, invoking ksh as `ksh -x` may help you see what gets executed by the startup scripts.

Thanks, that helped find the solution.

**Comment by JohnoKing** [comment]
> Going a bit off-topic, do you have a PKGBUILD you could share? I might create one myself someday but not yet.

As it so happens I recently adopted the orphaned ksh93-git package and updated it to use the 93u+m dev branch instead of 93u+: https://aur.archlinux.org/packages/ksh93-git
There is no package with the stable release (v1.0.3) at the moment because the [ksh](https://archlinux.org/packages/community/x86_64/ksh/) package is still on ksh2020 for some reason. If you want to make a PKGBUILD for v1.0.3, I suggest you base it on the ksh93-git PKGBUILD.

**Comment by Piscium** [comment]
I had previously checked the ksh93-git package and noticed it was orphaned and pointing to the old version. Good that you have adopted it. I will use either your git package or create one for 1.03. As for the official Arch ksh package, I thought of sending an email to its maintainer suggesting to use this repo instead as source, but haven't done it yet.

Thanks again, I will mark this issue as solved.
