### ISSUE TITLE
Should `/dev/` be treated specially by `test -e`?

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#548]
This is a problem I ran into on Haiku, where the in the following regression tests the checks for `/dev/xxx/` and `/dev/fd/` wrongly succeed (and apparently the check for `/dev/fd` is supposed to succeed, even if it doesn't actually exist):
https://github.com/ksh93/ksh/blob/d84067a00161262f492be1836fcd64f2dd9f7d67/src/cmd/ksh93/tests/bracket.sh#L334-L337
```
test bracket(C.UTF-8) begins at 2022-10-01+16:54:51
        bracket.sh[75]: warning: running as root: skipping tests involving r/w permissions
        bracket.sh[337]: FAIL: /dev/xxx/ exists
test bracket(C.UTF-8) failed at 2022-10-01+16:54:53 with exit code 1 [ 158 tests 1 error ]
```

The cause of the test failure is the if statement preceeding the call to `permission()` when handling `-e`:
https://github.com/ksh93/ksh/blob/d84067a00161262f492be1836fcd64f2dd9f7d67/src/cmd/ksh93/bltins/test.c#L445-L447

This change was an intentional addition in ksh93u- 2010-08-26 (https://github.com/ksh93/ast-open-archive/commit/f21d0d8cfe18ff812586221514325ce6b3d02f49). The relevant changelog entry is as follows:
https://github.com/ksh93/ksh/blob/d84067a00161262f492be1836fcd64f2dd9f7d67/src/cmd/ksh93/RELEASE#L666-L667

My question is if this addition even makes sense, and if there's a valid use case for it. I don't see any reason why checking for, say, `/dev/fd` should succeed if that feature isn't supported by the operating system (on Haiku I'd expect the test for `/dev/fd` to fail). The feature 93u- added seems to be inherently broken.

**Comment by McDutchie** [comment]
> The feature 93u- added seems to be inherently broken.

Agreed. A `test`/`[`/`[[` result should be valid to determine if a certain file system path can be used with an external utility, not just the shell. E.g., on AIX (and presumably on Haiku) we get:
```
$ test -e /dev/fd/0 && cat /dev/fd/0
cat: /dev/fd/0: No such file or directory
```
…which should *never* happen. It's yet another instance where they broke the basic paradigm. And, as usual, they didn't even break it consistently -- `test -e` does not work for /opt/ast/bin builtins.

This misfeature is so wrong and broken I think it should be fixed for 1.0.4 as well, even though it's been around for 12 years now, so fixing it may actually break some scripts. On the other hand, it's undocumented except for the RELEASE file, so it probably went mostly unnoticed. I'll have to add a note to the `COMPATIBILITY` file in any case.

Between this and all the other breakage we're still finding, I'm starting to regret releasing 1.0 when I did. Nonsense like this has no business being in a release version. \<sigh>

For completeness' sake: the correct way to test for the existence of this shell functionality is simply to try it and handle errors, e.g., test the exit status of `echo yes | { read devfd </dev/fd/3; } 3<&0 2>dev/null` which will return successfully and set `devfd` to `yes` if /dev/fd/3 is supported by either the shell or the kernel.
