### ISSUE TITLE
Backspacing past backslash in vi mode is broken in two ways

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#56]
This bug was signalled and videoed by @saper in https://github.com/ksh-community/ksh/issues/8#issuecomment-605896180 and the subsequent comment. [Video 1](https://asciinema.org/a/E3Rq3et07MMQG5BaF7vkXQTg0?autoplay=1); [video 2](https://asciinema.org/a/314833?autoplay=1) (see also instructions there).

The entire https://github.com/ksh-community/ksh/issues/8 thread contains background information worth reading.

Note that the first variant of this bug also applies to raw POSIX (neither vi nor emacs) editing mode if a UTF-8 locale is active, as this raw editing mode is handled by edit/vi.c in that case.

**Comment by JohnoKing** [comment]
The second bug can be replicated with other characters (although without the odd phenomena with `^?`):

```
$ set -o vi
$ a:aaa <ESC> <Shift-T> <:> <Shift-C> <i * 2> <Backspace * 3>
```

**Comment by McDutchie** [comment]
After examining the behaviour of various vi(1) implementations I'm now not convinced that the second bug is actually a bug (apart, of course, from the wrong behaviour with backslashes and `^?`). The only vi(1) implementation I've found that allows you to backspace past where you originally pressed Shift-C is vim. POSIX [specifies](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html#tag_20_152_13_49) that Shift-C (which is the same as c$) uses a separate unnamed buffer, so this makes sense. Vim deliberately breaks with vi on certain points, presumably including this one, but ksh's vi mode should emulate vi and not vim.
