### ISSUE TITLE
ksh leaves invoked hist -e line on screen after ^X^E

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#563]
I think this is historical, more of a "why" kind of thing...

`ksh` leaves the `hist -e` invocation on the screen after the round-trip through the editor. when invoked with ^X^E.

Example:

```
$ echo $KSH_VERSION
Version AJM 93u+m/1.1.0-alpha+4a2801b6 2022-10-14
$ 
```

(use ^X^E, make a round trip through the editor, in my case qemacs)

```
$ \hist -e "${VISUAL:-${EDITOR:-vi}}" 777
echo $KSH_VERSION
Version AJM 93u+m/1.1.0-alpha+4a2801b6 2022-10-14
$ 
```

None of `zsh`, `bash`, `mksh` (which has to be weird and use ^Xe), leave the `hist -e` invocation lying there.

`ksh` *doesn't* insert the `hist -e` into the history file, but can leave debris:

```
[787] mbp13 $ history
...
787	history
[10:26 AM][ttys001 +2][~]
[788] mbp13 $ \hist -e "${VISUAL:-${EDITOR:-vi}}" 788
[10:26 AM][ttys001 +2][~]
[789] mbp13 $ history
...
787	history
788	789	history
[10:27 AM][ttys001 +2][~]
[790] mbp13 $
```

[788] is a null command left behind by the `hist -e`. ^_^

**Comment by McDutchie** [comment]
I've no opinion on whether the hist -e command should be echoed, but that null command in the history is certainly a bug.

**Comment by posguy99** [comment]
I think it shouldn't echo it, because none of the other shells do.  Well, of the three I tested.

If it consumes a history entry, it should actually be in the history, and it isn't.  But it shouldn't consume a history entry, either, and it does.

🤷‍♂️

**Comment by posguy99** [comment]
The null can easily be created.

```
[868] mbp13 $ ^x^e

(editor opens, exit editor with no input)

[869] mbp13 $ history | tail -1
868	869	history | tail -1
[870] mbp13 $ 
```

I got `mksh` to insert a blank line (vs a null) into the history with the same sequence.

**Comment by McDutchie** [comment]
Thank you very much for this PR which fixes multiple bugs!

**Comment by posguy99** [comment]
The blank line is still in the history and the editor invocation is still echoed to the screen.  I applaud the bug fixes, but...

**Comment by McDutchie** [comment]
I will look at this later when I have some time.

**Comment by McDutchie** [comment]
I am not convinced that the shell repeating the edited line is a bug. I tested this on mksh, bash, and zsh, and they all do it too.

When you empty the file and save, an empty history entry is created. mksh also does this, but bash and zsh don't – it also doesn't seem useful. So I might fix that.

**Comment by posguy99** [comment]
It's not that it leaves the edited line, it's that it leaves the **invocation** of the editor on the screen, but it is not in the history.  I don't think it should put the editor invocation in the history, I think it shouldn't be on the screen.

I know why `ksh` does it, it fakes text input of the invocation, with conditioning so it doesn't go into the history.  I don't know how the others do it.

**Comment by McDutchie** [comment]
I don't see any invocation of the editor left on the screen. Do you mean the `hist -e` command that you typed? If so, why should it not leave that on the screen?

**Comment by posguy99** [comment]
I didn't type it.  `ksh` invokes $EDITOR by forcing that line into the input buffer.

If I had typed it, I would expect it to be in the history.  I hit ^X^E on an existing line.

Is there even one of the Bourne-ish shells that leaves that line on the screen? `bash`, `zsh`, `mksh` don't leave it there.  `oksh` and `pdksh` (which are really the same thing, I know) don't.

**Comment by McDutchie** [comment]
> I didn't type it. `ksh` invokes $EDITOR by forcing that line into the input buffer.
> 
> If I had typed it, I would expect it to be in the history. I hit ^X^E on an existing line.

Now the penny has dropped. Sorry about that, I'm just thick sometimes.

**Comment by McDutchie** [comment]
BTW, `fc`/`hist` commands that edit a history line don't go into the history themselves even if you type them, this is intended.

**Comment by McDutchie** [comment]
> I didn't type it. `ksh` invokes $EDITOR by forcing that line into the input buffer.

Yes, that is exactly what it does, in the ed_fulledit function. So it is in fact as if you had typed it yourself. To avoid echoing it I would have to use a completely different method of invoking the editor, which is nontrivial. https://github.com/ksh93/ksh/blob/11f38783570193846b2eb48063c1eb85aeb10a9a/src/cmd/ksh93/edit/completion.c#L614-L643

**Comment by posguy99** [comment]
I was reading through `mksh` edit.c, but I don't even see where its equivalent `x_edit_line` even ever gets called, but there must be somewhere, because it works.

https://github.com/MirBSD/mksh/blob/master/edit.c

**Comment by McDutchie** [comment]
Try this patch, it seems to work for me:
```diff
diff --git a/src/cmd/ksh93/edit/completion.c b/src/cmd/ksh93/edit/completion.c
index 633db23e1..7d61c54ea 100644
--- a/src/cmd/ksh93/edit/completion.c
+++ b/src/cmd/ksh93/edit/completion.c
@@ -633,13 +633,9 @@ int ed_fulledit(Edit_t *ep)
 		sh_onstate(SH_HISTORY);
 		hist_flush(sh.hist_ptr);
 	}
-	cp = strcopy((char*)ep->e_inbuf,e_runvi);
-	cp = strcopy(cp, fmtbase((intmax_t)ep->e_hline,10,0));
-#if SHOPT_VSH
-	ep->e_eol = ((unsigned char*)cp - (unsigned char*)ep->e_inbuf)-(sh_isoption(SH_VI)!=0);
-#else
-	ep->e_eol = ((unsigned char*)cp - (unsigned char*)ep->e_inbuf);
-#endif
+	sfprintf(sh.strbuf,e_runvi,ep->e_hline-1);
+	sh_trap(sfstruse(sh.strbuf),0);
+	ep->e_inbuf[ep->e_eol=0]=0;
 	return 0;
 }
 
```

**Comment by posguy99** [comment]
The $EDITOR invocation is no longer displayed, but the behavior of the shell is different before and after the patch.

Before the patch...

`$ pwd

/Users/mwilson/src/posguy99/ksh

$ ls

ANNOUNCE         LICENSE.md       README.md        arch/            docs/            src/

COPYRIGHT        NEWS             TODO             bin/             pty_patch.patch

$ \hist -e "${VISUAL:-${EDITOR:-vi}}" 55



$ `


The editor invocation line is displayed, ^X^E did not retrieve the previous command, came back to a prompt.

After the patch...

`$ 

$ pwd

/Users/mwilson/src/posguy99/ksh

$ ver

ksh: Version AJM 93u+m/1.1.0-alpha+b743f4c3/MOD 2023-03-24

$ ls

ANNOUNCE         LICENSE.md       README.md        arch/            docs/            src/

COPYRIGHT        NEWS             TODO             bin/             pty_patch.patch

ls

ANNOUNCE         LICENSE.md       README.md        arch/            docs/            src/

COPYRIGHT        NEWS             TODO             bin/             pty_patch.patch



$ `


The editor invocation line is not displayed, but ^X^E brought the previous history line (the `ls`) into the editor, and submitted it again for execution when the editor was exited.

If you ^X^E on an existing line, the behavior in both is the same, just one displays the invocation and the other does not.

-- 
Marc Wilson
***@***.***

**Comment by McDutchie** [comment]
> The $EDITOR invocation is no longer displayed, but the behavior of the shell is different before and after the patch.

Yeah, I figured out it was broken about half an hour after I posted it, so I deleted it.
