### ISSUE TITLE
Remove inheritance of variable attributes via `A__z` env var

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#566]
This misfeature should go the way of exported aliases (present in ksh88, removed in ksh93).

Variable attribute inheritance for newly invoked scripts rarely (if ever) seems to be used intentionally, but does sometimes cause real problems for scripts in child processes that use the same variable names as variables exported by the scripts invoking them. E.g., if the parent does `integer SOMEVAR; export SOMEVAR`, then the child script will probably not expect `SOMEVAR` to be of an integer type without it having declared it as such.

This was kept in 1.0 for compatibility reasons (and disabled in posix mode) but should be removed as of 1.1.

The environment is for communicating environment variables from parent to child via simple string values. Doing anything more complicated with it is a mistake.

Ref.: 00d439605f2ff0f10883f4ba235594a143869731, 7954855f21145112599e4a66ae199693e4313453

**Comment by ormaaj** [comment]
That is hilarious! I never noticed `A__z`

**Comment by McDutchie** [comment]
The only mention of this in the original ksh man page is this one sentence: "Exported variables pass values and attributes to the environment." I've never seen it mentioned or documented anywhere else.
