### ISSUE TITLE
macOS: Build failure (complaining about missing libmd.dylib)

### ISSUE THREAD

**Issue by pghvlaans** [ksh93/ksh#567]
macOS Monterey, Version 12.6. (recently uninstalled `xcode`, if that matters)

Running `IFFEFLAGS=-d1 bin/package make` failed, saying that `libmd.dylib` could not be found:

    iffe: test: output{ ... }end ...
    dyld[40642]: Library not loaded: '/usr/lib/libmd.dylib'
      Referenced from: '/Users/jimu/KSH/ksh/arch/darwin.i386-64/src/cmd/builtin/40461.exe'
      Reason: tried: '/Users/jimu/KSH/ksh/arch/darwin.i386-64/lib/libmd.dylib' (no such file), '/usr/lib/libmd.dylib' (no such file), 
    '/usr/local/lib/libmd.dylib' (no such file)
    iffe: line 496: 40642: Abort
    iffe: ... 
    iffe: test: output{ ... }end ...
    dyld[40656]: Library not loaded: '/usr/lib/libmd.dylib'
      Referenced from: '/Users/jimu/KSH/ksh/arch/darwin.i386-64/src/cmd/builtin/40461.exe'
      Reason: tried: '/Users/jimu/KSH/ksh/arch/darwin.i386-64/lib/libmd.dylib' (no such file), '/usr/lib/libmd.dylib' (no such file), 
    '/usr/local/lib/libmd.dylib' (no such file)
    iffe: line 496: 40656: Abort
    iffe: ... 
    iffe: Output block failed to compile. Export IFFEFLAGS=-d1 to debug.
    mamake [cmd/builtin]: *** exit code 1 making FEATURE/pty
    mamake: *** exit code 1 making cmd/builtin
    mamake: *** exit code 1 making all
    package: make failed at Sun Oct 23 11:24:11 JST 2022 in /Users/jimu/KSH/ksh/arch/darwin.i386-64

I'm attaching the full `make.out` in case there's anything else of interest.
[make.out.txt](https://github.com/ksh93/ksh/files/9845632/make.out.txt)

**Comment by pghvlaans** [comment]
Probably a false alarm: I set up a clean VM, installed `homebrew` and everything built fine. I imagine I made some kind of mistake when uninstalling the graphical frontend for `xcode`.

Please feel free to close.

**Comment by McDutchie** [comment]
FWIW, you don't need Homebrew to build ksh; all you need is the command line development tools that you can install using `xcode-select --install`.

**Comment by McDutchie** [comment]
This is actually a valid issue – same as #596.
