### ISSUE TITLE
Build version for executing scripts only

### ISSUE THREAD

**Issue by HansH111** [ksh93/ksh#570]
Is it possible to build a ksh version for executing scripts only.
so without emacs or vi or any interactive usage.

**Comment by pghvlaans** [comment]
The line editors can be disabled by switching `VSH` and `ESH` to `0` in `src/cmd/ksh93/SHOPT.sh`. I don't think there are any options to build a completely non-interactive binary, though.

**Comment by JohnoKing** [comment]
As previously stated, the line editor modes can both be disabled during compile time. As for creating a completely non-interactive binary, I don't think that is feasible or desirable. Even when ksh is never launched in interactive mode, some degree of interactivity may be required when running scripts (such as for the `read` builtin). Building a completely non-interactive binary would likely cause a large number of scripts to break.

**Comment by HansH111** [comment]
Yes that is what I thought I could do, but somehow the ESH=0 is breaking of compilation

```
+ cc -D_AST_ksh_release '-DSHOPT_2DMATCH=1' '-DSHOPT_ACCT=0' '-DSHOPT_AUDIT=0' '-DSHOPT_BGX=1' '-DSHOPT_BRACEPAT=1' '-DSHOPT_DYNAMIC=1' '-DSHOPT_EDPREDICT=0' '-DSHOPT_ESH=0' '-DSHOPT_FILESCAN=1' '-DSHOPT_FIXEDARRAY=1' '-DSHOPT_HISTEXPAND=0' '-DSHOPT_KIA=0' '-DSHOPT_MULTIBYTE=0' '-DSHOPT_NAMESPACE=1' '-DSHOPT_NOECHOE=0' '-DSHOPT_OPTIMIZE=1' '-DSHOPT_PFSH=0' '-DSHOPT_RAWONLY=1' '-DSHOPT_REMOTE=0' '-DSHOPT_STATS=0' '-DSHOPT_SUID_EXEC=1' '-DSHOPT_SYSRC=0' '-DSHOPT_TYPEDEF=1' '-DSHOPT_VSH=0' -no-pie -s -fPIC -m64 -D_AST_ICONV -s -static -L. -L/root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib -o ksh pmain.o libshell.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libdll.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libcmd.a -lutil /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a -lutil /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a /root/git_remote/kshbuild/ksh-master/arch/linux.i386-64/lib/libast.a
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: libshell.a(edit.o): in function `ed_putstring':
edit.c:(.text+0x7b8): undefined reference to `ed_putchar'
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: libshell.a(edit.o): in function `ed_nputchar':
edit.c:(.text+0x7f9): undefined reference to `ed_putchar'
collect2: error: ld returned 1 exit status
```

Seems it always requires the ESH option to be set

**Comment by pghvlaans** [comment]
I just now managed to get it built without `ESH` and `VSH` by moving the `#endif` line at `src/cmd/ksh93/edit/edit.c:802` to `815` (just after the function `ed_nputchar`). Can you give that a try?

**Comment by HansH111** [comment]
Yes, that works just fine.
thx

**Comment by McDutchie** [comment]
That's a bug in the preprocessor directives that should be fixed.

**Comment by McDutchie** [comment]
The closest we can currently get to your request is disabling SHOPT_ESH, SHOPT_VSH and SHOPT_HISTEXPAND.

Your feature request is interesting and I'll consider it. It shouldn't require disabling the `read` built-in which is not actually concerned with any interactive state of the shell. It should be possible to add SHOPT_INTERACTIVE which, when disabled, compiles out the PS1 and PS2 prompts, the history mechanism, and anything that is only run when sh_is{option,state}(SH_INTERACTIVE).

**Comment by McDutchie** [comment]
@HansH111, [here](/ksh93/ksh/commit/28021c06949439f15a5d0e97eaf49541108de4a7)'s a proper `SHOPT_SCRIPTONLY` compile-time option. Enjoy!
