### ISSUE TITLE
vi mode: invalid character output when tabbing from a wide character

### ISSUE THREAD

**Issue by pghvlaans** [ksh93/ksh#571]
EDIT: Please see [this comment](https://github.com/ksh93/ksh/issues/571#issuecomment-1304970130) below for a summary.

In `vi` mode only, using completion next to a wide character causes a pair of invalid characters to appear at the end of the line (as `^¿^¿`). In some cases, the last input character is deleted; this sometimes happens when completion will operate on a string of one or two wide characters (e.g. `ls あう(tab)`).

An adjustment to `out` when in `vi` mode at `completion.c:280` (`ed_expand`) appears to be the cause:

    out = outbuff + *cur + (sh_isoption(SH_VI)!=0);

The adjustment is needed to move `out` off of the last item in the string to be completed (in `emacs` mode, it is already in the next position). It works fine when `out` is initially on a character with a one-to-one narrow equivalent. Because wide characters have already been converted to a string of (negative) narrow characters, however, the adjustment puts `out` in the middle of the character representation. This produces the trailing garbage output as the `overlaid` function inappropriately zeroes part of the last input character before the tab.

One fix would be to increment `out` further in the following situations:
* The last character before tabbing is wide (negative `*out` and `*(out-1)`)
* The last character before tabbing is narrow, but is immediately followed by a wide character (negative `*out`, positive `*(out-1)`)

EDIT: Doesn't work. Please see [this comment](https://github.com/ksh93/ksh/issues/571#issuecomment-1298622827) below for an updated patch.

````
--- src/cmd/ksh93/edit/completion.c
+++ src/cmd/ksh93/edit/completion.c
@@ -278,6 +278,15 @@
 #endif /* SHOPT_MULTIBYTE */
 #if SHOPT_VSH
 	out = outbuff + *cur + (sh_isoption(SH_VI)!=0);
+#if SHOPT_MULTIBYTE
+	if(sh_isoption(SH_VI))
+	{
+		if(*out < 0 && *(out-1) > 0)
+			out += (CHARSIZE - 1);
+		else if (*out < 0)
+			out += (CHARSIZE - 2);
+	}
+#endif /* SHOPT_MULTIBYTE */
 #else
 	out = outbuff + *cur;
 #endif
````

This could also be done by determining the size of the previous character directly, but I'm not sure if that would be less horrible. I'm also not sure whether this isn't too ASCII-centric. Any thoughts?

**Comment by pghvlaans** [comment]
Actually, incrementing further over a normal-width character makes `*` and `=` give incorrect output (as if they were completing for the following character), so the `(*out < 0 && *(out-1) > 0)` condition will have to go. One invalid character is carried over in that case, but I think it might be a different bug (since `out` would be at the start of the following character like it's supposed to be).

EDIT: Yep, definitely a different bug. This one affects `emacs` mode as well. If there is more than one completion option:

* When using `*` in `vi` mode, all in-word characters after the cursor position are duplicated at the end of the completion. In `emacs` mode, the character under the cursor is also duplicated
* ~~In `=`, the completion menu is unresponsive~~

**Comment by pghvlaans** [comment]
I'm going to do some more research about how `wchar_t` characters correspond to single-bit characters and try to come up with a better solution. The patch above relies on wides being of width `CHARSIZE - 1`, which may not be true of all of them.

**Comment by pghvlaans** [comment]
The patch (and current `vi` mode) is pretty badly broken for [Unicode combined accents](https://www.ncbi.nlm.nih.gov/staff/beck/charents/accents.html). The patched version fails to complete with ordinary accented characters like `é`. It seems like it will be necessary to find the actual size of the previous character.

**Comment by pghvlaans** [comment]
Using the width of the narrow-character representation of the `cur_virt` character seems to be working and the invalid characters are gone. `*` and `=` are producing correct completions and characters with plain accents are working again, unlike the earlier patch:

EDIT: `d` below is an array; add forgotten comment.

````
--- src/cmd/ksh93/include/edit.h
+++ src/cmd/ksh93/include/edit.h
@@ -81,6 +81,9 @@
 	int	e_lookahead;	/* index in look-ahead buffer */
 	int	e_fcol;		/* first column */
 	int	e_wsize;	/* width of display window */
+#if SHOPT_MULTIBYTE
+	int	e_savedwidth;	/* saved width of a character */
+#endif /* SHOPT_MULTIBYTE */
 	char	*e_outbase;	/* pointer to start of output buffer */
 	char	*e_outptr;	/* pointer to position in output buffer */
 	char	*e_outlast;	/* pointer to end of output buffer */

--- src/cmd/ksh93/edit/vi.c
+++ src/cmd/ksh93/edit/vi.c
@@ -2555,6 +2555,11 @@
 		ch = c;
 		if(mode>=0 && c=='\\' && virtual[mode+1]=='/')
 			c = '=';
+#if SHOPT_MULTIBYTE
+	char *d[CHARSIZE+1];
+	wchar_t *savechar = &virtual[cur_virt];
+	vp->ed->e_savedwidth = mbconv(d,*savechar);
+#endif /* SHOPT_MULTIBYTE */
 		if(ed_expand(vp->ed,(char*)virtual, &cur_virt, &last_virt, ch, vp->repeat_set?vp->repeat:-1)<0)
 		{
 			if(vp->ed->e_tabcount)

--- src/cmd/ksh93/edit/completion.c
+++ src/cmd/ksh93/edit/completion.c
@@ -278,6 +278,10 @@
 #endif /* SHOPT_MULTIBYTE */
 #if SHOPT_VSH
 	out = outbuff + *cur + (sh_isoption(SH_VI)!=0);
+#if SHOPT_MULTIBYTE
+	if(sh_isoption(SH_VI) && ep->e_savedwidth > 0)
+		out += (ep->e_savedwidth - 1);
+#endif /* SHOPT_MULTIBYTE */
 #else
 	out = outbuff + *cur;
 #endif
````

The `edit` struct gets new `e_savedwidth`, which can be used to transfer information about the width of a particular character if needed. Please let me know if this is an unacceptable change. The width of the character at `cur_virt` is determined in `vi.c`, and then `completion.c` uses `e_savedwidth` to place `out` at the end of the character.

As a side note, It turns out that characters with combined accents can be completed from the "base" letter in `vi` mode (e.g., files starting with combined-accent `à` appear in the completion menu for `ls a(TAB)`). Attempting to tab from combined-accent letters now simply fails in patched `vi` mode.  `emacs` mode, `oksh` and `bash` all handle such letters in this way, so this seems to be a valid solution.

Now the only thing left to do is to track down the `*` and `=` bug.

**Comment by pghvlaans** [comment]
Quick update: I made a small change to initialize `e_savedchar` as `0` in `edit.c`. Regression tests are all passing on Linux.

I haven't found the other bug(s) yet. ~~Interestingly, the selection menu, when reached by `=` (`M-ESC M-=` in `emacs` mode), always fails to accept input if there are characters later in the line. When it is reached by tabbing, however, it accepts input regardless.~~

EDIT: I've come to the conclusion that unresponsive `=` completion may not be a bug after all; the option simply needs to be entered with another `=`. Like `*` completion, trailing characters in the same word are printed after the completion.

**Comment by pghvlaans** [comment]
I'm going to run the regression tests on *BSD and macOS and make a PR if they pass, but here's an overview of the two bugs and their fixes:

* `vi` mode: Completing from a wide character (i.e., a character represented by more than one narrow character) produces invalid characters at the end of the completion. This happens because when `out` is adjusted for `vi` mode in `completion.c`, the width of the character is not taken into account, and `out` is placed in the middle of the character rather than at the start of the next character. Check for the character width in `vi.c` and pass it to the `edit` struct as `e_savedwidth`; increment `out` by the width of the character when in `vi` mode.
* `vi` and `emacs` mode: Using `=` and `*` completion does not replace the word under the cursor. Instead, any trailing characters in the same word are printed at the end of the completion. This is contrary to Bolsky and Korn, pg. 99 and 115. In `vi.c` and `emacs.c`, remove all characters up to the next word boundary once completion occurs.

**Comment by McDutchie** [comment]
> `vi` and `emacs` mode: Using `=` and `*` completion does not replace the word under the cursor. Instead, any trailing characters in the same word are printed at the end of the completion. This is contrary to Bolsky and Korn, pg. 99 and 115. In `vi.c` and `emacs.c`, remove all characters up to the next word boundary once completion occurs.

The book says that completion replaces the current word; it does not say that they ignore the part of the word under and to the right of the cursor. So those characters should not be removed from consideration. I think a better approach might be to implicitly move the cursor to the position immediately following the current word before doing the completion. This is how ksh88 and pdksh/mksh appear to act, and I would support restoring that behaviour in ksh93 as it makes more sense.

Note that the same issue applies to ESC ESC (in emacs) and `\` (in vi) as well – and, by extension, to tab completion (which ISTR is implemented in terms of those, so should not have to be fixed separately unless I'm misremembering something).

Since this issue is unrelated to the current wide character bug, I would prefer it to be a separate PR.

**Comment by pghvlaans** [comment]
> The book says that completion replaces the current word; it does not say that they ignore the part of the word under and to the right of the cursor. So those characters should not be removed from consideration.

Ah, understood. The examples in the book are ambiguous, unfortunately, but it does talk about "appending to" the current word, which would seem to suggest doing the completion from the end like `mksh` does.

I'll make separate PRs.
