### ISSUE TITLE
.sh.match trashed by ${vname% %% # ## / //...}

### ISSUE THREAD

**Issue by phidebian** [ksh93/ksh#583]
I bumped into this

1. KSH latest (ubuntu 22.04 build on latest dev) (Same pb with package ksh)

```
TC$ echo $KSH_VERSION                                                         
Version AJM 93u+m/1.1.0-alpha+4ec93745 2022-10-31

TC$ [[ "12" =~ 12 ]] && echo "${.sh.match%2} ${.sh.match%2}"
1 

TC$ [[ "12" =~ 12 ]] && echo "${.sh.match#1} ${.sh.match#1}"

```
2. BASH (package)
```
PW$ [[ "12" =~ 12 ]] && echo "${BASH_REMATCH%2} ${BASH_REMATCH%2}" 
1 1 
PW$ [[ "12" =~ 12 ]] && echo "${BASH_REMATCH#1} ${BASH_REMATCH#1}" 
2 2
```

3. ZSH (package)
```
PW$ [[ "12" =~ 12 ]] && echo "${MATCH%2} ${MATCH%2}" 
1 1

PW$ [[ "12" =~ 12 ]] && echo "${MATCH#1} ${MATCH#1}"
2 2
```
I didn't investigated at all, but working on another =~ I discovered that ksh93 implemented =~ along with ${vname[%#/]...} all with the same code base, i.e they all deal with .sh.match, then trashing it, sounds like a design flaw. Yet it may be easy to separate all this, will see.

Again I may have mis-read the docco, (would not be the first time), may be this is documented, but a quick .sh.match scan don't mention any setting (temper) on .sh.match for ${vname% %% # ## / //}

**Comment by hyenias** [comment]
Trashing it? More like just potentially unsetting/overwriting the array/value(s) with the next successful results of a pattern match lookup. `.sh.match` is **a temporary storage array of the last successful pattern matched results**.

```ksh
$ [[ 12 =~ 12 ]] && { typeset -p .sh.match; echo ${.sh.match[0]%2}; typeset -p .sh.match; echo ${.sh.match[0]%2}; typeset -p .sh.match; }
.sh.match[0]=12
1
.sh.match[0]=2

.sh.match[0]=2
```
I would recommend copying or moving the `.sh.match` array elements/values you wish to keep from the most recent successful pattern match to another variable before performing another patten match operation as `.sh.match` contents are subject to change.

I do not considered this a design flaw.

```ksh
$ [[ 12 =~ 12 ]] && { typeset -m foo=.sh.match[0]; echo $foo ${foo%2} ${foo%2} $foo; }
12 1 1 12
```

**Comment by phidebian** [comment]
@hyenias Indeed this is a work around, saving it before overwriting it, yet it is not documented anywhere that <code>${vname% %%  # ## / //}</code> will overwrite .sh.match, and bash and zsh don't do this (don't have the other shells at hand). 

The test case I gave here is a streamline of a bash script of mine I backported to ksh93, where I use to <code>=\~</code> to setup BASH_REMATCH then use its elements until next <code>=\~</code>, I never imagined that <code>${vname% %%  # ## / //}</code> would overwrite the match array between the 2 <code>=\~</code>, it require a deep ksh93 internals knowledge to envision that.

So to me this is a bug, at least a docco bug (easiest path to fix) or a functional bug if we consider bash/zsh are right. I don't really mind that ksh93 diverge with other shell, as long as it is explicitly documented (Specially in a porting guide :-) )

To me it is a bug, albeit very low prio, so referencing it as bug, allow someone to fix it one day... 

I thought it was a design flaw, but as you said it seems it is not, it is just that <code>${vname% %%  # ## / //}</code> should use it own 'private/local' .sh.match for its own business, and pass it along to regcomp/regexec, and that's seem easy to do.

If tagged as [bug], I can volunteer to investigate for a fix...

**Comment by phidebian** [comment]
Interestingly, we learned that ksh93 do 'modify' .sh.match when it is not too friendly to so, as explained above, and then when it would be friendly to really 'modify' it, it doesn't as seen here

1. BASH
```
$ [[ "aa111" =~ ^[a-z]+ ]] 
$ echo "m0='${BASH_REMATCH}'"
m0='aa'
$ [[ "00aa111" =~ ^[a-z]+ ]] 
$ echo "m0='${BASH_REMATCH}'"
m0=''  <<--- expected
```
2. KSH
```
$ [[ "aa111" =~ ^[a-z]+ ]]
$ echo "m0='${.sh.match}'"
m0='aa'
$ [[ "00aa111" =~ ^[a-z]+ ]]
$ echo "m0='${.sh.match}'"
m0='aa'  <<----- huh?

```
Ok I know we can work around this, i.e reset .sh.match before any use or check [[ status, yet it is a common practice to assume a no match, would give a NULL string result.

Just verified the ZSH behave like KSH on this latest point while it behave like BASH for the former point, so I guess there is no definite answer... 

I then discovered that apparently .sh.match has a history of problems with ksh93, so may be I am stepping on someone else toes, or may be this was discussed already, if so, ignore all this.

**Comment by hyenias** [comment]
I disagree with your assertion that it is common practice that a NULL string is returned when no match was found when using ksh.

As for documentation, I learned about the .sh.match variable from book, "O'REILLY Learning the Korn Shell, 2nd Editiion" section "4.5.7. The .sh.match Variable" that states:

> The .sh.match variable was introduced in ksh93l. It is an indexed array (see Chapter 6), whose values are set every time you do a pattern matching operation on a variable, such as ${filename%%*/}, with any of the #, % operators (for the shortest match), or ##, %% (for the longest match), or / and // (for substitutions). .sh.match[0] contains the text that matched the entire pattern. .sh.match[1] contains the text that matched the first parenthesized subexpression, .sh.match[2] the text that matched the second, and so on. The values of .sh.match become invalid (meaning, don't try to use them) if the variable on which the pattern matching was done changes.

Additionally, I also have the following from a saved Linux man page of ksh93:
> .sh.match
> An indexed array which stores the most recent match and sub-pattern matches after conditional pattern matches that match and after variables expansions using the operators #, %, or /. The 0-th element stores the complete match and the i-th. element stores the i-th submatch. The .sh.match variable becomes unset when the variable that has expanded is assigned a new value.

**Comment by phidebian** [comment]
@hyenias , Ha! touche, I don't have the O'REILLY, and for the last one is still confusing to me. 
```
$ a=111aaa         # A Variable is set
$ echo ${a#111}    # A variable is expanded with a match
aaa

$ echo ${.sh.match} # The match
111

$ a=huh   # A variable that  has expanded is assigned a new value

$ # The .sh.match variable becomes unset when the variable 
$ # that has expanded is assigned a new value. 
$ # Well not really...
$ echo ${.sh.match} 
111
```

Personnally, since the last sentence is ambiguous, I red "The .sh.match is unset before using it :-) " But I admit I am biased here, this is not that either.

All in all, this could be closed a pilot error, I don't take offense, yet I believe it could still be classified at least as [enhancement], because when implemented ala bash, it would not break any existing ksh93 script, as currently the programmer has to explicilty, reset .sh_match all the time before use and/or test [[ status all the time before trusting .sh.match, and then implementing the bash shortcut would not break that.

**Comment by McDutchie** [comment]
OK, to summarise, I see two change requests here:

1. Pattern matching operations done on .sh.match itself should be exempted from modifying .sh.match.
2. Whenever a pattern matching operation yields a non-match, .sh.match should be reset.

I might have agreed with these points if we'd be designing this feature from scratch. But changing either behaviour now could break existing scripts, so they should not be changed in the 1.0 series. They could be considered as potentially incompatible changes in the 1.1 series or up, but I still don't think the case for changing them is very compelling; the current situation seems quite workable if you're aware of how it works. The documentation could do with clarifying these points in any case, though.

Another point that was raised:

3. It is unclear what the following from the manual means, and if it is even correct: "The .sh.match variable becomes unset when the variable that has expanded is assigned a new value."

This is true. I'll do some investigating. It may simply be wrong, or it may be that AT&T changed the behaviour in an older ksh version without updating the manual.

**Comment by McDutchie** [comment]
> 3. It is unclear what the following from the manual means, and if it is even correct: "The .sh.match variable becomes unset when the variable that has expanded is assigned a new value."
> 
> This is true. I'll do some investigating. It may simply be wrong, or it may be that AT&T changed the behaviour in an older ksh version without updating the manual.

The earliest ksh version I can run is 93p+ from 2004-10-11 (thanks to @JohnoKing's work on the ksh93-history repo). That version already acts like the current one, so the manual page sentence appears to be incorrect. I don't know if it was ever correct between 2001 (when this feature was introduced) and 2004, but it doesn't really matter. The sentence is also inconsistent with the quote (above) from the O'Reilly book. So I think it should be deleted from the manual.

**Comment by phidebian** [comment]
@McDutchie Thanx.
