### ISSUE TITLE
Building in strict C99 mode

### ISSUE THREAD

**Issue by fweimer-rh** [ksh93/ksh#587]
Future versions of GCC and Clang will reject implicit function declarations and implicit ints by default. We are trying to get Fedora ready for this change:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

To support this, I'm building packages with an instrumented compiler that logs errors in a difficult-to-suppress way, to capture places where these new errors might impact feature probing code.

Running a build, I find these occurrences:

```none
/builddir/build/BUILD/ksh-1.0.4/src/cmd/INIT/w2.c:23: implicit function declaration: iswspace
./Fea8d1662.c:45: implicit function declaration: wcwidth
./Fea8d1662.c:38: implicit function declaration: wcwidth
./Fea8d1796.c:162: defaulting to int
./Fea8d1796.c:161: defaulting to int
./Fea8d6386.c:52: defaulting to int
./Fea8d7175.c:6: defaulting to int
./Fea8d7175.c:6: defaulting to int
./Fea8d7175.c:7: defaulting to int
./Fea8d7175.c:3: defaulting to int
conf.tmp.c:30: implicit function declaration: printf
conf.tmp.c:19: implicit function declaration: open
conf.tmp.c:22: implicit function declaration: strtol
conf.tmp.c:23: implicit function declaration: strtol
conf.tmp.c:20: implicit function declaration: open
./ea8d12739.c:41: implicit function declaration: __xstat
./ea8d12739.c:62: implicit function declaration: getfsstat
./ea8d18213.c:44: implicit function declaration: utimets
./ea8d19014.c:40: implicit function declaration: _open
./ea8d19014.c:84: implicit function declaration: _pathconf
./ea8d19014.c:76: implicit function declaration: _link
./ea8d19014.c:74: implicit function declaration: _getpagesize
./ea8d19014.c:86: implicit function declaration: _rename
./ea8d19014.c:92: implicit function declaration: _truncate
./ea8d19014.c:90: implicit function declaration: _stat
./ea8d19014.c:94: implicit function declaration: _unlink
./ea8d19014.c:96: implicit function declaration: _utime
./ea8d19014.c:70: implicit function declaration: _chmod
./ea8d19014.c:63: implicit function declaration: _chdir
./ea8d19014.c:44: implicit function declaration: _close
./ea8d19014.c:42: implicit function declaration: _fstat
./ea8d19014.c:68: implicit function declaration: _access
./ea8d19014.c:47: implicit function declaration: _read
./ea8d19014.c:61: implicit function declaration: _mkdir
./ea8d19014.c:47: implicit function declaration: _write
./ea8d19014.c:104: implicit function declaration: system
```

These all indicate places where GCC now reports errors at compile time. Many of them were link-time errors before (all the Windows-style `_`-prefixed functions, for example).

But I have a hard time to find the places of the functions that *should* be available, namely:

* `open`
* `printf`
* `strtol`
* `system`

The location of those implicit `int`s also eludes me.

The `__xstat` error is somewhat concerning as well, this function is no longer to be used on current glibc.

The `iswspace` reference I can find due to the full path, but I'm stumped what this is supposed to do. Obviously it's some kind of feature probing, but where is it used?

`wcwidth` is probably harmless, it is correctly detected in the end.

Any help with this is appreciated!

**Comment by pghvlaans** [comment]
Thank you very much for sharing the modified GCC. 

`conf.tmp.c` is generated and regenerated by `src/lib/libast/comp/conf.sh`. I altered the script to save these temporary files for diagnostics, and it appears that the following locations are producing the implicit declarations in `conf.tmp.c`:

* `conf.sh:1285` (`printf`, one each of `strtol` and `open`):
```
				*)	cat > $tmp.c <<!
${head}
#include <sys/types.h>
#include <limits.h>
#include <unistd.h>$systeminfo$headers
${tail}
${script}
!
```
* `conf.sh:1136` (`strtol`, `open`)
```
					*)	cat > $tmp.c <<!
${head}
#include <stdio.h>
#include <sys/types.h>
#include <limits.h>
#include <unistd.h>$systeminfo$headers
${tail}
${script}
!
```

Does anyone know if there would be negative side effects to adding the missing includes here?

Anyway, I'll have some time to help look for `system` and maybe the `int`s over the next couple of days.

**Comment by pghvlaans** [comment]
The implicit `system` declaration is at `src/lib/libast/features/omitted:79`.

**Comment by pghvlaans** [comment]
It turned out that implicit `int` calls broke `PATH` detection when building with the modified GCC. Three of them appeared when running `src/cmd/INIT/iffe.sh`:

* `src/lib/libast/features/vmalloc:117` (`./Fea8d6386.c:52` above):
```
tst	stk_down note{ stack grows downward }end execute{
	static growdown()
```
* `src/lib/libast/features/lib:66` (`./Fea8d1796.c:161,162` above):
```
	error() { }
	strerror() { }
	int main() { errno = 0; error(); strerror(); return 0; }
```
The others appeared in `src/lib/libast/features/param.sh`:
* `src/lib/libast/features/param.sh:45`:
```
struct stat V_stat_V;
F_stat_F() { V_stat_V.st_mode = 0; }" > $tmp.c
```
As far as looking for the remaining implicit declarations is concerned, I've set up a [testing branch](https://github.com/pghvlaans/ksh/tree/conf-diagnostic) at my fork. It saves the temporary `c` files generated by `iffe.sh`, `conf.sh` and `param.sh` so they can be examined after compilation. (The items mentioned in my previous comments already have provisional fixes.)

For reference, saving occurs before the temporary file is sent to the compiler, so the last temporary file modified before the error file is probably a good place to start looking.

**Comment by JohnoKing** [comment]
I've begun working on fixing this on a test branch of my own and thus far have a working binary (although I'm not finished testing yet). To test the compile, I'm using the following wrapper script to run GCC 13.1.1 (and also the current GCC git commit):
```sh
#!/bin/sh
exec gcc -std=c99 -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=old-style-definition "$@"
#exec gcc -std=gnu99 -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=old-style-definition "$@"
```
