### ISSUE TITLE
nameref fails when not using positional arguments

### ISSUE THREAD

**Issue by elmehdou** [ksh93/ksh#593]
nameref (typeset -n) fails when not using positional arguments (ex: $1).

Version: sh (AT&T Research) 93u+m/1.0.0-beta.2 2021-12-17

Testing example:
```shell
function func_a {
    nameref ref=$1
    ref=( a=1 b=2 c=3 )
}

function func_b {
    typeset return_var=$1
    nameref ref=$return_var
    ref=( 1 2 3 )
}

# Success
function func_c1 {
    typeset var1
    func_a var1
    echo "var1.a = ${var1.a}"
}
func_c1

# Failure
function func_c2 {
    typeset var2
    func_b var2
    echo "var2[@] = ${var2[@]}"
}
func_c2
```

Am I misunderstanding how nameref works? Is this the expected behavior?

**Comment by hyenias** [comment]
I do not know about expected behavior but I have never attempted using  a local variable assignment later on when creating namerefs within a function pointing to outside of the function. Here is the nameref man entry:

```
A nameref is a variable that is a reference to another variable.  A nameref is created with  the  -n  attribute  of
typeset.  The value of the variable at the time of the typeset command becomes the variable that will be referenced
whenever the nameref variable is used.  The name of a nameref cannot contain a ..  When a variable or function name
contains a ., and the portion of the name up to the first . matches the name of a nameref, the variable referred to
is obtained by replacing the nameref portion with the name of the variable referenced by the nameref.  If a nameref
is  used as the index of a for loop, a name reference is established for each item in the list.  A nameref provides
a convenient way to refer to the variable inside a function whose name is passed as an argument to a function.  For
example, if the name of a variable is passed as the first argument to a function, the command
        typeset -n var=$1
inside the function causes references and assignments to var to be references and assignments to the variable whose
name has been passed to the function.
``` 

The result of your `func_c2` function is that `var2` ends up getting creating in the default global namespace. Try issuing `typeset -p var2` outside of any of your functions.

```ksh
$ func_c2
var2[@] =
$ typeset -p var2
typeset -a var2=(1 2 3)
```

**Comment by elmehdou** [comment]
The goal is to set the value of the variable in the parent scope not the global one. Using the name stored in `$1` or in another variable shouldn't make a difference.

**Comment by elmehdou** [comment]
Here is a somewhat relevant example of the problem at hand:
```shell
#!/bin/ksh

function sql_query_csv {
	typeset usage
	# METADATA
	usage+="[+NAME?${.sh.fun} --- Sql query result to csv.]"
	# OPTIONS
	usage+="[r:return-var]:[?Return variable.]"

	while getopts "${usage}" option; do
		case "${option}" in
			r) typeset -n return_var="${OPTARG}" ;;
		esac
	done

	return_var="return value"
}

function calling_func {
	typeset test_var
	sql_query_csv -r test_var
	echo "local test_var: ${test_var}"
}

calling_func
echo "global test_var: ${test_var}"
```

If I use `$2` instead of `${OPTARG}` it works just fine and the variable `test_var` in the `calling_func` scope is set . My question being why doesn't it work as it is supposed to with `${OPTARG}` ?

**Comment by hyenias** [comment]
I agree that the nameref lookup using the provided local variable is not working as described via nested functions. I would guess that the variable lookup/assignment/etc. is not accounting for this nested function situation and as such the result is being placed into the global scope. I looked within https://github.com/ksh93/ksh/blob/dev/src/cmd/ksh93/tests/nameref.sh and did not find a similar test case for a nameref using a variable within nested functions.

I played around with your code a little and got it to work of sorts by changing sql_query_csv to old style function which should default to using globals but it appears it is not as checked by the additional global variable checks. It seems ksh is getting mixed up on the global and local scoping when using nested functions in this manner.

```ksh
sql_query_csv() {
  typeset usage option
  # METADATA
  usage="[+NAME?${.sh.fun} --- Sql query result to csv.]"
  # OPTIONS
  usage+="[r:return-var]:[?Return variable.]"

  while getopts "${usage}" option; do
    case "${option}" in
    r) typeset -n return_var="${OPTARG}" ;;
    esac
  done

  return_var='return value'
}

function calling_func {
  typeset test_var
  sql_query_csv -r test_var
  echo "local test_var: ${test_var}"
}

calling_func
{
[[ -z $test_var ]] || echo global test_var exists
[[ -z $usage ]] || echo global usage exists
[[ -z $option ]] || echo global option exists
[[ -z $return_var ]] || echo global return_var exists
}

```
Results:
```ksh
local test_var: return value
```
I would have expected the following to occur but it did not until I removed `typeset usage option` from the old style global ksh function.
```
$ calling_func
local test_var: return value
...
global usage exists
global option exists
```

**Comment by hyenias** [comment]
Here is how I used `set` to place the getops `option` results back into a known positional parameter of $1 as a workaround until this bug can be addressed.
```ksh
function sql_query_csv {
  typeset usage option
  # METADATA
  usage="[+NAME?${.sh.fun} --- Sql query result to csv.]"
  # OPTIONS
  usage+="[r:return-var]:[?Return variable.]"

  while getopts "${usage}" option; do
    case "${option}" in
    r) set -- "$OPTARG"; typeset -n return_var="$1" ;;
    esac
  done

  return_var='return value'
}

function calling_func {
  typeset test_var
  sql_query_csv -r test_var
  echo "local test_var: ${test_var}"
}

calling_func
{
[[ -z $test_var ]] || echo global test_var exists
[[ -z $usage ]] || echo global usage exists
[[ -z $option ]] || echo global option exists
[[ -z $return_var ]] || echo global return_var exists
}
```

**Comment by elmehdou** [comment]
Unfortunately this workaround doesn't breaks `getops` if there are any options after the relevant one. `$2` also fails for that matter. As you can see the uri variable doesn't get set.

```shell
function sql_query_csv {
  typeset usage option
  # METADATA
  usage="[+NAME?${.sh.fun} --- Sql query result to csv.]"
  # OPTIONS
  usage+="[r:return-var]:[?Return variable.]"
  usage+="[u:uri]:[?Connection URI.]"
  usage+="[q:query]:[?SQL Query.]"

  typeset query
  typeset uri 

  while getopts "${usage}" option; do
    case "${option}" in
    r) set -- "${OPTARG}"; typeset -n return_var="$1" ;;
    q) query="${OPTARG}" ;;
    u) uri="${OPTARG}" ;;
    esac
  done

  return_var='return value'

  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "return_var: ${return_var}"
  echo "query: ${query}"
  echo "uri: ${uri}"
}

function calling_func {
  typeset test_var
  sql_query_csv -q "select * from table" -r test_var -u usr/pwd
  
  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "local test_var: ${test_var}"
}

calling_func
echo
echo "-----SCOPE: GLOBAL-----"
echo "global test_var: ${test_var}"
```

Could there be another workaround perhaps ?
Very much appreciated.

**Comment by elmehdou** [comment]
A little workaround using `eval` and `$OPTIND`. Though i'm not sure about the implications of using eval (seems pretty harmless in this case):

```shell
#!/bin/ksh
function sql_query_csv {
  typeset usage option
  # METADATA
  usage="[+NAME?${.sh.fun} --- Sql query result to csv.]"
  # OPTIONS
  usage+="[r:return-var]:[?Return variable.]"
  usage+="[u:uri]:[?Connection URI.]"
  usage+="[q:query]:[?SQL Query.]"

  typeset query
  typeset uri 
  while getopts "${usage}" option; do
    case "${option}" in
    r) eval typeset -n return_var="\$$((OPTIND-1))" ;;
    u) uri="${OPTARG}" ;;
    q) query="${OPTARG}" ;;
    esac
  done

  return_var="value"

  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "return_var: ${return_var}"
  echo "query: ${query}"
  echo "uri: ${uri}"
}

function calling_func {
  typeset test_var
  sql_query_csv -q "select * from table" -r test_var -u usr/pwd
  # sql_query_csv --man
  
  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "local test_var: ${test_var}"
}

calling_func
echo
echo "-----SCOPE: GLOBAL-----"
echo "global test_var: ${test_var}"
```

Result
```
-----SCOPE: sql_query_csv-----
return_var: value
query: select * from table
uri: usr/pwd

-----SCOPE: calling_func-----
local test_var: value

-----SCOPE: GLOBAL-----
global test_var: 
```

**Comment by hyenias** [comment]
Oh, I see--change the programming requirements and expand on them... :) All good.

Nice bit of work to utilize $OPTIND within the getops loop.

Your solution does work. As for using eval, it all depends on how much you trust your input(s). Did you validate/sanitize all inputs for eval? Are all the inputs under your control? And etc... Your call, your program.

However, if you would like to avoid the eval solution; you could simply store the getops -r results in a temporary variable and act on it later when you have no further need of the passed positional parameters.

```ksh
function sql_query_csv {
  typeset usage option
  # METADATA
  usage="[+NAME?${.sh.fun} --- Sql query result to csv.]"
  # OPTIONS
  usage+="[r:return-var]:[?Return variable.]"
  usage+="[u:uri]:[?Connection URI.]"
  usage+="[q:query]:[?SQL Query.]"

  typeset query
  typeset uri
  typeset rvar='' # temporary storage for return_var

  while getopts "${usage}" option; do
    case "${option}" in
    r) rvar="$OPTARG" ;;
    u) uri="${OPTARG}" ;;
    q) query="${OPTARG}" ;;
    esac
  done

  if [[ -n $rvar ]]
  then
    set -- "$rvar"
    typeset -n return_var="$1"
  fi

  return_var="value"

  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "return_var: ${return_var}"
  echo "query: ${query}"
  echo "uri: ${uri}"
}

function calling_func {
  typeset test_var
  sql_query_csv -q "select * from table" -r test_var -u usr/pwd
  
  echo
  echo "-----SCOPE: ${.sh.fun}-----"
  echo "local test_var: ${test_var}"
}

calling_func
echo
echo "-----SCOPE: GLOBAL-----"
echo "global test_var: ${test_var}"
```

**Comment by McDutchie** [comment]
Minimal reproducer:
```sh
function f
{
        typeset v=$1
        nameref r=$v
        r=(1 2 3)
}

function g
{
        typeset v2
        f v2
        typeset -p v2
}

g
```

Actual output: none
Expected ouput: `typeset -a v2=(1 2 3)`

**Comment by McDutchie** [comment]
Something must be going wrong with static scoping. If `typeset v2` is deleted so `v2` is not made local to `g`, it works fine.

Positional parameters are not statically scoped, which *might* help explain why it works to replace the first two lines of the function `f` with `nameref r=$1`.

**Comment by McDutchie** [comment]
Actually, given how static scoping works, it is not surprising the reproducer fails. What is surprising is that using `nameref r=$1` directly *does* work. Under static scoping, the `f` function should not have access to `g`'s local variables at all!

**Comment by hyenias** [comment]
Is this perhaps an exception to that static scoping rule? Instead of passing by value, we are passing by reference. Manual entry for nameref says:

> A nameref provides a convenient way to refer to the variable inside a function whose name is passed as an argument to a function.  For example, if the name of a variable is passed as the first argument to a function, the command
>         typeset -n var=$1
> inside the function causes references and assignments to var to be references and assignments to the variable whose name has been passed to the function.

**Comment by McDutchie** [comment]
There is nothing in that text that actually says that this particular usage breaks the static scoping barrier (whereas a similar usage as in the reproducer doesn't break it), though I will admit it seems to be vaguely implied. I will have to fix the doc, but first I'd like to find the code that actually implements this. It looks like another one of those typical AT&T ugly special-casing hacks, but this is likely one we can't get rid of :-/

**Comment by McDutchie** [comment]
The special-casing is handled in setall() in typeset.c, here: https://github.com/ksh93/ksh/blob/e928daa66e308214f549111ac0a811b6ee9f535b/src/cmd/ksh93/bltins/typeset.c#L972-L976

That code specifically switches to the previous static scope if we're assigning a positional parameter to a nameref as a part of a `typeset -n` or `nameref` declaration command. So that is the only case in which that will work.

It's a typical AT&T ksh hack, but I'm afraid it's not a bug. And since there are plenty of scripts that depend on this, we cannot change it.
