### ISSUE TITLE
ksh93 exits with status 0 upon error reading a script

### ISSUE THREAD

**Issue by sckendall2** [ksh93/ksh#595]
A customer reported that a large, long-running script exited early, but with status 0. This should have been impossible. We eventually figured out that the cluster filesystem containing the script had gone offline while the script was executing. The shell, reading a block of the script itself, got ESTALE from read(2). The bug is that the shell swallowed the error, treating it like EOF. It should have exited with an error status.

To reproduce the bug easily, you need a modern enough Linux that strace can inject errors. In the following session, we create a trivial script and run it under strace twice, the first time to see which read(2) calls read the script, and the second time to inject the error.

```
$ echo 'echo hello' > s.sh
$ strace -e trace=read ksh93 s.sh                                  
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\16\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\16\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0PS\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`&\2\0\0\0\0\0"..., 832) = 832
read(3, "65536\n", 31)                  = 6
read(11, "echo hello\n", 65536)         = 11
read(11, "", 65536)                     = 0
hello
+++ exited with 0 +++
$ strace -e trace=read -e inject=read:error=ESTALE:when=6 ksh93 s.sh
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\16\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\16\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0PS\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`&\2\0\0\0\0\0"..., 832) = 832
read(3, "65536\n", 31)                  = 6
read(11, 0x7fbb563cbdb0, 65536)         = -1 ESTALE (Stale file handle) (INJECTED)
+++ exited with 0 +++
$ 
```

Variations on that last command are to substitute EIO (a more severe error) for ESTALE, or when=7 for when=6. These variations also display the buggy behavior. The latter variation models something more like the original report we got from our customer, where the script was large and the error occurred not in reading the first block of the file, but in reading a later block.

The OS in the above session RHEL 7.9; the package is ksh-20120801-142.el7.x86_64; KSH_VERSION is Version AJM 93u+ 2012-08-01. We see the bug in every other version of ksh93 and mksh we tested, and in dash, and in some but not all versions of bash. The bash bug report is https://savannah.gnu.org/support/index.php?110763.  The mksh bug report is https://bugs.launchpad.net/mksh/+bug/2002044. 

Despite the almost-uniform behavior of implementations, I assert that the behavior is a bug: one cannot build reliable software with a tool that swallows errors. Assuming the error is caught, POSIX (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html) requires an exit status in the range 1-125: "A non-interactive shell detected an error other than command_file not found or executable, including but not limited to syntax, redirection, or variable assignment errors." A diagnostic message is a good idea, too, of course.

How likely is the bug to reoccur without fault injection? Unlikely in a script smaller than ksh93's read block size, 64 KB. The bug becomes more likely if the script lives on an unreliable filesystem, and is larger than one block, and runs for a long time in a portion of the script before the last block.

**Comment by phidebian** [comment]
As explained in many places (for instance https://savannah.gnu.org/support/index.php?110763) ioerror on read is treated as EOF on many shell. 

On explicit read builtin this is ok, because the script can act on this.

On internal shell operations, reading a script from runstring, sourcing a script, ioerror on script volume are possible, and mishandling from app too (app here mean gigantic scripts) .

Generally a script app have other strategy than just the exit value to figure out how the it exited, a simple status file can do it <code> echo started >status</code> then <code>echo OK >status</code> is good enough, then running the script, and checking the status file would be more accurate than just the exit value of zero. 

Another strategy is to place the script on a ramdisk before using it, this way no read error can occur beside a system panic.

Since POSIX don't specify what to do on internal script read error (error 127 and 126 are not for this) I doubt any fix will be implemented. When POSIX define 125, then may be :-)

**Comment by sckendall2** [comment]
Suppose an operating system terminated a process _with a status of success_ upon an I/O error in its executable file. Is that a bug or a feature? Would it change your mind to find that some other OSes do the same thing? How about if you found that the relevant standard doesn’t address this exact case?

How is this shell behavior any different?

**Comment by phidebian** [comment]
If an application is sensitive about this IO error on internal read (script loading) it should be written in a language that that interact with the OS with this granularity. Now if an application is written in a shell which has a very limited interface with the OS, i.e all the OS section 2 (syscall) is not directly accessible, then this application must rely on the shell feature only, here the feature is EIO on internal read (script loading) are handled as EOF, if this is not good enough for the app, the app should choose another language to be implemented or workaround this. It is indeed possible to fix the various shells to behave differently yet it would require coordination (POSIX). This particular occurence (FS stale on internal read) is so easily workable around that I am not sure someone would like to spare time on this while no POSIX change is made and explicitly state what to do in this situation. Meanwhile a workaround is the best route I guess.

**Comment by phidebian** [comment]
For the fun of it, I cutted a patch of what could be an implementation, if the issue-595 is promoted to bug one day.

This issue-595 branch  https://github.com/phidebian/ksh/tree/issue-595 as no QA update, yet it doesn't break the current QA (on ubuntu 22.04 x86_64).

You can clone it, build it and run it.

It can be tested locally like this, cd to <code>bin/</code> then create the <code>s.sh</code> file like this

```
$ cd arch/linux.i386-64/bin
$ echo '#!/d1/ksh-latest/arch/linux.i386-64/bin/ksh
echo "What a wonderfull world!"' >s.sh
```

- Inject on the runstring    <code>./ksh ./s.sh</code>

```      
strace -e trace=read -e inject=read:error=ESTALE:when=5 ./ksh ./s.sh
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
read(3, "# Locale name alias data base.\n#"..., 4096) = 2996
read(3, "", 4096)                       = 0
read(10, 0x56399555de50, 65536)         = -1 ESTALE (Stale file handle) (INJECTED)
ksh: error [Stale file handle] on /d1/ksh-phideb/arch/linux.i386-64/bin/s.sh
+++ exited with 126 +++
```
./ksh exited with code 126 that is documented in ksh as <code>#define EXIT_NOEXEC     126     /* other exec error     */
</code> so it can be considered an other exec error, yet bash and NOEXEC tend to mean the script is not executable..., if POSIX decide it should be 125 we could adapt later.

- Inject on shebang, make s.sh executable and run it <code>./s.sh</code>
```
$ strace -e trace=read -e inject=read:error=ESTALE:when=5 ./s.sh
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
read(3, "# Locale name alias data base.\n#"..., 4096) = 2996
read(3, "", 4096)                       = 0
read(10, 0x55e86375de50, 65536)         = -1 ESTALE (Stale file handle) (INJECTED)
ksh: error [Stale file handle] on /d1/ksh-phideb/arch/linux.i386-64/bin/s.sh
+++ exited with 126 +++
```
- Inject on sourcing <code>. ./s.sh</code>
```
$ strace -e trace=read -e inject=read:error=ESTALE:when=5 ./ksh -e ". ./s.sh"
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
read(3, "# Locale name alias data base.\n#"..., 4096) = 2996
read(3, "", 4096)                       = 0
read(3, 0x55a45de58660, 65536)          = -1 ESTALE (Stale file handle) (INJECTED)
ksh: error [Stale file handle] on /d1/ksh-phideb/arch/linux.i386-64/bin/s.sh
+++ exited with 126 +++
```

**Comment by McDutchie** [comment]
Thanks for the test branch, @phidebian!

I can't get the error to trigger in xec.c, only in main.c.

I think the `eof_or_error:` routine in main.c is a more logical place for it:
```diff
diff --git a/src/cmd/ksh93/sh/main.c b/src/cmd/ksh93/sh/main.c
index 8447a6614..4e57a042c 100644
--- a/src/cmd/ksh93/sh/main.c
+++ b/src/cmd/ksh93/sh/main.c
@@ -561,6 +561,11 @@ static void	exfile(register Sfio_t *iop,register int fno)
 					continue;
 				}
 			}
+			else if(errno && sferr)
+			{
+				errormsg(SH_DICT,ERROR_SYSTEM|ERROR_PANIC,"read from script failed");
+				UNREACHABLE();
+			}
 			if(errno==0 && sferr && --maxtry>0)
 			{
 				sfclrlock(iop);
```

**Comment by McDutchie** [comment]
Austin Group (POSIX) discussion is ongoing at <https://austingroupbugs.net/view.php?id=1629>.

**Comment by McDutchie** [comment]
> I can't get the error to trigger in xec.c, only in main.c.

Oh, I see: the xec.c patch is for dot scripts.
