### ISSUE TITLE
Function definition syntax restrictions odd and not matching documentation

### ISSUE THREAD

**Issue by hvdijk** [ksh93/ksh#598]
ksh documents the function syntax in its manpage as:

>        function varname { list ;}
>        varname () { list ;}

That is, it documents that a function body must begin with `{` and end with `}`.

POSIX says:

>     fname ( ) compound-command [io-redirect ...]

That is, it allows any compound-command and allows redirections.

ksh's implementation actually allows everything POSIX requires, and more, but with odd restrictions: all the following POSIX-valid function definitions work:

    f() { echo hello; } >&2; f
    f() ( echo hello ) >&2; f
    f() for x in :; do echo hello; done >&2; f
    f() case x in x) echo hello; esac >&2; f
    f() if :; then echo hello; fi >&2; f
    f() while ! echo hello; do :; done >&2; f
    f() until echo hello; do :; done >&2; f

as does the non-POSIX-valid

    f() echo hello; f
    f() g() echo hello; f; g
    >&2 f() echo hello; f # writes to stdout in ksh/bosh, writes to stderr in zsh

However, the following non-POSIX-valid tests, which I would expect to work for consistency, do not work:

    f() >&2 echo hello; f
    f() echo hello >&2; f

This instead results in

> syntax error at line 1: `>&' unexpected

Function definitions using the `function` keyword, meanwhile, require `{` and `}`, but still allow the `}` to be followed by redirections, contrary to what the manpage says:

    function f { echo hello; } >&2; f

There are three separate but closely related aspects to this issue:

- There is a mismatch between ksh documentation and ksh implementation.
- There is a conflict between POSIX and ksh documentation (but not between POSIX and ksh implementation).
- There is a surprising restriction in ksh's implementation that may or may not be wanted.

**Comment by ormaaj** [comment]
The grammar described in the manual is hand-wavy and not comprehensive.

> ksh's implementation actually allows everything POSIX requires, and more, but with odd restrictions: all the following POSIX-valid function definitions work:

That's correct. mksh has a similar implementation. 


> However, the following non-POSIX-valid tests, which I would expect to work for consistency, do not work:
> 
> ```
> f() >&2 echo hello; f
> f() echo hello >&2; f
> ```
> 
> This instead results in
> 
> > syntax error at line 1: `>&' unexpected

Admonishment for the user that writes this is a delightful surprise indeed - it's perfect! Must be a feature.

> Function definitions using the `function` keyword, meanwhile, require `{` and `}`, but still allow the `}` to be followed by redirections, contrary to what the manpage says:
> 
> ```
> function f { echo hello; } >&2; f
> ```

They're not really related. The POSIX function definition syntax allowing a simple command is an undocumented extension. It may be changed in the future.

The POSIX function syntax should be thought of as accepting a compound command argument whereas the curly braces of the ksh93 `function` syntax should be considered as tokens that are integral to the `function` construct itself. That aspect is currently unique to ksh93. Other shells that have implemented similar syntax for interoperability have done it differently. It's quite likely that `function` will be further modified and extended in the future to facilitate new requirements pertaining to the type system.

**Comment by hvdijk** [comment]
> The POSIX function syntax should be thought of as accepting a compound command argument whereas the curly braces of the ksh93 `function` syntax should be considered as tokens that are integral to the `function` construct itself.

I get that. That is exactly why I would have *expected* `function f { echo hello; } >&2; f` to fail. Yet it succeeds.

**Comment by ormaaj** [comment]
Yeah the optional redirect is also just part of the syntax and the manual is "wrong" ish. The braces actually do clean up some ambiguities and make it easier to use it in places that would otherwise create conflicts.

There are some other subtleties to the redirect as well such as POSIX allowing (arguably) both the expansion and evaluation order to [depend on the type of command](https://www.vidarholen.net/contents/blog/?p=865) (that's a decent overview. That post misses a few important points and mostly focuses on bash). By separating out the redirect from the compound command syntax we sidestep that ambiguity and allow a redirect applied to a function to be guaranteed consistent behaviour in any context. (ksh makes that guarantee anyway but this way we don't clash with the spec).

Nobody ever put in the effort to perfect the manual. You have to read between the lines and infer the intention behind just about everything. Almost every feature has at least a few mysterious properties about it. Anything that we can't determine through detective work can only be resolved by continuing where Korn et al left off by making such decisions ourselves.

**Comment by McDutchie** [comment]
> * There is a mismatch between ksh documentation and ksh implementation.
> * There is a conflict between POSIX and ksh documentation (but not between POSIX and ksh implementation).

Could you (or someone) indicate the exact language/location in the documentation that is wrong? I can't easily find it and don't have time to dig. A patch or PR to fix it would be even better.

> * There is a surprising restriction in ksh's implementation that may or may not be wanted.

TBH, I'm not inclined to change anything here. Even `functname() simple_command` without a redirection didn't work correctly on any ksh93 version until e920f42e93cb24549afd8568912058bb1501ef34 (see #203). In practice, almost no one knows this is a thing and people always use braces for function definitions – which is surely how #203 went unnoticed for decades.

**Comment by hvdijk** [comment]
> Could you (or someone) indicate the exact language/location in the documentation that is wrong? I can't easily find it and don't have time to dig. A patch or PR to fix it would be even better.

The quote comes from lines 603 and 605 in `sh.1`. If `f() echo >&2` were to be accepted, the fix would be trivial: change

    function varname { list ;}
    varname () { list ;}

to

    function varname { list ;} [redirection...]
    varname () command

since the section on redirections already says "may appear anywhere in a simple-command or may precede or follow a command". I'd need to look up the syntax for manpages to be able to create a PR for this.

However...

> TBH, I'm not inclined to change anything here.

...without changing the parser to accept this (a perfectly reasonable choice that I am not disagreeing with), this documentation would still be wrong. Perhaps

    function varname { list ;} [redirection...]
    varname () compound-command [redirection...]

would cover it, leaving `varname () simple-command` undocumented?

Note that in general, ksh also has the documented extension of accepting

    >&2 (echo hello)

where POSIX sh requires

    (echo hello) >&2

but extension also does not apply to the command in function definitions, the redirection here too is required to appear at the end. The function definition syntax like this, specifying that redirections must appear at the end, should cover that.

> Even `functname() simple_command` without a redirection didn't work correctly on any ksh93 version until [e920f42](https://github.com/ksh93/ksh/commit/e920f42e93cb24549afd8568912058bb1501ef34) (see #203).

Thanks for the reference. I was not aware that this did not work reliably.
