### ISSUE TITLE
Segmentation fault when using $"..."

### ISSUE THREAD

**Issue by ko1nksm** [ksh93/ksh#599]
Multilingualization using `$"..."` will result in segmentation faults.

At least ksh93u+m/1.0.4 reproduced the problem. but I had a problem is not being translated with my own builds (not segmentation faults).

I have prepared reproducible code.
https://github.com/ko1nksm/ksh93-i18n

```console
koichi@server:~/workspace/ksh93-i18n$ cat ksh93-i18n
#!/usr/bin/env ksh
export NLSPATH=locale/%l/%N.cat
echo $"Hello World!"

koichi@server:~/workspace/ksh93-i18n$ cat locale/C/ksh93-i18n.msg
$quote "
$set 3 This is the C locale message set
1 "Hello World!"

koichi@server:~/workspace/ksh93-i18n$ cat locale/ja/ksh93-i18n.msg
$quote "
$set 3 This is the ja locale message set
1 "こんにちは世界！"
```
```console
koichi@server:~/workspace/ksh93-i18n$ ./run-on-docker.sh
+ docker build -t ksh93-i18n .
Sending build context to Docker daemon  110.6kB
Step 1/6 : FROM debian:sid
 ---> a7723f2657fb
Step 2/6 : RUN apt-get update && apt-get install -y ksh libc-dev-bin locales-all
 ---> Using cache
 ---> deeb066547da
Step 3/6 : COPY . /root/
 ---> d2c676ac5d5c
Step 4/6 : WORKDIR /root
 ---> Running in 2d8f26743fe5
Removing intermediate container 2d8f26743fe5
 ---> 163ea8b3ffab
Step 5/6 : ENV LANG=C.UTF-8
 ---> Running in 2d566d1bf6cc
Removing intermediate container 2d566d1bf6cc
 ---> 208d3e386af0
Step 6/6 : RUN ./gencat.sh
 ---> Running in 0ae679ec8e4b
+ gencat locale/C/ksh93-i18n.cat locale/C/ksh93-i18n.msg
+ gencat locale/ja/ksh93-i18n.cat locale/ja/ksh93-i18n.msg
Removing intermediate container 0ae679ec8e4b
 ---> 842f7d1e8b63
Successfully built 842f7d1e8b63
Successfully tagged ksh93-i18n:latest
+ docker run --rm -it ksh93-i18n
root@b9fa94a07950:~# LANG=ja_JP.UTF-8 ./ksh93-i18n
Segmentation fault (core dumped)
root@b9fa94a07950:~#
```

**Comment by ko1nksm** [comment]
What I build myself is not translated.

```console
koichi@server:~/workspace/ksh93-i18n$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

koichi@server:~/workspace/ksh93-i18n$ uname -a
Linux server 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

koichi@server:~/workspace/ksh93-i18n$ ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
koichi@server:~/workspace/ksh93-i18n$ LANG=ja_JP.UTF-8 ksh ./ksh93-i18n
こんにちは世界！

koichi@server:~/workspace/ksh93-i18n$ ksh93u+m --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+9bec2b78 2023-01-09
koichi@server:~/workspace/ksh93-i18n$ LANG=ja_JP.UTF-8 ksh93u+m ./ksh93-i18n
Hello World!
```

**Comment by McDutchie** [comment]
I've been unable to reproduce the problem and get a stack trace. Is it possible to make a minimal reproducer that doesn't depend on Docker?

**Comment by ko1nksm** [comment]
My second comment (https://github.com/ksh93/ksh/issues/599#issuecomment-1387016804) is when I ran it without Docker. I have not been able to reproduce the segmentation fault with my own build of ksh93u+m without Docker. However, I am experiencing a issue with not being able to translate it. I am thinking that it is probably a related issue. I ran `bin/package make` to build ksh93u+m.

I first noticed this problem on macOS (without Docker). ksh93u+m was installed via Homebrew. Below is the log.

```console
$ uname -a
Darwin MacBookPro.home 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64

$ ./gencat.sh # Regenerate message catalogs
+ for i in C ja
+ gencat locale/C/ksh93-i18n.cat locale/C/ksh93-i18n.msg
+ for i in C ja
+ gencat locale/ja/ksh93-i18n.cat locale/ja/ksh93-i18n.msg


$ # === Works as expected on original ksh93 on macOS. ===
$ /bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
$ LANG=C /bin/ksh ksh93-i18n
Hello World!
$ LANG=ja_JP.UTF-8 /bin/ksh ksh93-i18n
こんにちは世界！


$ # === Segmentation fault on ksh93u+m ===
$ ksh --version
  version         sh (AT&T Research) 93u+m/1.0.4 2022-10-22
$ LANG=C ksh ksh93-i18n
Hello World!
$ LANG=ja_JP.UTF-8 ksh ksh93-i18n
[1]    49198 segmentation fault  LANG=ja_JP.UTF-8 ksh ksh93-i18n
```

**Comment by ko1nksm** [comment]
The issue seems to be in the commit f38494ea1dd17a8e785cca0b524adb46db71bc08.  ~~I am guessing that changing the third argument of `strgrpmatch` from `int*` to `ssize_t*` may be the cause, but~~ I don't fully understand the code and am struggling.

**Comment by ko1nksm** [comment]
This patch appears to have fixed my issue, but I don't know if it is the right fix.

```diff
diff --git a/src/lib/libast/comp/iconv.c b/src/lib/libast/comp/iconv.c
index fb0096fc..736da407 100644
--- a/src/lib/libast/comp/iconv.c
+++ b/src/lib/libast/comp/iconv.c
@@ -180,7 +180,7 @@ if (error_info.trace < DEBUG_TRACE) sfprintf(sfstderr, "%s: debug-%d: AHA%d _ast
 #if DEBUG_TRACE
 if (error_info.trace < DEBUG_TRACE) sfprintf(sfstderr, "%s: debug-%d: AHA%d _ast_iconv_name n=%d bp=%p cp=%p ccode=%d name=\"%s\"\n", error_info.id, error_info.trace, __LINE__, n, bp, cp, cp->ccode, cp->name);
 #endif
-               if (strgrpmatch(m, cp->match, sub, elementsof(sub) / 2, STR_MAXIMAL|STR_LEFT|STR_ICASE))
+               if (strngrpmatch(m, strlen(m), cp->match, sub, elementsof(sub) / 2, STR_MAXIMAL|STR_LEFT|STR_ICASE))
                {
                        if (!(c = m[sub[1]]))
                        {
```

**Comment by McDutchie** [comment]
Strangely enough, I still cannot reproduce the segfault on my end, even after recompiling ksh with AddressSantizer enabled. So I cannot obtain a stack trace that I could use to begin to analyse the problem.

But your patch (nice find, by the way!) did give me an important clue, as I remembered that `strgrpmatch` is actually defined in terms of `strngrpmatch`, as follows: https://github.com/ksh93/ksh/blob/da74ed6f26ccad2a241a18c3518cbc8c94a7c378/src/lib/libast/string/strmatch.c#L198-L202

So it is equivalent, except that the `STR_INT` bit flag is added. Your patch removes that flag, which seems to be what fixes the problem.

Now if we could figure out exactly *why* not passing the `STR_INT` bit flag fixes it, then I would probably be comfortable committing this.

Although, a quick `grep -r` shows that every other str(n)grpmatch call in this codebase currently explicitly passes the `STR_INT` flag. Which makes me wonder if the following patch might be better:

```diff
diff --git a/src/lib/libast/string/strmatch.c b/src/lib/libast/string/strmatch.c
index 51971d6b8..23d94cfff 100644
--- a/src/lib/libast/string/strmatch.c
+++ b/src/lib/libast/string/strmatch.c
@@ -198,5 +198,5 @@ strsubmatch(const char* s, const char* p, int flags)
 int
 strgrpmatch(const char* b, const char* p, ssize_t* sub, int n, int flags)
 {
-	return strngrpmatch(b, b ? strlen(b) : 0, p, sub, n, flags|STR_INT);
+	return strngrpmatch(b, b ? strlen(b) : 0, p, sub, n, flags);
 }
```

(By the way, my testing shows that ksh2020 (and thus, presumably, ksh 93v- beta) has this same bug. The `STR_INT` bit flag was introduced in f38494ea1dd17a8e785cca0b524adb46db71bc08, the same commit that introduced this bug, and which backported the new `${.sh.match}` from 93v-. So it looks like we backported an AT&T bug.)

**Comment by McDutchie** [comment]
> Now if we could figure out exactly _why_ not passing the `STR_INT` bit flag fixes it, then I would probably be comfortable committing this.

That seems fairly simple. In strngrpmatch(): https://github.com/ksh93/ksh/blob/da74ed6f26ccad2a241a18c3518cbc8c94a7c378/src/lib/libast/string/strmatch.c#L96-L103 So, `STR_INT` simply means that the fourth argument, `sub`, refers to an array of `int` elements instead of `ssize_t`. Those are not the same size; on my system, sizeof(int)==4 and sizeof(ssize_t)==8. In `_ast_iconv_name` in iconv.c, `sub` is an array of `ssize_t` but the `STR_INT` flag was incorrectly passed. This explains the bug.

**Comment by McDutchie** [comment]
`ccmapid()` in string/ccmapid.c has the same bug: https://github.com/ksh93/ksh/blob/da74ed6f26ccad2a241a18c3518cbc8c94a7c378/src/lib/libast/string/ccmapid.c#L139-L144 – `sub` is of type `ssize_t` but `STR_INT` is implicitly passed via `strgrpmatch`.

**Comment by McDutchie** [comment]
I had a difficult time converting the reproducer into a regression test. After some hours I figured out that the messages are only found if the catalog name (the *.cat file name minus .cat) is identical to the complete file name part of $0. When you call a ksh syntax function, $0 changes to the function name, so it looks for *functionname*.cat instead of *scriptname*.cat.

**Comment by ko1nksm** [comment]
What the hell! 😖

**Comment by McDutchie** [comment]
> After some hours I figured out that the messages are only found if the catalog name (the *.cat file name minus .cat) is identical to the complete file name part of $0.

Hmm. This is due to the `%N` in `NLSPATH`. If that is replaced by a hardcoded file name, that is found instead. Good.

**Comment by McDutchie** [comment]
The bug seems to have been the result of a confusion surrounding an API transition from `int` to `ssize_t`. In the 93v- beta, we find two versions of the function, both of which are sensible, and which one was used depended on the API version in use:
* [new ssize_t version, does not pass STR_INT](https://github.com/ksh93/ksh93-history/blob/e788d536e001675ba8c52e3cba4f185f435e6f85/src/lib/libast/string/strmatch.c#L169-L173)
* [old int version, passes STR_INT](https://github.com/ksh93/ksh93-history/blob/e788d536e001675ba8c52e3cba4f185f435e6f85/src/lib/libast/string/strmatch.c#L207-L211)

What ended up backported was a new version that passed STR_INT like the old version, which is incorrect. So this is not an AT&T bug after all. (I don't know why the reproducer fails on ksh2020 then.)
