### ISSUE TITLE
Restore nmake, make it build

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#60]
I get it, ksh93/ksh doesn't have nmake.  Thus:

```
[ 7:59 AM][ttys000][../src/ksh]
iMac $ bin/package write tgz source ksh   
package: must have nmake to generate archives
[ 8:00 AM][ttys000][../src/ksh]
iMac $ bin/package write tgz binary ksh
package: must have nmake to generate archives
```

So... how is it done now?  If there's something obvious I should have seen in 'package --man', feel free to point it out.

(There was a posting on the Korn Shell list that I have to find again, that made it sound like it was terribly easy to bring nmake back... have to find that again)

**Comment by posguy99** [comment]
Hmmm... found the reference on the Korn Shell list:

https://groups.google.com/d/msg/korn-shell/ugnRKBn9PY0/KWBWl0cJBQAJ

But it doesn't work, I can't build the ast repo, it blows up trying to build libast (I think) and thus can't build nmake.

(macOS 10.14.6)

**Comment by McDutchie** [comment]
I'm on macOS 10.14.6 as well. Restoring nmake from the git history is on my to-do list. The simple and obvious way to do that is:
```sh
git checkout reboot~1 src/cmd/nmake src/cmd/probe src/lib/libardir
```
That gets nmake to build, but the build then breaks further on, at least on macOS. At some point I'll make a serious effort to figure out how to do this and fix the build.

The original AST repo doesn't build on macOS at all (with or without nmake) so it's not surprising the solution proposed in the link doesn't work. Even if it did, I don't think that's a real solution. No one has nmake preinstalled, so it really needs to come as part of the source tree if it is to work for everyone.

Meanwhile, for binary packages at least, all you really need is `arch/*/bin/ksh` and `src/cmd/ksh93/sh.1` and those are pretty trivial to just copy into a package tree manually. And the source is just a `git clone` away. So I haven't seen the packaging functionality as a very high priority so far. But it should all start working again when nmake is eventually restored to working order.

**Comment by posguy99** [comment]
Where I was headed was munging the ksh93 portfile to be able to install ksh93/ksh.  It grabs INIT and ast-ksh from MacPorts distfiles and builds it, but there are no such packages ATM for ksh93/ksh.  I was going to create a local portfile and a local repository for the files.

Not that I still can't, but it will get much more complicated.  It could grab the git repo, or I could have some monster patch file diff (man, *that* would be brittle).

**Comment by McDutchie** [comment]
You can download a tarball of the current git code directly from github, like:
```sh
curl -L -o ksh-master.tar.gz https://github.com/ksh93/ksh/archive/master.tar.gz
```
and that is a functional source archive, you can just `cd ksh-master && bin/package make`.

**Comment by posguy99** [comment]
I've gone back through old emails, and I don't get it.  You started over from att/ast, what removed nmake, anyway?

**Comment by McDutchie** [comment]
Commit 2940b3f5367c127e48f10e23a47b38e8d0b8007f (also tagged `reboot`) did that. Since some of the extra stuff still doesn't build on macOS (and in any case it didn't build with nmake), the quickest way to get on with fixing ksh was to start out by removing all the stuff that the ksh-community fork did. But because this is now forked off of the ast repo, it's all still in the git history, so it's restorable if a way can be figured out to make it build.

**Comment by JohnoKing** [comment]
I can get nmake to fully build ksh on FreeBSD and (with GCC only) Linux using the following commands:
```sh
git checkout reboot~1 src/cmd/cpp src/cmd/nmake src/cmd/probe src/lib/libardir src/lib/libpp
bin/package make ast-ksh CCFLAGS='-O2 -fPIC'
```

**Comment by McDutchie** [comment]
Thanks @JohnoKing, how did you figure out those dependencies?

Unfortunately that still doesn't make it build on my Mac. I get a huge amount of warnings about redefined macros, then a build failure in libcmd/id.c due to an undefined `NGROUPS_MAX` macro. [Here is the build log](https://www.inlv.org/tmp/make.out). I won't have time to seriously look in to that any time soon, so maybe you or someone else can make something of it?

**Comment by JohnoKing** [comment]
I can replicate the `NGROUPS_MAX` build error on Linux when building with Clang 10. att/ast#86 has a hack that works around it.

> Thanks @JohnoKing, how did you figure out those dependencies?

I reintroduced everything from the ast repo, then removed anything that wasn't required to build nmake and ksh through process of elimination.

**Comment by McDutchie** [comment]
Applying the linked hack and running `USE_CLANG=yes CC=clang bin/package make ast-ksh` still fails for me, but differently. [Build log here](https://www.inlv.org/tmp/make2.out). It seems like it fails before ever reaching libcmd, the previous point of failure. The apparent culprit is a syntax error in comp/memccpy.c, but the syntax error in that file looks fine, so probably some macro is messing things up. &lt;shrug>

**Comment by McDutchie** [comment]
Restoring nmake became a lot more complicated after I removed libcoshell (3613da4240b82023b6861af08b57c2c426248766) and 3dfs (fbc6cd42866db7c6dcc46247c99e79076c5172ec); turns out nmake depends on both in ways that cannot easily be disentangled.

So I made an [experimental branch](/ksh93/ksh/tree/nmake_experimental) with nmake restored.

So far it is confirmed:
* to build on Solaris using Solaris Studio or gcc, on HP-UX using gcc, and on Linux using gcc;
* *not* to build on any system using clang.

----

One really mysterious regression pops up when you build with nmake:
```
test leaks begins at 2020-08-21+03:02:15
	leaks.sh[146]: memory leak on PATH reset before subshell PATH search (leaked 142112 bytes after 512 iterations)
test leaks failed at 2020-08-21+03:02:15 with exit code 1 [ 15 tests 1 error ]
```
This leak had been fixed in 361fe1fcc3097568b08d63a5ba3f979eee17c408. ~~But building with nmake somehow makes that fix ineffective!~~ Any ideas anyone?

*edit:* The fix is not actually ineffective; if you revert it, the memory leak grows. So there is a different memory leak being triggered by building with nmake.

**Comment by benalt613** [comment]
I'd like to see this compile on Cygwin on Windows.

**Comment by McDutchie** [comment]
At this point I don't think nmake is going to happen. There is no one who is interested in debugging the problems with it in the nmake test branch. It requires libcoshell, which is disused and suffers from bit rot.

I think the way forward will be to replace nmake/mamake with a widely used and installed make utility, probably GNU make. It will require translating the Makefiles and/or Mamfiles, then changing the package scripts to invoke a different make utility. Should not be too radical or difficult.

**Comment by McDutchie** [comment]
On the other hand, further experimentation shows that the Mamfile format is actually not that difficult to understand. It's a bit like assembly language. There are very few commands, and mamake.c is very small, so we can probably figure out and document everything.

One thing that would improve it would be to allow indentation -- that could drastically increase the readability of the Mamfiles. They use make...done blocks, but now it's very hard to see where they begin and end.

**Comment by McDutchie** [comment]
Adding support for Mamfile code indentation to mamake is very easily achieved with this diff:
```diff
diff --git a/src/cmd/INIT/mamake.c b/src/cmd/INIT/mamake.c
index ccda9cd..1a0bcc6 100644
--- a/src/cmd/INIT/mamake.c
+++ b/src/cmd/INIT/mamake.c
@@ -1129,7 +1129,10 @@ input(void)
 	else if (*state.input && *(e = state.input + strlen(state.input) - 1) == '\n')
 		*e = 0;
 	state.sp->line++;
-	return state.input;
+	e = state.input;
+	while (isspace(*e))
+		e++;	/* allow indentation */
+	return e;
 }
 
 /*
```

**Comment by McDutchie** [comment]
And here's a simple script that will automatically indent a Mamfile. Since make...done is the only kind of block supported, it's easy to do. It's amazing how much more readable that makes these files -- this is something we could work with!
```sh
#!/usr/bin/env ksh
# usage: ksh Mamfile_indent.ksh <Mamfile >Mamfile.new
IFS=''; set -fCu  # safe mode
indent=0
sed 's/^[[:space:]]*//' |
while	read -r line
do	[[ $line == done* ]] && let indent--
	for ((i=0; i<indent; i++))
	do	print -n $'\t'
	done
	print -r $line
	[[ $line == make* ]] && let indent++
done
```

**Comment by McDutchie** [comment]
> On the other hand, further experimentation shows that the Mamfile format is actually not that difficult to understand. It's a bit like assembly language. There are very few commands, and mamake.c is very small, so we can probably figure out and document everything.

Or, we could just read Glenn Fowler's paper on the subject, that documents everything:

http://web.archive.org/web/20130615145159/http://www2.research.att.com/~gsf/mam/mam.html
