### ISSUE TITLE
ksh93 should stop dumping core when a process kills itself

### ISSUE THREAD

**Issue by tapas118** [ksh93/ksh#600]
When a ksh script executes a program and that particular program dies because of signal,
ksh will then die in the same way, including a core dump.

If you run the following script: with the argument -SEGV
you would get TWO core dumps, one from "sh" (also ksh)
because of the kill and then the original script which kills
itself with the same signal. Same happens when you use
-ABRT

Script details:-

#!/bin/sh

sh -c 'kill '$1' $$'

===========

KSH version:-
=============
root@admin-:/var/cores# print ${.sh.version}
Version AJM 93u+m/1.0.4 2022-10-22
root@admin-:/var/cores#

BT of cores:-
============
root@admin-:/var/cores# /usr/bin/pstack core.sh.0.1674470385
core 'core.sh.0.1674470385' of 7294:    sh -c kill -ABRT $$
 0007ff77a5fc9534 kill (0x100300250?, 0x6?, 0x100000?, 0x100300?, 0x1002c5228?, 0x10009db40?) + 8
 000000010009d184 job_walk (0x1?, 0x10009db50?, 0x6?, 0x100300250?, 0x7ff77a6634b21?, 0x1c7e?) + 324
 0000000100103b64 b_kill (0x6?, 0x1002c9000?, 0x100000?, 0x100000?, 0x1002c49e8?, 0x10009d?) + 524
 00000001000e4454 sh_exec (0x1002c49e8?, 0x0?, 0x7ff77a6634a90?, 0x5?, 0x7ff77a6634a81?, 0x1002c4ea8?) + 30a4
 0000000100065940 exfile (0x4?, 0x0?, 0xffffffff?, 0x1002c49e8?, 0x14?, 0x7ff77a663e1e0?) + 8d0
 0000000100065048 sh_main (0x100305000?, 0x0?, 0x840000200001?, 0x10001f?, 0x1002c49e8?, 0x10001f000?) + af8
 000000010006445c main (0x3?, 0xfffffffa29e0c378?, 0xfffffffa29e0c398?, 0x10000?, 0x400000000?, 0x4?) + 3c
 00000001000643f0 _start (0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x1002c2000?) + 110
root@admin-:/var/cores#
root@admin-:/var/cores#
root@admin-:/var/cores# /usr/bin/pstack core.ksh.0.1674470385
core 'core.ksh.0.1674470385' of 7292:   /bin/ksh ./test5.ksh -ABRT
 0007fda9553c9534 kill (0x1002c49e8?, 0x6?, 0x0?, 0x100000?, 0x1002c4000?, 0x6?) + 8
 0000000100065054 sh_main (0x100305000?, 0x3?, 0x840000000000?, 0x10001f?, 0x1002c49e8?, 0x10001f000?) + b04
 000000010006445c main (0x3?, 0xfffffff3c33add68?, 0xfffffff3c33add88?, 0x10000?, 0x400000000?, 0x4?) + 3c
 00000001000643f0 _start (0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x1002c2000?) + 110
root@admin-:/var/cores#

**Comment by tapas118** [comment]
Once again I have reverify the above test scenario and can see only one core dump for bash which is expected.

**Comment by McDutchie** [comment]
I can reproduce the problem if an original AT&T ksh 93u+ is used in the hashbang path of the test script instead of my system's /bin/sh.  This may be the bug that was fixed in b3050769ea281f5ff49feed6d4b1354e8db5d68a and 4df6d674a08c7ca92e70e2c44b9ebd3756071719.
