### ISSUE TITLE
`printf -v %B` overwrites/truncates data

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#608]
Reproducer:
```
typeset  -b foo
read -N8 foo <<<abcdefghijklmnop
printf -v got '%s / %B\n' "$foo" foo
print -rn "$got"
```

Expected output:
```
YWJjZGVmZ2g= / abcdefgh
```

Actual output:
```
YWJjZGVm
```

When `printf -v got '%s / %B\n' "$foo" foo` is replaced by `got=$(printf '%s / %B\n' "$foo" foo)`, the bug does not occur.

Two observations:
* The `%B` (which converts back from base64) overwrote the results of `%s / `. Except, the final newline (`\n') is not overwritten.
* The output was truncated to 8 characters, which was the length passed to `read -N`. If you change the length passed to `read -N`, the length of the output changes accordingly.

So, there must be some kind of state leakage going on.

**Comment by hyenias** [comment]
More notes:
```ksh
# Flipping the printf format codes results in correct output
$ printf -v got '%B / %s\n' foo "$foo"; typeset -p foo got
typeset -b foo=YWJjZGVmZ2g=
got=$'abcdefgh / YWJjZGVmZ2g=\n'

$ printf -v got "%B / $foo\n" foo; typeset -p foo got
typeset -b foo=YWJjZGVmZ2g=
got=$'abcdefgh / YWJjZGVmZ2g=\n'
```

**Comment by McDutchie** [comment]
ksh2020 shares this bug, so there's no fix to backport from 93v- or 2020.

**Comment by JohnoKing** [comment]
I've found out that this bug is caused by `printf -v` and `%B` both making use of `sh.strbuf2`:
https://github.com/ksh93/ksh/blob/3de9b461b1711057001b4a85b515185523d6ad70/src/cmd/ksh93/bltins/print.c#L308-L314
https://github.com/ksh93/ksh/blob/3de9b461b1711057001b4a85b515185523d6ad70/src/cmd/ksh93/bltins/print.c#L1019-L1025

Simply making `-v` use `sh.strbuf` instead avoids the bug. The patch below seems to work and all regression tests pass, although I'm not sure if the patch has unintended side effects of its own:
```diff
diff --git a/src/cmd/ksh93/bltins/print.c b/src/cmd/ksh93/bltins/print.c
index b6e321f70..614a26626 100644
--- a/src/cmd/ksh93/bltins/print.c
+++ b/src/cmd/ksh93/bltins/print.c
@@ -307,9 +307,9 @@ skip:
 		argv++;
 	if(vname)
 	{
-		if(!sh.strbuf2)
-			sh.strbuf2 = sfstropen();
-		outfile = sh.strbuf2;
+		if(!sh.strbuf)
+			sh.strbuf = sfstropen();
+		outfile = sh.strbuf;
 		goto printf_v;
 	}
 skip2:

```

**Comment by McDutchie** [comment]
Nice catch. That makes complete sense of the bug. Before committing this we should verify if something else uses sh.strbuf in a way that might conflict.

Side note: unlike sh.strbuf2, sh.strbuf is [unconditionally opened at init time](https://github.com/ksh93/ksh/blob/3de9b461b1711057001b4a85b515185523d6ad70/src/cmd/ksh93/sh/init.c#L1286), so doesn't need to be opened before use.

**Comment by McDutchie** [comment]
sh.strbuf is used in extend() in a way that could conflict with the patch above.

So I thought maybe %B could use sh.strbuf instead of sh.strbuf2. And that does fix the bug, too. But the `case 'B':` code in extend() calls fmtbase64() which calls nv_getval() which uses sh.strbuf. 

I haven't found direct triggers for those conflicts but I'm sure they must be there. printf has many formatting operators which many code paths to various parts of the shell. Even if there is no conflict now, one could easily arise with future code changes.

So, to be safe, it seems we just have to use a dedicated Sfio string buffer for `printf -v`. It's a trivial change. Using a locally scoped static stream pointer (which is auto-initialised to NULL) means we only have to open the buffer stream on first use.

New patch:

```diff
diff --git a/src/cmd/ksh93/bltins/print.c b/src/cmd/ksh93/bltins/print.c
index cbb6f0f39..ae02a5fde 100644
--- a/src/cmd/ksh93/bltins/print.c
+++ b/src/cmd/ksh93/bltins/print.c
@@ -307,9 +307,10 @@ skip:
 		argv++;
 	if(vname)
 	{
-		if(!sh.strbuf2)
-			sh.strbuf2 = sfstropen();
-		outfile = sh.strbuf2;
+		static Sfio_t *vbuf;
+		if(!vbuf)
+			vbuf = sfstropen();
+		outfile = vbuf;
 		goto printf_v;
 	}
 skip2:
```

**Comment by McDutchie** [comment]
A more efficient alternative: write the value onto the AST stack (see `man src/lib/libast/man/stk.3`) instead. The value on the stack won't linger around occupying memory after the command has finished, because [the stack gets reset](https://github.com/ksh93/ksh/blob/3de9b461b1711057001b4a85b515185523d6ad70/src/cmd/ksh93/sh/xec.c#L2656-L2662) in sh_exec() after executing each command – whereas a dedicated string buffer for `printf -v` won't be reset until `printf -v` is used again. This could make a significant difference if it is used for formatting large values.

```diff
diff --git a/src/cmd/ksh93/bltins/print.c b/src/cmd/ksh93/bltins/print.c
index cbb6f0f39..c0a07556f 100644
--- a/src/cmd/ksh93/bltins/print.c
+++ b/src/cmd/ksh93/bltins/print.c
@@ -307,9 +307,7 @@ skip:
 		argv++;
 	if(vname)
 	{
-		if(!sh.strbuf2)
-			sh.strbuf2 = sfstropen();
-		outfile = sh.strbuf2;
+		outfile = sh.stk;
 		goto printf_v;
 	}
 skip2:
@@ -388,7 +386,7 @@ printf_v:
 				exitval = 1;
 	}
 	if(vname)
-		nv_putval(vname, sfstruse(outfile), 0);
+		nv_putval(vname, stkfreeze(sh.stk,1), 0);
 #if !SHOPT_SCRIPTONLY
 	else if(sflag)
 	{
```

This is less safe than the previous patch because it assumes that nothing else will write to the stack before the `printf` operation has completed. But since the efficiency gains are potentially significant, I'd be interested to see if any breakage with this patch can be found.

**Comment by McDutchie** [comment]
> But since the efficiency gains are potentially significant, I'd be interested to see if any breakage with this patch can be found.

Found breakage. The shell quoting routine sh_fmtq() writes quoted values to the stack, which conflicts with the patch using the stack. With the above patch:

```
$ arch/*/bin/ksh -c 's="one two"; printf -v foo "%q / %q / %q" "$s" "$s" "$s"; echo "$foo"'
'one two'
```

Correct behaviour (including with the second-to-last patch above):

```
$ ksh -c 's="one two"; printf -v foo "%q / %q / %q" "$s" "$s" "$s"; echo "$foo"'                    
'one two' / 'one two' / 'one two'
```

So, dedicated Sfio buffer it is.
