### ISSUE TITLE
Parsing bug in definition of custom arithmetic functions

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#623]
So far undocumented, except in the `RELEASE` file, is this functionality (`RELEASE` claims it was introduced on 2010-03-24 but it appears in ksh93-history on 2010-06-25, and it doesn't actually start being usable until 2010-10-10):
```
10-03-24 +Arithmetic functions can be defined using the shell function syntax,
	  'function .sh.math.name x y z{...}' , where name is the function name
	  invoked within ((...)) and x y z are long double arguments passed
	  as name references.  y and z are used for functions with two and
	  three arguments respectively.  The value of the function is the value
	  of the long double .sh.value variable when the function returns.
```

Example:

```sh
function .sh.math.inc i {
        .sh.value=i+1;
}
echo $((inc(2)))
```

Output: 3. So far, so good. But:

```sh
function .sh.math.inc i { .sh.value=i+1; }
echo $((inc(2)))
```

Output: 
```
arith.sh[2]: .sh.math.inc[1]: .sh.value=i+1: not found
```

When the function is defined on one line, the assignment is not recognised and ksh tries to execute it as a command.

**Comment by phidebian** [comment]
Actually 1liner can work

````
TC$ function .sh.math.a b { .sh.value=b+1; } ; echo $((a(1)))  
ksh: .sh.math.a: line 1: .sh.value=b+1: not found
nan

TC$ function .sh.math.a b { : ; .sh.value=b+1; } ; echo $((a(1)))
2
````

I think there is a bug regarding .sh.var assignment as first statement after a {
I don't know any writable .sh.var but if it was possible to get one I think
````
function a { .sh.b=c; } 
````
Would fail the same way.

When doing 
````
function x a b c {
````
after the `{` a `\n` or an identifier (var name) will setup the assignok flag, but a `.` as in `.sh.var` will go in a path where we miss the setup of this flag, then making the assignment a command `a=b command not found`

By forcing assignok in parse.c::921 funct()
````
		lexp->assignok=1; /* Issue#623 Phi */
  		t->funct.functtre = item(lexp,SH_NOIO);
````
We ensure we accept assignment right away, this kind preset it for the other case who will re-set it, i.e after '\n' or `:;` in the example.

I propose this patch https://github.com/phidebian/ksh/tree/bug-623
I pushed a PR https://github.com/ksh93/ksh/pull/624

**Comment by McDutchie** [comment]
This also works:
```
function .sh.math.a b { ((.sh.value=b+1)); } ; echo $((a(1)))
```
It is only the shell assignment syntax that is broken.
