### ISSUE TITLE
macOS Ventura detects termcap support, not terminfo support

### ISSUE THREAD

**Issue by pghvlaans** [ksh93/ksh#635]
I'm not positive whether this is a bug or not (not a macOS expert), but it doesn't seem right. Using e.g. ~~`tput up` throws an error, while~~ `/usr/bin/tput cuu1` is fine. This would suggest that the system is using `terminfo` rather than `termcap`.

EDIT: My system has `/opt/local/bin/tput`, which doesn't support `termcap`. So in fact, it should probably register as supporting both, since `/usr/bin/tput` does and that's what shows up as `_pth_tput`. Is this just a peculiarity of my system?

**Comment by pghvlaans** [comment]
Apparently `/usr/bin/tput ed` and `/usr/bin/tput rmdc` both return `1`. According to `tput(1)`, however: 

```
This  implementation  (unlike  others) can accept both termcap and terminfo names for the
       capname feature, if termcap support is compiled in.  However, the predefined termcap  and
       terminfo names have two ambiguities in this case (and the terminfo name is assumed):

       •   The termcap name dl corresponds to the terminfo name dl1 (delete one line).
           The  terminfo  name  dl  corresponds to the termcap name DL (delete a given number of
           lines).

       •   The termcap name ed corresponds to the terminfo name rmdc (end delete mode).
           The terminfo name ed corresponds to the termcap name cd (clear to end of screen).
```

**Comment by McDutchie** [comment]
So, looks like `/usr/bin/tput` on macOS is broken. For our purposes, it works correctly with termcap codes but not with terminfo codes, so ksh is right to detect termcap and not terminfo. I don't see a bug on our end here...

**Comment by pghvlaans** [comment]
Indeed.
