### ISSUE TITLE
${var+set} still does not work correctly within loops

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#637]
This is a variant of att#70 that is still in current 93u+m. Reproducer:

```sh
unset -v var
for i in 1 2 3 4 5; do
        case ${var+s} in
        ( s )   echo set; unset -v var;;
        ( '' )  echo unset; var.get() { : ; };;
        esac
done
```

Actual output:

```
unset
unset
unset
unset
unset
```

Expected output (and actual output when ksh is recompiled with `SHOPT_OPTIMIZE` disabled in SHOPT.sh):

```
unset
set
unset
set
unset
```

When a .get discipline function definition is used to set the variable instead of an assignment, the loop invariants optimizer causes incorrect results.

I am wondering if the `SHOPT_OPTIMIZE` code should be removed instead of spending more time hunting down bugs with it. Here are the results of a 50-iteration [shbench](http://fossil.0branch.com/csb/doc/trunk/README.md) run on a ksh 93u+m/1.0.5beta compiled with `SHOPT_OPTIMIZE` enabled (`ksh_opt`) and disabled (`ksh_noopt`) on my 2021 MacBook Pro (Apple M1 CPU). Default compiler optimisation (`-Os`) was used for both binaries.

```
---------------------------------------------------------
name             ./ksh_opt            ./ksh_noopt
---------------------------------------------------------
braces.ksh       0.154 [0.152-0.165]  0.157 [0.155-0.162]
charsplit.ksh    0.324 [0.321-0.333]  0.325 [0.322-0.335]
extglob.ksh      0.202 [0.200-0.207]  0.201 [0.200-0.208]
fibonacci.ksh    0.154 [0.152-0.160]  0.159 [0.157-0.162]
gsub.ksh         0.169 [0.167-0.170]  0.169 [0.167-0.173]
hanoi.ksh        0.183 [0.180-0.186]  0.185 [0.181-0.187]
numfor.ksh       0.409 [0.406-0.414]  0.415 [0.411-0.425]
numloop.ksh      0.224 [0.222-0.231]  0.230 [0.225-0.239]
parens.ksh       0.265 [0.261-0.273]  0.267 [0.263-0.275]
piln2.ksh        0.504 [0.496-0.515]  0.516 [0.508-0.539]
plus-equals.ksh  0.484 [0.479-0.495]  0.482 [0.477-0.490]
printf.ksh       0.326 [0.323-0.329]  0.335 [0.332-0.345]
qsort.ksh        0.565 [0.542-0.596]  0.557 [0.523-0.601]
rand.ksh         0.336 [0.329-0.370]  0.356 [0.342-0.392]
rand2.ksh        0.253 [0.247-0.290]  0.252 [0.250-0.256]
sample.ksh       0.458 [0.452-0.466]  0.459 [0.455-0.470]
shuffle.ksh      0.327 [0.324-0.342]  0.330 [0.328-0.332]
sieve.ksh        0.300 [0.298-0.311]  0.301 [0.299-0.306]
---------------------------------------------------------
```

By the looks of it, the overall performance difference is somewhere between insignificant and nonexistent. Can anyone find a use case where the loop variants optimizer actually makes an appreciable performance difference?

Ping @hyenias, @JohnoKing, @jghub

**Comment by hyenias** [comment]
I thought to myself do I have a long running ksh program that is ksh intensive with lots of looping. Sure do. Enter the Game of Life. Can you guess which was faster: ksh's standard loop variant or ksh without it?

I have a two versions of Game of Life. I ran them on my little Cortex A53 x 4 box (gillian) having comparatively much smaller L1-3 caches and has in-order processors compared to your superb massively out-of-order processors with caches several times larger.

Here are the results for a real world ksh program of Game of Life using a seed colony for repeatable results.
```
$ ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+641191e5/MOD 2023-04-09

# This version of GoL uses float operations and 2d arrays
$ ksh life1.ksh
tick   820   0.497 sec  avg  0.561 sec 244x64
Elapsed time: 460.2608449459
$ ksh637 life1.ksh
tick   820   0.480 sec  avg  0.543 sec 244x64
Elapsed time: 445.6459848881

# This version of GoL uses more string operations with 1d arrays
$ ksh lifenew.ksh
  Evolutions: 308
  Total time: 128.406791
  Average time: 0.416823
$ ksh637 lifenew.ksh
  Evolutions: 308
  Total time: 125.405626
  Average time: 0.407084
```
The winner goes to ksh637 compiled with SHOPT_OPTIMIZE=0. It is %2-3 faster for my versions of Game of Life.
460.2608449459/445.6459848881 = 1.0327947755693787
128.406791/125.405626 = 1.0239316615667626

**Comment by hyenias** [comment]
I got shbench working on gillian test box to compare by installing `apt install rs athena-jot` on this Debian 11 machine. shbench micro benchmarks varied. All-in-all, after working with shbench the only concerned benchmark for me was the printf test. When I looked into this micro benchmark, it just prints out one line in a for loop using numbers.

I then altered this one line printf test to use echo and print to compare. ksh637 was faster using echo and print but slower when using this particular printf format string as noted above. I would rather have echo and print run faster.

**Comment by McDutchie** [comment]
There is a clear performance difference if you only measure invariant variable expansion within loops. The following is on my MacBook M1 (arm64) laptop and ksh compiled with `-Os`.

With `SHOPT_OPTIMIZE` disabled (set to 0) in `SHOPT.sh`:

```
$ arch/darwin.arm64-64/bin/ksh -c 'typeset -i i; foo=bar; time for((i=0;i<10000000;i++)); do : $foo $foo $foo; done'                 

real	0m06,649s
user	0m06,162s
sys	0m00,486s

```

With `SHOPT_OPTIMIZE` re-enabled:

```
$ arch/darwin.arm64-64/bin/ksh -c 'typeset -i i; foo=bar; time for((i=0;i<10000000;i++)); do : $foo $foo $foo; done'

real	0m02,855s
user	0m02,378s
sys	0m00,475s
```

**Comment by McDutchie** [comment]
Meanwhile I seem to have found a fix. When defining a discipline function, we need to clear out the saved optimization values for the variable in question. This patch moves the code that does that from `nv_unref` to its own `nv_optimize_clear` function so that it can be called from `nv_setdisc`, which sets the discipline function.

There is also a tweak to the loop to find the getval/getnum discipline in `nv_optimize`. It is used to disable optimization if a getval/genum discipline is set. That loop breaks when `OPTIMIZE_disc` is found, but that means it won't find any getval/genum disciplines set after the optimize discipline. Instead, assign the appropriate variable (xp) without breaking the loop. I have not found any bugs that this may fix, but the current code looks incorrect and the fix doesn't cause regressions either. If anything the fix may prevent future problems.

<details><summary>Patch</summary>

```diff
diff --git a/src/cmd/ksh93/include/name.h b/src/cmd/ksh93/include/name.h
index 74684894f..61a8194f1 100644
--- a/src/cmd/ksh93/include/name.h
+++ b/src/cmd/ksh93/include/name.h
@@ -182,7 +182,10 @@ extern int		nv_arraysettype(Namval_t*, Namval_t*,const char*,int);
 extern int		nv_aimax(Namval_t*);
 extern int		nv_atypeindex(Namval_t*, const char*);
 extern void		nv_setlist(struct argnod*, int, Namval_t*);
-extern void 		nv_optimize(Namval_t*);
+#if SHOPT_OPTIMIZE
+    extern void		nv_optimize(Namval_t*);
+    extern void		nv_optimize_clear(Namval_t*);
+#endif /* SHOPT_OPTIMIZE */
 extern void		nv_outname(Sfio_t*,char*, int);
 extern void 		nv_unref(Namval_t*);
 extern void		_nv_unset(Namval_t*,int);
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 633fc6464..29a32bc91 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -2543,6 +2543,19 @@ static void optimize_clear(Namval_t* np, Namfun_t *fp)
 	}
 }
 
+void nv_optimize_clear(Namval_t *np)
+{
+	Namfun_t *fp;
+	for(fp = np->nvfun; fp; fp = fp->next)
+	{
+		if(fp->disc == &OPTIMIZE_disc)
+		{
+			optimize_clear(np,fp);
+			return;
+		}
+	}
+}
+
 static void put_optimize(Namval_t* np,const char *val,int flags,Namfun_t *fp)
 {
 	nv_putv(np,val,flags,fp);
@@ -2559,7 +2572,7 @@ const Namdisc_t OPTIMIZE_disc  = {sizeof(struct optimize),put_optimize,0,0,0,0,c
 void nv_optimize(Namval_t *np)
 {
 	Namfun_t *fp;
-	struct optimize *op, *xp;
+	struct optimize *op, *xp = 0;
 	if(sh.argaddr)
 	{
 		if(np==SH_LINENO)
@@ -2575,9 +2588,9 @@ void nv_optimize(Namval_t *np)
 				return;
 			}
 			if(fp->disc == &OPTIMIZE_disc)
-				break;
+				xp = (struct optimize*)fp;
 		}
-		if((xp= (struct optimize*)fp) && xp->ptr==sh.argaddr)
+		if(xp && xp->ptr==sh.argaddr)
 			return;
 		if(xp && xp->next)
 		{
@@ -2625,8 +2638,6 @@ void sh_optclear(void *old)
 	sh.optlist = old;
 }
 
-#else
-#   define	optimize_clear(np,fp)
 #endif /* SHOPT_OPTIMIZE */
 
 /*
@@ -3487,17 +3498,7 @@ void nv_unref(Namval_t *np)
 	free(np->nvalue.nrp);
 	np->nvalue.cp = sh_strdup(nv_name(nq));
 #if SHOPT_OPTIMIZE
-	{
-		Namfun_t *fp;
-		for(fp=nq->nvfun; fp; fp = fp->next)
-		{
-			if(fp->disc == &OPTIMIZE_disc)
-			{
-				optimize_clear(nq,fp);
-				return;
-			}
-		}
-	}
+	nv_optimize_clear(nq);
 #endif
 }
 
diff --git a/src/cmd/ksh93/sh/nvdisc.c b/src/cmd/ksh93/sh/nvdisc.c
index c1b49ca6e..fcb824ab2 100644
--- a/src/cmd/ksh93/sh/nvdisc.c
+++ b/src/cmd/ksh93/sh/nvdisc.c
@@ -570,6 +570,9 @@ char *nv_setdisc(Namval_t* np,const char *event,Namval_t *action,Namfun_t *fp)
 		else if(type==LOOKUPN)
 			dp->getnum = lookupn;
 		vp->disc[type] = action;
+#if SHOPT_OPTIMIZE
+		nv_optimize_clear(np);
+#endif
 	}
 	else
 	{
```
</details>
