### ISSUE TITLE
Intermittent types test failure on Debian 11 aarch64 box 

### ISSUE THREAD

**Issue by hyenias** [ksh93/ksh#661]
I just found an intermittent error occurring on the types(C.UTF-8) test on my Debian 11 aarch64 box. Commit a0c104f32bcf39b4d9884574a911a8edff2afc2b introduced the trouble.
```
gillian:/tmp/ksh$ for ((n=0, i=0; i<10; i++)); do bin/shtests -u types || (( ++n )); done; printf 'Failed %i out of %i\n' $n $i
...
#### Regression-testing /tmp/ksh/arch/linux.arm64-64/bin/ksh ####
test types(C.UTF-8) begins at 2023-06-11+20:27:53
	types.sh[552]: FAIL: typeset -p of nested type not correct (expected 'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(a=hello))));)', got $'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(a=\'\'))));)')
test types(C.UTF-8) failed at 2023-06-11+20:27:54 with exit code 1 [ 100 tests 1 error ]
Total errors: 1
...
Failed 7 out of 10
```

**Comment by McDutchie** [comment]
Mysterious. I've got the types.sh tests running in an infinite loop on that very same box (thanks for continuing to provide access, by the way) and I cannot reproduce the error after hundreds of tries.

How did you conclude that that commit caused the trouble?

**Comment by hyenias** [comment]
Interesting. I just ran the `bin/shtests types` via the last compile which is left sitting there on /tmp/ksh. Next, I just git checkout each commit starting at the next point higher up in the listing from the 39th ksh version I saved until I got fails again.

When I test a new HEAD commit, I log in and go to ~/bin then copy my last working ksh file to kshold## file via `mv ~/bin//ksh ~/bin/kshold44` for instance. My last old file is kshold41 at the moment. I then go into the appropriate ksh93 git directory and perform a git pull. I then `cp -rp ksh /tmp`. `cd /tmp/ksh`. `bin/package make`. `bin/shtests`. `cp arch/*/bin/ksh ~/bin`.

During today's git commit compile, I came across this error. So, I ran it again and it passed. Then I ran it again but it failed. Then I tried it 10-30 times by hand using the up arrow on `bin/shtests types` and it failed more times. So, I then just starting working backwards from my most recent kshold file to see when the last time it did not produce an error. kshold41 failed, kshold40 failed, kshold39 passed. So between my 39th version and 40th version something happened. I just started at the beginning of the month on the commits and worked towards the 40th version.

```
gillian:/tmp/ksh$ kshold41 --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+1faf04d5 2023-06-02
gillian:/tmp/ksh$ kshold40 --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+a5cfb049/MOD 2023-05-19
gillian:/tmp/ksh$ kshold39 --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+37a05ffc/MOD 2023-05-01
```

From my history file:
```
KSH=~/bin/kshold41 bin/shtests types
KSH=~/bin/kshold40 bin/shtests types
KSH=~/bin/kshold39 bin/shtests types
KSH=~/bin/kshold40 bin/shtests types
~/bin/kshold39 --version
~/bin/kshold40 --version
ls
rm -rf arch
git status
git checkout d507847afb02fc001f8ed6b198842a70ccfb675e
git log
bin/package make
bin/shtests types
for ((i=10; --i;)); do bin/shtests types; done
git log
git checkout a9225650b37804ac9874d68908c49da648caaf2d
bin/package make
bin/shtests types
git checkout 9034be6aa60d4477e4e62ad9a8352c6b718097e5
git status
bin/package make
bin/shtests types
for ((i=10; --i;)); do bin/shtests types; done
git checkout 5826275c68fd3c03573e634daf0a947dc4cbeba8
git status
bin/package make
bin/shtests types
for ((i=10; --i;)); do bin/shtests types; done
git checkout a0c104f32bcf39b4d9884574a911a8edff2afc2b
bin/package make
bin/shtests types
rm -rf arch
git checkout 5826275c68fd3c03573e634daf0a947dc4cbeba8
git status
bin/package make
bin/shtests types
for ((i=11; --i;)); do bin/shtests types; done
git checkout a0c104f32bcf39b4d9884574a911a8edff2afc2b
bin/shtests types
bin/package make
bin/shtests types
git branch -a
for ((n=0, i=0; i<10; i++)); do bin/shtests -u types || (( ++n )); done; printf 'Failed %i out of %i\n' $n $i
```
```
gillian:/tmp/ksh$ bin/shtests types
#### Regression-testing /tmp/ksh/arch/linux.arm64-64/bin/ksh ####
test types begins at 2023-06-11+22:04:23
test types passed at 2023-06-11+22:04:23 [ 100 tests 0 errors ]
test types(C.UTF-8) begins at 2023-06-11+22:04:23
	types.sh[552]: FAIL: typeset -p of nested type not correct (expected 'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(a=hello))));)', got $'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(a=\'\'))));)')
test types(C.UTF-8) failed at 2023-06-11+22:04:24 with exit code 1 [ 100 tests 1 error ]
test types(shcomp) begins at 2023-06-11+22:04:24
test types(shcomp) passed at 2023-06-11+22:04:24 [ 100 tests 0 errors ]
Total errors: 1
CPU time       user:      system:
main:      0m00.038s    0m00.023s
tests:     0m00.629s    0m00.601s
gillian:/tmp/ksh$
```
If you can do the same thing I am doing on the same box without error then it is perhaps something in my profile--I guess. You have superuser access on this box so you can become me and give it a whirl.

**Comment by McDutchie** [comment]
This is bizarre. When the current working directory is /tmp/ksh, the intermittent fail is reproducible. When the currnet working directory is /home/pi/src/ksh, it is not. Even when testing the exact same shell binary.

```
pi@gillian:~$ cd /tmp/ksh
pi@gillian:/tmp/ksh$ bin/shtests types SHELL=/tmp/ksh/arch/linux.arm64-64/bin/ksh
#### Regression-testing /tmp/ksh/arch/linux.arm64-64/bin/ksh ####
test types begins at 2023-06-11+23:14:18
test types passed at 2023-06-11+23:14:18 [ 100 tests 0 errors ]
test types(C.UTF-8) begins at 2023-06-11+23:14:18
        types.sh[552]: FAIL: typeset -p of nested type not correct (expected 'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(
a=hello))));)', got $'typeset -C b=(typeset -C -a ca=( [4]=(b_t b=(a_t b=(a=\'\'))));)')
test types(C.UTF-8) failed at 2023-06-11+23:14:19 with exit code 1 [ 100 tests 1 error ]
test types(shcomp) begins at 2023-06-11+23:14:19
test types(shcomp) passed at 2023-06-11+23:14:19 [ 100 tests 0 errors ]
Total errors: 1
CPU time       user:      system:
main:      0m00.035s    0m00.028s
tests:     0m00.633s    0m00.573s
pi@gillian:/tmp/ksh$ cd /home/pi/src/ksh
pi@gillian:~/src/ksh$ bin/shtests types SHELL=/tmp/ksh/arch/linux.arm64-64/bin/ksh
#### Regression-testing /tmp/ksh/arch/linux.arm64-64/bin/ksh ####
test types begins at 2023-06-11+23:14:28
test types passed at 2023-06-11+23:14:29 [ 100 tests 0 errors ]
test types(C.UTF-8) begins at 2023-06-11+23:14:29
test types(C.UTF-8) passed at 2023-06-11+23:14:29 [ 100 tests 0 errors ]
test types(shcomp) begins at 2023-06-11+23:14:29
test types(shcomp) passed at 2023-06-11+23:14:29 [ 100 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.049s    0m00.014s
tests:     0m00.645s    0m00.607s
pi@gillian:~/src/ksh$ bin/shtests types SHELL=/tmp/ksh/arch/linux.arm64-64/bin/ksh
#### Regression-testing /tmp/ksh/arch/linux.arm64-64/bin/ksh ####
test types begins at 2023-06-11+23:14:31
test types passed at 2023-06-11+23:14:31 [ 100 tests 0 errors ]
test types(C.UTF-8) begins at 2023-06-11+23:14:31
test types(C.UTF-8) passed at 2023-06-11+23:14:32 [ 100 tests 0 errors ]
test types(shcomp) begins at 2023-06-11+23:14:32
test types(shcomp) passed at 2023-06-11+23:14:32 [ 100 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.046s    0m00.018s
tests:     0m00.658s    0m00.546s
```
[many more successful test runs snipped]

**Comment by McDutchie** [comment]
So, since the CWD clearly doesn't have anything to do with anything, there must be some kind of undefined behaviour going on. Who knows where. Maybe it's stack corruption as the shell uses the AST stack widely, but that is pure speculation.

**Comment by hyenias** [comment]
Just tested today's HEAD and it worked--sort of. I used a different directory on /tmp as I already had /tmp/ksh. /tmp/kshnew worked. So, I did more testing, the type tests fail when directory name has length of 2-3 characters such as /tmp/aa or /tmp/aaa. Putting ksh into a subdirectory allows the tests to pass as well. Currently I have left the original /tmp/ksh at /tmp/kshx which passes using a 4 character directory name. Current head of 3c2b0dcf64aacbe9882a9ba185dc0640a189bf87 fails if dir is 2-3 chars off of /tmp.

**Comment by McDutchie** [comment]
Hmm. Seems it's always the `C.UTF-8` test that fails. Maybe the problem is in multibyte processing somewhere.

**Comment by McDutchie** [comment]
Testing again on the same Debian 11 aarch64 box, in /tmp/ksh. I cannot reproduce the problem at all now. @hyenias, can you confirm?

**Comment by hyenias** [comment]
Just tested current build and all tests passed after 30 mins of testing. No failures on `bin/shtests -u types` nor any other tests.
```ksh
gillian:~$ ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+f2bc1f45 2024-03-24
```
