### ISSUE TITLE
Still problems building in strict C99 mode

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#664]
This is further to #587 and #657. (Ping @JohnoKing)

See: https://bugzilla.redhat.com/show_bug.cgi?id=2144903#c4

```
Vincent Mihalkovič 2023-06-26 17:12:35 UTC

I built the 1.0.6 release with an instrumented GCC* (https://koji.fedoraproject.org/koji/taskinfo?taskID=102618961),
and this is the output (on x86_64):

*** GCC errors begin ***
./F72c01755.c:166: pointer-from-int-conversion in argument
./F72c01755.c:169: pointer-to-int-conversion in argument
./F72c01755.c:169: pointer-from-int-conversion in argument
./F72c01755.c:167: pointer-to-int-conversion in argument
./F72c01755.c:167: pointer-from-int-conversion in argument
./F72c01755.c:166: pointer-to-int-conversion in argument
conf.tmp.c:22: implicit function declaration: strtol
conf.tmp.c:19: implicit function declaration: open
conf.tmp.c:30: implicit function declaration: printf
conf.tmp.c:20: implicit function declaration: open
conf.tmp.c:23: implicit function declaration: strtol
./72c012523.c:41: implicit function declaration: __xstat
./72c017824.c:44: implicit function declaration: utimets
./72c018531.c:77: implicit function declaration: _link
./72c018531.c:75: implicit function declaration: _getpagesize
./72c018531.c:85: implicit function declaration: _pathconf
./72c018531.c:91: implicit function declaration: _stat
./72c018531.c:93: implicit function declaration: _truncate
./72c018531.c:87: implicit function declaration: _rename
./72c018531.c:71: implicit function declaration: _chmod
./72c018531.c:69: implicit function declaration: _access
./72c018531.c:43: implicit function declaration: _fstat
./72c018531.c:62: implicit function declaration: _mkdir
./72c018531.c:95: implicit function declaration: _unlink
./72c018531.c:41: implicit function declaration: _open
./72c018531.c:64: implicit function declaration: _chdir
./72c018531.c:45: implicit function declaration: _close
./72c018531.c:48: implicit function declaration: _write
./72c018531.c:48: implicit function declaration: _read
./72c018531.c:97: implicit function declaration: _utime
*** GCC errors end ***

I posted the results above, and now I have to look into the actual ksh source code location that triggers the
compiler errors.

*https://fedoraproject.org/wiki/Toolchain/PortingToModernC
```

**Comment by JohnoKing** [comment]
~I'm not sure if any of these are worth fixing in ksh.~ The instrumentation system Fedora is using appears to be flawed. Excerpts from the page [PortingToModernC](https://fedoraproject.org/wiki/Toolchain/PortingToModernC) (emphasis added):
> Using [Frédéric Bérat's Mass Prebuild tool](https://gitlab.com/fedora/packager-tools/mass-prebuild), we build packages with instrumented gcc and redhat-rpm-config packages that fail the build if certain errors occur anywhere during the build. These forced failures are guaranteed to happen **even if the build system ignores the exit status of a gcc command and continues regardless** (for example, during configure checks).

> Some functions are expected to be undefined (e.g., pledge does not exist on Linux). Calls to them result in implicit declarations, which is a false positive in this context. As a result, in the redhat-rpm-config package, there is [an exception list in the reporting code](https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/private-f38-toolchain/f/report-gcc-errors.lua).

> Implicit int/pointer conversion. Starting with the .implicits.5. versions, such errors are logged as well. The current implementation **exhibits some false positives** (even though cascading errors are suppressed in the .implicits.6. compiler), and there is currently **no working suppression mechanism.**

Looking at their exception list, many of the functions here that are expected to fail with implicit declaration errors aren't included as exceptions (i.e., __xstat, utimets, _close, etc.). Those problems should be fixed in Fedora's exception list, not ksh.

Perhaps the pointer conversion errors are worth looking into, ~but I thus far haven't been able to reproduce any of those errors. I also cannot reproduce the implicit functions errors that apparently occur in conf.tmp.c, so I'm not sure where to start regarding those.~

**Comment by JohnoKing** [comment]
Update: I have reproduced those errors on a Fedora VM after installing the special gcc. The conf.tmp.c errors specifically can be fixed with the following patch:
```diff
diff --git a/src/lib/libast/comp/conf.tab b/src/lib/libast/comp/conf.tab
index cd50e8bf7..412475241 100644
--- a/src/lib/libast/comp/conf.tab
+++ b/src/lib/libast/comp/conf.tab
@@ -390,6 +390,9 @@ PBS_MESSAGE			POSIX	SC 2 FUW
 PBS_TRACK			POSIX	SC 2 FUW
 PHYS_PAGES			SUN	SC 1 0
 PID_MAX				SVID	SC 1 LMU	30000	cc{
+	#include <fcntl.h>
+	#include <stdio.h>
+	#include <stdlib.h>
 	int main(void)
 	{
 		long	v;
```

**Comment by JohnoKing** [comment]
Here is my attempt at adding the required exeptions to the exception list (~it unfortunately doesn't fix the errors for some reason~ **edit:** the patch has been updated and afaict works correctly):
```diff
--- a/report-gcc-errors.lua	2023-06-27 06:08:19.692141632 +0000
+++ b/report-gcc-errors.lua	2023-06-28 03:23:49.838405338 +0000
@@ -36,27 +36,45 @@
   "__cpu_to_le32",
   "__cpu_to_le64",
   "__sync_swap",
+  "__xstat",
+  "_access",
   "_alloca",
   "_byteswap_uint64",
   "_byteswap_ulong",
   "_byteswap_ushort",
+  "_chdir",
+  "_chmod",
+  "_close",
   "_controlfp",
   "_controlfp_s",
   "_dup",
   "_fdopen",
   "_fileno",
   "_fpclass",
+  "_fstat",
+  "_getpagesize",
   "_isatty",
+  "_link",
   "_logb",
+  "_mkdir",
   "_mkgmtime",
   "_mulx_u32",
+  "_open",
+  "_pathconf",
+  "_read",
+  "_rename",
   "_rtc",
   "_scprintf",
   "_snprintf",
   "_spin_lock_try",
   "_spin_unlock",
+  "_stat",
   "_strdup",
   "_syscall0",
+  "_truncate",
+  "_unlink",
+  "_utime",
+  "_write",
   "_wstat64",
   "acl",
   "acl_get_perm_np",
@@ -125,6 +143,7 @@
   "tcgetwinsize",
   "typeof",
   "unw_backtrace_skip",
+  "utimets",
   "wcslcpy",
   "wcstonum",
 }
```

**Comment by McDutchie** [comment]
Fixed in commits referenced above.
