### ISSUE TITLE
Regression in behavior of `exit` with no args in trap handler

### ISSUE THREAD

**Issue by sckendall2** [ksh93/ksh#667]
`exit` with no args in a trap handler should reflect the status of "the command that executed immediately preceding the trap action", according to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#exit). In other words, this script should exit with status 0:
```
trap 'false; exit' EXIT; true
```
The bug is that in RHEL 9.2, with KSH_VERSION="Version AJM 93u+m/1.0.0-beta.1 2021-05-10", this script exits with status 1. Nearly all KornShell implementations I tested, including all older ksh93 versions, get this right.

This is a pretty obscure bug. It seems unwise to invoke exit in an EXIT trap at all. But one of my colleagues was unwise in this way, and his script broke on the above platform.

I haven't tried this in more recent builds of 93u+m. My apologies if this bug has been fixed since that version, or if it was introduced downstream.

**Comment by McDutchie** [comment]
That's a very early beta version. It should not be used. Please upgrade to the latest release.

This bug was in 93u+ 2012-08-01 as well (so, older ksh93 versions actually did not get this right). It was fixed for 93u+m in commit 092b90da81f1ab1d45495052615fb4bf83a25d03 (9th Sept 2020).

**Comment by McDutchie** [comment]
However, your particular reproducer was not yet included in the regression tests, so I'll add it.

**Comment by McDutchie** [comment]
Eek. Looks like I misinterpreted this at the time. The bug is still present and is, in fact, the same one as #687.
