### ISSUE TITLE
Subshell read command fails for 0 or 1 characters plus tab

### ISSUE THREAD

**Issue by wymby** [ksh93/ksh#676]
The following:

	( read a; print "$a" )

beeps and ignores a tab if it is entered before two other characters have been typed.  With () 
removed, it works in an interactive shell (but fails in an invoked script).

**Comment by pghvlaans** [comment]
Interestingly, this does not appear to be reproducible if a delimiter other than newline is set, e.g. 

    ( read -d x a ; print "$a" )

**Comment by McDutchie** [comment]
@wymby, thanks for the report. Looks like @pghvlaans has capably fixed the bug (thanks!), so I'll merge his pull request now.
