### ISSUE TITLE
printf with %d: the man page should say that when ".." is used, the precision is 1

### ISSUE THREAD

**Issue by vinc17fr** [ksh93/ksh#679]
For `printf` with `%d`, when a single dot is used without a precision, the precision is taken as 0. So the ksh93 specific case `..` to provide a base without giving a precision (e.g. `%..2d`) is ambiguous: does this mean that the precision is missing (like without any dot, thus defaulting to 1) or does this mean that the precision is 0 (like with a single dot)? This should be documented in the man page (`sh.1`).

A test shows that the precision is 1 in this case (which is much more useful for the user than 0):
```
$ printf ">%..2d<\n" 0
>0<
```

**Comment by McDutchie** [comment]
Thanks for the suggestion!
