### ISSUE TITLE
RFE: meson build

### ISSUE THREAD

**Issue by kloczek** [ksh93/ksh#682]
In forked https://github.com/att/ast/tree/refs/tags/2020.0.0 still it is possible to find well coded meson files.

Is it will be accepted as PR here adaptation of these files? 🤔

**Comment by McDutchie** [comment]
No, I don't want to make ksh dependent on any particular build system. It's very widely portable as it is now: it only depends on a POSIX compliant userland and compiler to build. I don't want to give that up. We'd lose compatibility with some more obscure systems like AIX and QNX, that cannot run meson. If I recall correctly, ksh2020 never worked on Solaris either.

**Comment by kloczek** [comment]
This RFE is not about replace current build framework but about add meson based one.

**Comment by posguy99** [comment]
IMO, it doesn't add anything and someone would have to maintain it going forward.

**Comment by McDutchie** [comment]
Sorry, I'm afraid no one has time for that.
