### ISSUE TITLE
Negative integer literal with radix symbol should be formatted as positive with unary minus for integers defined with an explicit base.

### ISSUE THREAD

**Issue by ormaaj** [ksh93/ksh#696]
Cute example:
```bash
#!/usr/bin/env ksh
builtin getconf
integer 20 MAKEOPTS
x=20#j$(getconf _NPROCESSORS_ONLN) let 'MAKEOPTS = x'
printf '%s %s %d %..20d %s\n' "$MAKEOPTS" "$((MAKEOPTS *= -1))" MAKEOPTS{,} "$MAKEOPTS"
```
```
20#j12 -7622 -7622 -j12 20#b53bjh07be4cjje
```
I think ksh packs the radix and integer into an atomic value, as in the last parameter expansion,  so it doesn't have to re-parse intermediary results during evaluation, and generally for an unambiguous representation that preserves information through different manipulations.

For features that produce formatted literals, you typically prefer to extract the unary minus, as in the second to last output field, especially when an integer is defined with an explicit non-decimal base.

That was probably a motivation for the arbitrary base conversion specification, but that's currently the only way to get the sign out of the two's complement representation. Others like `typeset -p` produce the jibberish internal representation, and others like `print -C` and `print -v` seem to be broken.

**Comment by McDutchie** [comment]
Thanks for your report, though de-obfuscating it has been a bit of a challenge.

From observed behaviour, the problem seems to be that the generation of non-base 10 values does not support negative numbers and is being incorrectly treated as unsigned.

```
$ (v=7622; integer 20 v; typeset -p v)
typeset -l -i 20 v=20#j12
$ (v=-7622; integer 20 v; typeset -p v)
typeset -l -i 20 v=20#b53bjh07be4cjje
$ (v=-1; integer 16 v; typeset -p v)
typeset -l -i 16 v=16#ffffffffffffffff
```

**Comment by ormaaj** [comment]
Ah. I figured it might be some deliberate mechanism since it seems to preserve values and operations on them work, but it could have just worked out that way too.

**Comment by McDutchie** [comment]
It is undefined behaviour, but most systems just wrap around integer overflows, which makes it more likely for the right thing to happen:

```
$ ((v=16#ffffffffffffffff)); echo $v
-1
$ ((v=16#fffffffffffffffe)); echo $v
-2
```

**Comment by McDutchie** [comment]
To format numbers, `nv_getval()` calls libast's `fmtbase` (name.c, line 2790). The `fmtbase` function simply assumes that all numbers with a specified base (including 10, if explicitly specified) are non-negative and treats them as unsigned. Bizarre.

Note that the unary minus sign needs to come before the base prefix for ksh arithmetic expansions to do the right thing in the other direction (i.e. `-20#j12`, not `20#-j12`), so that is what this patch produces.

```diff
diff --git a/src/lib/libast/string/fmtbase.c b/src/lib/libast/string/fmtbase.c
index 36f0c1090..1aecc84e1 100644
--- a/src/lib/libast/string/fmtbase.c
+++ b/src/lib/libast/string/fmtbase.c
@@ -30,19 +30,22 @@
 char*
 fmtbase(intmax_t n, int b, int p)
 {
-	char*	buf;
+	char	*buf, *obuf;
 	int	z;
 
 	if (!p)
 	{
 		if (!n)
 			return "0";
-		if (!b)
+		if (!b || b == 10)
 			return fmtint(n, 0);
-		if (b == 10)
-			return fmtint(n, 1);
 	}
-	buf = fmtbuf(z = 72);
+	obuf = buf = fmtbuf(z = 72);
+	if (n < 0)
+	{
+		*buf++ = '-';
+		n = -n;
+	}
 	sfsprintf(buf, z, p ? "%#..*I*u" : "%..*I*u", b, sizeof(n), n);
-	return buf;
+	return obuf;
 }
```

With the patch, your reproducer (simplified version):

```sh
integer 20 n=20#j12
printf '%s %s %d %..20d %s\n' "$n" "$((n *= -1))" n n "$n"
```

now outputs:

```
20#j12 -7622 -7622 -j12 -20#j12
```

**Comment by McDutchie** [comment]
But with that patch it will not do the right thing for numbers that are actually unsigned and so large that the most significant bit is set. `fmtbase` is going to need an extra argument and things are going to need some refactoring.
