### ISSUE TITLE
request: builtin hash - exit status 1 on search failure

### ISSUE THREAD

**Issue by dicktyr** [ksh93/ksh#732]
both bash and dash return exit status 1 if PATH search fails
but ksh always returns exit status 0

differentiating exit status enables

`hash cmd && cmd ...`

rather than

`[[ -n type -p cmd ]] && cmd ...`

**Comment by McDutchie** [comment]
ksh93 already has a way to do what you want:

`whence -pq cmd && cmd ...`

As for `hash`, the behaviour on other POSIXy shells is:
* mksh always returns 0, like ksh93.
* bash, dash, FreeBSD sh, NetBSD sh, yash and zsh not only return status 1 on command not found, but also print an error message.

POSIX [says](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/hash.html#tag_20_56_14) that `hash` shall return non-zero on error, but does not define 'command not found' as an error condition — whereas, for `command -v`, [it does](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html#tag_20_22_14).

Still, I could change ksh 93u+m's behaviour for `hash` to match that of all the non-ksh shells (in which case we should also add the error message), but it would have to be for version 1.1 and up as the change is not backward compatible.
