### ISSUE TITLE
`test ! = -o a` exits with 0 instead of 1

### ISSUE THREAD

**Issue by vinc17fr** [ksh93/ksh#740]
With ksh93u+m 1.0.8-1 under Debian/unstable:
```
$ test ! = -o a ; echo $?
0
```
while I get 1 with dash 0.5.12-6, mksh 59c-35, bash 5.2.21-2, coreutils 9.4-3.1 and zsh 5.9-6.

In the [POSIX spec of `test`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html) for 4 arguments:
> If $1 is '!', negate the three-argument test of $2, $3, and $4.

The negation is not what is done:
```
$ test = -o a ; echo $?
0
```

**Comment by vinc17fr** [comment]
Hmm... I can see that setting the `posix` option with `set -o posix` gives the expected result.

Note that in general, the main purpose of the `test` command in shells is to get the POSIX behavior. Otherwise, `[[ ... ]]` should be used instead. So I'm wondering why the POSIX behavior is not the default for `test`.

**Comment by McDutchie** [comment]
> Note that in general, the main purpose of the test command in shells is to get the POSIX behavior. Otherwise, [[ ... ]] should be used instead. 

“Should be” != “is”. There are plenty of ksh scripts that use `test` / `[`. Backward compatibility is important.

> So I'm wondering why the POSIX behavior is not the default for `test`.

Backward compatibility. See 9b259c944e2b4ffb2db7cdbfb84d0fb0645949db for reasons.

I will see what can be done about fixing the reproducer above. But I'm not making any promises. Messing with the `test` code carries a high risk of introducing new bugs and backward incompatibilities.

**Comment by vinc17fr** [comment]
In any case, I always thought that ksh was meant to conform to POSIX. For instance, this is how it is advertised (with no warnings about this not being the default behavior)
* [by IBM](https://www.ibm.com/docs/en/aix/7.2?topic=shell-korn-posix-commands): "The Korn shell is an interactive command interpreter and command programming language. It conforms to the Portable Operating System Interface for Computer Environments (POSIX), an international standard for operating systems."
* [by Debian](https://packages.debian.org/bookworm/ksh93u+m), in the ksh93u+m package description: "KornShell is an interactive UNIX command interpreter as well as a POSIX compliant scripting language which is a superset of sh(1), the System V UNIX shell."

**Comment by McDutchie** [comment]
> In any case, I always thought that ksh was meant to conform to POSIX.

Yes, that's how it was always advertised, but it's just not quite true. I've found many ways in which traditional ksh93 behaviour is not compliant with the POSIX standard. Fixing that by default would break compatibility with too many ksh scripts, which is why I've added a `posix` compliance option. See the manual page under `Built-in Commands` → `set` →  `-o` → `posix` for a list of these differences.

**Comment by McDutchie** [comment]
> I will see what can be done about fixing the reproducer above. But I'm not making any promises. Messing with the `test` code carries a high risk of introducing new bugs and backward incompatibilities.

There is no easy way to fix this, and it's not worth the high risk of introducing new bugs.

**Comment by vinc17fr** [comment]
It has been reported again as #858.

**Comment by McDutchie** [comment]
Yeah, I forgot all about this issue and decision. Let's test the patch in #858 and see if this can be fixed after all.

**Comment by McDutchie** [comment]
See https://github.com/ksh93/ksh/issues/858#issuecomment-2907843464

**Comment by vinc17fr** [comment]
Yes, I agree that the POSIX spec was absurd.
