### ISSUE TITLE
document shell option behavior wrt functions

### ISSUE THREAD

**Issue by adavies42** [ksh93/ksh#751]
It's a long-standing behavior of ksh that `set -e` and `set -x` need to be repeated at the beginning of `function` functions (but not `()` functions) even if they're active in the main script.

Is it actually documented anywhere? Are there any other shell options that don't inherit into functions and/or differ between the two types of functions?

**Comment by hlangeveld** [comment]
I recall that the AST team always tried to preserve existing behaviour for established syntax. For that reason, any new behaviour was only enabled in the new `function name {` ... syntax.

**Comment by adavies42** [comment]
To be clear, what I'm suggesting is an addition to [src/cmd/ksh93/sh.1](https://github.com/ksh93/ksh/blob/2e8aeee968a4d58fda0d95b2aba6b629e9cd46b1/src/cmd/ksh93/sh.1), probably to the [Functions section](https://github.com/ksh93/ksh/blob/2e8aeee968a4d58fda0d95b2aba6b629e9cd46b1/src/cmd/ksh93/sh.1#L4040), documenting how `set -o` options behave wrt both types of functions.

**Comment by McDutchie** [comment]
Thanks for the heads-up on this omission, @adavies42. I've read [the code](https://github.com/ksh93/ksh/blob/2e8aeee968a4d58fda0d95b2aba6b629e9cd46b1/src/cmd/ksh93/sh/xec.c#L3004-L3184) for executing `function` keyword syntax functions and errexit and xtrace are the only two options that are turned off within such a function.
