### ISSUE TITLE
e8b45cc8 Broke FreeBSD Build

### ISSUE THREAD

**Issue by cschuber** [ksh93/ksh#754]
e8b45cc8 broke its build on FreeBSD in various places. After circumventing the first two errors by adding environment variables for AR and STDCHMOD, there was a failure to link because -fPIC was not specified during compile.

**Comment by McDutchie** [comment]
Unfortunately, I cannot reproduce the build failure. It builds fine for me on FreeBSD, both x86_64 and arm64.

What is your precise build procedure and how can I reproduce it?

**Comment by McDutchie** [comment]
I'm still unable to reproduce this on FreeBSD (having tried multiple versions on two architectures), however, I just reproduced the failure on OmniOS (an illumos distribution), with symptoms identical to those reported in https://github.com/ksh-community/ksh/issues/20. Investigating.

**Comment by McDutchie** [comment]
Found the cause. The bug is triggered when CC is exported in the environment. As of e8b45cc8c7e2f9178b072455bdcd3cc598c6d272, this prevents the probe from being done. I can reproduce this on any system now.

The following patch reverts the relevant change and should fix the bug. Sorry about that, and thanks for the report!

```diff
diff --git a/src/cmd/INIT/mamake.c b/src/cmd/INIT/mamake.c
index 1cc85f1f..f604379c 100644
--- a/src/cmd/INIT/mamake.c
+++ b/src/cmd/INIT/mamake.c
@@ -297,6 +297,7 @@ static struct				/* program state		*/
 	int		indent;		/* debug indent			*/
 	int		keepgoing;	/* do siblings on error		*/
 	int		never;		/* never execute		*/
+	int		probed;		/* probe already done		*/
 	int		verified;	/* don't bother with verify()	*/
 
 	Stream_t	streams[4];	/* input file stream stack	*/
@@ -2112,8 +2113,11 @@ static unsigned long make(Rule_t *r, int inloop, unsigned long modtime, Buf_t **
 				setval(state.vars, t, v);
 				if (strcmp(t, "MAMAKE_STRICT") == 0)
 					state.strict = *v ? atoi(v) : 1;
-				else if (strcmp(t, "CC") == 0)
-					probe();
+			}
+			if (!state.probed && strcmp(t, "CC") == 0)
+			{
+				state.probed = 1;
+				probe();
 			}
 			continue;
 
```

**Comment by cschuber** [comment]
Thanks. The build was performed by the ports plumbing. The ports plumbing sets CC, LD, among other environment variables. This is because a developer or advanced user can build a port using the C compiler in the base system (LLVM) or any of the C compilers in ports. Additionally, ld in base is (LLVM). A person could use binutils instead. The reason for this is the ability to cross compile under Linux, MacOS, or non-native hardware.

**Comment by McDutchie** [comment]
Thanks for the extra info. The ports plumbing should build the 93u+m/1.0.9 release fine (knock on wood).

Also, could you close https://github.com/ksh-community/ksh/issues/20? I can't, as that's not my repo and I'm not the reporter.
