### ISSUE TITLE
ksh dev@3b33b438 fails signal regression test on macOS 13.6.7 Intel and ARM

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#765]
$ bin/package clean && bin/package make && bin/package test
... builds ...
... tests ...

test signal begins at 2024-07-19+05:36:06
	signal.sh[613]: FAIL: regression involving SIGPIPE in subshell (expected status 0 and 'exited 9', got status 0 and 'exited 265')
test signal failed at 2024-07-19+05:36:16 with exit code 1 [ 57 tests 1 error ]
test signal(C.UTF-8) begins at 2024-07-19+05:36:16
	signal.sh[613]: FAIL: regression involving SIGPIPE in subshell (expected status 0 and 'exited 9', got status 0 and 'exited 265')
test signal(C.UTF-8) failed at 2024-07-19+05:36:27 with exit code 1 [ 57 tests 1 error ]
test signal(shcomp) begins at 2024-07-19+05:36:27
	shcomp-signal.ksh[613]: FAIL: regression involving SIGPIPE in subshell (expected status 0 and 'exited 9', got status 0 and 'exited 265')
test signal(shcomp) failed at 2024-07-19+05:36:37 with exit code 1 [ 57 tests 1 error ]

Repeatable on both arches.

**Comment by posguy99** [comment]
Tested also on Debian 12 ARM64 with same failure.

**Comment by McDutchie** [comment]
Thanks for the report. That's what I get for committing a fix right before leaving for holiday. I think I've got it actually fixed now, but I want to do more testing this time before committing.

Patch against current dev branch (3b33b438): revert fault.c changes, apply workaround to jobs.c instead.

```diff
diff --git a/src/cmd/ksh93/sh/fault.c b/src/cmd/ksh93/sh/fault.c
index f96591be7..523857140 100644
--- a/src/cmd/ksh93/sh/fault.c
+++ b/src/cmd/ksh93/sh/fault.c
@@ -689,7 +689,7 @@ noreturn void sh_done(int sig)
 	sfsync((Sfio_t*)sfstdout);
 	if((sh.chldexitsig && sh.realsubshell) || (savxit&SH_EXITSIG && (savxit&SH_EXITMASK) == savlastsig))
 		sig = savxit&SH_EXITMASK;
-	if(sig && !(sh.realsubshell && sig==SIGPIPE))
+	if(sig)
 	{
 		/* generate fault termination code */
 		if(RLIMIT_CORE!=RLIMIT_UNKNOWN)
@@ -713,7 +713,7 @@ noreturn void sh_done(int sig)
 		kiaclose((Lex_t*)sh.lex_context);
 #endif /* SHOPT_KIA */
 	/* Exit with portable 8-bit status (128 + signum) if last child process exits due to signal */
-	if(sig || sh.chldexitsig)
+	if(sh.chldexitsig)
 		savxit = savxit & ~SH_EXITSIG | 0200;
 	exit(savxit&SH_EXITMASK);
 }
diff --git a/src/cmd/ksh93/sh/jobs.c b/src/cmd/ksh93/sh/jobs.c
index 676de21fd..fb19b7a75 100644
--- a/src/cmd/ksh93/sh/jobs.c
+++ b/src/cmd/ksh93/sh/jobs.c
@@ -1447,7 +1447,8 @@ int	job_wait(pid_t pid)
 						if(px->p_flag&P_SIGNALLED)
 						{
 							sh.exitval |= SH_EXITSIG;
-							sh.chldexitsig = 1;
+							if(!(sh.realsubshell && px->p_exit==SIGPIPE))
+								sh.chldexitsig = 1;
 						}
 						if(intr)
 							px->p_flag &= ~P_EXITSAVE;
```

**Comment by posguy99** [comment]
Ok, builds and passes all tests with this patch.
