### ISSUE TITLE
Build failures: musl and glibc-2.33

### ISSUE THREAD

**Issue by pghvlaans** [ksh93/ksh#778]
RE: 13c6f5d

The build is failing on Void (musl) and 32-bit Slackware 15.0 (glibc-2.33):

    iffe: test: capture output of /home/pghvlaans/KSHDEV/ksh/src/lib/libast/features/map.c ...
    In file included from ./iffe.7667.c:59:
    ./FEATURE/random:11:8: error: unknown type name 'uint32_t'
      11 | extern uint32_t arc4random(void);
         |        ^~
    iffe: test: capture output of /home/pghvlaans/KSHDEV/ksh/src/lib/libast/features/map.c ... cannot run

EDIT: It fails on Slackware64 15.0 as well. *BSD and Slackware64 -current (glibc-2.40) are fine.

**Comment by pghvlaans** [comment]
Please let me know if you'd like something tested on these VMs.

**Comment by McDutchie** [comment]
Ugh.

I think I'm just going to revert this commit, and then get rid of the `_map_libc` symbol completely. I've not seen evidence that it's any actual use, the libast dependencies are too messy, and we could do without this extra maintenance load.

Some of the mappings in features/map.c are now hardcoded and those should be kept.
