### ISSUE TITLE
SHOPT_EDPREDICT is broken & no def for CURSOR_UP, ERASE_EOS and pr_string

### ISSUE THREAD

**Issue by k2662** [ksh93/ksh#786]

**Comment by McDutchie** [comment]
So it is. Bit rot strikes again. Thanks for the report.

(Note: this applies to the 1.0 branch only, as SHOPT_EDPREDICT is deprecated and has been removed on the dev branch)

**Comment by McDutchie** [comment]
Now fixed on the 1.0 branch.
