### ISSUE TITLE
Arithmetic function `isinfinite` missing?

### ISSUE THREAD

**Issue by dnewhall** [ksh93/ksh#796]
The man page says `isinfinite` is one of the predefined arithmetic functions, but when I go and test it:
```shell
$ echo $(( isinfinite(inf) ))
ksh: isinfinite(inf) : unknown function
```

`isinf(inf)` works as expected, though.

Was this removed and the documentation needs to be updated? Should it be in there and no one noticed it was missing until now?

**Comment by McDutchie** [comment]
As the manual page says: “Any of the following math library functions _that are in the C math library_ can be used within an arithmetic expression:”, etc.

What functions are in the C math library depends on the operating system. Your system has `isinf` but not `isinfinite` (as does mine; I don't know on what systems `isinfinite` exists). Both are checked for at compile time [in math.tab](https://github.com/ksh93/ksh/blob/caf8a66f3ecbc549b5550bcb7565050bce221d1a/src/cmd/ksh93/data/math.tab#L57-L58), which is parsed by [math.sh](https://github.com/ksh93/ksh/blob/caf8a66f3ecbc549b5550bcb7565050bce221d1a/src/cmd/ksh93/features/math.sh#L1), which is [executed by iffe](https://github.com/ksh93/ksh/blob/caf8a66f3ecbc549b5550bcb7565050bce221d1a/src/cmd/ksh93/Mamfile#L41-L49).

**Comment by dnewhall** [comment]
Should Ksh make some guarantees here? They are really useful, but if they are platform-defined it makes any shell script that uses them inherently non-portable.

I just found out this is a big issue with `fpclassify`, which cannot be portably used at all in its current state (`fpclassify(nan)` returns 0 on Linux, 1 on MacOS, and 2 on FreeBSD...)
