### ISSUE TITLE
previous command fetching in vi-mode with command 'k' does skip over history entries starting with whitespace.

### ISSUE THREAD

**Issue by jghub** [ksh93/ksh#799]
seen with Version AJM 93u+m/1.1.0-alpha+4467eaff 2024-08-01  (but issue probably older I seem to recall):

if for some reason a command is entered with leading whitespace, the leading whitespace is preserved in the history file (in ksh93u+, too).  such commands can be recalled from history in 93u+  without problem, both, in vi and emacs mode.

but in 93u+m such entries are simply ignored when using vi-mode (`set -o vi`), i.e.  the `k` and `j` commands skip over such entries. emacs mode still works just fine.

**Comment by McDutchie** [comment]
Thanks for the report. A test of my stash of compiled commits says that this bug was introduced by commit 5eeeed066cd6ac9eac1b2f604e4ea3866869c4e9. Ping @pghvlaans 

*edit:* See also 4ec937455617514d5cb12aef4be69e7438a83232, f840ce81880f03d4dfb303d3f4d138e9f551cd38

**Comment by McDutchie** [comment]
The `blankline` function (formerly `isallwhitespace`) is supposed to determine if a line is entirely blank. However, the vi.c version of it only examines the line until `cur_virt` (`editb.e_cur`), the current cursor position. I think it should be looking until `last_virt` (`editb.e_eol`) instead, the position of the last character on the line.

The emacs.c version of `blankline` actually has the same issue; it examines the line until `cur` (`editb.e_cur`),, not `eol` (`editb.e_eol`). But, unlike vi, emacs positions the cursor at the end when arrowing up, so that's not as noticeable.

Please test this patch:

```diff
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index fdde3d7ec..18bb1a36a 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1706,7 +1706,7 @@ static char blankline(Emacs_t *ep, genchar *out)
 {
 	int x;
 	ep->mark = cur;
-	for(x=0; x < cur; x++)
+	for(x=0; x <= eol; x++)
 	{
 #if SHOPT_MULTIBYTE
 		if(!iswspace((wchar_t)out[x]))
diff --git a/src/cmd/ksh93/edit/vi.c b/src/cmd/ksh93/edit/vi.c
index 3a328dd88..4e6d9d3c5 100644
--- a/src/cmd/ksh93/edit/vi.c
+++ b/src/cmd/ksh93/edit/vi.c
@@ -2615,7 +2615,7 @@ yankeol:
 static char blankline(Vi_t *vp)
 {
 	int x;
-	for(x=0; x <= cur_virt; x++)
+	for(x=0; x <= last_virt; x++)
 	{
 #if SHOPT_MULTIBYTE
 		if(!iswspace((wchar_t)virtual[x]))
```

**Comment by pghvlaans** [comment]
The `blankline` name and description are certainly wrong. My apologies. Just two things to consider:

1. Is the bug here or in 93+u? `mksh` skips lines starting with whitespace in history recall, but `pdksh` does not. I couldn't find anything about this in the man page or B&K.
2. Tab completion needs to check for whitespace up to and including the cursor only to avoid displaying the full contents of the path.

That is, if space-initial names should be recalled by `k` or `j`, `blankline` cannot be used for both completion and history recall.

EDIT: I fired up System V in an emulator. In `ksh` version 88d, lines starting with a space are recalled. Perhaps `mksh` added this behavior because it was in `bash`.

**Comment by McDutchie** [comment]
Re 1: mksh avoids recording lines starting with whitespace or IFS characters in the history in the first place (i.e., they do not show up in `fc -l` output), which is different. (See https://github.com/mirbsd/mksh/commit/32875713867d69224625a55f8bacd258776a5c18) ksh93 has never done this or anything like it.

**Comment by pghvlaans** [comment]
Understood. Tab completion and recall can't use the same handling, then.

**Comment by McDutchie** [comment]
I also wonder why blankline() in emacs.c assigns `ep->mark = cur;`. What's that for?

**Comment by McDutchie** [comment]
Patch version two: use a flag argument to make `blankline` check for whitespace for the entire line (for arrowing up and down) or up to the cursor only.
```diff
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index fdde3d7ec..d1cfcfc5b 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -171,7 +171,7 @@ static void search(Emacs_t*,genchar*,int);
 static void setcursor(Emacs_t*,int, int);
 static void show_info(Emacs_t*,const char*);
 static void xcommands(Emacs_t*,int);
-static char blankline(Emacs_t*, genchar*);
+static char blankline(Emacs_t*, genchar*, int);
 
 int ed_emacsread(void *context, int fd,char *buff,int scend, int reedit)
 {
@@ -664,9 +664,9 @@ update:
 			cur = eol;
 			draw(ep,UPDATE);
 			/* skip blank lines when going up/down in history */
-			if(c==cntl('N') && hline != histlines && blankline(ep,out))
+			if(c==cntl('N') && hline != histlines && blankline(ep,out,0))
 				ed_ungetchar(ep->ed,cntl('N'));
-			else if(c==cntl('P') && hline != hismin && blankline(ep,out))
+			else if(c==cntl('P') && hline != hismin && blankline(ep,out,0))
 				ed_ungetchar(ep->ed,cntl('P'));
 			continue;
 		}
@@ -929,7 +929,7 @@ static int escape(Emacs_t* ep,genchar *out,int count)
 		case '*':		/* filename expansion */
 		case '=':	/* escape = - list all matching file names */
 		{
-			if(cur<1 || blankline(ep,out))
+			if(cur<1 || blankline(ep,out,1))
 			{
 				beep();
 				return -1;
@@ -1215,7 +1215,7 @@ static void xcommands(Emacs_t *ep,int count)
                 case cntl('E'):	/* invoke emacs on current command */
 			if(eol>=0 && sh.hist_ptr)
 			{
-				if(blankline(ep,drawbuff))
+				if(blankline(ep,drawbuff,1))
 				{
 					cur = 0;
 					eol = 1;
@@ -1702,11 +1702,11 @@ static int _isword(int c)
 /*
  * determine if the command line is blank (empty or all whitespace)
  */
-static char blankline(Emacs_t *ep, genchar *out)
+static char blankline(Emacs_t *ep, genchar *out, int uptocursor)
 {
 	int x;
 	ep->mark = cur;
-	for(x=0; x < cur; x++)
+	for(x=0; uptocursor ? (x < cur) : (x <= eol); x++)
 	{
 #if SHOPT_MULTIBYTE
 		if(!iswspace((wchar_t)out[x]))
diff --git a/src/cmd/ksh93/edit/vi.c b/src/cmd/ksh93/edit/vi.c
index 3a328dd88..7485115ab 100644
--- a/src/cmd/ksh93/edit/vi.c
+++ b/src/cmd/ksh93/edit/vi.c
@@ -174,7 +174,7 @@ typedef struct _vi_
 
 static const char paren_chars[] = "([{)]}";   /* for % command */
 
-static char	blankline(Vi_t*);
+static char	blankline(Vi_t*, int);
 static void	cursor(Vi_t*, int);
 static void	del_line(Vi_t*,int);
 static int	getcount(Vi_t*,int);
@@ -634,9 +634,9 @@ static int cntlmode(Vi_t *vp)
 			virtual[last_virt+1] = '\0';
 			gencpy(vp->U_space, virtual);
 			/* skip blank lines when going up/down in history */
-			if((c=='k' || c=='-') && curhline != histmin && blankline(vp))
+			if((c=='k' || c=='-') && curhline != histmin && blankline(vp,0))
 				ed_ungetchar(vp->ed,'k');
-			else if((c=='j' || c=='+') && curhline != histmax && blankline(vp))
+			else if((c=='j' || c=='+') && curhline != histmax && blankline(vp,0))
 				ed_ungetchar(vp->ed,'j');
 			break;
 
@@ -660,7 +660,7 @@ static int cntlmode(Vi_t *vp)
 		case 'v':
 			if(vp->repeat_set==0)
 			{
-				if(blankline(vp) || cur_virt == INVALID)
+				if(blankline(vp,1) || cur_virt == INVALID)
 				{
 					cur_virt = 0;
 					last_virt = cur_virt;
@@ -1248,7 +1248,7 @@ static void getline(Vi_t* vp,int mode)
 		{
 			if(!sh_isoption(SH_VI) || !sh.nextprompt)
 				goto fallback;
-			if(blankline(vp))
+			if(blankline(vp,1))
 			{
 				ed_ringbell();
 				break;
@@ -2256,7 +2256,7 @@ addin:
 	case '\\':		/** do file name completion in place **/
 	case '=':		/** list file name expansions **/
 	{
-		if(cur_virt == INVALID || blankline(vp))
+		if(cur_virt == INVALID || blankline(vp,1))
 			return BAD;
 		/* FALLTHROUGH */
 		save_v(vp);
@@ -2612,10 +2612,10 @@ yankeol:
 /*
  * determine if the command line is blank (empty or all whitespace)
  */
-static char blankline(Vi_t *vp)
+static char blankline(Vi_t *vp, int uptocursor)
 {
 	int x;
-	for(x=0; x <= cur_virt; x++)
+	for(x=0; x <= (uptocursor ? cur_virt : last_virt); x++)
 	{
 #if SHOPT_MULTIBYTE
 		if(!iswspace((wchar_t)virtual[x]))
```

**Comment by pghvlaans** [comment]
> I also wonder why blankline() in emacs.c assigns `ep->mark = cur;`. What's that for?

I can't remember. It can probably be gotten rid of, though.

Anyway, the new patch is working here.
