### ISSUE TITLE
Too much memory is allocated when reading big lines

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#95]
There is a severe memory allocation bug that was reported in att/ast#1401. Too much memory is being allocated when ksh reads lines of increasing size from a file. In the following example ksh uses 12GB of RAM to read a 41MB file:

```sh
$ dd if=/dev/zero of=./zeroes count=4096 bs=10000
$ ksh -c 'read line < ./zeroes; grep VmPeak /proc/$$/status ; echo "."'
VmPeak:  12548348 kB
.
```

The cause is located in the vmalloc's memory allocation. This bug disappears when ksh is compiled with `-D_std_malloc` added to `CCFLAGS` because that flag causes vmalloc to become a wrapper for the operating system's malloc implementation (i.e., the native `malloc` and `free` functions are used instead of vmalloc's replacements):
```sh
# Run after deleting ./arch and recompiling ksh with `-D_std_malloc`
$ dd if=/dev/zero of=./zeroes-std count=4096 bs=10000
$ arch/*/bin/ksh -c 'read line < ./zeroes-std; grep VmPeak /proc/$$/status ; echo "."'
VmPeak:  88492 kB
.
```

For reference, ksh93v- and ksh2020 use the following amounts of memory with the reproducer:
```sh
# ksh93v- uses a more reasonable amount of memory, indicating vmalloc was (edit: partially) fixed after ksh93u+
$ ksh93v -c 'read line < ./zeroes; grep VmPeak /proc/$$/status ; echo "."'
VmPeak:  131572 kB
.

# ksh2020 uses standard malloc instead of vmalloc
$ ksh2020 -c 'read line < ./zeroes; grep VmPeak /proc/$$/status ; echo "."'
VmPeak:  88480 kB
.
```

**Comment by McDutchie** [comment]
Here is the result of a [`shbench`](https://github.com/ksh-community/shbench) run (ping @jghub) on macOS with Apple's stock /bin/ksh 93u+ 2012-08-01, current ksh 93u+m compiled with vmalloc, and ksh 93u+m compiled with macOS system malloc. It would be interesting to see the results of similar runs on other operating systems.
```
------------------------------------------------------
name             /bin/ksh  ./ksh_vmalloc  ./ksh_malloc
------------------------------------------------------
braces.ksh       0.702     0.686          0.758
charsplit.ksh    0.802     0.954          0.952
extglob.ksh      0.526     0.543          0.541
fibonacci.ksh    0.708     0.758          0.742
gsub.ksh         0.917     0.935          0.909
hanoi.ksh        1.127     1.101          1.113
numfor.ksh       0.836     0.831          0.852
numloop.ksh      0.704     0.721          0.705
parens.ksh       1.042     1.007          1.055
piln2.ksh        1.635     1.632          1.614
plus-equals.ksh  1.214     1.185          1.191
printf.ksh       1.163     1.205          1.231
qsort.ksh        1.482     1.584          1.647
rand.ksh         1.304     1.442          1.360
rand2.ksh        0.924     0.975          0.963
sample.ksh       1.543     1.419          1.414
shuffle.ksh      1.325     1.342          1.349
sieve.ksh        1.243     1.102          1.087
------------------------------------------------------
```
Of course it should be run repeatedly and then averaged to get reliable results, but I think this already shows that the difference is either negligible or very close to negligible, at least on macOS.

On ksh 93v, it looks like vmalloc is basically rewritten, and it wouldn't surprise me if it depended on a lot of API changes in libast as well. So I don't think we can just upgrade it by copying those files over.

Does anyone feel like trying to find and backport a fix for vmalloc from ksh 93v? That fix is not going to come from me, as this stuff is well beyond my current skill set.

If no one else is available to do that, I'm inclined to apply the following diff and be done with it.
```diff
diff --git a/src/lib/libast/features/vmalloc b/src/lib/libast/features/vmalloc
index 787ccb8..6fc5f01 100644
--- a/src/lib/libast/features/vmalloc
+++ b/src/lib/libast/features/vmalloc
@@ -207,10 +207,11 @@ tst	malloc_hook note{ gnu malloc hooks work }end execute{
 
 cat{
 	#include "FEATURE/mmap"
-	#if _BLD_INSTRUMENT || cray || _UWIN && _BLD_ast
+	/* for now, always use the OS's standard malloc due to https://github.com/ksh93/ksh/issues/95 */
+	/* #if _BLD_INSTRUMENT || cray || _UWIN && _BLD_ast */
 	#undef	_map_malloc
 	#define _std_malloc	1	/* defer to standard malloc */
-	#endif
+	/* #endif */
 	#if _mmap_anon
 	#define _mem_mmap_anon	1
 	#endif
```

**Comment by JohnoKing** [comment]
These are the results I'm getting on Arch Linux when ksh is compiled with GCC:
```
Results with CCFLAGS='-O2'
--------------------------------------------------
name             ./ksh-vmalloc    ./ksh-std-malloc
--------------------------------------------------
braces.ksh       0.381            0.321
charsplit.ksh    **fail**         **fail**
extglob.ksh      0.009            0.009
fibonacci.ksh    0.414            0.355
gsub.ksh         0.006            0.006
hanoi.ksh        0.311            0.306
numfor.ksh       0.673            0.588
numloop.ksh      0.523            0.507
parens.ksh       0.242            0.216
piln2.ksh        1.122            1.103
plus-equals.ksh  0.365            0.354
printf.ksh       0.199            0.174
qsort.ksh        0.005            0.006
rand.ksh         0.776            0.780
rand2.ksh        0.592            0.567
sample.ksh       0.948            0.931
shuffle.ksh      0.693            0.713
sieve.ksh        0.745            0.749
--------------------------------------------------

Results with CCFLAGS="-O3 -fno-strict-aliasing -flto=$(nproc)" LDFLAGS="-flto=$(nproc)"
--------------------------------------------------------
name             ./ksh-vmalloc-lto  ./ksh-std-malloc-lto
--------------------------------------------------------
braces.ksh       0.322              0.275
charsplit.ksh    **fail**           **fail**
extglob.ksh      0.009              0.009
fibonacci.ksh    0.363              0.326
gsub.ksh         0.006              0.006
hanoi.ksh        0.286              0.268
numfor.ksh       0.512              0.530
numloop.ksh      0.434              0.419
parens.ksh       0.211              0.199
piln2.ksh        0.955              0.925
plus-equals.ksh  0.337              0.332
printf.ksh       0.181              0.169
qsort.ksh        0.006              0.005
rand.ksh         0.709              0.707
rand2.ksh        0.529              0.518
sample.ksh       0.826              0.751
shuffle.ksh      0.698              0.649
sieve.ksh        0.656              0.663
--------------------------------------------------------
```
I'm not sure why the charsplit benchmark is failing (happens on my system with all versions of ksh), but regarding performance glibc's malloc tends to be slightly faster.

**Comment by McDutchie** [comment]
Unfortunately, when building with system malloc, the `vmstate` builtin is a no-op, invalidating all the memory leak tests.

Sometimes it appears to work, e.g. when running `bin/shtests leaks`, but adding a debug `vmstate` command immediately before the final `exit` reveals that the `busy` values are always zero:
```
$ bin/shtests leaks
#### Regression-testing /usr/local/src/ksh93/ksh/arch/darwin.i386-64/bin/ksh ####
test leaks begins at 2020-07-26+19:45:29
region=0x10cc12958 method=best flags=0 size=32768 segments=1 busy=(0,0,0) free=(32640,3,28432)
test leaks passed at 2020-07-26+19:45:30 [ 6 tests 0 errors ]
test leaks(C.UTF-8) begins at 2020-07-26+19:45:30
region=0x109095958 method=best flags=0 size=32768 segments=1 busy=(0,0,0) free=(32640,3,28432)
test leaks(C.UTF-8) passed at 2020-07-26+19:45:30 [ 6 tests 0 errors ]
test leaks(shcomp) begins at 2020-07-26+19:45:30
region=0x1023a0958 method=best flags=0 size=32768 segments=1 busy=(0,0,0) free=(32640,3,28432)
test leaks(shcomp) passed at 2020-07-26+19:45:30 [ 6 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.007s    0m00.015s
tests:     0m00.223s    0m00.268s
```
…so that's useless. This would be a disadvantage of disabling vmalloc. There seems to be no other way of measuring memory leaks that is both reliable and portable.

**Comment by McDutchie** [comment]
Actually, that's not quite true. For some reason, it works when running `bin/shtests leaks`.

When it doesn't work, `state.regions` is zero in this block:
https://github.com/ksh93/ksh/blob/a2f13c19f2c822a4cb7fc1c700d1f07d7f01f1f9/src/lib/libcmd/vmstate.c#L186-L197

Apparently, `state.regions` is not initialised properly when comping with OS malloc. There is some trigger that gets it to initialise later, but I haven't figured out what that is.

**Comment by McDutchie** [comment]
Re: https://github.com/ksh93/ksh/issues/95#issue-665784215

If ksh93v's malloc uses 131572 kB and the system's malloc uses 88480 kB for the same command, doesn't that indicate that even the ksh93v- beta's vmalloc is still broken? That's a significant difference.

**Comment by JohnoKing** [comment]
I have looked into this bug further and have found out two things regarding vmalloc:

1. The following script ([taken from here](https://gist.github.com/ormaaj/12874b68acd06ee98b59)) causes a memory fault with ksh93u+ vmalloc because everything has been modified to run in a subshell. No memory fault occurs in ksh93v- or when ksh is built with `-D_std_malloc`:
```sh
$ cat funcname-subshell.ksh
#!/usr/bin/env ksh
( # Everything below must be run in a subshell, including the creation of functions.
    typeset -a FUNCNAME

    function FUNCNAME.get {
        nameref self=${.sh.name}
        if (( .sh.subscript < .sh.level )); then
            trap "(( .sh.level -= .sh.subscript + 1 )); eval '(( .sh.level = ${.sh.level} ))' \; _=\${.sh.fun}" DEBUG
            trap - DEBUG;
        fi

    (( .sh.subscript < .sh.level - 2 )) && self[.sh.subscript + 1]=
    }

    function f {
        if (($1 < 10)); then
            print -r -- "${FUNCNAME[@]}"
            g $(($1 + 1))
        fi
        print -r -- "${FUNCNAME[@]}"
    }

    function g {
        if (($1 < 10)); then
            print -r -- "${FUNCNAME[@]}"
            f $(($1 + 1))
        fi
        print -r -- "${FUNCNAME[@]}"
    }

    #typeset -ft FUNCNAME.get f g
    f 0
)

$ ./ksh-vmalloc ./funcname-subshell.ksh; echo
f
g f
f g f
g f g f
f g f g f
g f g f g f
f g f g f g f
g f g f g f g f
f g f g f g f g f
g f g f g f g f g f
f g f g f g f g f g f
g f g f g f g f g f 
Memory fault

$ ./ksh-std-malloc ./funcname-subshell.ksh; echo
f
g f
f g f
g f g f
f g f g f
g f g f g f
f g f g f g f
g f g f g f g f
f g f g f g f g f
g f g f g f g f g f
f g f g f g f g f g f
g f g f g f g f g f 
f g f g f g f g f  
g f g f g f g f   
f g f g f g f    
g f g f g f     
f g f g f      
g f g f       
f g f        
g f         
f 

```

2. Backporting the (partial) memory usage fix from ksh93v- will require going through both pre-releases of ksh93v because the bugfix is strewn across both ksh93v pre-releases (being 2013-10-10-alpha and 2014-12-24 beta):
```sh
# The memory usage is lower than in ksh93u+, although still much more than
# the last release of ksh93v-.
$ ksh93v-2013 -c 'read line < ./zeroes; grep VmPeak /proc/$$/status ; echo "."'
VmPeak:	1688976 kB
.
```

Note: I've included a patch below that allows the first pre-release of ksh93v to build on Linux. The last pre-release of ksh93v can be built from the [2016-01-10-beta branch](https://github.com/att/ast/tree/2016-01-10-beta) of the AST repository.

[ksh93v-2013-build.patch.txt](https://github.com/ksh93/ksh/files/4994759/ksh93v-2013-build.patch.txt)

**Comment by JohnoKing** [comment]
I've found another crash caused in part by vmalloc. The following script crashes in part due to a memory allocation bug in vmalloc (full details are in #113, which fixes part of this crash):
```sh
$ cat ./vmalloc-subshell-crash.ksh
#!/bin/ksh
(
    for ((n=0; n != 50000; n++)) do
        (
            function foo {
                (true)
            }
            foo
         )
    done
)
$ ksh ./vmalloc-subshell-crash.ksh
Memory fault
```
Considering vmalloc doesn't tend to be much faster than standard malloc (in fact on Linux vmalloc is consistently **slower** than glibc's malloc, see [this comment](https://github.com/ksh93/ksh/issues/95#issuecomment-664009139)), I'm in favor of using `-D_std_malloc` by default.

**Comment by McDutchie** [comment]
> Considering vmalloc doesn't tend to be much faster than standard malloc (in fact on Linux vmalloc is consistently **slower** than glibc's malloc, see [this comment](https://github.com/ksh93/ksh/issues/95#issuecomment-664009139)), I'm in favor of using `-D_std_malloc` by default.

Agreed. But that means we're unable to run `bin/shtests leaks`. There appears to be no other way of testing for memory leaks that is both portable and reliable. So I'd like to leave vmalloc enabled in the current development branch, and disable it by default in future beta/release branches.

**Comment by JohnoKing** [comment]
> So I'd like to leave vmalloc enabled in the current development branch, and disable it by default in future beta/release branches.

Maybe this could be done with a release flag like `-DSHOPT_RELEASE`, e.g.:
```C
#if SHOPT_RELEASE
#define _std_malloc 1
#endif
```
Such a flag could be used to control other things as well (if necessary).
